import type { ModuleDef } from '@/lib/rust/types';
import { m2Lesson } from './m2.lesson';
import { m3Lesson } from './m3.lesson';

const m1Lesson = [
  '## 起步与所有权',
  '',
  '这一模块的目标很明确：把 Rust 工具链装好、把最基础的语法跑通，然后一头扎进 Rust 最核心也最容易劝退的概念——**所有权（ownership）与借用（borrowing）**。',
  '几乎每一份 Rust 后端岗位的 JD 都会把「熟悉所有权与借用检查器」写在硬要求第一行，因为它是 Rust 之所以"没有 GC 也没有内存错误"的根本原因。',
  '把这一节吃透，后面的 trait、生命周期、async 才不会变成玄学。',
  '',
  '---',
  '',
  '### 一、装好工具链：rustup 与 cargo',
  '',
  'Rust 的官方安装器叫 `rustup`，它同时管理编译器（rustc）、包管理器（cargo）和工具链版本。',
  '',
  '**Linux / macOS**：',
  '',
  '```bash',
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
  'source "$HOME/.cargo/env"',
  '```',
  '',
  '**Windows**：到 rustup.rs 下载 `rustup-init.exe` 双击运行；或者在 PowerShell 里执行 `winget install Rustlang.Rustup`。',
  'Windows 还需要 MSVC 构建工具（安装器会提示你装 Visual Studio Build Tools），这一步别跳过。',
  '',
  '装完验证：',
  '',
  '```bash',
  'rustc --version   # rustc 1.9x.x',
  'cargo --version   # cargo 1.9x.x',
  'rustup update     # 以后升级就靠它',
  '```',
  '',
  '> 本站的练习直接调用官方 Rust Playground 编译运行，**你不装工具链也能做题**。但后面的实战项目要在本地跑 `cargo test`、`cargo clippy`，所以越早装好越好。',
  '',
  '### 二、cargo 日常命令',
  '',
  '`cargo` 是你今后每天都要敲几十遍的命令。新建一个项目：',
  '',
  '```bash',
  'cargo new hello_dojo      # 建二进制项目（带 src/main.rs）',
  'cargo new mylib --lib     # 建库项目（带 src/lib.rs）',
  'cd hello_dojo',
  '```',
  '',
  '生成的目录结构是固定的：`Cargo.toml`（依赖与元信息）、`src/main.rs`（入口）、`target/`（编译产物，记得写进 .gitignore）。',
  '',
  '| 命令 | 作用 | 什么时候用 |',
  '| --- | --- | --- |',
  '| `cargo run` | 编译并运行 | 想看输出 |',
  '| `cargo check` | 只做类型/借用检查，不生成可执行文件 | 写代码时高频验证，比 build 快好几倍 |',
  '| `cargo build --release` | 开优化编译 | 要测性能、要发版 |',
  '| `cargo test` | 跑单元测试与文档测试 | 每次改完逻辑 |',
  '| `cargo fmt` | 按官方风格格式化代码 | 提交前 |',
  '| `cargo clippy` | 静态检查，给出更地道的写法 | 提交前，团队常要求零警告 |',
  '',
  '`cargo fmt` 和 `cargo clippy` 在真实团队里几乎都是 CI 的门禁，养成习惯：**写完先 check，提交前 fmt + clippy**。',
  '',
  '### 三、变量与可变性',
  '',
  'Rust 的变量**默认不可变**。这不是给你添堵，而是让"这个值会不会被改"变成类型系统层面的信息。',
  '',
  '```rust',
  'let x = 5;',
  '// x = 6;          // 编译错误：cannot assign twice to immutable variable',
  '',
  'let mut y = 5;',
  'y = 6;             // OK',
  '```',
  '',
  '**遮蔽（shadowing）**：用 `let` 重新声明同名变量，可以改变类型，旧值被"盖住"。它和 `mut` 是两回事——`mut` 是原地改值，遮蔽是造了个新变量。',
  '',
  '```rust',
  'let spaces = "   ";          // &str',
  'let spaces = spaces.len();   // usize，合法',
  '```',
  '',
  '**常量**用 `const`，必须标类型、必须是编译期可求值的表达式，命名习惯全大写：',
  '',
  '```rust',
  'const MAX_RETRY: u32 = 3;',
  '```',
  '',
  '### 四、基本类型',
  '',
  '- **整数**：`i8/i16/i32/i64/i128/isize` 与无符号的 `u8/.../usize`。不写类型时默认 `i32`。索引和长度用 `usize`。',
  '- **浮点**：`f32`、`f64`（默认）。',
  '- **布尔**：`bool`，只有 `true` / `false`，不存在"非零即真"。',
  "- **字符**：`char` 是 4 字节的 Unicode 标量，`'中'` 是合法的 char。",
  '- **元组**：`let pair: (i32, &str) = (1, "one");`，用 `pair.0` 取值，可以解构 `let (a, b) = pair;`。',
  '- **数组**：`let arr = [1, 2, 3];` 长度是类型的一部分（`[i32; 3]`），长度可变的用 `Vec<T>`。',
  "- **字符串**：`String` 是可增长、拥有所有权的堆字符串；`&str` 是字符串切片（借用）。字面量 `\"abc\"` 的类型是 `&'static str`。",
  '',
  'Rust 不做隐式数值转换，跨类型要显式 `as`：',
  '',
  '```rust',
  'let a: i64 = 10;',
  'let b: i32 = a as i32;',
  '```',
  '',
  '### 五、函数与表达式',
  '',
  '```rust',
  'fn add(a: i32, b: i32) -> i32 {',
  '    a + b        // 没有分号 = 表达式 = 返回值',
  '}',
  '```',
  '',
  '参数**必须**标类型，返回值用 `->` 标注。函数体最后一个**表达式**（不带分号）就是返回值；加了分号就变成语句，返回值变成 `()`（unit）。',
  '这是新手最常见的错误来源之一：多写一个分号，编译器就报 `expected i32, found ()`。',
  '',
  'Rust 里"块"也是表达式：',
  '',
  '```rust',
  'let y = {',
  '    let x = 3;',
  '    x * 2        // 块的值是 6',
  '};',
  '```',
  '',
  '### 六、控制流',
  '',
  '`if` 是表达式，可以直接赋值；条件必须是 `bool`：',
  '',
  '```rust',
  'let n = 7;',
  'let label = if n % 2 == 0 { "偶数" } else { "奇数" };',
  '```',
  '',
  '三种循环：',
  '',
  '```rust',
  '// 1. loop：无限循环，break 可以带值出来',
  'let mut i = 0;',
  'let found = loop {',
  '    i += 1;',
  '    if i * i > 50 { break i; }',
  '};',
  '',
  '// 2. while：条件循环',
  'let mut countdown = 3;',
  'while countdown > 0 { countdown -= 1; }',
  '',
  '// 3. for：遍历迭代器，日常最常用',
  'for n in 1..=5 { println!("{n}"); }        // 1..=5 含右端；1..5 不含',
  'for item in ["a", "b"] { println!("{item}"); }',
  '```',
  '',
  '实战里 `for` 占绝对多数——手写下标 `while` 循环在 Rust 里既啰嗦又容易越界，`clippy` 也会提醒你换成迭代器。',
  '',
  '### 七、所有权三规则',
  '',
  '这是整个 Rust 的地基，只有三条：',
  '',
  '1. **每个值都有一个所有者（owner）变量**；',
  '2. **同一时刻只能有一个所有者**；',
  '3. **所有者离开作用域时，值被自动释放（drop）**。',
  '',
  '```rust',
  '{',
  '    let s = String::from("hello");   // s 拥有这段堆内存',
  '    println!("{s}");',
  '}                                    // 作用域结束，s 被 drop，内存自动释放',
  '```',
  '',
  '没有 GC，也不用手动 `free`：编译器在编译期就知道该在哪一行插入释放代码。这就是 Rust 能同时拿到"C 的性能"和"托管语言的内存安全"的原因。',
  '',
  '### 八、move 语义与 Copy',
  '',
  '把一个 `String` 赋值给另一个变量时，**不是拷贝，而是所有权转移（move）**：',
  '',
  '```rust',
  'let s1 = String::from("hello");',
  'let s2 = s1;              // 所有权从 s1 move 到 s2',
  '// println!("{s1}");      // 编译错误：borrow of moved value: `s1`',
  '```',
  '',
  '为什么？因为如果两个变量都认为自己拥有同一块堆内存，作用域结束时就会释放两次（double free）。Rust 直接在编译期把 `s1` 标记为失效。',
  '',
  '想要两份数据就显式 `clone`（明码标价的深拷贝）：',
  '',
  '```rust',
  'let s2 = s1.clone();      // 现在 s1 和 s2 都可用',
  '```',
  '',
  '而 `i32`、`bool`、`char`、`f64`、以及"全是这类字段的元组"实现了 `Copy`：它们在栈上，赋值就是按位复制，原变量依然可用。',
  '',
  '```rust',
  'let a = 5;',
  'let b = a;                // Copy，不是 move',
  'println!("{a} {b}");      // 完全合法',
  '```',
  '',
  '**把值传给函数，等同于赋值**：非 Copy 类型传进去就 move 进去了，除非函数把它再返回出来，或者——你用借用。',
  '',
  '### 九、借用：& 与 &mut',
  '',
  '借用就是"我只想看看/改改，不夺走所有权"。',
  '',
  '```rust',
  'fn char_count(s: &String) -> usize {   // 借用，不获取所有权',
  '    s.chars().count()',
  '}',
  '',
  'let title = String::from("所有权");',
  'let n = char_count(&title);            // 传引用',
  'println!("{title} 有 {n} 个字");        // title 还在！',
  '```',
  '',
  '**借用检查器的两条铁律**：',
  '',
  '1. 在任意时刻，要么有**任意多个不可变引用 `&T`**，要么有**恰好一个可变引用 `&mut T`**，二者不能同时存在；',
  '2. **引用必须永远有效**，不能指向已经被释放的数据（不允许悬垂引用）。',
  '',
  '```rust',
  'let mut s = String::from("hi");',
  'let r1 = &s;',
  'let r2 = &s;          // 多个不可变引用，OK',
  'println!("{r1} {r2}");',
  '',
  'let r3 = &mut s;      // OK：r1/r2 到上一行就不再使用了（NLL）',
  'r3.push_str(" there");',
  '```',
  '',
  '**给你一个直觉**：不可变引用像"多人同时读一份文档"，可变引用像"一个人独占编辑"。读的时候不许有人改，改的时候不许有人读——这正是数据竞争的定义，Rust 把它挪到了编译期。',
  '这条规则在单线程里防的是"迭代时修改集合"这类经典 bug；到了模块五讲并发时，它会直接升级成"Rust 没有数据竞争"的保证。',
  '',
  '编译器还有个叫 **NLL（非词法生命周期）** 的能力：引用的生命周期在**最后一次使用**处就结束，而不是等到作用域花括号。所以上面 `r3` 那行才能通过。',
  '遇到借用报错时，第一反应应该是：**「这个引用的最后一次使用在哪？能不能让它更早结束？」**',
  '',
  '常见的三种解法，按优先级排：缩短引用存活范围 → 先把需要的值 copy 出来 → 实在不行才 `clone`。',
  '',
  '### 十、切片（slice）',
  '',
  '切片是"对一段连续数据的借用"，它不拥有数据：',
  '',
  '```rust',
  'let s = String::from("hello world");',
  'let hello = &s[0..5];      // &str，等价于 &s[..5]',
  'let world = &s[6..11];',
  '',
  'let arr = [1, 2, 3, 4, 5];',
  'let mid: &[i32] = &arr[1..4];   // [2, 3, 4]',
  '```',
  '',
  '**注意**：字符串切片按**字节**索引，切在多字节 UTF-8 字符中间会直接 panic。一个中文字在 UTF-8 里通常占 3 字节，所以 `&s[0..3]` 才是第一个汉字。要按字符处理请用 `s.chars()`。',
  '',
  '函数签名尽量写 `&str` 而不是 `&String`，写 `&[i32]` 而不是 `&Vec<i32>`——前者更通用，`String` 和 `Vec` 都能自动解引用传进去。这是 code review 里的高频建议。',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 在自己机器上用 rustup 装好工具链，用 cargo 新建、运行、检查、格式化一个项目',
  '- [ ] 说清楚 `let` / `let mut` / 遮蔽 / `const` 四者的区别',
  '- [ ] 正确使用整数、浮点、bool、char、元组、数组、`String` 与 `&str`',
  '- [ ] 写出带返回值的函数，并解释"多写一个分号"为什么会编译失败',
  '- [ ] 用 `if` 表达式和 `loop`/`while`/`for` 组织控制流',
  '- [ ] 背出所有权三规则，并说明 move 与 `Copy` 的差别',
  '- [ ] 看懂 `borrow of moved value` 和 `cannot borrow as mutable` 两类报错，并独立修好',
  '- [ ] 用 `&` / `&mut` 设计函数签名，用切片避免不必要的 `clone`',
].join('\n');

const m4Lesson = [
  '## 迭代器、智能指针、测试与 serde',
  '',
  '这一模块把你从"能跑"推到"写得地道"。',
  '',
  '你会学到：',
  '',
  '- **迭代器**：`map` / `filter` / `fold` / `collect` / `zip` / `take_while` 等适配器链，惰性求值的含义，以及为什么迭代器链通常和手写循环一样快',
  '- **闭包**：`Fn` / `FnMut` / `FnOnce` 三种闭包 trait，`move` 闭包捕获所有权',
  '- **智能指针**：`Box<T>`（堆分配、递归类型）、`Rc<T>`（单线程共享所有权）、`RefCell<T>`（内部可变性，把借用检查推迟到运行时），以及 `Rc<RefCell<T>>` 这个经典组合的适用边界',
  '- **测试**：`#[test]`、`assert_eq!`、`#[should_panic]`、返回 `Result` 的测试、集成测试目录 `tests/`',
  '- **serde**：`#[derive(Serialize, Deserialize)]`、`serde_json` 的序列化与反序列化、字段重命名与可选字段',
  '',
  '**为什么 JD 需要它**：`serde` 出现在几乎每一份 Rust 后端 JD 里——REST API 的请求/响应体、配置文件、消息队列负载全靠它。',
  '而"有单元测试习惯"是招聘方筛简历的硬指标；迭代器写法则直接影响 code review 通过率。',
  '',
  '> **本模块练习制作中**，将随后续批次上线；学完后是实战项目 `todo-json` CLI（serde 持久化 + 测试 + clippy 零警告）。',
].join('\n');

const m5Lesson = [
  '## 线程与并发',
  '',
  'Rust 最有说服力的卖点：**"fearless concurrency"——数据竞争在编译期就被挡掉**。这一模块讲清楚它是怎么做到的。',
  '',
  '你会学到：',
  '',
  '- `std::thread::spawn` 与 `JoinHandle`，`move` 闭包为什么在这里是必需的',
  '- **channel**：`std::sync::mpsc` 的发送端/接收端，多生产者单消费者模型',
  '- **共享状态**：`Mutex<T>` 与 `RwLock<T>` 的加锁与毒化（poisoning），`Arc<T>` 跨线程共享所有权，经典组合 `Arc<Mutex<T>>`',
  '- **`Send` 与 `Sync`**：两个 marker trait 到底约束了什么，为什么 `Rc` 不是 `Send` 而 `Arc` 是',
  '- 死锁与锁粒度：持锁做 IO、持锁跨 await 是生产事故的常见来源',
  '',
  '**为什么 JD 需要它**：`Send + Sync` 是 Rust 面试的必考题，也是你写 axum handler 时编译器最爱报的那类错误的根源。',
  '理解了它，模块六的 async 才不会变成"到处加 Arc 试到编译通过"。',
  '',
  '> **本模块练习制作中**，将随后续批次上线。本模块所有练习都会保证输出确定性（固定 join 顺序或先排序再打印）。',
].join('\n');

const m6Lesson = [
  '## async 与 tokio',
  '',
  '到这里你开始真正接触 Rust 后端的主战场。绝大多数云后端 Rust JD 的第一硬要求就是 **async/await + Tokio**。',
  '',
  '你会学到：',
  '',
  '- `async fn` 返回的是 **Future**，不 `.await` 就什么都不会发生（惰性）；`.await` 处是让出点',
  "- **Tokio 运行时**：`#[tokio::main]`、多线程调度器与 work stealing、`spawn` 出的任务为什么要求 `Send + 'static`",
  '- **并发原语**：`join!` 并发等待、`select!` 竞速、`tokio::sync::{mpsc, oneshot, Mutex}` 与标准库版本的区别',
  '- **阻塞的代价**：在 async 上下文里做同步 IO 或 CPU 密集运算会饿死整个调度器，正确做法是 `spawn_blocking`',
  '- 超时、取消与优雅关闭：`timeout`、任务取消语义、`CancellationToken` 思路',
  '',
  '**为什么 JD 需要它**：高并发 API 服务、消息消费者、行情/撮合系统全部建立在 Tokio 之上。',
  '"能解释 async Rust 的陷阱"（持锁跨 await、阻塞调度线程、Future 未被 await）几乎是 senior 岗位的分水岭问题。',
  '',
  '> **本模块练习制作中**，将随后续批次上线；学完后是实战项目「tokio 并发抓取器」。',
].join('\n');

const m7Lesson = [
  '## axum + sqlx + WebSocket',
  '',
  '这一模块把前面所有零件拼成一个真实的后端服务，也是本课程最贴近日常工作的部分。',
  '',
  '你会学到：',
  '',
  '- **axum**：`Router` 与路由、提取器（`Path` / `Query` / `Json` / `State`）、`IntoResponse` 与统一错误响应、中间件与 `tower` 分层',
  '- **应用状态**：把连接池、配置装进 `State`，以及它为什么必须 `Clone + Send + Sync`',
  '- **sqlx**：连接池、编译期校验的 `query!` 宏、迁移（migrations）、事务、`FromRow` 映射',
  '- **WebSocket**：升级握手、读写分离的两个循环、广播（broadcast channel）与连接生命周期管理',
  '- 分层设计：把业务逻辑抽成**纯函数**，让 handler 只做解析与编排——这样才测得动',
  '',
  '**为什么 JD 需要它**：axum + sqlx + PostgreSQL 是当前 Rust 云后端最主流的组合，加拿大远程 Senior Rust 后端岗位几乎照抄这套栈。',
  '',
  '> **本模块练习制作中**，将随后续批次上线。练习只考纯函数化的 handler 逻辑（不绑端口），真正跑起服务器放在实战项目 p4。',
].join('\n');

const m8Lesson = [
  '## 生产化与求职',
  '',
  '最后一段路：把"能跑的服务"变成"敢上线的服务"，再把它变成"能拿到 offer 的作品"。',
  '',
  '你会学到：',
  '',
  '- **可观测性**：`tracing` 的 span 与 event、结构化日志、`tracing-subscriber` 分级过滤，为什么它比 `println!` 强一个量级',
  '- **错误处理工程化**：`thiserror` 定义库错误、`anyhow` 收口应用错误、错误如何映射成 HTTP 状态码',
  '- **配置与部署**：环境变量与配置分层、多阶段 `Dockerfile`（构建缓存 + 精简运行镜像）、健康检查、优雅关闭',
  '- **CI**：GitHub Actions 跑 `fmt --check` / `clippy -D warnings` / `test`，以及依赖缓存',
  '- **求职**：基于真实 JD 的能力对照清单、简历里怎么描述 Rust 项目、高频面试题（所有权、生命周期、`Send`/`Sync`、async 陷阱）',
  '',
  '**为什么 JD 需要它**：Docker/CI/可观测性几乎出现在每一份后端 JD 的"加分项"甚至硬要求里。',
  '面试到最后拼的往往不是语法，而是"你有没有把服务真正跑在生产里过"。',
  '',
  '> **本模块练习制作中**，将随后续批次上线；验收挂在实战项目 p4（完整 axum 后端 + tracing + Dockerfile + CI）。',
].join('\n');

export const allModules: ModuleDef[] = [
  {
    id: 'm1',
    order: 1,
    title: '起步与所有权',
    tierKey: 'beginner',
    tierLabel: '小白',
    summary:
      '装好 rustup/cargo，掌握变量、类型与控制流，吃透所有权、move、借用与切片——每份 Rust JD 的第一条硬要求。',
    lesson: m1Lesson,
  },
  {
    id: 'm2',
    order: 2,
    title: '结构体、枚举与模式匹配',
    tierKey: 'beginner',
    tierLabel: '小白',
    summary:
      '用 struct/enum 给领域建模，用 match 穷尽分支，以 Option/Result 取代 null 与异常——后端错误处理的起点。',
    lesson: m2Lesson,
  },
  {
    id: 'm3',
    order: 3,
    title: 'trait、泛型与生命周期',
    tierKey: 'intermediate',
    tierLabel: '初级',
    summary:
      'trait 抽象行为、泛型零成本复用、生命周期标注读懂借用报错——读懂 tokio/axum/serde 文档的入场券。',
    lesson: m3Lesson,
  },
  {
    id: 'm4',
    order: 4,
    title: '迭代器、智能指针、测试与 serde',
    tierKey: 'intermediate',
    tierLabel: '初级',
    summary:
      '迭代器链写出地道 Rust，Box/Rc/RefCell 管好内存，单元测试与 serde 序列化——REST API 的日常装备。',
    lesson: m4Lesson,
  },
  {
    id: 'm5',
    order: 5,
    title: '线程与并发',
    tierKey: 'advanced',
    tierLabel: '中级',
    summary:
      'thread/channel/Mutex/Arc 与 Send+Sync，理解 Rust 如何在编译期消灭数据竞争——并发岗位的必考题。',
    lesson: m5Lesson,
  },
  {
    id: 'm6',
    order: 6,
    title: 'async 与 tokio',
    tierKey: 'advanced',
    tierLabel: '中级',
    summary:
      'Future 惰性、Tokio 运行时、join/select 与 spawn_blocking，避开持锁跨 await 等生产陷阱——云后端 JD 的第一硬需求。',
    lesson: m6Lesson,
  },
  {
    id: 'm7',
    order: 7,
    title: 'axum + sqlx + WebSocket',
    tierKey: 'senior',
    tierLabel: '高级',
    summary:
      '路由、提取器、State、连接池、事务与 WebSocket 广播，把业务逻辑纯函数化——当下最主流的 Rust 后端技术栈。',
    lesson: m7Lesson,
  },
  {
    id: 'm8',
    order: 8,
    title: '生产化与求职',
    tierKey: 'sprint',
    tierLabel: '冲刺',
    summary:
      'tracing 可观测性、thiserror/anyhow、Dockerfile 与 CI，配 JD 能力对照与高频面试题——把作品变成 offer。',
    lesson: m8Lesson,
  },
];

export function getModuleById(id: string): ModuleDef | undefined {
  return allModules.find((module) => module.id === id);
}
