export const m2Lesson = [
  '## 结构体、枚举与模式匹配',
  '',
  '有了所有权的地基，这一模块开始造"自己的类型"。',
  '如果说所有权决定了 Rust 的**安全边界**，那么类型建模决定了 Rust 的**表达力上限**：',
  '**结构体（struct）** 把相关数据聚成一个整体，**枚举（enum）** 表达"多选一"的状态，**模式匹配（match）** 强制你把每一种情况都处理掉。',
  '',
  '这三样东西合起来能做到一件在很多语言里做不到的事——**让非法状态无法被表示（make illegal states unrepresentable）**。',
  '一个"订单既已完成又已取消"的对象，在 Rust 里可以做到根本构造不出来，而不是靠代码审查和运行时断言去防。',
  '',
  '---',
  '',
  '### 一、结构体的三种形态',
  '',
  '最常用的是**具名字段结构体**：',
  '',
  '```rust',
  '#[derive(Debug, Clone, PartialEq)]',
  'struct Driver {',
  '    name: String,',
  '    rating: f64,',
  '    trips: u32,',
  '    active: bool,',
  '}',
  '```',
  '',
  '另外两种在实战里也很常见：',
  '',
  '```rust',
  'struct Meters(f64);          // 元组结构体：给基础类型套一层语义（newtype）',
  'struct Config;               // 单元结构体：没有数据，只作为一个类型标记',
  '```',
  '',
  '`Meters(f64)` 这种 **newtype 模式**特别值得记住：`fn drive(d: Meters)` 和 `fn drive(d: f64)` 的区别在于，',
  '前者让你**不可能**把"秒数"当"米数"传进去。零运行时开销，纯编译期收益。',
  '',
  '### 二、构造、字段简写与更新语法',
  '',
  '```rust',
  'let name = String::from("老王");',
  'let rating = 4.8;',
  '',
  'let d1 = Driver {',
  '    name,          // 字段简写：变量名与字段名相同，写一次就够',
  '    rating,',
  '    trips: 0,',
  '    active: true,',
  '};',
  '',
  'let d2 = Driver {',
  '    trips: 128,',
  '    ..d1.clone()   // 结构体更新语法：其余字段从 d1 复制过来',
  '};',
  '```',
  '',
  '⚠️ **更新语法的坑**：`..d1` 对非 `Copy` 字段（比如 `String`）是**移动**而不是拷贝。',
  '写 `..d1` 之后 `d1.name` 就失效了（部分移动，partial move），继续用 `d1` 会报 `use of partially moved value`。',
  '要么像上面那样先 `clone()`，要么接受 `d1` 被消耗掉。',
  '',
  '### 三、derive：让编译器替你写样板代码',
  '',
  '```rust',
  '#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]',
  'struct Point { x: i32, y: i32 }',
  '```',
  '',
  '| derive | 给你什么 | 什么时候加 |',
  '| --- | --- | --- |',
  '| `Debug` | `{:?}` / `{:#?}` 打印 | 几乎所有类型都该加，调试和 `assert_eq!` 都靠它 |',
  '| `Clone` | `.clone()` 显式深拷贝 | 需要复制时 |',
  '| `Copy` | 赋值即按位复制（隐式） | 所有字段都是 `Copy` 的小类型 |',
  '| `PartialEq` / `Eq` | `==` 比较 | 要比较、要写 `assert_eq!` 时 |',
  '| `Default` | `Type::default()` | 配置类结构体 |',
  '',
  '`{:#?}` 是"美化版 Debug"，会换行缩进打印，排查复杂结构时非常好用。',
  '',
  '### 四、impl：方法与关联函数',
  '',
  '`impl` 块里的函数分两类，区别只有一个——**第一个参数是不是 `self`**：',
  '',
  '```rust',
  'impl Driver {',
  '    fn new(name: String) -> Self {          // 关联函数：Driver::new(...)',
  '        Self { name, rating: 5.0, trips: 0, active: true }',
  '    }',
  '',
  '    fn is_veteran(&self) -> bool {          // 方法：d.is_veteran()，只读借用',
  '        self.trips >= 100',
  '    }',
  '',
  '    fn finish_trip(&mut self) {             // 需要改字段：可变借用',
  '        self.trips += 1;',
  '    }',
  '',
  '    fn into_name(self) -> String {          // 消耗自己：调用后原变量就没了',
  '        self.name',
  '    }',
  '}',
  '```',
  '',
  'Rust 没有"构造函数"这种语法，`new` 只是社区约定的关联函数名；`Self` 是"当前类型"的别名。',
  '**签名选择的默认顺序是 `&self` → `&mut self` → `self`**：能只读就别要可变，能借用就别夺走所有权。',
  '这条习惯直接决定了你的 API 好不好用——一个动不动就吃掉所有权的方法，调用方会被迫到处 `clone`。',
  '',
  '方法调用还有个贴心设计：**自动引用与解引用**。`d.is_veteran()` 编译器会自动补成 `Driver::is_veteran(&d)`，',
  '所以你永远不需要写 C++ 里那种 `->`。',
  '',
  '### 五、枚举：比"类继承"更适合建模状态',
  '',
  'Rust 的枚举**每个变体都能携带自己的数据，形状还可以各不相同**：',
  '',
  '```rust',
  'enum RideEvent {',
  '    Requested,                       // 无数据',
  '    Accepted { driver: String },     // 结构体变体',
  '    Moved(i32, i32),                 // 元组变体',
  '    Cancelled(String),               // 带原因',
  '}',
  '```',
  '',
  '在传统 OOP 里，这种"一个事件有好几种形态"通常用抽象基类 + 若干子类表达。两种做法的取舍很清晰：',
  '',
  '- **类继承**：容易加新的子类，但每加一个"操作"就要改所有子类；且调用方拿到基类指针后，永远不确定自己面对的到底是谁。',
  '- **枚举 + match**：容易加新的操作（写个新函数就行），加新变体时编译器会**逼你把所有 `match` 补齐**；调用方一眼看得见全部可能性。',
  '',
  '后端建模的绝大多数场景——订单状态、消息类型、错误种类——变体集合是相对稳定的，操作却在不断增加，所以枚举几乎总是更划算。',
  '这也是为什么 Rust 标准库把 `Option` 和 `Result` 都做成枚举。',
  '',
  '枚举同样可以有 `impl`：',
  '',
  '```rust',
  'impl RideEvent {',
  '    fn is_terminal(&self) -> bool {',
  '        matches!(self, RideEvent::Cancelled(_))',
  '    }',
  '}',
  '```',
  '',
  '`matches!` 宏是"只想问是不是某个模式"时的速记，返回 `bool`。',
  '',
  '### 六、match：穷尽性是一张安全网',
  '',
  '`match` 必须覆盖所有可能，漏一个变体就是编译错误 `E0004: non-exhaustive patterns`。',
  '别把它当成编译器挑刺——**当同事给枚举加了一个新变体，所有没处理它的 `match` 会当场编译失败**，',
  '而不是在生产环境里悄悄走进 `default` 分支，然后半夜给你打电话。',
  '',
  '```rust',
  'let label = match event {',
  '    RideEvent::Requested => String::from("已下单"),',
  '    RideEvent::Accepted { driver } => format!("{driver} 已接单"),',
  '    RideEvent::Moved(x, y) => format!("移动到 ({x}, {y})"),',
  '    RideEvent::Cancelled(reason) => format!("取消：{reason}"),',
  '};',
  '```',
  '',
  '模式的花样比 `switch` 多得多：',
  '',
  '```rust',
  'match n {',
  '    0 => "零",',
  '    1..=9 => "个位数",              // 范围模式，含两端',
  '    10 | 20 | 30 => "整十",         // 多模式用 | 合并',
  '    x if x < 0 => "负数",           // 匹配守卫：模式后面再加布尔条件',
  '    x @ 100..=199 => {              // @ 绑定：既匹配范围又拿到值',
  '        println!("三位数 {x}");',
  '        "三位数"',
  '    }',
  '    _ => "其他",                    // 通配兜底',
  '}',
  '```',
  '',
  '**分支自上而下依次尝试，第一个匹配上的胜出**，所以书写顺序就是优先级。',
  '',
  '关于 `_` 有一条工程经验：**对自己领域内的枚举，尽量老实列全变体，不要图省事用 `_` 兜住**。',
  '`_` 会让"加了新变体"这件事变得静悄悄，你就白白放弃了穷尽性检查这张安全网。',
  '`_` 更适合用在整数、字符串这类本来就无法穷尽的类型上。',
  '',
  '模式不只出现在 `match` 里——`let`、函数参数、`for` 的循环变量全都是模式，所以**解构**随处可用：',
  '',
  '```rust',
  'let Point { x, y } = point;                 // 解构结构体',
  'let (name, age) = ("老王", 38);              // 解构元组',
  'for (index, value) in items.iter().enumerate() { }   // 解构迭代器产出的元组',
  '',
  'match order {                                // 嵌套模式：一层层往里匹配',
  '    Order { status: OrderStatus::Cancelled, reason: Some(r), .. } => println!("取消：{r}"),',
  '    Order { status: OrderStatus::Cancelled, .. } => println!("取消：原因不明"),',
  '    Order { fare, .. } if fare > 100.0 => println!("大额订单"),',
  '    _ => println!("普通订单"),',
  '}',
  '```',
  '',
  '结构体模式里的 `..` 表示"其余字段我不关心"，它让模式在结构体新增字段时不会被迫改动。',
  '嵌套模式配合守卫，可以把一段本来要写三层 `if` 嵌套的判断压成一屏可读的分支表——这也是 Rust 代码读起来"扁"的原因之一。',
  '',
  '### 七、Option：Rust 没有 null',
  '',
  '```rust',
  'enum Option<T> { Some(T), None }',
  '```',
  '',
  '空指针被 Tony Hoare 本人称为"我的十亿美元错误"。Rust 的解法不是"更小心地检查 null"，而是**在类型层面消灭它**：',
  '`Option<i32>` 和 `i32` 是两个不同的类型，编译器绝不允许你把前者直接当后者用。',
  '于是"忘记判空"从运行时崩溃变成了编译期报错。',
  '',
  '取值的常用姿势：',
  '',
  '```rust',
  'match maybe_age {',
  '    Some(age) => println!("{age} 岁"),',
  '    None => println!("未知"),',
  '}',
  '',
  'if let Some(age) = maybe_age {          // 只关心一种情况时更短',
  '    println!("{age} 岁");',
  '} else {',
  '    println!("未知");',
  '}',
  '',
  'let Some(age) = maybe_age else {        // let-else：不满足就提前退出，主干不缩进',
  '    return Err("缺少年龄".into());',
  '};',
  'println!("{age} 岁");                   // 这之后 age 就是普通的值了',
  '',
  'while let Some(item) = stack.pop() {    // 循环版本',
  '    println!("{item}");',
  '}',
  '```',
  '',
  '常用组合子（不写 `match` 也能干活）：',
  '',
  '| 方法 | 作用 |',
  '| --- | --- |',
  '| `unwrap_or(默认值)` | 没有值就用默认值 |',
  '| `unwrap_or_default()` | 用类型的 `Default` |',
  '| `unwrap_or_else(\\|\\| ...)` | 默认值需要计算时（惰性） |',
  '| `map(\\|v\\| ...)` | 有值就变换，`None` 原样传递 |',
  '| `and_then(\\|v\\| ...)` | 变换结果本身也是 `Option` 时（扁平化） |',
  '| `ok_or("错误")` | `Option` 转 `Result` |',
  '',
  '**`unwrap()` 和 `expect()` 会在 `None` 时 panic**。写练习和原型无所谓，但生产服务里的裸 `unwrap` 就是一颗定时炸弹——',
  '至少也要用 `expect("这里不可能为空，因为上一行刚插入")` 把"我凭什么确信"写清楚，供未来的自己和 code review 检查。',
  '',
  '### 八、Result 与 ? 的第一课',
  '',
  '```rust',
  'enum Result<T, E> { Ok(T), Err(E) }',
  '```',
  '',
  '`Option` 说"有没有"，`Result` 说"成没成、为什么没成"。Rust 没有异常机制，**任何可能失败的操作都把失败当作返回值交给你**，',
  '所以函数签名本身就是一份诚实的契约：看到 `-> Result<Config, ConfigError>` 你立刻知道这里要处理失败。',
  '',
  '```rust',
  'fn parse_age(s: &str) -> Result<u8, String> {',
  '    let n: i32 = s',
  '        .trim()',
  '        .parse::<i32>()',
  '        .map_err(|e| format!("无法解析：{e}"))?;   // map_err 只改错误分支；? 失败就提前返回',
  '',
  '    if !(0..=130).contains(&n) {',
  '        return Err(format!("年龄超出范围：{n}"));',
  '    }',
  '    Ok(n as u8)',
  '}',
  '```',
  '',
  '`?` 运算符做的事只有两件：**`Ok(v)` 就把 `v` 取出来继续往下走；`Err(e)` 就立刻 `return Err(e.into())`**。',
  '它让"主干逻辑"和"出错就走人"在视觉上分离，是 Rust 错误处理读起来比 `if err != nil` 舒服的关键。',
  '注意末尾那个 `.into()`：它要求当前函数的错误类型能从被传播的错误类型转换过来——',
  '这就是为什么模块三讲 `From` trait 时会说"给自己的错误类型实现 `From`，`?` 就自动通了"。',
  '',
  '`Result` 也有一整套组合子：`map` / `map_err` / `and_then` / `unwrap_or_else` / `ok()`（丢掉错误换成 `Option`）。',
  '这一模块先建立"失败是值"的心智模型即可，`?` 的完整规则、自定义错误类型、`thiserror` / `anyhow` 分别在模块三和模块八展开。',
  '',
  '### 九、常见坑：match 会不会把值移走',
  '',
  '这是本模块最容易撞墙的地方，也是所有权知识第一次和模式匹配正面相遇。',
  '',
  '```rust',
  'let msg = Some(String::from("hello"));',
  'match msg {',
  '    Some(s) => println!("{s}"),   // s 把 String 从 msg 里"搬"出来了',
  '    None => {}',
  '}',
  '// println!("{msg:?}");           // 错误：value moved',
  '```',
  '',
  '解法是**匹配引用**——把 `match msg` 改成 `match &msg`：',
  '',
  '```rust',
  'match &msg {',
  '    Some(s) => println!("{s}"),   // s 的类型是 &String，只是借用',
  '    None => {}',
  '}',
  'println!("{msg:?}");              // 依然可用',
  '```',
  '',
  '这背后是 **match ergonomics**（匹配人体工学）：当被匹配的值是引用时，模式里绑定出来的变量会自动变成引用，',
  '你不用写成 `Some(ref s)` 那种老式写法。',
  '',
  '同样的道理适用于结构体的**部分移动**：',
  '',
  '```rust',
  'let d = Driver::new(String::from("老王"));',
  'let name = d.name;        // String 字段被移出，d 变成"部分移动"状态',
  '// println!("{d:?}");     // 错误：use of partially moved value',
  'let trips = d.trips;      // 但 Copy 字段仍然可以读',
  '```',
  '',
  '记住一条实用判据：**只是想看，就借用（`&`）；确实要拿走，才移动**。遇到 `value moved here` 先问自己"我真的需要拥有它吗"。',
  '',
  '### 十、这些能力在 JD 里对应什么',
  '',
  '类型建模是 Rust 面试的**第一道分水岭**：语法谁都能背，但"给我设计一个订单状态机"能立刻区分出会不会用 Rust 思考。',
  '',
  '- **"熟悉 Rust 类型系统 / 领域建模"**：用 struct + enum 建模，而不是把一切塞进 `HashMap<String, String>` 或者到处传字符串状态；',
  '- **"错误处理经验"**：面试高频题"你怎么做错误处理"，答案的起点就是 `Option` / `Result` + `?`，而不是异常和 null 检查；',
  '- **"代码健壮性 / 线上事故少"**：把状态编码进枚举、让编译器逼你穷尽分支，是 Rust 服务比同类服务少一大批空指针与非法状态事故的直接原因；',
  '- **接下来的所有模块**：`Iterator`、`Future`、`axum` 的提取器全都建立在枚举与模式匹配之上——`Poll::Ready/Pending`、`Option<Item>` 都是老朋友。',
  '',
  '一个可以直接搬进面试回答的例子：**用 `Option<T>` 表达"可能不存在的记录"，用 `Result<T, E>` 表达"可能失败的调用"，用自定义枚举表达"有限状态"，剩下的交给 `match` 穷尽性检查。**',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 定义具名结构体、元组结构体（newtype）与单元结构体，并说清各自的用途',
  '- [ ] 用字段简写和结构体更新语法构造实例，并解释 `..other` 为什么可能导致部分移动',
  '- [ ] 在 `impl` 块里写关联函数与方法，并在 `&self` / `&mut self` / `self` 之间做出正确选择',
  '- [ ] 说明 `#[derive(Debug, Clone, Copy, PartialEq, Default)]` 各自带来什么',
  '- [ ] 定义带数据的枚举，并讲清它相比"抽象基类 + 子类"的取舍',
  '- [ ] 熟练使用 `match`：范围模式、`|` 多模式、匹配守卫、`@` 绑定，并解释穷尽性检查的工程价值',
  '- [ ] 在 `let`、函数参数、`for` 中用模式解构结构体与元组，并用 `..` 忽略不关心的字段',
  '- [ ] 看懂 `E0004: non-exhaustive patterns` 并独立修好，同时知道为什么不该随手用 `_` 兜底',
  '- [ ] 用 `Option<T>` 取代 null，熟练使用 `if let` / `let else` / `unwrap_or` 等取值方式',
  '- [ ] 用 `Result<T, E>` 表达可能失败的操作，会用 `map_err` 转换错误、用 `?` 传播错误',
  '- [ ] 解释 `match value` 与 `match &value` 的区别，并独立修好 `value moved` 类报错',
].join('\n');
