export const m4Lesson = [
  '## 迭代器、智能指针、测试与 serde',
  '',
  '前三个模块解决的是"能不能写出来"，这一模块解决的是"写得像不像 Rust 工程师写的"。',
  '迭代器链决定你的 code review 能不能一次过，智能指针决定你在"编译器不让我共享/修改"时有没有正确的武器，',
  '单元测试是招聘方筛简历的硬指标，而 `serde` 是后端 JD 里出现频率最高的一个具体 crate——REST 的请求体与响应体、配置文件、消息队列负载，全靠它在 JSON 和 struct 之间来回翻译。',
  '',
  '---',
  '',
  '### 一、迭代器：一个 trait，一个方法',
  '',
  '`Iterator` 这个 trait 的必需方法只有一个：',
  '',
  '```rust',
  'trait Iterator {',
  '    type Item;',
  '    fn next(&mut self) -> Option<Self::Item>;   // 取下一个，取完了返回 None',
  '}',
  '```',
  '',
  '其余七十多个方法都是基于 `next` 的默认实现。所以只要你为自己的类型实现了 `next`，`map`、`filter`、`take`、`sum` 全部免费到手——这是 trait 默认方法最漂亮的一次应用。',
  '',
  '迭代器方法分成两类，分清它们，迭代器就不神秘了：',
  '',
  '- **适配器（adapter）**：`map`、`filter`、`enumerate`、`zip`、`take`、`skip`、`rev`、`chain`、`flat_map`… 它们**返回一个新的迭代器**，本身什么都不做；',
  '- **消费器（consumer）**：`collect`、`sum`、`count`、`fold`、`for_each`、`any`、`all`、`find`、`max_by`… 它们**把迭代器跑完**，产出一个最终值。',
  '',
  '**迭代器是惰性的**：只搭流水线不通电，直到消费器出现才真正开始转。',
  '',
  '```rust',
  'let v = vec![1, 2, 3];',
  'v.iter().map(|x| println!("{x}"));   // 警告：unused `Map` that must be used —— 一行都不会打印',
  'v.iter().for_each(|x| println!("{x}"));  // 这才会执行',
  '```',
  '',
  '`Iterator` 上标了 `#[must_use]`，所以上面那行会收到编译器警告。看到 "iterators are lazy and do nothing unless consumed" 就知道少写了消费器。',
  '',
  '自己实现一个迭代器也就十行，实现完立刻能享受整条适配器链：',
  '',
  '```rust',
  'struct Countdown(u32);',
  '',
  'impl Iterator for Countdown {',
  '    type Item = u32;',
  '    fn next(&mut self) -> Option<u32> {',
  '        if self.0 == 0 { return None; }',
  '        self.0 -= 1;',
  '        Some(self.0 + 1)',
  '    }',
  '}',
  '',
  'let v: Vec<u32> = Countdown(3).filter(|n| n % 2 == 1).collect();  // [3, 1]',
  '```',
  '',
  '这也解释了为什么 Rust 的 `for` 循环能遍历任何东西：`for` 要的只是一个实现了 `IntoIterator` 的值，而所有 `Iterator` 都自动实现了 `IntoIterator`。',
  '',
  '### 二、为什么迭代器链比 for 循环更 Rust',
  '',
  '第一是**表达意图**：`for` 循环里你得从代码反推"这段在筛选还是在聚合"，而 `filter(...).map(...).sum()` 一眼就说清了。',
  '第二是**安全**：手写下标循环容易越界、容易在遍历中改集合，迭代器把这些坑都堵死了。',
  '第三是**零成本**：泛型单态化 + 内联之后，迭代器链编译出来的机器码通常和手写循环等价，还常常因为编译器能证明不越界而**省掉边界检查**，反而更快。',
  '',
  '所以在 Rust 里"写得地道"和"写得快"不冲突。`clippy` 也会主动把 `needless_range_loop`、`manual_filter_map` 这类写法提示成迭代器形式。',
  '',
  '### 三、iter / into_iter / iter_mut 怎么选',
  '',
  '这是新手最常卡住的地方，其实只有一句话：**看你想要引用还是所有权**。',
  '',
  '| 写法 | Item 类型 | 集合还能用吗 | 什么时候用 |',
  '| --- | --- | --- | --- |',
  '| `v.iter()` | `&T` | 能 | 只读遍历（最常用） |',
  '| `v.iter_mut()` | `&mut T` | 能 | 原地修改每个元素 |',
  '| `v.into_iter()` | `T` | **不能**（被消耗） | 要把元素的所有权取出来 |',
  '',
  '`for x in &v` 等价于 `v.iter()`，`for x in &mut v` 等价于 `iter_mut()`，`for x in v` 等价于 `into_iter()`——所以在 `for` 循环里漏写 `&` 会把集合吃掉，这是 `borrow of moved value` 的常见来源。',
  '',
  '`iter()` 产出的是引用，闭包里常常要多解一层：',
  '',
  '```rust',
  'let v = vec![1, 2, 3, 4];',
  'let big: Vec<i32> = v.iter().filter(|x| **x > 2).copied().collect();',
  'let big: Vec<i32> = v.iter().copied().filter(|x| *x > 2).collect();  // 先 copied，闭包干净很多',
  '```',
  '',
  '对实现了 `Copy` 的元素，习惯性地在链头加 `.copied()`（或 `.cloned()`）能省下一大堆 `*`。',
  '',
  '### 四、常用适配器与消费器速查',
  '',
  '```rust',
  'let words = vec!["3", "x", "7"];',
  '',
  '// filter_map：过滤 + 转换一步到位，返回 None 的项被丢弃',
  'let nums: Vec<i32> = words.iter().filter_map(|s| s.parse().ok()).collect();  // [3, 7]',
  '',
  '// enumerate：带上下标',
  'for (i, w) in words.iter().enumerate() { println!("{i}: {w}"); }',
  '',
  '// zip：两条流并排走，短的那条结束就停',
  'let pairs: Vec<(&str, i32)> = words.iter().copied().zip([1, 2, 3]).collect();',
  '',
  '// fold：所有消费器的祖宗，sum/count/max 都是它的特例',
  'let total = nums.iter().fold(0, |acc, n| acc + n);',
  '',
  '// any / all / position：短路求值，找到答案立刻停',
  'let has_x = words.iter().any(|w| *w == "x");',
  '```',
  '',
  '`collect` 值得单独说：它靠 `FromIterator` 决定收进什么容器，所以**必须告诉它目标类型**，否则报 `type annotations needed`。',
  '',
  '```rust',
  'let v: Vec<i32> = it.collect();              // 左边标注',
  'let v = it.collect::<Vec<i32>>();            // 或者用 turbofish',
  'let m: HashMap<&str, u32> = pairs.collect(); // 收成 map',
  'let s: String = chars.collect();             // 收成字符串',
  '',
  '// 最实用的一招：Vec<Result<T, E>> 可以直接收成 Result<Vec<T>, E>',
  '// 任何一项出错就整体 Err，成功则拿到干净的 Vec',
  'let parsed: Result<Vec<i32>, _> = words.iter().map(|s| s.parse::<i32>()).collect();',
  '```',
  '',
  '### 五、闭包与三个 trait',
  '',
  '闭包就是"能捕获环境的匿名函数"。捕获方式由**闭包体怎么用这个变量**自动推导，分三档，对应三个 trait：',
  '',
  '| trait | 捕获方式 | 能调用几次 | 例子 |',
  '| --- | --- | --- | --- |',
  '| `Fn` | 不可变借用 `&T` | 多次 | `\\|x\\| x * factor` |',
  '| `FnMut` | 可变借用 `&mut T` | 多次 | `\\|x\\| { count += 1; x }` |',
  '| `FnOnce` | 取得所有权（move 走） | **一次** | `\\|\\| drop(buffer)` |',
  '',
  '它们是包含关系：每个 `Fn` 都是 `FnMut`，每个 `FnMut` 都是 `FnOnce`。',
  '**写函数参数时要求最宽松的那个**——只读读就写 `Fn`，需要改捕获变量写 `FnMut`，只调一次且要吃掉捕获变量才写 `FnOnce`。要求太严会白白挡掉合法的调用方。',
  '',
  '`move` 关键字强制按所有权捕获，跟"调用几次"无关：',
  '',
  '```rust',
  'let data = vec![1, 2, 3];',
  'let closure = move || println!("{data:?}");   // data 被搬进闭包',
  'closure();',
  'closure();                                    // 仍可多次调用：它是 Fn，只是捕获方式变了',
  '```',
  '',
  '模块五讲线程时 `thread::spawn` 必须配 `move` 闭包，原因就在这里：新线程可能活得比当前作用域长，借用不够安全。',
  '',
  '三种传闭包的写法，按开销从低到高：泛型参数 `fn f<F: Fn(i32) -> i32>(f: F)`（静态分发、可内联）、`impl Fn(i32) -> i32`（同上，写法更短）、`Box<dyn Fn(i32) -> i32>`（动态分发，能存进集合、能作为字段）。',
  '',
  '### 六、智能指针选型决策树',
  '',
  '智能指针 = 指针 + 额外能力（自动释放、引用计数、内部可变性）。它们靠 `Deref` 让你像用普通引用一样用它，靠 `Drop` 在离开作用域时收尾。',
  '',
  '- **`Box<T>`**：唯一所有权 + 数据放堆上。三个典型用途：递归类型（`Option<Box<Node>>`，否则 `error[E0072]: recursive type has infinite size`）、trait 对象（`Box<dyn Error>`）、把很大的值挪出栈；',
  '- **`Rc<T>`**：单线程**共享**所有权，`Rc::clone` 只是计数 +1（很便宜），归零才释放。只给**只读**访问；',
  '- **`RefCell<T>`**：内部可变性，把借用检查从编译期挪到**运行期**。`borrow()` / `borrow_mut()` 规则不变，违反时 panic（`already borrowed: BorrowMutError`）；',
  '- **`Rc<RefCell<T>>`**：单线程"共享 + 可变"的标准组合；',
  '- **`Arc<T>` / `Arc<Mutex<T>>`**：上面两者的跨线程版本（模块五详讲）。`Rc` 的计数不是原子的，所以它不是 `Send`，编译器会直接拦下跨线程使用。',
  '',
  '**决策树**：只有一个所有者？→ 直接用值或 `Box`。多个所有者要共享？→ 单线程 `Rc`、多线程 `Arc`。共享的同时还要改？→ 单线程再套 `RefCell`、多线程再套 `Mutex` 或 `RwLock`。',
  '',
  '**心智模型**：`RefCell` 不是绕过借用规则，而是**把同一条规则的检查时机推迟了**。代价是"编译期错误"变成了"运行期 panic"，所以能用普通借用解决的问题就别上 `RefCell`。',
  '真实项目里大量出现 `Rc<RefCell<T>>` 往往是数据结构设计有问题的信号——先想想能不能改成索引（`Vec` + `usize`）或者把可变性收拢到一处。',
  '',
  '还有一个 `Weak<T>`：`Rc` 之间互相持有会形成**循环引用**，计数永远降不到 0，内存泄漏。把其中一个方向换成 `Rc::downgrade` 得到的 `Weak`（不增加强计数，用 `upgrade()` 取值），环就断了。父子树里"子指向父"的那条边通常就是 `Weak`。',
  '',
  '### 七、测试：Rust 自带电池',
  '',
  '单元测试就写在**被测代码同一个文件**里，放在一个带 `#[cfg(test)]` 的模块中——这个属性保证测试代码只在 `cargo test` 时编译，不会进入发布产物：',
  '',
  '```rust',
  'pub fn add(a: i32, b: i32) -> i32 { a + b }',
  '',
  '#[cfg(test)]',
  'mod tests {',
  '    use super::*;                       // 把外层的东西引进来',
  '',
  '    #[test]',
  '    fn adds_two_numbers() {',
  '        assert_eq!(add(2, 3), 5);',
  '    }',
  '',
  '    #[test]',
  '    #[should_panic(expected = "除数为 0")]',
  '    fn panics_on_zero() {',
  '        divide(1, 0);',
  '    }',
  '',
  '    #[test]',
  '    fn works_with_question_mark() -> Result<(), String> {',
  '        let n: i32 = "42".parse().map_err(|_| "解析失败".to_string())?;',
  '        assert_eq!(n, 42);',
  '        Ok(())                          // 返回 Result 的测试可以用 ? 串联',
  '    }',
  '}',
  '```',
  '',
  '断言宏：`assert!(条件)`、`assert_eq!(左, 右)`、`assert_ne!`，都可以在后面追加自定义消息（`assert!(ok, "id={id} 时失败", id = id)`）。',
  '`assert_eq!` 失败时会打印左右两边的 `Debug` 输出，所以被测类型记得 `#[derive(Debug, PartialEq)]`。',
  '',
  '常用命令：',
  '',
  '| 命令 | 作用 |',
  '| --- | --- |',
  '| `cargo test` | 跑全部测试（含文档测试） |',
  '| `cargo test add` | 只跑名字里含 `add` 的测试 |',
  '| `cargo test -- --nocapture` | 让通过的测试也打印 stdout |',
  '| `cargo test -- --test-threads=1` | 串行执行（测试默认并行） |',
  '| `#[ignore]` + `cargo test -- --ignored` | 把慢测试隔离出来单独跑 |',
  '',
  '三种测试的分工：**单元测试**在 `src/` 里，可以测私有函数；**集成测试**放 `tests/` 目录，每个文件是独立 crate，只能用公开 API，测的是"用户视角"；**文档测试**写在 `///` 注释的代码块里，`cargo test` 会真的编译运行它，保证文档不会过期。',
  '',
  '写测试的两个习惯值得从第一天养成。一是**测试名要写成一句陈述句**（`returns_none_for_empty_input` 而不是 `test1`），失败时读输出就知道坏了哪条业务规则；',
  '二是每个测试只断言一件事，别把五个场景塞进一个 `#[test]`——测试并行执行，一个函数里第一条断言炸了，后面几条就永远跑不到。',
  '边界条件优先覆盖：空输入、单元素、重复元素、极值、以及所有会返回 `Err` 的分支。',
  '',
  '工程上最关键的一条经验：**把业务逻辑抽成纯函数**。handler 里塞满数据库调用和 HTTP 解析就没法测；把"算什么"和"从哪拿数据"分开，测试就只剩下输入输出比对。模块七的 axum 部分会把这条原则用到底。',
  '',
  '### 八、serde 全家桶',
  '',
  'serde 是 **ser**ialize + **de**serialize 的缩写，它把"数据结构"和"数据格式"解耦：你的 struct 只实现一次 `Serialize` / `Deserialize`，就能对接 JSON、YAML、TOML、MessagePack、bincode 等一大堆格式。',
  '',
  '```toml',
  '# Cargo.toml',
  'serde = { version = "1", features = ["derive"] }   # derive 特性别忘了开',
  'serde_json = "1"',
  '```',
  '',
  '```rust',
  'use serde::{Deserialize, Serialize};',
  '',
  '#[derive(Debug, Serialize, Deserialize)]',
  '#[serde(rename_all = "camelCase")]          // Rust 蛇形 <-> JSON 驼峰，一行搞定',
  'struct User {',
  '    user_id: u32,                           // <-> "userId"',
  '    #[serde(rename = "name")]               // 单个字段改名，优先级高于 rename_all',
  '    display_name: String,',
  '    #[serde(default)]                       // JSON 里缺这个字段时用 Default::default()',
  '    tags: Vec<String>,',
  '    #[serde(skip_serializing_if = "Option::is_none")]',
  '    note: Option<String>,                   // None 时序列化输出里整个字段消失',
  '}',
  '',
  'let user: User = serde_json::from_str(json)?;      // JSON -> struct',
  'let text = serde_json::to_string(&user)?;          // struct -> 紧凑 JSON',
  'let pretty = serde_json::to_string_pretty(&user)?; // struct -> 缩进 JSON',
  '```',
  '',
  '几个高频属性：`#[serde(alias = "...")]` 兼容旧字段名；`#[serde(skip)]` 完全忽略某字段；`#[serde(flatten)]` 把嵌套 struct 摊平进父层；`#[serde(deny_unknown_fields)]` 让多余字段直接报错（配置文件校验很实用）。',
  '',
  '枚举的 JSON 表示是实战里最容易踩坑的地方，serde 提供四种，选错了就对不上前端或第三方接口：',
  '',
  '```rust',
  '#[derive(Serialize, Deserialize)]',
  '#[serde(tag = "type", rename_all = "snake_case")]   // 内部标签',
  'enum Event {',
  '    Click { x: i32, y: i32 },   // -> {"type":"click","x":1,"y":2}',
  '    Close,                      // -> {"type":"close"}',
  '}',
  '```',
  '',
  '不写 `tag` 是**外部标签**（默认，`{"Click":{"x":1,"y":2}}`）；`#[serde(tag = "t", content = "c")]` 是相邻标签；`#[serde(untagged)]` 则完全靠结构猜测，灵活但错误信息很难读，非必要不用。',
  '',
  '不想定义 struct 时可以用动态的 `serde_json::Value` 和 `json!` 宏，但**能定义 struct 就定义 struct**——静态类型是 Rust 相对动态语言最大的优势，`Value` 满天飞会把这个优势直接扔掉。',
  '',
  '反序列化的错误类型是 `serde_json::Error`，它自带出错位置（行、列）。工程里通常用 `thiserror` 把它包进自己的错误枚举（模块八会讲），或者像本模块练习里那样先 `map_err` 成 `String`。',
  '',
  '### 九、这一节的常见坑',
  '',
  '1. **`collect` 报 type annotations needed**：忘了标注目标容器，补 `let x: Vec<_>` 或 `collect::<Vec<_>>()`；',
  '2. **迭代器写完没反应**：只有适配器没有消费器，编译器的 "iterators are lazy" 警告就是在说这个；',
  '3. **`for x in v` 之后 v 不能用了**：那是 `into_iter()`，只想读就写 `for x in &v`；',
  '4. **闭包里的 `**x`**：`iter().filter(...)` 的闭包参数是 `&&T`，加 `.copied()` 或改用 `.iter().filter(|&&x| ...)` 模式解构；',
  '5. **`RefCell` 运行期 panic**：同一作用域里先 `borrow()` 又 `borrow_mut()`。让 `Ref` 守卫尽早离开作用域（别把 `x.borrow()` 的结果长期存着）；',
  '6. **`Rc` 循环引用泄漏**：用 `Weak` 打断环；',
  '7. **`#[serde(default)]` 要求类型实现 `Default`**：自定义类型记得 `#[derive(Default)]`，或者用 `#[serde(default = "函数名")]` 指定默认值构造函数；',
  '8. **浮点数在测试里别用 `assert_eq!` 直接比**：用差值小于一个 epsilon，或者干脆用整数分表示金额。',
  '',
  '### 十、和 JD、面试的对应',
  '',
  '翻十份 Rust 后端 JD，`serde` 几乎每份都点名；"有完善的单元测试习惯 / 熟悉 TDD" 也是高频硬要求。',
  '面试里这一节的常考题有：迭代器为什么是零成本抽象、`iter` 和 `into_iter` 的区别、`Fn` 三兄弟的差异与何时需要 `move`、',
  '`Box` / `Rc` / `RefCell` 各自解决什么问题、`Rc<RefCell<T>>` 为什么不能跨线程、如何避免循环引用。',
  '这些问题都不难，但答得含糊会被直接判定为"只会照着例子抄"。',
  '',
  '学完本模块，你就具备了写一个像样 CLI 工具的全部装备：迭代器处理数据、serde 做持久化、单元测试保证不回归。',
  '接下来的实战项目 `todo-json` 正是这三件事的合体：JSON 文件存取待办事项、纯函数化的业务逻辑、`cargo clippy` 零警告。',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 说清迭代器的惰性求值，分辨适配器与消费器，并解释"零成本抽象"具体指什么',
  '- [ ] 熟练串起 `map` / `filter` / `filter_map` / `enumerate` / `zip` / `fold` / `collect` 等常用方法',
  '- [ ] 正确区分 `iter` / `iter_mut` / `into_iter`，并知道 `for` 循环三种写法各自对应哪一个',
  '- [ ] 给 `collect` 补上类型标注，并会把 `Result` 的迭代器收成 `Result<Vec<_>, E>`',
  '- [ ] 说出 `Fn` / `FnMut` / `FnOnce` 的差别与包含关系，会把闭包作为泛型参数传进函数',
  '- [ ] 用 `Box<T>` 定义递归数据结构，并解释 `E0072` 为什么会出现',
  '- [ ] 按决策树选出 `Box` / `Rc` / `RefCell` / `Arc` 的正确组合，并说明 `Weak` 解决什么问题',
  '- [ ] 写出带 `#[cfg(test)]` 的单元测试模块，用 `assert_eq!`、`#[should_panic]` 与返回 `Result` 的测试',
  '- [ ] 用 `#[derive(Serialize, Deserialize)]` 加 `rename` / `rename_all` / `default` / `skip_serializing_if` 对接真实 JSON',
  '- [ ] 用 `serde_json` 完成解析、校验与序列化，并把错误转成自己的错误类型',
].join('\n');
