export const m6Lesson = [
  '## async 与 tokio',
  '',
  '到这一模块，你开始真正接触 Rust 后端的主战场。翻开任何一份云后端 Rust JD，第一条硬要求几乎都是 **async/await + Tokio**：高并发 API 服务、消息消费者、行情推送、撮合网关，全部建立在这套东西上。',
  '好消息是，async 并没有引入新的所有权规则——它只是把模块五里那套「线程 + 通道 + 共享状态」搬到了一个更省资源的执行模型上。坏消息是，它引入了一批**只在异步世界里才存在的陷阱**：Future 不 await 就不跑、在 async 里做阻塞调用会饿死整个调度器、跨 `.await` 持锁会死锁。这三条恰好是面试官最爱问的问题。',
  '',
  '---',
  '',
  '### 一、什么时候该用 async：IO 密集 vs CPU 密集',
  '',
  '先想清楚 async 解决的是什么问题。假设你要同时服务一万个 HTTP 连接，每个连接大部分时间都在**等**：等客户端发字节、等数据库回包、等下游服务响应。',
  '',
  '- **一个连接一个线程**：一万个线程，每个线程默认几 MB 栈空间，内存直接爆掉；调度器还要在它们之间疯狂切换（上下文切换要进内核）。',
  '- **async**：一万个**任务（task）**跑在少数几个工作线程上。任务在 `.await` 处主动让出，让出的代价只是保存一个状态机的几十个字节。切换发生在用户态，比线程切换便宜一到两个数量级。',
  '',
  '结论很清晰：',
  '',
  '| 场景 | 该用什么 |',
  '| --- | --- |',
  '| 大量并发连接、频繁等待网络/磁盘（IO 密集） | async + Tokio |',
  '| 图像编码、加解密、大矩阵运算（CPU 密集） | 线程池（`rayon` 或 `spawn_blocking`） |',
  '| 只有几个后台任务、逻辑简单 | `std::thread` 就够，别引入运行时 |',
  '',
  'async 不会让计算变快，它只让**等待**变便宜。把一段纯计算塞进 async 函数里，不但没有收益，还可能把调度器卡住（见第七节）。',
  '',
  '### 二、Future 是惰性状态机',
  '',
  '`async fn` 的返回值不是它写的那个类型，而是一个实现了 `Future` 的匿名类型：',
  '',
  '```rust',
  'async fn price() -> u32 { 25 }',
  '// 等价于：fn price() -> impl Future<Output = u32>',
  '',
  'let p = price();          // 函数体一行都没执行！p 只是个状态机',
  'let v: u32 = p.await;     // 现在才真正跑起来',
  '```',
  '',
  '`Future` 的核心方法只有一个：',
  '',
  '```rust',
  'fn poll(self: Pin<&mut Self>, cx: &mut Context<\'_>) -> Poll<Self::Output>',
  '```',
  '',
  '运行时调用 `poll`，Future 要么返回 `Poll::Ready(值)`（我做完了），要么返回 `Poll::Pending`（我还没好，等我准备好会通过 `cx` 里的 waker 叫醒你）。',
  '编译器把你写的 `async` 块编译成一个**枚举状态机**：每一个 `.await` 就是一个状态点，本地变量被存进状态机的字段里。所以「跨 `.await` 持有某个东西」在实现上就是「把它存进了状态机」——这一点在第七节会变成一条硬约束。',
  '',
  '**这就是 Rust 与 JavaScript 最大的差别**：JS 的 Promise 一创建就开始跑，Rust 的 Future 必须有人 poll 才会前进。忘了 `.await`，编译器只给你一个 `unused_must_use` 警告，程序静悄悄什么都不做——这是新手第一号 bug（本模块 m6-03 专门修它）。',
  '',
  '### 三、Tokio 运行时：谁在驱动这些 Future',
  '',
  '标准库只定义了 `Future` 这个接口，**不提供执行器**。真正不停调用 `poll`、管理定时器、和操作系统的 epoll/kqueue 打交道的，是运行时——生态里事实标准就是 **Tokio**。',
  '',
  '```rust',
  '#[tokio::main]',
  'async fn main() {',
  '    // ...',
  '}',
  '```',
  '',
  '这个宏做的事很朴素：把 `async fn main` 改写成普通 `fn main`，里面建一个运行时再 `block_on(你的 Future)`。展开后大致是：',
  '',
  '```rust',
  'fn main() {',
  '    tokio::runtime::Builder::new_multi_thread()',
  '        .enable_all()',
  '        .build()',
  '        .unwrap()',
  '        .block_on(async { /* 你的 main 体 */ })',
  '}',
  '```',
  '',
  '默认是**多线程调度器**：工作线程数等于 CPU 核数，每个线程有自己的任务队列，闲下来的线程会去**偷**别人队列里的任务（work stealing），这样负载天然均衡。',
  '写单元测试时用 `#[tokio::test]`，它默认建的是**单线程（current-thread）运行时**——更轻、更容易复现问题；需要多线程时写 `#[tokio::test(flavor = "multi_thread")]`。',
  '',
  '### 四、tokio::spawn：任务、Send 与 \'static',
  '',
  '`.await` 是「在当前任务里等」，`tokio::spawn` 则是「把这段 Future 交给运行时，变成一个能被调度到任意线程上的独立任务」：',
  '',
  '```rust',
  'let handle = tokio::spawn(async move {',
  '    fetch(url).await',
  '});',
  'let result = handle.await.unwrap();   // JoinHandle 产出 Result<T, JoinError>',
  '```',
  '',
  '`spawn` 立刻返回 `JoinHandle<T>`，任务**在你 await handle 之前就已经在跑了**。await 它得到的是 `Result<T, JoinError>`——因为任务可能 panic，也可能被取消（`handle.abort()`）。',
  '',
  '它的签名要求 Future 满足 `Send + \'static`，这两个约束直接继承自模块五：',
  '',
  '- **`Send`**：任务可能被 work stealing 搬到另一个线程，所以它跨 `.await` 持有的所有东西都必须能安全跨线程移动。这就是为什么 async 代码里 `Rc` 用不了、要换 `Arc`。',
  '- **`\'static`**：运行时不知道这个任务会活多久，所以它不能借用调用者栈上的局部变量。解决办法就是 `async move`，把需要的数据**移动**进去；要共享则用 `Arc::clone` 后再 move。',
  '',
  '一句话记忆：**`join!` 是「在一个任务里交替推进几个 Future」，`spawn` 是「造出多个真正的任务」**。前者不需要 `Send + \'static`，可以直接借用局部变量；后者能吃满多核。',
  '',
  '### 五、三板斧：join! / select! / timeout',
  '',
  '```rust',
  '// 1) join!：全都要，等最慢的那个；返回元组，顺序与参数顺序一致',
  'let (user, orders) = tokio::join!(load_user(id), load_orders(id));',
  '',
  '// 2) select!：谁先完成用谁，其余分支的 Future 当场被丢弃',
  'let winner = tokio::select! {',
  '    v = primary() => v,',
  '    v = backup()  => v,',
  '};',
  '',
  '// 3) timeout：给等待加上限，返回 Result',
  'match tokio::time::timeout(Duration::from_secs(3), call_api()).await {',
  '    Ok(resp) => handle(resp),',
  '    Err(_elapsed) => tracing_warn(),',
  '}',
  '```',
  '',
  '几条实战经验：',
  '',
  '- 相互独立的请求一律 `join!`，串行 await 是新手最常见的性能浪费；数量不定时用 `futures::future::join_all` 或 `JoinSet`。',
  '- `select!` 的典型用途是「主副本 + 备份副本对冲请求」和「正常逻辑 + 关闭信号」：`_ = shutdown.recv() => break`。',
  '- **任何跨网络的 `.await` 都应该有超时**。没有超时的等待就是定时炸弹：下游一卡，你的连接池和任务数就会无限堆积，最后整个服务被拖死。',
  '- 超时和 `select!` 落败在 Rust 里都表现为**丢弃 Future**，也就是取消。取消不会回滚已经做了一半的副作用，这一点设计接口时必须想清楚。',
  '',
  '### 六、通道选型：mpsc / oneshot / broadcast / watch',
  '',
  '`tokio::sync` 提供的是**异步版**通道：`send` / `recv` 在满或空时 `.await` 让出，而不是阻塞线程。别在 async 代码里用 `std::sync::mpsc`——它一阻塞就把整个工作线程钉死了。',
  '',
  '| 通道 | 形态 | 典型场景 |',
  '| --- | --- | --- |',
  '| `mpsc::channel(n)` | 多生产者、单消费者，容量 n | 工作队列、日志/指标汇聚，容量即背压 |',
  '| `oneshot::channel()` | 一次性，单值 | 请求-响应：把 `Sender` 随请求发过去，等一个回执 |',
  '| `broadcast::channel(n)` | 多生产者、多消费者，每人一份 | 聊天室/WebSocket 广播、配置热更新通知 |',
  '| `watch::channel(v)` | 单值最新态，多订阅者 | 「当前配置」「是否正在关闭」这类只关心最新值的状态 |',
  '',
  '`mpsc` 有一个人人都会踩的坑：**`rx.recv()` 只有在所有 `Sender` 都被丢弃后才返回 `None`**。如果你 clone 了发送端分发给生产者，却把原始那个 `tx` 留在作用域里，接收循环就会永远卡住。标准写法是分发完就 `drop(tx);`（本模块 m6-05 练的就是它）。',
  '',
  '### 七、任务集合与优雅关闭',
  '',
  '任务数量不固定时，别自己维护一个 `Vec<JoinHandle<_>>`——用 `JoinSet`，它能按**完成顺序**取回结果，并且在被丢弃时自动 abort 掉所有还没跑完的任务：',
  '',
  '```rust',
  'let mut set = tokio::task::JoinSet::new();',
  'for url in urls {',
  '    set.spawn(async move { fetch(url).await });',
  '}',
  'let mut results = Vec::new();',
  'while let Some(res) = set.join_next().await {',
  '    results.push(res.unwrap());          // 完成顺序不可控，要确定性就最后排序',
  '}',
  '```',
  '',
  '想限制并发度（比如最多同时打 20 个下游请求），标准做法是 `tokio::sync::Semaphore`：每个任务先 `acquire().await` 拿到许可再干活，许可用完就自动排队。这是给下游做保护的最常用手段。',
  '',
  '**优雅关闭**是生产服务的必修课：收到 `SIGTERM` 后不能立刻 `exit`，而要停止接收新请求、让正在处理的请求跑完、再退出。骨架长这样：',
  '',
  '```rust',
  'loop {',
  '    tokio::select! {',
  '        Some(job) = queue.recv() => handle(job).await,',
  '        _ = tokio::signal::ctrl_c() => {',
  '            println!("开始优雅关闭…");',
  '            break;',
  '        }',
  '    }',
  '}',
  '```',
  '',
  '更复杂的场景用 `watch` 通道或 `tokio_util::sync::CancellationToken` 把「关闭信号」传播给所有子任务，让每个任务自己选择在哪个 `.await` 点退出。模块八讲部署时还会回到这个话题。',
  '',
  '### 八、异步三大陷阱',
  '',
  '**陷阱一：在 async 里做阻塞调用。**',
  '',
  '```rust',
  'async fn handler() {',
  '    std::thread::sleep(Duration::from_secs(1));   // 灾难',
  '    let data = std::fs::read("big.bin").unwrap(); // 同样是灾难',
  '}',
  '```',
  '',
  '这类调用不会让出，而是把**整个工作线程**霸占住。多线程运行时一共就那么几个工作线程，几个这样的 handler 就能让所有请求一起卡住——面试高频题「阻塞 runtime 会发生什么」问的就是这个。正确做法：',
  '',
  '- 睡眠用 `tokio::time::sleep`，文件/网络用 `tokio::fs` / `tokio::net`；',
  '- 无法改造的同步库调用、或超过几十微秒的 CPU 计算，包进 `tokio::task::spawn_blocking(|| ...)`，它跑在专门的阻塞线程池上；',
  '- 大批量并行计算交给 `rayon`，不要塞进 async 运行时。',
  '',
  '**陷阱二：跨 `.await` 持有 `MutexGuard`。**',
  '',
  '```rust',
  'let guard = data.lock().unwrap();   // std::sync::Mutex',
  'save(&guard).await;                 // 编译报错：guard 不是 Send',
  '```',
  '',
  '第二节说过，跨 `.await` 的局部变量会被存进状态机；`std` 的 `MutexGuard` 不是 `Send`，于是整个 Future 不是 `Send`，`tokio::spawn` 直接拒收——编译器帮你拦下了一个死锁。两种解法：',
  '',
  '```rust',
  '// A. 缩短持锁范围：拿到值就放锁（首选）',
  'let snapshot = { let g = data.lock().unwrap(); g.clone() };',
  'save(&snapshot).await;',
  '',
  '// B. 确实需要跨 await 持锁时，换 tokio::sync::Mutex（它的 lock() 是 async 的）',
  'let mut g = data.lock().await;',
  'g.push(fetch_one().await);',
  '```',
  '',
  '注意 `tokio::sync::Mutex` 比 `std` 版本慢，而且**不是**用来替代 `std::sync::Mutex` 的通用方案。经验法则：**只保护内存里的数据、临界区不含 `.await` → 用 `std::sync::Mutex`；临界区必须跨 `.await` → 才换 `tokio::sync::Mutex`。**',
  '',
  '**陷阱三：cancel safety（取消安全）。**',
  '',
  '`select!` 的落败分支、`timeout` 超时的 Future，都会在它停住的那个 `.await` 点被直接丢弃，中间状态全部消失。所以放进 `select!` 的操作必须「被取消也不丢数据」：`sleep`、`mpsc::Receiver::recv()` 是取消安全的；',
  '而「从 socket 读了一半的一条消息」「已经扣款但还没写账」放进 `select!` 就会静默丢数据。Tokio 文档会在方法上明确标注 **Cancel safety** 一节，读第三方 async API 时请专门看这一段。不确定时，把这段逻辑 `spawn` 成独立任务，用 `oneshot` 拿结果——任务不会因为你 select 输了就被取消。',
  '',
  '### 九、和 JD 的对应关系',
  '',
  '- 「熟悉 async/await 与 Tokio 生态」= 会用 `#[tokio::main]`、`spawn`、`join!`/`select!`/`timeout`、`tokio::sync` 通道；',
  '- 「高并发服务经验」= 能解释为什么 async 比一连接一线程省，并知道背压该加在哪（通道容量、信号量、连接池）；',
  '- 「能定位线上性能问题」= 一眼看出「有人在 async 里做了阻塞调用」；',
  '- senior 岗位的分水岭问题基本就三道：**阻塞 runtime 会怎样？跨 await 持锁为什么编译不过？select! 的取消安全是什么？** 这一模块的七道练习正好覆盖它们。',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 说清楚 async 适合 IO 密集、不适合 CPU 密集，并解释任务与线程的成本差别',
  '- [ ] 解释「Future 是惰性状态机」，看懂 `expected u32, found opaque type` 这类忘了 `.await` 的报错',
  '- [ ] 说出 `#[tokio::main]` 展开成了什么，区分多线程调度器与 current-thread 运行时',
  '- [ ] 正确使用 `tokio::spawn` 与 `JoinHandle`，并说明它为什么要求 `Send + \'static`',
  '- [ ] 用 `join!` 把独立请求并发化，用 `select!` 做竞速与优雅关闭，给每个外部调用套上 `timeout`',
  '- [ ] 在 `mpsc` / `oneshot` / `broadcast` / `watch` 之间按场景选型，并记得 drop 掉多余的 `Sender`',
  '- [ ] 用 `JoinSet` 管理数量不定的任务，用 `Semaphore` 限并发，用 `select!` + 信号写出优雅关闭骨架',
  '- [ ] 避开异步三大陷阱：阻塞调用改用 `spawn_blocking`、缩短持锁范围、评估操作是否 cancel safe',
].join('\n');
