export const m7Lesson = [
  '## axum + sqlx + WebSocket',
  '',
  '这一模块把前六个模块的 Rust、serde、并发与 async 手感，收束成一套后端服务的形状：HTTP 请求由 axum 拆开，业务规则在 service 中执行，sqlx 负责持久化，WebSocket 把状态变化推给在线用户。',
  '重点不是背框架方法名，而是建立边界感：**handler 只做协议适配，service 表达业务，db 层处理存储；能写成纯函数的逻辑就不要绑死在网络和数据库上。**',
  '',
  '> Rust Playground 不能绑定端口或向服务发请求，而且当前环境没有提供 axum crate。因此本模块练习用“handler 形状的纯函数 + 类型建模”训练路由、extractor、分页、消息协议和错误转换。真正启动 axum、连接 PostgreSQL 并做端到端请求，会在 **p4 毕业项目**完成。',
  '',
  '---',
  '',
  '### 一、REST：先设计资源，再选择 method',
  '',
  'REST 路由围绕名词资源组织。`/orders` 表示订单集合，`/orders/{id}` 表示集合中的一个订单；动作由 HTTP method 表达：',
  '',
  '| 目的 | method 与路径 | 常见响应 |',
  '| --- | --- | --- |',
  '| 列表 | `GET /orders` | `200 OK` + 数组或分页对象 |',
  '| 创建 | `POST /orders` | `201 Created` + 新资源 |',
  '| 查看 | `GET /orders/{id}` | `200 OK` 或 `404 Not Found` |',
  '| 局部更新 | `PATCH /orders/{id}` | `200 OK` / `204 No Content` |',
  '| 删除 | `DELETE /orders/{id}` | `204 No Content` 或 `404 Not Found` |',
  '',
  '避免 `/createOrder`、`/deleteOrder?id=1` 这种 RPC 式路径，也不要让同一个 method/path 根据请求体里的某个字段偷偷变成完全不同的动作。统一的资源表更容易授权、生成文档、做指标，也更符合调用方预期。',
  '',
  '列表接口通常把过滤、排序、分页放进 query string，例如 `GET /orders?status=paid&page=2&per_page=20`。页码从 0 还是 1 开始、空集有几页、越界返回空页还是错误，都必须成为明确契约。m7-04 把这些边界抽成纯函数；接上数据库后，同一语义会变成稳定的 `WHERE`、`ORDER BY`、`LIMIT` 和 `OFFSET`。',
  '',
  '常见坑是先分页再过滤：那会导致每页数量忽多忽少，总数也错误。正确顺序是**过滤 → 稳定排序 → 统计总数 → 分页**。排序还要有确定的次级键，例如 `ORDER BY created_at DESC, id DESC`，否则同一时间戳的记录可能跨页漂移。',
  '',
  '### 二、axum 的心智模型：一切由类型连接',
  '',
  'axum 没有藏着一个庞大的控制器运行时。可以把它理解成四样东西：`Router` 把 method/path 映射到 handler；handler 是 async 函数；extractor 从请求中提取类型；返回值通过 `IntoResponse` 变成 HTTP 响应。',
  '',
  '```rust',
  'use axum::{',
  '    extract::{Path, State},',
  '    routing::{get, post},',
  '    Json, Router,',
  '};',
  '',
  'let app = Router::new()',
  '    .route("/orders", get(list_orders).post(create_order))',
  '    .route("/orders/{id}", get(get_order))',
  '    .with_state(state);',
  '```',
  '',
  'handler 的参数表就是请求契约：`Path<u64>` 解析路径参数，`Query<Filter>` 解析查询串，`State<AppState>` 取得共享状态，`Json<CreateOrder>` 读取并反序列化 body。提取失败时，handler 甚至不会运行，axum 会用 extractor 的 rejection 生成响应。',
  '',
  '```rust',
  'async fn create_order(',
  '    State(state): State<AppState>,',
  '    Path(shop_id): Path<u64>,',
  '    Json(input): Json<CreateOrder>,',
  ') -> Result<Json<Order>, ApiError> {',
  '    let order = state.orders.create(shop_id, input).await?;',
  '    Ok(Json(order))',
  '}',
  '```',
  '',
  'extractor 从左到右执行。`Path`、`Query`、`State` 只读 request parts，可以放在前面；`Json` 要消费只能读取一次的 body，必须是最后一个 extractor。顺序错时经常只看到一大段 “trait `Handler` is not implemented”，真正要检查的是：参数是不是合法 extractor、body extractor 是否最后、Future 是否 `Send`、所有返回分支能否转成同一种响应。m7-03 就是把这条类型约束缩成最小模型。',
  '',
  '### 三、State 里放什么，不放什么',
  '',
  '`State<AppState>` 适合承载所有请求共享、可廉价克隆的依赖，例如连接池、配置快照、服务对象和广播发送端：',
  '',
  '```rust',
  '#[derive(Clone)]',
  'struct AppState {',
  '    db: sqlx::PgPool,',
  '    events: tokio::sync::broadcast::Sender<OrderEvent>,',
  '}',
  '```',
  '',
  '克隆 `PgPool` 或 channel sender 只是克隆内部句柄，不会复制整池连接。不要把“当前用户”“本次请求 ID”这类请求级数据塞进全局 State；它们应该来自认证 extractor 或 extension。也不要为了可变数据就给整个 AppState 套一个巨大的 `Mutex`，否则互不相关的请求会排队。优先让数据库承担持久状态，让 channel 传递事件；确需内存状态时，再把锁缩到最小数据结构，并避免持锁跨 `.await`。',
  '',
  '### 四、为什么 handler 要薄，纯函数要厚',
  '',
  '端口、socket、时钟和真实数据库都会让测试变慢且不稳定。好的 handler 像转换插头：把 HTTP 类型转成领域输入，调用 service，再把领域结果转成响应。字段校验、状态迁移、分页边界、权限判定等规则应尽量写成普通函数：',
  '',
  '```rust',
  'fn validate(input: CreateOrder) -> Result<ValidOrder, ValidationErrors> {',
  '    // 不知道 axum，也不依赖数据库',
  '}',
  '',
  'async fn create_order(Json(input): Json<CreateOrder>) -> Result<impl IntoResponse, ApiError> {',
  '    let valid = validate(input)?;',
  '    let saved = service.create(valid).await?;',
  '    Ok((StatusCode::CREATED, Json(saved)))',
  '}',
  '```',
  '',
  '这样单元测试可以直接覆盖所有分支；少量集成测试检查 service 与数据库；最后只留少量端到端测试验证路由、认证和序列化真的接对。不是“因为 Playground 受限才纯函数化”，而是生产代码本来就需要这种可测试边界。本模块练的是手感与形状，p4 再把这些零件接成真服务。',
  '',
  '### 五、sqlx：让 SQL 在编译期接受审问',
  '',
  'sqlx 是异步 SQL 工具，不是替你隐藏 SQL 的 ORM。`query!` / `query_as!` 宏接收字符串字面量，并在编译时核对 SQL、绑定参数和结果列类型：字段改名、可空性变化、Rust 类型不匹配，能更早暴露。',
  '',
  '```rust',
  'let order = sqlx::query_as!(',
  '    OrderRow,',
  '    r#"SELECT id, item, quantity',
  '       FROM orders',
  '       WHERE id = $1"#,',
  '    id',
  ')',
  '.fetch_optional(&pool)',
  '.await?;',
  '```',
  '',
  '宏校验需要构建时访问与目标 schema 一致的开发数据库，或者读取提交到仓库的 `.sqlx` 离线元数据。团队常在 schema 更新后运行 `cargo sqlx prepare`，CI 再用 `cargo sqlx prepare --check` 防止查询元数据过期。若查询必须动态拼接，就改用运行期 `query` / `QueryBuilder`，并用绑定参数传值；绝不要用 `format!` 把用户输入拼进 SQL。',
  '',
  '迁移是 schema 的版本历史，应该和代码一起评审、按顺序执行。每次迁移尽量小且可理解：创建表、加索引、约束非空、回填数据往往需要分阶段完成。生产环境的大表 `ALTER` 可能长时间锁表，不能把“本地一秒跑完”当成上线依据。',
  '',
  '### 六、连接池不是一个全局连接',
  '',
  '`PgPool` 管理一组可复用连接。请求执行查询时临时取得连接，完成后归还；事务则在同一连接上连续执行并原子提交或回滚。池太小会让请求排队，太大会把 PostgreSQL 压垮。容量要结合实例数一起算：10 个服务实例、每池 20 条连接，数据库看到的是最多 200 条。',
  '',
  '要配置连接超时、空闲回收和最大生命周期，并观察等待连接的耗时。一次请求里相关的“扣库存 + 创建订单 + 写事件记录”应放进事务；但不要在事务中等待远程 HTTP 或 WebSocket 发送，那会无谓占用连接并扩大锁的范围。',
  '',
  '### 七、WebSocket：升级之后是两个长期循环',
  '',
  'WebSocket 起点仍是 HTTP。`WebSocketUpgrade` extractor 校验升级请求，`on_upgrade` 在握手完成后接管连接。随后通常把 socket 拆成读半边和写半边：读循环把客户端帧解析成领域命令，写循环从 channel 接收事件并编码成帧。',
  '',
  '```text',
  'HTTP upgrade',
  '      ↓',
  '建立连接 → 注册订阅者',
  '      ├─ 读循环：frame → ClientMsg → service',
  '      └─ 写循环：broadcast receiver → OutMsg → frame',
  '      ↓',
  '关闭 / 超时 / 任一循环失败 → 取消另一半并清理成员',
  '```',
  '',
  '对 tbaygo 的实时订单场景，数据库仍是事实来源；WebSocket 只是低延迟通知通道。创建或更新订单成功提交后，发布 `OrderCreated` / `OrderStatusChanged` 事件，在线客户端收到后更新界面；断线重连时必须重新拉取快照，不能假设消息从不丢。',
  '',
  '`tokio::sync::broadcast` 很适合“一条事件发给每个在线连接”：每个连接 `subscribe()` 得到独立 receiver。但它是有界缓冲，慢消费者可能收到 `Lagged`，表示旧消息已被覆盖。业务必须决定断开慢连接、提示重同步，还是容忍丢失；不能对错误简单 `unwrap()`。同时要处理 ping/pong、客户端主动 close、发送失败、认证过期与服务关闭，确保成员登记和 task 都被清理。',
  '',
  'm7-05 把网络层剥掉，只保留 tagged JSON 协议和 join / leave / broadcast 状态机。真实实现只是把“读取 frame”和“写回 OutMsg”接在它两端。',
  '',
  '### 八、错误处理分层：handler → service → db',
  '',
  '错误也要遵守依赖方向。db 层返回存储语义，如未找到、唯一键冲突、连接失败；service 层增加领域语义，如库存不足、非法状态迁移；handler 层最终映射为对外稳定的状态码和 JSON 错误码。',
  '',
  '```text',
  'sqlx::Error / DbError',
  '          ↓ From',
  '      ServiceError',
  '          ↓ From',
  '        ApiError',
  '          ↓ IntoResponse',
  'HTTP status + 稳定 JSON body',
  '```',
  '',
  '`thiserror` 适合给库和业务枚举生成 `Display`、`source` 与透明包装；`From` 让 `?` 在层与层之间完成转换。不要把数据库连接串、原始 SQL、内部表名直接返回客户端。对外给稳定错误码，对内用 tracing 记录完整错误链。也不要把所有错误都映射成 `500`：输入错误通常是 `400`，未认证是 `401`，无权限是 `403`，资源不存在是 `404`，唯一键或状态冲突常是 `409`，依赖暂时不可用可用 `503`。',
  '',
  '### 九、从本模块走到 p4',
  '',
  '进入 p4 时，不需要推翻本模块的代码。先保留已经通过单元测试的校验、分页和消息状态机，再在外面逐层加适配器：用 axum extractor 构造领域输入，用 service 调用这些纯函数，用 sqlx repository 落库，最后让 handler 实现 HTTP 与 WebSocket 响应。每加一层就增加对应层级的测试，失败时能迅速判断是协议、业务还是存储问题。',
  '',
  '端到端验收应覆盖一次完整用户旅程：创建订单、查询订单、更新状态、收到实时事件、断线后重新同步。测试数据库从迁移开始建立，测试结束后隔离或清理数据；HTTP 断言状态码与稳定错误码，WebSocket 断言事件类型和关键字段。这样 p4 验证的是“各层确实接通”，而不是重复穷举纯函数已经覆盖过的每个边界。',
  '',
  '### 十、常见坑与排查顺序',
  '',
  '- handler 报巨长 trait bound：先看 extractor 顺序与返回类型，再看 Future 是否因为持有非 `Send` 值跨 `.await`。',
  '- `Json` 校验只停在“能反序列化”：语法正确不代表业务合法；字段错误应稳定、可测试，必要时一次返回多项。',
  '- 分页 `page - 1` 下溢或乘法溢出：先处理 0，再用安全算术，并固定排序。',
  '- 每次请求新建连接池：池应该在启动时创建并通过 State 共享；请求只克隆句柄。',
  '- 事务开着去调远程服务：缩短事务范围，把外部副作用放到提交后，可靠事件可用 outbox 模式。',
  '- WebSocket 只写 happy path：连接一定会半开、延迟、掉线和积压，必须为取消与清理设计。',
  '- 把广播当数据库：通知可以丢，持久事实不能丢；重连要能从 HTTP/数据库恢复。',
  '',
  '这些能力直接对应 Rust 后端 JD 中常见的“axum/tower 服务开发、PostgreSQL/sqlx、异步并发、实时消息、API 设计、错误处理与可测试架构”。面试时比起背一段 Router 代码，更重要的是能解释 extractor 为何有顺序、连接池为何可 Clone、事务边界如何选、慢 WebSocket 消费者怎么办。',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 用资源、HTTP method 与状态码设计一致的订单 REST API',
  '- [ ] 解释 Router、handler、extractor、State 和 IntoResponse 如何由类型系统连接',
  '- [ ] 看懂并修复 axum handler 的 extractor 顺序与 trait bound 报错',
  '- [ ] 把校验、分页和协议状态机抽成无需端口与数据库的纯函数',
  '- [ ] 说明 sqlx 编译期查询校验、离线元数据、迁移与连接池的职责',
  '- [ ] 设计 WebSocket 升级、读写循环、broadcast 广播、慢消费者与断线恢复',
  '- [ ] 用 From / thiserror 把 db → service → handler 错误逐层收敛且不泄露内部信息',
  '- [ ] 清楚说明本模块与 p4 的边界：这里练后端形状，p4 完成真实服务器与端到端验证',
].join('\n');
