export const m8Lesson = [
  '## 生产化与求职',
  '',
  '最后一段路，做的事和前七个模块完全不同：不再学语言特性，而是把「能在我机器上跑的服务」变成「敢挂在公网上、出了事能查、别人能接手」的服务，再把它变成「能拿到 offer 的作品」。',
  '这一段的内容在语法上没有难度，却是简历筛选和面试终面的真正分水岭——会写 axum handler 的人很多，能说清楚「日志怎么查、镜像多大、CI 跑什么、SIGTERM 之后发生了什么」的人少得多。',
  '',
  '---',
  '',
  '### 一、tracing：比 println! 强一个量级的可观测性',
  '',
  '先说为什么不能用 `println!`。线上排查时你问的问题从来不是「打印了什么」，而是',
  '**「过去五分钟里，`route=/orders` 且 `status=500` 的请求有多少条，分别属于哪个 request_id」**。',
  '要能这么查，日志就必须是**字段**（结构化）而不是句子。这正是 `tracing` 与老牌 `log` 的分水岭。',
  '',
  '```rust',
  'tracing::info!(order_id = %id, amount_cents = 1999, "订单已创建");',
  '// INFO orders: order_id=8f3c amount_cents=1999 message="订单已创建"',
  '```',
  '',
  '`%id` 表示按 `Display` 记录，`?err` 表示按 `Debug` 记录，不写符号就是把值当成基本类型。本模块 m8-02 手写的那个渲染函数，就是这一行输出的简化版。',
  '',
  '**event 与 span 的区别**是 `tracing` 最值钱的设计：',
  '',
  '- **event**（`info!` / `warn!` / `error!`）是一个时间点上发生的事；',
  '- **span** 是一段有开始和结束的**上下文**，span 里发生的所有 event 会自动继承 span 的字段。',
  '',
  '```rust',
  '#[tracing::instrument(skip(state), fields(order_id = %id))]',
  'async fn get_order(state: AppState, id: OrderId) -> Result<Json<Order>, AppError> {',
  '    let order = state.db.find(id).await?;   // 这里面打的任何日志都自动带上 order_id',
  '    tracing::info!(status = %order.status, "命中订单");',
  '    Ok(Json(order))',
  '}',
  '```',
  '',
  '`#[instrument]` 会为整个函数开一个 span，自动记录参数、耗时与返回是否出错。`skip(state)` 很重要——连接池、密码、大 body 不该进日志。',
  '异步场景下 span 会跟着任务在 `.await` 之间正确进出，这是它和「手动打两行日志」的本质差别。',
  '',
  '**和 `log` 的关系**：`log` 是更早的门面 crate，很多依赖（hyper、sqlx 的一部分）仍在用它。开启 `tracing` 的 `log` 特性后，这些日志会被自动桥接进同一套 subscriber，你不需要维护两套输出。',
  '',
  '**订阅者（subscriber）负责把 event 变成人或机器能看的东西**，标准起手式：',
  '',
  '```rust',
  'use tracing_subscriber::{EnvFilter, fmt};',
  '',
  'fmt()',
  '    .with_env_filter(EnvFilter::try_from_default_env()',
  '        .unwrap_or_else(|_| EnvFilter::new("info,tower_http=debug")))',
  '    .json()          // 生产用 JSON，本地开发去掉这行更好读',
  '    .init();',
  '```',
  '',
  '之后用 `RUST_LOG=info,my_app::db=trace cargo run` 就能按模块调级别，**不用改代码、不用重新编译**。',
  '',
  '**生产日志三条纪律**（面试里问「你们线上日志怎么管」就答这三条）：',
  '',
  '1. **一个请求一个 request_id，并贯穿全链路**。入口中间件生成（或从上游 `X-Request-Id` 透传），放进 span 字段，所有下游日志自动带上。没有它，并发请求的日志就是一锅粥。',
  '2. **日志分级要有纪律**：`error` = 需要人介入的事故；`warn` = 降级但自愈；`info` = 业务里程碑（订单创建、支付完成）；`debug`/`trace` = 排查用，生产默认关。把用户输入错误打成 `error` 会让告警彻底失灵。',
  '3. **永远不要记录密钥、令牌、完整卡号、个人身份信息**。`#[instrument(skip(...))]` 和给敏感字段包一层自定义 `Debug` 是最省事的两个手段；日志一旦落盘就等于扩散了。',
  '',
  '再往上还有 metrics（Prometheus 的 QPS / P99 / 错误率）和 tracing 的 OpenTelemetry 导出（跨服务链路），但对求职来说，**把 tracing + request_id + 分级过滤讲清楚就已经超过大多数候选人**。',
  '',
  '### 二、错误处理收口：thiserror 在库、anyhow 在应用',
  '',
  '模块二学了 `Result`，m8-01 补上了工程化的那一半：',
  '',
  '| 位置 | 用什么 | 理由 |',
  '| --- | --- | --- |',
  '| 库 / 领域模块 | `thiserror` 定义具体错误枚举 | 调用方要能 `match` 出分支，映射成 HTTP 状态码或重试策略 |',
  '| 应用入口 / main / 一次性脚本 | `anyhow::Result` + `.context(...)` | 只关心「出错了，带上下文往上抛」，不需要类型化 |',
  '',
  '```rust',
  '// 库：类型化，调用方可 match',
  '#[derive(Debug, thiserror::Error)]',
  'pub enum StoreError {',
  '    #[error("找不到订单 {0}")]',
  '    NotFound(String),',
  '    #[error("数据库出错")]',
  '    Db(#[from] sqlx::Error),      // #[from] 生成 From，? 自动转换',
  '}',
  '',
  '// 应用：加上下文，别让报错只剩一句 "No such file"',
  'let cfg = std::fs::read_to_string(path)',
  '    .with_context(|| format!("读取配置文件失败：{path}"))?;',
  '```',
  '',
  '在 Web 服务里，这两层的交汇点是 `impl IntoResponse for AppError`：把 `NotFound` 映射 404、校验类映射 400、其余一律 500，**并且 500 的响应体里绝不能带数据库原始错误**（那是信息泄露），只在日志里 `error!(error = ?err)` 记全。',
  '',
  '### 三、配置：十二要素与分层覆盖',
  '',
  'm8-03 练的就是这条链路：',
  '',
  '```text',
  '内置默认值  <  配置文件  <  环境变量  <  命令行参数     （右边优先级更高）',
  '```',
  '',
  '同一个镜像要在 dev / staging / prod 里跑，代码不能改、配置文件不该打进镜像，能变的只有启动时注入的环境变量——这就是十二要素应用（12-factor app）的「配置与代码分离」。生态里 `config`、`figment` 两个 crate 都是这套逻辑的成熟实现。',
  '',
  '几条实操经验：',
  '',
  '- **启动即校验**：配置在 `main` 的前十行就解析成强类型结构体，缺字段、端口越界立刻退出。最糟糕的是跑了两小时后才在某个冷门分支上 panic。',
  '- **拼错的环境变量要报错，不能静默忽略**：`APP_PROT=9000` 静默失效是真实事故的常见根因。',
  '- **密钥不进仓库、不进镜像**：本地用 `.env`（写进 `.gitignore`），线上用编排平台的 secret；`Debug` 打印配置时把敏感字段脱敏。',
  '',
  '### 四、Docker 化：多阶段构建与镜像瘦身',
  '',
  'Rust 的编译产物是一个静态性很强的二进制，天生适合做小镜像。标准多阶段 Dockerfile：',
  '',
  '```dockerfile',
  '# ---- 构建阶段 ----',
  'FROM rust:1-slim AS builder',
  'WORKDIR /app',
  '',
  '# 先只 copy 清单文件，单独编一次依赖，占住缓存层',
  'COPY Cargo.toml Cargo.lock ./',
  'RUN mkdir src && echo "fn main() {}" > src/main.rs && \\',
  '    cargo build --release && rm -rf src',
  '',
  '# 再 copy 真实源码，只重编自己的代码',
  'COPY src ./src',
  'RUN touch src/main.rs && cargo build --release',
  '',
  '# ---- 运行阶段 ----',
  'FROM debian:bookworm-slim',
  'RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*',
  'COPY --from=builder /app/target/release/orders_api /usr/local/bin/orders_api',
  'EXPOSE 8080',
  'CMD ["orders_api"]',
  '```',
  '',
  '要点逐条对应生产坑：',
  '',
  '- **依赖层缓存**：不做这一步，每改一行代码都要重编几百个依赖包，CI 从两分钟变二十分钟。上面这种「假 main.rs」写法是最朴素的版本；工程上更干净的是 **`cargo-chef`**（`cargo chef prepare` 生成依赖清单再 `cargo chef cook`），它连 workspace 多包的场景也处理得很好。',
  '- **运行阶段只复制二进制**：`rust:1` 完整镜像 1.5 GB 起步，`debian:bookworm-slim` + 二进制通常 80–120 MB。',
  '- **`ca-certificates` 别忘**：运行镜像里缺根证书，所有 HTTPS 出站请求都会失败，报错还很难懂。',
  '- **绑 `0.0.0.0`**：容器里监听 `127.0.0.1`，外面永远连不上，这是新手第一号部署事故。',
  '- **别用 root 跑**：`RUN useradd -m app && USER app`。',
  '',
  '**musl 静态编译**（`x86_64-unknown-linux-musl`）能把运行阶段换成 `FROM scratch` 或 `alpine`，镜像压到 15 MB 上下，也不用管 glibc 版本兼容。代价是：',
  '',
  '- musl 的默认内存分配器在多线程高并发下明显慢于 glibc（可以换 `jemalloc`/`mimalloc` 缓解）；',
  '- 依赖 C 库（原生 `openssl`、部分数据库驱动）时交叉编译会很折腾——解法通常是换成纯 Rust 的 `rustls`；',
  '- 调试工具全没了，进容器排查会很难受。',
  '',
  '经验法则：**默认走 `debian-slim`，只有在镜像体积和冷启动真的重要（边缘节点、Serverless、按量拉取）时才上 musl。**',
  '',
  '### 五、CI：GitHub Actions 四步门禁',
  '',
  '```yaml',
  'name: ci',
  'on: [push, pull_request]',
  '',
  'jobs:',
  '  check:',
  '    runs-on: ubuntu-latest',
  '    steps:',
  '      - uses: actions/checkout@v4',
  '      - uses: dtolnay/rust-toolchain@stable',
  '        with:',
  '          components: rustfmt, clippy',
  '      - uses: Swatinem/rust-cache@v2      # 依赖与编译产物缓存，通常快 3–10 倍',
  '      - run: cargo fmt --all -- --check',
  '      - run: cargo clippy --all-targets --all-features -- -D warnings',
  '      - run: cargo test --all-features',
  '      - run: cargo build --release',
  '```',
  '',
  '这四步几乎是 Rust 团队的通用门禁，顺序也有讲究：**先跑最快最容易挂的**（格式化秒级，clippy 比测试快），失败早、反馈快。',
  '',
  '- `-D warnings` 把 clippy 警告升级为错误，这是「团队零警告」的实现方式；本地提交前跑一遍同样的命令，别让 CI 当你的第一读者。',
  '- 缓存用 `Swatinem/rust-cache`，它会自动按 `Cargo.lock` 哈希做 key，比手写 `actions/cache` 靠谱。',
  '- 需要数据库的集成测试用 `services:` 起一个 postgres 容器；`sqlx::query!` 宏在 CI 里没数据库会**编译失败**，解法是提交 `.sqlx` 离线缓存（`cargo sqlx prepare`）或改用运行时的 `query_as`。',
  '- 加分项：`cargo audit`（依赖漏洞）、`cargo deny`（许可证与重复依赖）、以及在 tag 上触发的 docker build & push。',
  '',
  '**为什么这件事对求职特别划算**：招聘方点开你的仓库，第一眼看到的往往就是那个绿色的 CI 徽章。它传达的信息是「这个人知道工程规范」，成本却只有一个 20 行的 YAML。',
  '',
  '### 六、部署形态：三条路怎么选',
  '',
  '| 形态 | 怎么做 | 适合 | 代价 |',
  '| --- | --- | --- | --- |',
  '| **裸 VPS + systemd** | `scp` 二进制上去，写一个 unit 文件，`systemctl enable --now` | 个人项目、小流量服务，最省钱也最好懂 | 自己管证书、日志轮转、滚动更新 |',
  '| **容器**（Docker Compose / K8s） | 上面的多阶段镜像 + 编排 | 团队协作、多服务、需要水平扩容 | 多一层运维复杂度 |',
  '| **平台**（Fly.io / Shuttle / Railway） | `fly launch` 或 `cargo shuttle deploy` | 快速把 demo 挂上公网给面试官看 | 可控性弱、成本随规模上升 |',
  '',
  'systemd unit 的最小可用版本：',
  '',
  '```ini',
  '[Unit]',
  'Description=orders_api',
  'After=network.target',
  '',
  '[Service]',
  'ExecStart=/usr/local/bin/orders_api',
  'Environment=RUST_LOG=info',
  'EnvironmentFile=/etc/orders_api.env   # 密钥放这里，权限 600',
  'Restart=always',
  'RestartSec=2',
  'KillSignal=SIGTERM                    # 先温柔地请你退出',
  'TimeoutStopSec=30                     # 30 秒不退再 SIGKILL',
  '',
  '[Install]',
  'WantedBy=multi-user.target',
  '```',
  '',
  '注意最后两行：**所有编排系统停服务的方式都是「先 SIGTERM，等一会儿，再 SIGKILL」**，所以你的服务必须自己处理优雅关闭——m8-04 练的正是这套骨架：',
  '',
  '```rust',
  'let shutdown = async {',
  '    tokio::signal::ctrl_c().await.ok();      // 生产上还要监听 SIGTERM',
  '};',
  'axum::serve(listener, app)',
  '    .with_graceful_shutdown(shutdown)',
  '    .await?;',
  '```',
  '',
  '收到信号后要做三件事：**停止接受新连接 → 把在途请求处理完 → 关掉连接池再退出**。做不到这一点，每次发版都会有一批用户看到 502，而且可能留下写了一半的数据。',
  '再配一个 `/health` 端点（编排系统靠它判断实例是否可用；探活只检查进程活着，就绪检查再连一次数据库），你的服务就算是「可运维」的了。',
  '',
  '还有三件小事，缺一件就会在上线当天变成大事：**反向代理**（nginx / Caddy 在前面终止 TLS、限流、转发真实 IP，Rust 服务只监听本机端口）、**日志落地**（systemd 直接 `journalctl -u orders_api -f` 就能看，容器则交给平台的日志收集，不要自己写文件再纠结轮转）、以及**回滚预案**（二进制或镜像保留上一版，出事一条命令切回去，比熬夜热修安全得多）。',
  '',
  '### 七、求职冲刺：把作品变成 offer',
  '',
  '**1）简历怎么写 Rust 项目。** 招聘方扫一份简历平均只有十几秒，所以**每一条都要是「做了什么 + 用了什么 + 结果如何（带数字）」**，不要写「熟悉 Rust」这种无法证伪的话。套用这个模板：',
  '',
  '```text',
  '[项目名]（Rust / axum / sqlx / PostgreSQL / Docker）—— github.com/you/xxx',
  '· 用 axum + sqlx 实现订单服务，12 个 REST 端点 + WebSocket 实时推送，统一错误映射与分页；',
  '· 引入 tracing 结构化日志与 request_id 全链路透传，定位问题的时间从「翻日志」变成「一次查询」；',
  '· 多阶段 Dockerfile 把镜像从 1.5 GB 压到 96 MB，GitHub Actions 三步门禁（fmt/clippy -D warnings/test）全绿；',
  '· 集成测试 21 个用例覆盖 CRUD、鉴权与并发写入，CI 平均 2 分 10 秒。',
  '```',
  '',
  '数字不必来自「百万 QPS」，**镜像体积、用例数量、CI 时长、并发数、P99 延迟**这些你自己就能测出来的指标同样有说服力，而且面试官会顺着追问——那正是你准备好的主场。前面四个实战项目（p1 CLI、p2 解析器、p3 并发抓取、p4 axum 服务）刚好能填满这一块。',
  '',
  '**2）GitHub 整理清单**（面试前一小时也来得及）：',
  '',
  '- [ ] README 首屏有一句话定位、架构图或目录说明、**本地三行命令跑起来**、API 一览表；',
  '- [ ] CI 徽章是绿的；`cargo clippy -- -D warnings` 本地也干净；',
  '- [ ] 仓库里没有 `target/`、`.env`、密钥，`.gitignore` 完整；',
  '- [ ] commit 信息像人写的（`feat: 订单状态机` 而不是 `update`、`fix bug`）；',
  '- [ ] 置顶（pin）四个项目，其余练习仓收进一个 archive 仓；',
  '- [ ] 每个项目有一段「已知取舍」——写清楚为什么用 SQLite 不用 Postgres、为什么没做鉴权，**主动暴露取舍比假装完美更像资深**。',
  '',
  '**3）面试准备路径。** 站内 `/resources` 页有两块正好配套：**JD 能力对照表**（每一条硬要求对应本站哪个模块、哪个项目）和**高频面试题库**（所有权与 clone、生命周期与 `\'static`、静态与动态分发、`Send`/`Sync`、`Rc<RefCell>` 与 `Arc<Mutex>`、Future 惰性、阻塞 runtime、cancel safety）。建议的节奏是：',
  '',
  '- **先对照 JD 表勾一遍**，把「能说清楚」和「只是见过」分开；',
  '- 每道题**出声讲一遍**（对着摄像头或朋友），能讲出来才算会——技术面就是限时口述；',
  '- 每个答案后面都挂一个**你自己代码里的例子**：「我在 p3 里就踩过这个坑，当时是……」，这比背标准答案有效十倍；',
  '- 准备三个 STAR 故事：一个性能问题、一个并发/借用检查器的硬仗、一个上线事故或取舍。',
  '',
  '面试官几乎一定会顺着你的项目往下钻，提前把这四个追问的答案想好：**「并发上来之后瓶颈在哪，你怎么测出来的？」「这里为什么 clone，能不能不 clone？」「这个 `unwrap` 在生产上炸了会怎样？」「服务重启时正在处理的请求怎么办？」**。前两个考语言理解，后两个考生产意识——本模块的四道练习正好各覆盖一半。',
  '',
  '**4）零 Rust 工作经验怎么打。** 现实是大多数 Rust 岗位写着「2–3 年 Rust 经验」，而市场上根本没有那么多人满足——所以**差异化打法不是掩饰年限，而是展示深度**：',
  '',
  '- 把「我写过 Rust」换成**「我能解释 Rust 为什么这么设计」**：为什么 `Rc` 不是 `Send`、为什么跨 `.await` 持 `std` 的锁编译不过、`clone` 在什么时候是设计信号而不是解法。这类回答立刻把你和「照着文档抄 axum」的人分开。',
  '- 把过往语言的经验**折算**过来：写过 Go 的讲「channel 和 mpsc 的取舍」，写过 C++ 的讲「RAII 与所有权的对应、Rust 如何在编译期消灭 use-after-free」，写过 Java/Python 的讲「GC 停顿 vs 确定性析构」。年限不是零，只是换了个坐标系。',
  '- **投递策略**：优先「Rust + 你熟悉的领域」（后端、数据、区块链、嵌入式、CLI 工具），领域知识能补掉语言年限；也留意标注 Go/C++ 且团队正在迁移 Rust 的岗位。',
  '- **公开你的学习轨迹**：一个持续更新的 GitHub、几篇写清楚踩坑过程的技术笔记、给依赖的 crate 提过的 issue 或小 PR——这些是零经验者能拿出的最强信号。',
  '',
  '### 八、毕业标准',
  '',
  '这套课程的终点不是「做完所有练习」，而是下面这两条同时成立：',
  '',
  '1. **p4 的验收清单全部打勾**：REST CRUD 五个端点、迁移、统一错误映射、WebSocket 广播、tracing 日志、集成测试、多阶段 Dockerfile 跑得起来、CI 三步全绿、README 别人照着能跑。',
  '2. **你能在白板上讲清楚一个真实服务的架构**——从请求进来经过哪些中间件、状态放在哪、错误怎么冒泡成 HTTP 状态码、连接池多大、日志怎么串起来、发版时旧实例怎么优雅退出，一路讲到部署拓扑。',
  '',
  '第二条比第一条重要。写得出代码的人不少，**能把系统讲明白的人才拿得到 senior 的价码**。',
  '',
  '---',
  '',
  '### 完成本模块后你能…',
  '',
  '- [ ] 说清楚结构化日志为什么比 `println!` 强，用 `tracing` 的 event 与 span 记录带字段的日志',
  '- [ ] 用 `#[instrument(skip(...))]` 给 handler 加上下文，用 `EnvFilter` + `RUST_LOG` 在不改代码的前提下调级别',
  '- [ ] 背出生产日志三条纪律：request_id 贯穿全链路、分级有纪律、绝不记录敏感信息',
  '- [ ] 在库里用 `thiserror` 定义类型化错误、在应用入口用 `anyhow` 收口，并把错误映射成 HTTP 状态码',
  '- [ ] 实现「默认值 < 配置文件 < 环境变量」的分层配置，启动即校验，拼错的变量会报错而不是静默忽略',
  '- [ ] 写出带依赖层缓存的多阶段 Dockerfile，把镜像压到百 MB 级，并说明 musl 静态编译的取舍',
  '- [ ] 配一份 GitHub Actions：fmt --check → clippy -D warnings → test → build，带依赖缓存',
  '- [ ] 在裸 VPS + systemd、容器、平台三种部署形态之间按场景选型，并实现 SIGTERM 优雅关闭与健康检查',
  '- [ ] 用量化模板把 p1–p4 写进简历，按清单整理好 GitHub，对着 `/resources` 的 JD 表与题库完成面试准备',
].join('\n');
