import type { Exercise } from '@/lib/rust/types';

export const module3Exercises: Exercise[] = [
  {
    id: 'm3-01',
    moduleId: 'm3',
    title: '定义并实现第一个 trait',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### trait：给不同类型约定同一种能力',
      '',
      '`trait` 像一份能力契约：只要类型实现了 `Greeting`，就必须提供 `name`，同时可以直接复用默认方法 `greet`。',
      '',
      '```rust',
      'trait Greeting {',
      '    fn name(&self) -> &str;',
      '',
      '    fn greet(&self) -> String {',
      '        format!("你好，{}！", self.name())',
      '    }',
      '}',
      '```',
      '',
      '**要求**：',
      '',
      '1. 为 `Student` 实现 `Greeting`，让 `name` 返回学生姓名；',
      '2. 为 `Robot` 实现 `Greeting`，让 `name` 返回机器人型号；',
      '3. 在 `main` 中分别调用两个值继承到的默认方法 `greet`。',
      '',
      '程序必须恰好输出：',
      '',
      '```text',
      '你好，Ferris！',
      '你好，RustBot！',
      '```',
      '',
      '两个类型没有继承关系，却能通过同一份 trait 获得一致行为；这正是 Rust 组合式抽象的起点。',
    ].join('\n'),
    starterCode: [
      'trait Greeting {',
      '    fn name(&self) -> &str;',
      '',
      '    fn greet(&self) -> String {',
      '        format!("你好，{}！", self.name())',
      '    }',
      '}',
      '',
      'struct Student {',
      '    name: String,',
      '}',
      '',
      'struct Robot {',
      '    model: String,',
      '}',
      '',
      'impl Greeting for Student {',
      '    fn name(&self) -> &str {',
      '        // TODO: 返回学生姓名的字符串切片',
      '        ""',
      '    }',
      '}',
      '',
      'impl Greeting for Robot {',
      '    fn name(&self) -> &str {',
      '        // TODO: 返回机器人型号的字符串切片',
      '        ""',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let student = Student { name: String::from("Ferris") };',
      '    let robot = Robot { model: String::from("RustBot") };',
      '',
      '    println!("{}", student.greet());',
      '    println!("{}", robot.greet());',
      '}',
    ].join('\n'),
    solutionCode: [
      'trait Greeting {',
      '    fn name(&self) -> &str;',
      '',
      '    fn greet(&self) -> String {',
      '        format!("你好，{}！", self.name())',
      '    }',
      '}',
      '',
      'struct Student {',
      '    name: String,',
      '}',
      '',
      'struct Robot {',
      '    model: String,',
      '}',
      '',
      'impl Greeting for Student {',
      '    fn name(&self) -> &str {',
      '        &self.name',
      '    }',
      '}',
      '',
      'impl Greeting for Robot {',
      '    fn name(&self) -> &str {',
      '        &self.model',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let student = Student { name: String::from("Ferris") };',
      '    let robot = Robot { model: String::from("RustBot") };',
      '',
      '    println!("{}", student.greet());',
      '    println!("{}", robot.greet());',
      '}',
    ].join('\n'),
    expectedStdout: '你好，Ferris！\n你好，RustBot！\n',
    hints: [
      '`impl Trait for Type` 表示为某个具体类型实现这份能力契约。',
      '`name` 返回的是借用，不需要克隆字段；`&String` 会自动转换成 `&str`。',
      '两个方法体分别写 `&self.name` 和 `&self.model`，默认的 `greet` 不用重复实现。',
    ],
  },
  {
    id: 'm3-02',
    moduleId: 'm3',
    title: '泛型 largest 与 trait bound',
    difficulty: 2,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 一份算法，同时服务多种可比较类型',
      '',
      '**要求**：实现下面的泛型函数：',
      '',
      '```rust',
      'pub fn largest<T: PartialOrd + Copy>(list: &[T]) -> T',
      '```',
      '',
      '返回非空切片中最大的元素。`T` 不是某个具体类型，而是类型参数；两个约束分别表示：',
      '',
      '- `PartialOrd`：元素可以使用 `>` 比较；',
      '- `Copy`：可以把元素值从切片中复制出来作为返回值。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `&[3, 8, 2, 5]` | `8` |',
      '| `&[-10, -3, -20]` | `-3` |',
      '| `&[\'a\', \'z\', \'m\']` | `\'z\'` |',
      '',
      '本题约定 `list` **至少包含一个元素**。以隐藏单元测试判分，不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'pub fn largest<T: PartialOrd + Copy>(list: &[T]) -> T {',
      '    // TODO: 以第一个元素为当前最大值，遍历剩余元素并更新',
      '    list[0]',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn largest<T: PartialOrd + Copy>(list: &[T]) -> T {',
      '    let mut largest = list[0];',
      '',
      '    for &item in &list[1..] {',
      '        if item > largest {',
      '            largest = item;',
      '        }',
      '    }',
      '',
      '    largest',
      '}',
    ].join('\n'),
    hints: [
      '先写 `let mut largest = list[0];`，这样无需为“尚未找到元素”引入 `Option`。',
      '遍历 `&list[1..]`；模式 `for &item in ...` 会利用 `Copy` 得到值，而不是引用。',
      '循环中判断 `if item > largest { largest = item; }`，最后返回 `largest`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn finds_largest_integer() {',
      '        assert_eq!(largest(&[3, 8, 2, 5]), 8);',
      '    }',
      '',
      '    #[test]',
      '    fn handles_negative_integers() {',
      '        assert_eq!(largest(&[-10, -3, -20]), -3);',
      '    }',
      '',
      '    #[test]',
      '    fn compares_characters() {',
      "        assert_eq!(largest(&['a', 'z', 'm']), 'z');",
      '    }',
      '',
      '    #[test]',
      '    fn returns_the_only_element() {',
      '        assert_eq!(largest(&[42_u8]), 42);',
      '    }',
      '',
      '    #[test]',
      '    fn compares_floating_point_values() {',
      '        assert_eq!(largest(&[1.25_f64, 9.5, 3.75]), 9.5);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm3-03',
    moduleId: 'm3',
    title: '修复 E0369：缺少比较约束',
    difficulty: 3,
    judgeMode: 'compile',
    assertSource: [
      "// 断言：is_greater 必须是泛型函数（对多种可比较类型都可用）且返回 bool。",
      "// 写死成 fn is_greater(a: i32, b: i32) 这类特化版本会在这里编译失败。",
      "const _SIG_INT: fn(i32, i32) -> bool = is_greater;",
      "const _SIG_CHAR: fn(char, char) -> bool = is_greater;",
    ].join('\n'),
    prompt: [
      '### 泛型不是“什么操作都能做”',
      '',
      '下面的代码会触发类似错误：',
      '',
      '```text',
      'error[E0369]: binary operation `>` cannot be applied to type `T`',
      '```',
      '',
      '`T` 默认只代表“某个未知类型”。编译器不能假设所有类型都支持 `>`；只有在签名中写明 trait bound，函数体才有权使用对应能力。',
      '',
      '**要求**：只修改 `is_greater` 的泛型声明，为 `T` 添加恰当约束，让代码编译通过。不要把函数改成只接受 `i32`。',
      '',
      '修复后的函数应同时能比较整数和字符。这里不要求 `Copy`，因为 `PartialOrd` 的比较方法借用两侧值。',
    ].join('\n'),
    starterCode: [
      '// TODO: T 缺少支持 > 运算所需的 trait bound',
      'fn is_greater<T>(left: T, right: T) -> bool {',
      '    left > right',
      '}',
      '',
      'fn main() {',
      '    assert!(is_greater(9, 4));',
      "    assert!(is_greater('z', 'a'));",
      '}',
    ].join('\n'),
    solutionCode: [
      'fn is_greater<T: PartialOrd>(left: T, right: T) -> bool {',
      '    left > right',
      '}',
      '',
      'fn main() {',
      '    assert!(is_greater(9, 4));',
      "    assert!(is_greater('z', 'a'));",
      '}',
    ].join('\n'),
    hints: [
      '报错里的 `>` 对应的是标准库 trait `PartialOrd` 提供的比较能力。',
      '把约束写在尖括号内：`<T: 某个Trait>`。',
      '完整签名是 `fn is_greater<T: PartialOrd>(left: T, right: T) -> bool`。',
    ],
  },
  {
    id: 'm3-04',
    moduleId: 'm3',
    title: 'Summary：默认方法与 override',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 默认行为可以复用，也可以按类型改写',
      '',
      '请完成 `Summary` trait 及两个实现：',
      '',
      '```rust',
      'pub trait Summary {',
      '    fn headline(&self) -> &str;',
      '',
      '    fn summarize(&self) -> String {',
      '        // 默认实现必须调用 required 方法 headline',
      '    }',
      '}',
      '```',
      '',
      '**规则**：',
      '',
      '- `Article` 只实现 required 方法 `headline`，直接继承默认摘要：`（继续阅读）<标题>`；',
      '- `Alert` 同时实现 `headline`，并 override `summarize`：`[P<级别>] <标题>`；',
      '- 方法应返回借用或新建的 `String`，不要泄漏内存。',
      '',
      '例如文章标题 `"Rust trait 入门"` 的摘要是 `"（继续阅读）Rust trait 入门"`；',
      '级别为 `1`、标题为 `"服务不可用"` 的告警摘要是 `"[P1] 服务不可用"`。',
      '',
      '本题以隐藏单元测试判分，不要写 `main`。所有给出的公共类型和 trait 名称都要保留。',
    ].join('\n'),
    starterCode: [
      'pub trait Summary {',
      '    fn headline(&self) -> &str;',
      '',
      '    fn summarize(&self) -> String {',
      '        // TODO: 调用 required 方法 headline，返回“（继续阅读）<标题>”',
      '        String::new()',
      '    }',
      '}',
      '',
      'pub struct Article {',
      '    pub headline: String,',
      '}',
      '',
      'pub struct Alert {',
      '    pub level: u8,',
      '    pub headline: String,',
      '}',
      '',
      'impl Summary for Article {',
      '    fn headline(&self) -> &str {',
      '        // TODO: 返回字段的字符串切片',
      '        ""',
      '    }',
      '}',
      '',
      'impl Summary for Alert {',
      '    fn headline(&self) -> &str {',
      '        // TODO: 返回字段的字符串切片',
      '        ""',
      '    }',
      '',
      '    fn summarize(&self) -> String {',
      '        // TODO: override 默认方法，返回“[P<级别>] <标题>”',
      '        String::new()',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub trait Summary {',
      '    fn headline(&self) -> &str;',
      '',
      '    fn summarize(&self) -> String {',
      '        format!("（继续阅读）{}", self.headline())',
      '    }',
      '}',
      '',
      'pub struct Article {',
      '    pub headline: String,',
      '}',
      '',
      'pub struct Alert {',
      '    pub level: u8,',
      '    pub headline: String,',
      '}',
      '',
      'impl Summary for Article {',
      '    fn headline(&self) -> &str {',
      '        &self.headline',
      '    }',
      '}',
      '',
      'impl Summary for Alert {',
      '    fn headline(&self) -> &str {',
      '        &self.headline',
      '    }',
      '',
      '    fn summarize(&self) -> String {',
      '        format!("[P{}] {}", self.level, self.headline())',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '默认方法里可以调用同一 trait 的 required 方法：`self.headline()`。',
      '`Article` 无需再写 `summarize`；`Alert` 写同名方法就会覆盖默认实现。',
      '默认实现用 `format!("（继续阅读）{}", self.headline())`，告警实现用 `format!("[P{}] {}", self.level, self.headline())`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn article_uses_default_summary() {',
      '        let article = Article { headline: String::from("Rust trait 入门") };',
      '        assert_eq!(article.summarize(), "（继续阅读）Rust trait 入门");',
      '    }',
      '',
      '    #[test]',
      '    fn alert_overrides_default_summary() {',
      '        let alert = Alert { level: 1, headline: String::from("服务不可用") };',
      '        assert_eq!(alert.summarize(), "[P1] 服务不可用");',
      '    }',
      '',
      '    #[test]',
      '    fn required_method_exposes_article_headline() {',
      '        let article = Article { headline: String::from("零成本抽象") };',
      '        assert_eq!(article.headline(), "零成本抽象");',
      '    }',
      '',
      '    #[test]',
      '    fn required_method_exposes_alert_headline() {',
      '        let alert = Alert { level: 3, headline: String::from("延迟升高") };',
      '        assert_eq!(alert.headline(), "延迟升高");',
      '    }',
      '',
      '    #[test]',
      '    fn default_summary_handles_empty_headline() {',
      '        let article = Article { headline: String::new() };',
      '        assert_eq!(article.summarize(), "（继续阅读）");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm3-05',
    moduleId: 'm3',
    title: 'trait object 与动态分发',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 把不同具体类型放进同一个集合',
      '',
      '`Circle` 和 `Rectangle` 的大小、字段都不同，所以不能直接放进同一个普通 `Vec<T>`。',
      '`Box<dyn Shape>` 是 trait object：`Box` 在堆上持有具体值，`dyn Shape` 让调用在运行时通过 vtable 分发。',
      '',
      '**要求**：',
      '',
      '1. 为 `Circle` 和 `Rectangle` 实现 `Shape`；',
      '2. 圆面积使用 `std::f64::consts::PI * radius * radius`，矩形面积是 `width * height`；',
      '3. 构造一个 `Vec<Box<dyn Shape>>`，依次放入半径 `2.0` 的圆和 `3.0 × 4.0` 的矩形；',
      '4. 遍历集合，按两位小数打印名称与面积。',
      '',
      '程序必须恰好输出：',
      '',
      '```text',
      '圆：12.57',
      '矩形：12.00',
      '```',
      '',
      '这里必须保留异构集合和 `dyn Shape`，不要改成两个独立变量分别打印。',
    ].join('\n'),
    starterCode: [
      'trait Shape {',
      "    fn name(&self) -> &'static str;",
      '    fn area(&self) -> f64;',
      '}',
      '',
      'struct Circle {',
      '    radius: f64,',
      '}',
      '',
      'struct Rectangle {',
      '    width: f64,',
      '    height: f64,',
      '}',
      '',
      'impl Shape for Circle {',
      "    fn name(&self) -> &'static str {",
      '        "圆"',
      '    }',
      '',
      '    fn area(&self) -> f64 {',
      '        // TODO: 计算圆面积',
      '        0.0',
      '    }',
      '}',
      '',
      'impl Shape for Rectangle {',
      "    fn name(&self) -> &'static str {",
      '        "矩形"',
      '    }',
      '',
      '    fn area(&self) -> f64 {',
      '        // TODO: 计算矩形面积',
      '        0.0',
      '    }',
      '}',
      '',
      'fn main() {',
      '    // TODO: 创建 Vec<Box<dyn Shape>>，依次放入题面指定的圆和矩形',
      '    let shapes: Vec<Box<dyn Shape>> = Vec::new();',
      '',
      '    for shape in shapes {',
      '        println!("{}：{:.2}", shape.name(), shape.area());',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'trait Shape {',
      "    fn name(&self) -> &'static str;",
      '    fn area(&self) -> f64;',
      '}',
      '',
      'struct Circle {',
      '    radius: f64,',
      '}',
      '',
      'struct Rectangle {',
      '    width: f64,',
      '    height: f64,',
      '}',
      '',
      'impl Shape for Circle {',
      "    fn name(&self) -> &'static str {",
      '        "圆"',
      '    }',
      '',
      '    fn area(&self) -> f64 {',
      '        std::f64::consts::PI * self.radius * self.radius',
      '    }',
      '}',
      '',
      'impl Shape for Rectangle {',
      "    fn name(&self) -> &'static str {",
      '        "矩形"',
      '    }',
      '',
      '    fn area(&self) -> f64 {',
      '        self.width * self.height',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let shapes: Vec<Box<dyn Shape>> = vec![',
      '        Box::new(Circle { radius: 2.0 }),',
      '        Box::new(Rectangle { width: 3.0, height: 4.0 }),',
      '    ];',
      '',
      '    for shape in shapes {',
      '        println!("{}：{:.2}", shape.name(), shape.area());',
      '    }',
      '}',
    ].join('\n'),
    expectedStdout: '圆：12.57\n矩形：12.00\n',
    hints: [
      '两个 `area` 分别返回 `PI * self.radius * self.radius` 和 `self.width * self.height`。',
      '异构集合的类型要显式写成 `Vec<Box<dyn Shape>>`，每个具体值用 `Box::new(...)` 包起来。',
      '构造式是 `vec![Box::new(Circle { radius: 2.0 }), Box::new(Rectangle { width: 3.0, height: 4.0 })]`。',
    ],
  },
  {
    id: 'm3-06',
    moduleId: 'm3',
    title: '修复悬垂引用：返回所有权',
    difficulty: 3,
    judgeMode: 'compile',
    expectedStdout: "trait ready\n",
    prompt: [
      '### 为什么不能返回局部变量的引用',
      '',
      '下面的函数试图返回局部 `String` 的切片，会看到 `E0106` / `E0515` 一类诊断：',
      '',
      '```text',
      'error[E0106]: missing lifetime specifier',
      'error[E0515]: cannot return reference to local variable `label`',
      '```',
      '',
      '`label` 在函数结束时就会被释放；若允许返回 `&label`，调用方拿到的将是悬垂引用。这里没有任何生命周期标注能让局部值活得更久。',
      '',
      '**要求**：把 `make_label` 改为返回拥有所有权的 `String`，并直接把局部值移交给调用方。保留 `main` 的打印逻辑。',
      '',
      '修复原则是“让数据的所有权跟着返回值离开函数”，而不是随便添加一个看似很长的生命周期。',
    ].join('\n'),
    starterCode: [
      '// TODO: 不能返回局部 String 的引用，应改为返回拥有所有权的 String',
      'fn make_label() -> &str {',
      '    let label = String::from("trait ready");',
      '    &label',
      '}',
      '',
      'fn main() {',
      '    let label = make_label();',
      '    println!("{label}");',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn make_label() -> String {',
      '    let label = String::from("trait ready");',
      '    label',
      '}',
      '',
      'fn main() {',
      '    let label = make_label();',
      '    println!("{label}");',
      '}',
    ].join('\n'),
    hints: [
      '函数内部创建的数据必须由某个所有者带出函数，否则作用域结束就会被 drop。',
      '把返回类型从 `&str` 改成 `String`，这样调用方会接管堆字符串。',
      '签名写 `fn make_label() -> String`，最后一个表达式直接写 `label`，不要加 `&`。',
    ],
  },
  {
    id: 'm3-07',
    moduleId: 'm3',
    title: 'longest：标注输入输出关系',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 生命周期经典题：返回值到底借自谁',
      '',
      '**要求**：实现下面的函数，并显式写出生命周期参数：',
      '',
      "```rust",
      "pub fn longest<'a>(x: &'a str, y: &'a str) -> &'a str",
      '```',
      '',
      '返回**字节长度**较长的字符串切片；长度相等时返回 `x`。函数不创建新字符串，返回值必须借自两个输入之一。',
      '',
      '生命周期 `\'a` 的意思不是“让字符串多活一会儿”，而是告诉借用检查器：返回引用的有效范围不能超过两个输入引用都有效的重叠范围。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `"rust"`、`"go"` | `"rust"` |',
      '| `"cat"`、`"ferris"` | `"ferris"` |',
      '| `"ab"`、`"cd"` | `"ab"` |',
      '',
      '本题以隐藏单元测试判分，不要写 `main`，函数必须是 `pub`，也不要通过 `Box::leak` 制造伪静态引用。',
    ].join('\n'),
    starterCode: [
      '// TODO: 为两个输入引用和返回引用补上同一个生命周期参数',
      'pub fn longest(x: &str, y: &str) -> &str {',
      '    if x.len() >= y.len() {',
      '        x',
      '    } else {',
      '        y',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      "pub fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {",
      '    if x.len() >= y.len() {',
      '        x',
      '    } else {',
      '        y',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '有两个输入引用时，省略规则无法判断返回值来自哪一个，所以需要自己命名关系。',
      "在函数名后声明 `<'a>`，再把三个引用都写成 `&'a str`。",
      "完整签名是 `pub fn longest<'a>(x: &'a str, y: &'a str) -> &'a str`。",
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn returns_first_when_it_is_longer() {',
      '        assert_eq!(longest("rust", "go"), "rust");',
      '    }',
      '',
      '    #[test]',
      '    fn returns_second_when_it_is_longer() {',
      '        assert_eq!(longest("cat", "ferris"), "ferris");',
      '    }',
      '',
      '    #[test]',
      '    fn equal_length_prefers_first() {',
      '        assert_eq!(longest("ab", "cd"), "ab");',
      '    }',
      '',
      '    #[test]',
      '    fn handles_empty_strings() {',
      '        assert_eq!(longest("", "rust"), "rust");',
      '        assert_eq!(longest("", ""), "");',
      '    }',
      '',
      '    #[test]',
      '    fn borrows_from_owned_strings() {',
      '        let left = String::from("lifetime");',
      '        let right = String::from("trait");',
      '        assert_eq!(longest(&left, &right), "lifetime");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm3-08',
    moduleId: 'm3',
    title: '修复持有引用的结构体',
    difficulty: 4,
    judgeMode: 'compile',
    assertSource: [
      "// 断言：Excerpt 必须真的持有借用（带生命周期参数），而不是改成 String 绕过；",
      "// part() 必须返回借用而不是新分配的 String。",
      "fn _assert_holds_borrow<'a>(text: &'a str) -> Excerpt<'a> {",
      "    Excerpt { part: text }",
      "}",
      "fn _assert_part_returns_borrow<'a>(excerpt: &'a Excerpt<'a>) -> &'a str {",
      "    excerpt.part()",
      "}",
    ].join('\n'),
    prompt: [
      '### struct 里的引用也必须说明来源关系',
      '',
      '下面的 `Excerpt` 持有一个 `&str` 字段，却没有生命周期参数，因此会触发：',
      '',
      '```text',
      'error[E0106]: missing lifetime specifier',
      '```',
      '',
      '结构体实例不能比它借用的文本活得更久。编译器需要一个名字来表达这种关系：`Excerpt<\'a>` 中的 `part` 来自某个至少活到 `\'a` 的字符串。',
      '',
      '**要求**：',
      '',
      '1. 给结构体声明生命周期参数，并把它标到 `part` 字段；',
      '2. 给 `impl` 块补上对应的生命周期声明与类型实参；',
      '3. 保留 `part(&self) -> &str` 方法和 `main` 的行为。',
      '',
      '本题只判编译运行是否成功。不要把字段改成 `String`；这一题要练习的正是“结构体持有引用”。',
    ].join('\n'),
    starterCode: [
      '// TODO: 为持有引用的结构体声明生命周期参数',
      'struct Excerpt {',
      '    part: &str,',
      '}',
      '',
      '// TODO: impl 块也需要对应的生命周期声明与类型实参',
      'impl Excerpt {',
      '    fn part(&self) -> &str {',
      '        self.part',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let novel = String::from("第一句。第二句。");',
      '    let excerpt = Excerpt { part: &novel[..12] };',
      '    assert_eq!(excerpt.part(), "第一句。");',
      '}',
    ].join('\n'),
    solutionCode: [
      "struct Excerpt<'a> {",
      "    part: &'a str,",
      '}',
      '',
      "impl<'a> Excerpt<'a> {",
      '    fn part(&self) -> &str {',
      '        self.part',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let novel = String::from("第一句。第二句。");',
      '    let excerpt = Excerpt { part: &novel[..12] };',
      '    assert_eq!(excerpt.part(), "第一句。");',
      '}',
    ].join('\n'),
    hints: [
      '生命周期参数和泛型参数一样写在类型名后的尖括号里，例如 `Type<\'a>`。',
      '字段写成 `part: &\'a str`；实现时既要声明 `impl<\'a>`，也要写目标类型 `Excerpt<\'a>`。',
      "两处完整形式分别是 `struct Excerpt<'a>` 与 `impl<'a> Excerpt<'a>`。",
    ],
  },
  {
    id: 'm3-09',
    moduleId: 'm3',
    title: '综合：Pair 的条件实现与 From',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 只在能力足够时开放方法',
      '',
      '完成通用二元组类型 `Pair<T>`：',
      '',
      '```rust',
      'pub struct Pair<T> {',
      '    pub x: T,',
      '    pub y: T,',
      '}',
      '```',
      '',
      '**要求**：',
      '',
      '1. 保留对所有 `T` 都可用的构造函数 `Pair::new(x, y)`；',
      '2. 实现 `From<(T, T)> for Pair<T>`，让 `Pair::from((3, 8))` 保持原顺序转换；',
      '3. 仅当 `T: Display + PartialOrd` 时提供 `cmp_display(&self) -> String`；',
      '4. `x >= y` 时返回 `较大的成员是 x = <x>`，否则返回 `较大的成员是 y = <y>`。',
      '',
      '相等时选择 `x`。`Display` 负责 `{}` 格式化，`PartialOrd` 负责 `>=` 比较；这就是**条件实现**：结构体本身可容纳任何 `T`，只有需要额外能力的方法才加约束。',
      '',
      '本题以隐藏单元测试判分，不要写 `main`。禁止把 `Pair` 写死成整数类型。',
    ].join('\n'),
    starterCode: [
      'use std::fmt::Display;',
      '',
      '#[derive(Debug, PartialEq)]',
      'pub struct Pair<T> {',
      '    pub x: T,',
      '    pub y: T,',
      '}',
      '',
      'impl<T> Pair<T> {',
      '    pub fn new(x: T, y: T) -> Self {',
      '        Self { x, y }',
      '    }',
      '}',
      '',
      'impl<T> From<(T, T)> for Pair<T> {',
      '    fn from(value: (T, T)) -> Self {',
      '        // TODO: 解构元组并保持原顺序构造 Pair',
      '        let _ = value;',
      '        todo!("实现 From<(T, T)>")',
      '    }',
      '}',
      '',
      'impl<T: Display + PartialOrd> Pair<T> {',
      '    pub fn cmp_display(&self) -> String {',
      '        // TODO: 比较 x/y，并格式化题面指定的字符串',
      '        todo!("实现 cmp_display")',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::fmt::Display;',
      '',
      '#[derive(Debug, PartialEq)]',
      'pub struct Pair<T> {',
      '    pub x: T,',
      '    pub y: T,',
      '}',
      '',
      'impl<T> Pair<T> {',
      '    pub fn new(x: T, y: T) -> Self {',
      '        Self { x, y }',
      '    }',
      '}',
      '',
      'impl<T> From<(T, T)> for Pair<T> {',
      '    fn from(value: (T, T)) -> Self {',
      '        let (x, y) = value;',
      '        Self { x, y }',
      '    }',
      '}',
      '',
      'impl<T: Display + PartialOrd> Pair<T> {',
      '    pub fn cmp_display(&self) -> String {',
      '        if self.x >= self.y {',
      '            format!("较大的成员是 x = {}", self.x)',
      '        } else {',
      '            format!("较大的成员是 y = {}", self.y)',
      '        }',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '`From` 的 `value` 可以用 `let (x, y) = value;` 解构，再写 `Self { x, y }`。',
      '把约束只放在第二个 `impl`：`impl<T: Display + PartialOrd> Pair<T>`，不要限制结构体定义。',
      '在 `cmp_display` 中判断 `self.x >= self.y`，两个分支分别用 `format!` 输出题面给定文本。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn new_keeps_both_members() {',
      '        let pair = Pair::new(vec![1], vec![2]);',
      '        assert_eq!(pair.x, vec![1]);',
      '        assert_eq!(pair.y, vec![2]);',
      '    }',
      '',
      '    #[test]',
      '    fn from_tuple_preserves_order() {',
      '        let pair = Pair::from((3, 8));',
      '        assert_eq!(pair, Pair::new(3, 8));',
      '    }',
      '',
      '    #[test]',
      '    fn displays_x_when_x_is_larger() {',
      '        assert_eq!(Pair::new(9, 4).cmp_display(), "较大的成员是 x = 9");',
      '    }',
      '',
      '    #[test]',
      '    fn displays_y_when_y_is_larger() {',
      '        assert_eq!(Pair::new(2.5, 7.25).cmp_display(), "较大的成员是 y = 7.25");',
      '    }',
      '',
      '    #[test]',
      '    fn equality_prefers_x_and_supports_strings() {',
      '        assert_eq!(Pair::new("same", "same").cmp_display(), "较大的成员是 x = same");',
      '    }',
      '}',
    ].join('\n'),
  },
];
