import type { Exercise } from '@/lib/rust/types';

export const module8Exercises: Exercise[] = [
  {
    id: 'm8-01',
    moduleId: 'm8',
    title: '修复：手写错误类型让 ? 用不了',
    difficulty: 4,
    judgeMode: 'compile',
    expectedStdout: "监听 0.0.0.0:8080\n",
    prompt: [
      '### 修编译错误：`?` 转换不了，`Box<dyn Error>` 也收不下',
      '',
      '下面这段配置加载代码编译不过。先点「运行」看编译器怎么说：',
      '',
      '```text',
      'error[E0271]: type mismatch resolving `<u16 as FromStr>::Err == ConfigError`',
      '   |     let port: u16 = raw.parse()?;',
      '   |                         ^^^^^ expected `ConfigError`, found `ParseIntError`',
      '',
      'error[E0277]: `?` couldn\'t convert the error: `ConfigError: std::error::Error` is not satisfied',
      '   = note: the question mark operation (`?`) implicitly performs a conversion',
      '           on the error value using the `From` trait',
      '   = note: required for `Box<dyn std::error::Error>` to implement `From<ConfigError>`',
      '```',
      '',
      '两个报错其实是同一件事：**`?` 靠的是 `From` 转换，而 `Box<dyn Error>` 靠的是 `std::error::Error`**。',
      '一个只 `#[derive(Debug)]` 的裸枚举，两样都没有：',
      '',
      '- `raw.parse::<u16>()?` 想把 `ParseIntError` 变成 `ConfigError`，需要 `impl From<ParseIntError> for ConfigError`；',
      '- `main` 返回 `Result<(), Box<dyn Error>>`，`?` 要把 `ConfigError` 装箱，前提是它实现了 `Error`（而 `Error` 又要求 `Display`）。',
      '',
      '手写这一套（`Display` + `Error` + 三个 `From`）大概三十行样板代码。生态里的标准做法是 **`thiserror`**：',
      '',
      '```rust',
      'use thiserror::Error;',
      '',
      '#[derive(Debug, Error)]',
      'pub enum StoreError {',
      '    #[error("找不到订单 {0}")]           // 生成 Display',
      '    NotFound(String),',
      '    #[error("数据库出错")]',
      '    Db(#[from] sqlx::Error),             // 生成 From，让 ? 自动转换；同时成为 source()',
      '}',
      '```',
      '',
      '**分层原则（面试常问）**：',
      '',
      '| 位置 | 用什么 | 为什么 |',
      '| --- | --- | --- |',
      '| 库 / 领域模块 | `thiserror` 定义具体枚举 | 调用方要能 `match` 出分支、映射成 HTTP 状态码 |',
      '| 应用入口 / main / 脚本 | `anyhow::Result` | 只需要「出错了就带上下文往上抛」，不需要类型化 |',
      '',
      '反过来在库里用 `anyhow` 会让调用方失去分支判断能力；在 main 里逐个定义枚举则纯属自找麻烦。',
      '',
      '**要求**：用 `thiserror` 改写 `ConfigError`（`Missing` 分支带 `#[error(...)]`，`BadPort` 分支用 `#[from]` 接住 `ParseIntError`），',
      '让代码编译通过并**恰好**输出：',
      '',
      '```text',
      '监听 0.0.0.0:8080',
      '```',
      '',
      '`thiserror` 在 Playground 上已经可用，直接 `use thiserror::Error;` 即可。',
    ].join('\n'),
    starterCode: [
      'use std::num::ParseIntError;',
      '',
      '/// 库里的错误类型：调用方要能 match 出具体分支',
      '// TODO: 用 thiserror 给这个枚举加上 Display（#[error(...)]）与 From（#[from]）',
      '#[derive(Debug)]',
      'pub enum ConfigError {',
      '    Missing(&\'static str),',
      '    BadPort(ParseIntError),',
      '}',
      '',
      'fn lookup(entries: &[(&str, &str)], key: &\'static str) -> Result<String, ConfigError> {',
      '    entries',
      '        .iter()',
      '        .find(|(k, _)| *k == key)',
      '        .map(|(_, v)| v.to_string())',
      '        .ok_or(ConfigError::Missing(key))',
      '}',
      '',
      'fn port_of(entries: &[(&str, &str)]) -> Result<u16, ConfigError> {',
      '    let raw = lookup(entries, "PORT")?;',
      '    let port: u16 = raw.parse()?; // 需要 From<ParseIntError> for ConfigError',
      '    Ok(port)',
      '}',
      '',
      'fn main() -> Result<(), Box<dyn std::error::Error>> {',
      '    let entries = [("HOST", "0.0.0.0"), ("PORT", "8080")];',
      '',
      '    let host = lookup(&entries, "HOST")?; // 需要 ConfigError: std::error::Error',
      '    let port = port_of(&entries)?;',
      '',
      '    println!("监听 {host}:{port}");',
      '    Ok(())',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::num::ParseIntError;',
      'use thiserror::Error;',
      '',
      '/// 库里的错误类型：调用方要能 match 出具体分支',
      '#[derive(Debug, Error)]',
      'pub enum ConfigError {',
      '    #[error("缺少配置项 {0}")]',
      '    Missing(&\'static str),',
      '    #[error("PORT 不是合法端口号")]',
      '    BadPort(#[from] ParseIntError),',
      '}',
      '',
      'fn lookup(entries: &[(&str, &str)], key: &\'static str) -> Result<String, ConfigError> {',
      '    entries',
      '        .iter()',
      '        .find(|(k, _)| *k == key)',
      '        .map(|(_, v)| v.to_string())',
      '        .ok_or(ConfigError::Missing(key))',
      '}',
      '',
      'fn port_of(entries: &[(&str, &str)]) -> Result<u16, ConfigError> {',
      '    let raw = lookup(entries, "PORT")?;',
      '    let port: u16 = raw.parse()?;',
      '    Ok(port)',
      '}',
      '',
      'fn main() -> Result<(), Box<dyn std::error::Error>> {',
      '    let entries = [("HOST", "0.0.0.0"), ("PORT", "8080")];',
      '',
      '    let host = lookup(&entries, "HOST")?;',
      '    let port = port_of(&entries)?;',
      '',
      '    println!("监听 {host}:{port}");',
      '    Ok(())',
      '}',
    ].join('\n'),
    hints: [
      '两个报错分别缺 `From<ParseIntError>` 和 `std::error::Error`，`thiserror` 的 `#[from]` 与 `#[derive(Error)]` 正好各补一个。',
      '结构是：`use thiserror::Error;` + `#[derive(Debug, Error)]`，每个分支上面写一行 `#[error("...")]`（`{0}` 引用元组字段）。',
      '`BadPort` 那一行写成 `BadPort(#[from] ParseIntError)`——`#[from]` 会同时生成 `From` 实现和 `source()`，`?` 就通了。',
    ],
  },
  {
    id: 'm8-02',
    moduleId: 'm8',
    title: '结构化日志：渲染一行 key=value',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 为什么日志要「结构化」',
      '',
      '`println!("用户 {} 下单失败：{}", user, err)` 这种日志，人能读，机器读不了。',
      '线上排查时你要问的是「过去 5 分钟 `status=500` 且 `route=/orders` 的请求有多少条」——',
      '要能这么查，日志就必须是**字段**而不是句子。这就是 `tracing` 的做法：',
      '',
      '```rust',
      'tracing::info!(order_id = %id, elapsed_ms = 12, "订单已创建");',
      '// 输出：INFO orders: order_id=8f3c elapsed_ms=12 message="订单已创建"',
      '```',
      '',
      '本题不接真实的 subscriber，只写渲染这一行文本的**纯函数**——这也是生产代码里最该被单测覆盖的部分。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn log_line(level: Level, target: &str, fields: &[(&str, &str)]) -> String',
      '```',
      '',
      '规则：',
      '',
      '1. 先输出等级与 target：`"{LEVEL} {target}"`，等级文本为 `ERROR` / `WARN` / `INFO` / `DEBUG`；',
      '2. **没有字段时到此为止**（不留尾空格、不留冒号）；',
      '3. 有字段时接 `": "`，然后按**给定顺序**输出 `key=value`，字段之间用一个空格分隔（重复 key 原样保留，不去重）；',
      '4. value 满足下列**任一**条件时要用双引号包起来：为空串、含空格、含 `=`、含 `"`、含 `\\`；',
      '5. 引号内做转义：`\\` 写成 `\\\\`，`"` 写成 `\\"`。',
      '',
      '示例：',
      '',
      '| 调用 | 输出 |',
      '| --- | --- |',
      '| `log_line(Level::Debug, "app", &[])` | `DEBUG app` |',
      '| `log_line(Level::Info, "orders", &[("request_id", "abc123"), ("elapsed_ms", "12")])` | `INFO orders: request_id=abc123 elapsed_ms=12` |',
      '| `log_line(Level::Error, "orders::db", &[("msg", "connection refused"), ("dsn", "")])` | `ERROR orders::db: msg="connection refused" dsn=""` |',
      '| `log_line(Level::Warn, "cache", &[("key", "a=b")])` | `WARN cache: key="a=b"` |',
      '',
      '**本题以隐藏测试判分**：不要写 `main`，`Level` 与 `log_line` 都必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
      'pub enum Level {',
      '    Error,',
      '    Warn,',
      '    Info,',
      '    Debug,',
      '}',
      '',
      'impl Level {',
      '    pub fn as_str(self) -> &\'static str {',
      '        match self {',
      '            Level::Error => "ERROR",',
      '            Level::Warn => "WARN",',
      '            Level::Info => "INFO",',
      '            Level::Debug => "DEBUG",',
      '        }',
      '    }',
      '}',
      '',
      '/// 判断一个值是否需要加引号：空串、含空格、含 = 、含 " 、含 \\',
      'fn needs_quotes(value: &str) -> bool {',
      '    // TODO: 实现判断',
      '    let _ = value;',
      '    false',
      '}',
      '',
      '/// 需要引号时包上双引号并转义 \\ 与 "，否则原样返回',
      'fn render_value(value: &str) -> String {',
      '    // TODO: 实现转义',
      '    value.to_string()',
      '}',
      '',
      'pub fn log_line(level: Level, target: &str, fields: &[(&str, &str)]) -> String {',
      '    // TODO: 拼 "{LEVEL} {target}"；有字段时再接 ": " 与空格分隔的 key=value',
      '    let _ = (level, target, fields);',
      '    String::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
      'pub enum Level {',
      '    Error,',
      '    Warn,',
      '    Info,',
      '    Debug,',
      '}',
      '',
      'impl Level {',
      '    pub fn as_str(self) -> &\'static str {',
      '        match self {',
      '            Level::Error => "ERROR",',
      '            Level::Warn => "WARN",',
      '            Level::Info => "INFO",',
      '            Level::Debug => "DEBUG",',
      '        }',
      '    }',
      '}',
      '',
      '/// 判断一个值是否需要加引号：空串、含空格、含 = 、含 " 、含 \\',
      'fn needs_quotes(value: &str) -> bool {',
      '    value.is_empty()',
      '        || value',
      '            .chars()',
      '            .any(|c| c == \' \' || c == \'=\' || c == \'"\' || c == \'\\\\\')',
      '}',
      '',
      '/// 需要引号时包上双引号并转义 \\ 与 "，否则原样返回',
      'fn render_value(value: &str) -> String {',
      '    if !needs_quotes(value) {',
      '        return value.to_string();',
      '    }',
      '',
      '    let mut out = String::with_capacity(value.len() + 2);',
      '    out.push(\'"\');',
      '    for c in value.chars() {',
      '        match c {',
      '            \'\\\\\' => out.push_str("\\\\\\\\"),',
      '            \'"\' => out.push_str("\\\\\\""),',
      '            _ => out.push(c),',
      '        }',
      '    }',
      '    out.push(\'"\');',
      '    out',
      '}',
      '',
      'pub fn log_line(level: Level, target: &str, fields: &[(&str, &str)]) -> String {',
      '    let mut out = format!("{} {}", level.as_str(), target);',
      '',
      '    for (index, (key, value)) in fields.iter().enumerate() {',
      '        out.push_str(if index == 0 { ": " } else { " " });',
      '        out.push_str(key);',
      '        out.push(\'=\');',
      '        out.push_str(&render_value(value));',
      '    }',
      '',
      '    out',
      '}',
    ].join('\n'),
    hints: [
      '先把「无字段」这条路走通：`format!("{} {}", level.as_str(), target)` 直接返回就是答案的一半。',
      '拼字段时用 `enumerate()`：第 0 个字段前面接 `": "`，其余接 `" "`——这样就不会多出尾随空格。',
      '转义要一次遍历 `chars()`：遇到 `\\\\` 推 `"\\\\\\\\"`、遇到 `"` 推 `"\\\\\\""`，其余原样；注意先判断 `needs_quotes` 再决定要不要包引号。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn no_fields_has_no_trailing_colon_or_space() {',
      '        assert_eq!(log_line(Level::Debug, "app", &[]), "DEBUG app");',
      '        assert_eq!(log_line(Level::Error, "orders::db", &[]), "ERROR orders::db");',
      '    }',
      '',
      '    #[test]',
      '    fn plain_fields_keep_order() {',
      '        let line = log_line(',
      '            Level::Info,',
      '            "orders",',
      '            &[("request_id", "abc123"), ("elapsed_ms", "12")],',
      '        );',
      '        assert_eq!(line, "INFO orders: request_id=abc123 elapsed_ms=12");',
      '    }',
      '',
      '    #[test]',
      '    fn quotes_spaces_and_empty_values() {',
      '        let line = log_line(',
      '            Level::Error,',
      '            "orders::db",',
      '            &[("msg", "connection refused"), ("dsn", "")],',
      '        );',
      '        assert_eq!(line, r#"ERROR orders::db: msg="connection refused" dsn="""#);',
      '    }',
      '',
      '    #[test]',
      '    fn quotes_equals_and_escapes_quotes() {',
      '        let line = log_line(Level::Warn, "cache", &[("key", "a=b"), ("note", "say \\"hi\\"")]);',
      '        assert_eq!(line, r#"WARN cache: key="a=b" note="say \\"hi\\"""#);',
      '    }',
      '',
      '    #[test]',
      '    fn escapes_backslash_and_keeps_duplicate_keys() {',
      '        let line = log_line(',
      '            Level::Info,',
      '            "fs",',
      '            &[("path", "C:\\\\logs"), ("tag", "a"), ("tag", "b")],',
      '        );',
      '        assert_eq!(line, r#"INFO fs: path="C:\\\\logs" tag=a tag=b"#);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm8-03',
    moduleId: 'm8',
    title: '配置分层：默认值 + 环境变量覆盖',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 十二要素里的配置层级',
      '',
      '生产服务的配置从来不是一个来源，而是**层层覆盖**：',
      '',
      '```text',
      '内置默认值  <  配置文件  <  环境变量  <  命令行参数     （右边优先级更高）',
      '```',
      '',
      '为什么环境变量优先级高？因为同一个镜像要在 dev / staging / prod 跑，代码不能改、配置文件也不该塞进镜像，',
      '能变的只有启动时注入的环境变量。`config`、`figment` 这类 crate 干的就是这件事，本题手写一个最小版。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn load_config(defaults: &str, env_overrides: &[(&str, &str)]) -> Result<Config, String>',
      '```',
      '',
      '- `defaults` 是一段 JSON 对象文本（默认配置层）；',
      '- `env_overrides` 是「环境变量名 → 字符串值」列表，**按顺序应用，后面的赢**；',
      '- 只认 `APP_` 前缀，其余条目直接忽略（真实环境里 `PATH`、`HOME` 也都在环境变量里）；',
      '- 字段名 = 去掉 `APP_` 前缀后**转小写**，例如 `APP_PORT` → `port`；',
      '- 环境变量的值永远是字符串，要按 `defaults` 里该字段的 JSON 类型转换：',
      '',
      '| defaults 里的类型 | 转换规则 | 失败时 |',
      '| --- | --- | --- |',
      '| 数字 | `parse::<u64>()` | `Err`，消息含 `期望数字` |',
      '| 布尔 | 只接受 `"true"` / `"false"` | `Err`，消息含 `期望 true/false` |',
      '| 字符串 | 原样使用 | — |',
      '',
      '错误一律返回 `Err(String)`，消息里必须包含下列关键词之一：',
      '',
      '- `defaults` 不是合法 JSON 对象 → 含 `默认配置`',
      '- 覆盖了 `defaults` 里不存在的字段 → 含 `未知配置项`（拼错的环境变量必须报错，静默忽略是生产事故的常见源头）',
      '- 类型转换失败 → 含 `期望数字` 或 `期望 true/false`',
      '- 最终结构体反序列化失败（缺字段、端口越界等）→ 含 `配置校验失败`',
      '',
      '示例：',
      '',
      '```rust',
      'let defaults = r#"{"host":"127.0.0.1","port":8080,"workers":4,"debug":false}"#;',
      'let cfg = load_config(defaults, &[("APP_PORT", "9000"), ("PATH", "/usr/bin")]).unwrap();',
      'assert_eq!(cfg.port, 9000);      // 被覆盖',
      'assert_eq!(cfg.host, "127.0.0.1"); // 保持默认，PATH 被忽略',
      '```',
      '',
      '**本题以隐藏测试判分**：不要写 `main`，`Config` 与 `load_config` 必须是 `pub`。`serde` / `serde_json` 已在 Playground 可用。',
    ].join('\n'),
    starterCode: [
      'use serde::Deserialize;',
      'use serde_json::Value;',
      '',
      '#[derive(Debug, PartialEq, Deserialize)]',
      '#[serde(deny_unknown_fields)]',
      'pub struct Config {',
      '    pub host: String,',
      '    pub port: u16,',
      '    pub workers: usize,',
      '    pub debug: bool,',
      '}',
      '',
      'pub fn load_config(defaults: &str, env_overrides: &[(&str, &str)]) -> Result<Config, String> {',
      '    // TODO 1: 把 defaults 解析成 JSON 对象，失败或不是对象都返回含「默认配置」的错误',
      '    // TODO 2: 遍历 env_overrides，跳过不带 APP_ 前缀的；字段名去前缀后转小写',
      '    // TODO 3: 字段不在默认层里 -> 含「未知配置项」的错误；',
      '    //         在的话按默认值的 JSON 类型把字符串转成数字 / 布尔 / 字符串',
      '    // TODO 4: serde_json::from_value 出错 -> 含「配置校验失败」的错误',
      '    let _ = (defaults, env_overrides);',
      '    Err("尚未实现".to_string())',
      '}',
    ].join('\n'),
    solutionCode: [
      'use serde::Deserialize;',
      'use serde_json::Value;',
      '',
      '#[derive(Debug, PartialEq, Deserialize)]',
      '#[serde(deny_unknown_fields)]',
      'pub struct Config {',
      '    pub host: String,',
      '    pub port: u16,',
      '    pub workers: usize,',
      '    pub debug: bool,',
      '}',
      '',
      'pub fn load_config(defaults: &str, env_overrides: &[(&str, &str)]) -> Result<Config, String> {',
      '    let parsed: Value = serde_json::from_str(defaults)',
      '        .map_err(|e| format!("默认配置不是合法 JSON：{e}"))?;',
      '',
      '    let mut merged = match parsed {',
      '        Value::Object(map) => map,',
      '        _ => return Err("默认配置必须是一个 JSON 对象".to_string()),',
      '    };',
      '',
      '    for (raw_key, raw_value) in env_overrides {',
      '        let Some(name) = raw_key.strip_prefix("APP_") else {',
      '            continue;',
      '        };',
      '        let name = name.to_lowercase();',
      '',
      '        let current = merged',
      '            .get(&name)',
      '            .ok_or_else(|| format!("未知配置项 {name}（来自 {raw_key}）"))?;',
      '',
      '        let coerced = match current {',
      '            Value::Number(_) => {',
      '                let n: u64 = raw_value',
      '                    .parse()',
      '                    .map_err(|_| format!("{name} 期望数字，得到 {raw_value:?}"))?;',
      '                Value::from(n)',
      '            }',
      '            Value::Bool(_) => match *raw_value {',
      '                "true" => Value::Bool(true),',
      '                "false" => Value::Bool(false),',
      '                other => return Err(format!("{name} 期望 true/false，得到 {other:?}")),',
      '            },',
      '            Value::String(_) => Value::String(raw_value.to_string()),',
      '            _ => return Err(format!("{name} 的默认值类型不支持环境变量覆盖")),',
      '        };',
      '',
      '        merged.insert(name, coerced);',
      '    }',
      '',
      '    serde_json::from_value(Value::Object(merged))',
      '        .map_err(|e| format!("配置校验失败：{e}"))',
      '}',
    ].join('\n'),
    hints: [
      '先用 `serde_json::from_str::<Value>(defaults)?` 拿到 `Value::Object(map)`，后面所有覆盖都写进这个 map，最后一次性 `from_value` 成 `Config`——这就是「分层」的实现方式。',
      '筛前缀用 `raw_key.strip_prefix("APP_")`（返回 `Option<&str>`），配 let-else 写起来最干净；字段名记得 `to_lowercase()`。',
      '类型转换看的是 map 里**已有值**的类型：`Value::Number(_)` 就 `raw_value.parse::<u64>()`，`Value::Bool(_)` 就只认 `"true"`/`"false"`，`Value::String(_)` 直接 `Value::String(raw_value.to_string())`；查不到 key 就返回含「未知配置项」的错误。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    const DEFAULTS: &str = r#"{"host":"127.0.0.1","port":8080,"workers":4,"debug":false}"#;',
      '',
      '    #[test]',
      '    fn defaults_only() {',
      '        let cfg = load_config(DEFAULTS, &[]).expect("默认配置应当可用");',
      '        assert_eq!(cfg.host, "127.0.0.1");',
      '        assert_eq!(cfg.port, 8080);',
      '        assert_eq!(cfg.workers, 4);',
      '        assert!(!cfg.debug);',
      '    }',
      '',
      '    #[test]',
      '    fn env_overrides_win_and_unrelated_vars_are_ignored() {',
      '        let cfg = load_config(',
      '            DEFAULTS,',
      '            &[("APP_PORT", "9000"), ("PATH", "/usr/bin"), ("APP_HOST", "0.0.0.0")],',
      '        )',
      '        .expect("覆盖应当成功");',
      '        assert_eq!(cfg.port, 9000);',
      '        assert_eq!(cfg.host, "0.0.0.0");',
      '        assert_eq!(cfg.workers, 4);',
      '    }',
      '',
      '    #[test]',
      '    fn later_override_wins_and_bool_is_parsed() {',
      '        let cfg = load_config(',
      '            DEFAULTS,',
      '            &[("APP_DEBUG", "true"), ("APP_WORKERS", "1"), ("APP_WORKERS", "16")],',
      '        )',
      '        .expect("覆盖应当成功");',
      '        assert!(cfg.debug);',
      '        assert_eq!(cfg.workers, 16);',
      '    }',
      '',
      '    #[test]',
      '    fn unknown_key_is_rejected() {',
      '        let err = load_config(DEFAULTS, &[("APP_PROT", "9000")]).unwrap_err();',
      '        assert!(err.contains("未知配置项"), "实际错误：{err}");',
      '    }',
      '',
      '    #[test]',
      '    fn type_errors_are_reported() {',
      '        let err = load_config(DEFAULTS, &[("APP_PORT", "八千")]).unwrap_err();',
      '        assert!(err.contains("期望数字"), "实际错误：{err}");',
      '',
      '        let err = load_config(DEFAULTS, &[("APP_DEBUG", "yes")]).unwrap_err();',
      '        assert!(err.contains("期望 true/false"), "实际错误：{err}");',
      '    }',
      '',
      '    #[test]',
      '    fn broken_defaults_and_failed_validation() {',
      '        let err = load_config("{not json", &[]).unwrap_err();',
      '        assert!(err.contains("默认配置"), "实际错误：{err}");',
      '',
      '        let missing = r#"{"host":"127.0.0.1","port":8080,"workers":4}"#;',
      '        let err = load_config(missing, &[]).unwrap_err();',
      '        assert!(err.contains("配置校验失败"), "实际错误：{err}");',
      '',
      '        let err = load_config(DEFAULTS, &[("APP_PORT", "70000")]).unwrap_err();',
      '        assert!(err.contains("配置校验失败"), "实际错误：{err}");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm8-04',
    moduleId: 'm8',
    title: '修复：优雅退出骨架的借用与 move 错误',
    difficulty: 4,
    judgeMode: 'compile',
    expectedStdout: "worker 优雅退出，共处理 6 条任务\n",
    prompt: [
      '### 修编译错误：优雅关闭（graceful shutdown）',
      '',
      '容器编排（K8s、Fly.io、systemd）停服务的方式都一样：先发 `SIGTERM`，等你自己退出，超时才 `SIGKILL`。',
      '所以生产服务必须能**收到信号 → 停止接新活 → 把手上的活干完 → 退出**。标准骨架就是 `select!` + 关闭通道：',
      '',
      '```rust',
      'loop {',
      '    tokio::select! {',
      '        job = jobs.recv() => { /* 干活 */ }',
      '        _ = shutdown.changed() => break,   // 或 tokio::signal::ctrl_c()',
      '    }',
      '}',
      '```',
      '',
      '下面这段骨架编译不过，三个报错都是模块五、六里的老朋友：',
      '',
      '```text',
      'error[E0596]: cannot borrow `jobs` as mutable, as it is not declared as mutable',
      'error[E0596]: cannot borrow `shutdown` as mutable, as it is not declared as mutable',
      'error[E0382]: use of moved value: `tx`',
      '   note: `tx` was moved into the closure of a previous loop iteration',
      '```',
      '',
      '**学习点**：',
      '',
      '- `mpsc::Receiver::recv` 和 `watch::Receiver::changed` 都是 `&mut self`——接收端天生独占，形参要写 `mut jobs` / `mut shutdown`；',
      '- 每个生产者任务都要**自己的发送端**：`let tx = tx.clone();` 放在 `async move` 之前，克隆廉价（内部就是引用计数）；',
      '- 原始 `tx` 必须 `drop`，否则所有克隆结束后 `recv()` 也永远等不到 `None`——这是 mpsc 头号坑；',
      '- `watch::Sender::send` 在接收端全没了时返回 `Err`，关闭信号用 `let _ = ...` 忽略它才不会在退出路径上 panic。',
      '',
      '**要求**：只改必要的地方（两个 `mut` + 一次 `clone`），让它编译通过并**恰好**输出：',
      '',
      '```text',
      'worker 优雅退出，共处理 6 条任务',
      '```',
      '',
      '注意 worker 收到关闭信号后还用 `try_recv()` 把队列排干了——真实服务里这一步就是「不丢单」。',
    ].join('\n'),
    starterCode: [
      'use tokio::sync::{mpsc, watch};',
      '',
      '/// 消费任务直到收到关闭信号（或所有发送端都没了），再把队列排干，返回处理总数。',
      'async fn run_worker(jobs: mpsc::Receiver<u32>, shutdown: watch::Receiver<bool>) -> u32 {',
      '    let mut handled = 0;',
      '',
      '    loop {',
      '        tokio::select! {',
      '            job = jobs.recv() => {',
      '                match job {',
      '                    Some(_) => handled += 1,',
      '                    None => break, // 所有发送端都已 drop',
      '                }',
      '            }',
      '            _ = shutdown.changed() => break, // 收到关闭信号',
      '        }',
      '    }',
      '',
      '    // 优雅关闭：把已经进了队列的任务排干，不丢单',
      '    while jobs.try_recv().is_ok() {',
      '        handled += 1;',
      '    }',
      '',
      '    handled',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    let (tx, rx) = mpsc::channel::<u32>(32);',
      '    let (shutdown_tx, shutdown_rx) = watch::channel(false);',
      '',
      '    let worker = tokio::spawn(run_worker(rx, shutdown_rx));',
      '',
      '    let mut producers = Vec::new();',
      '    for i in 0..2u32 {',
      '        // TODO: 每个生产者任务都需要属于自己的发送端',
      '        producers.push(tokio::spawn(async move {',
      '            for j in 0..3u32 {',
      '                tx.send(i * 10 + j).await.expect("worker 还活着");',
      '            }',
      '        }));',
      '    }',
      '    drop(tx); // 原始发送端必须撤掉，否则 recv() 永远等不到 None',
      '',
      '    for producer in producers {',
      '        producer.await.expect("生产者不应 panic");',
      '    }',
      '',
      '    let _ = shutdown_tx.send(true); // 接收端可能已经退出，忽略 Err',
      '    let handled = worker.await.expect("worker 不应 panic");',
      '',
      '    println!("worker 优雅退出，共处理 {handled} 条任务");',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::sync::{mpsc, watch};',
      '',
      '/// 消费任务直到收到关闭信号（或所有发送端都没了），再把队列排干，返回处理总数。',
      'async fn run_worker(mut jobs: mpsc::Receiver<u32>, mut shutdown: watch::Receiver<bool>) -> u32 {',
      '    let mut handled = 0;',
      '',
      '    loop {',
      '        tokio::select! {',
      '            job = jobs.recv() => {',
      '                match job {',
      '                    Some(_) => handled += 1,',
      '                    None => break, // 所有发送端都已 drop',
      '                }',
      '            }',
      '            _ = shutdown.changed() => break, // 收到关闭信号',
      '        }',
      '    }',
      '',
      '    // 优雅关闭：把已经进了队列的任务排干，不丢单',
      '    while jobs.try_recv().is_ok() {',
      '        handled += 1;',
      '    }',
      '',
      '    handled',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    let (tx, rx) = mpsc::channel::<u32>(32);',
      '    let (shutdown_tx, shutdown_rx) = watch::channel(false);',
      '',
      '    let worker = tokio::spawn(run_worker(rx, shutdown_rx));',
      '',
      '    let mut producers = Vec::new();',
      '    for i in 0..2u32 {',
      '        let tx = tx.clone();',
      '        producers.push(tokio::spawn(async move {',
      '            for j in 0..3u32 {',
      '                tx.send(i * 10 + j).await.expect("worker 还活着");',
      '            }',
      '        }));',
      '    }',
      '    drop(tx); // 原始发送端必须撤掉，否则 recv() 永远等不到 None',
      '',
      '    for producer in producers {',
      '        producer.await.expect("生产者不应 panic");',
      '    }',
      '',
      '    let _ = shutdown_tx.send(true); // 接收端可能已经退出，忽略 Err',
      '    let handled = worker.await.expect("worker 不应 panic");',
      '',
      '    println!("worker 优雅退出，共处理 {handled} 条任务");',
      '}',
    ].join('\n'),
    hints: [
      '两个 `cannot borrow ... as mutable` 都出在 `run_worker` 的形参上：接收端的 `recv()` / `changed()` 都要 `&mut self`。',
      '`use of moved value: tx` 是因为循环第二轮时 `tx` 已经被第一个 `async move` 吃掉了；mpsc 的发送端本来就是设计成可以 clone 的。',
      '改三处：形参写成 `mut jobs: mpsc::Receiver<u32>, mut shutdown: watch::Receiver<bool>`，循环体第一行加 `let tx = tx.clone();`。',
    ],
  },
];
