import type { Exercise } from '@/lib/rust/types';

export const module4Exercises: Exercise[] = [
  {
    id: 'm4-01',
    moduleId: 'm4',
    title: '迭代器链：filter / map / collect',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### 用迭代器链代替手写循环',
      '',
      'Rust 的迭代器是**惰性**的：`iter()`、`filter()`、`map()` 都只是在搭一条流水线，',
      '直到遇到 `collect()` / `sum()` / `count()` 这类**消费器**才真正开始跑。',
      '',
      '```rust',
      'let v = vec![1, 2, 3, 4];',
      'let evens: Vec<i32> = v.iter().copied().filter(|n| n % 2 == 0).collect();',
      'let total: i32 = v.iter().sum();',
      'let n = v.iter().filter(|x| **x > 2).count();',
      '```',
      '',
      '两个新手必踩的点：',
      '',
      '- `v.iter()` 产出的是**引用** `&i32`，所以闭包参数常常要多解一层 `*`；加一个 `.copied()` 就能把流变成 `i32`，后面的闭包写起来干净得多。',
      '- `collect()` **必须**知道要收进什么容器，所以左边要写类型标注（`let x: Vec<i32> = ...`）或者用 `collect::<Vec<i32>>()`。',
      '',
      '**要求**：补全 `main`，让程序**恰好**输出：',
      '',
      '```text',
      '调整后：[93, 78, 90, 100, 69]',
      '及格人数 = 5',
      '总分 = 523',
      '最高分 = 100',
      '```',
      '',
      '规则：',
      '',
      '1. `adjusted`：只保留 **>= 60** 的分数，每个 **+2**，但**封顶 100**（用 `(s + 2).min(100)`），收集成 `Vec<i32>`；',
      '2. `passed`：>= 60 的分数**个数**；',
      '3. `total`：全部分数之和；',
      '4. `best`：最高分（`max()` 返回 `Option`，用 `unwrap()` 取出）。',
      '',
      '第一行的 `{adjusted:?}` 用的是 `Debug` 格式化，`Vec` 会打印成 `[93, 78, ...]` 这种样子。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let scores = vec![58, 91, 76, 43, 88, 100, 67];',
      '',
      '    // TODO: 过滤出 >= 60 的分数，每个 +2 且封顶 100，收集成 Vec<i32>',
      '    let adjusted: Vec<i32> = Vec::new();',
      '    println!("调整后：{adjusted:?}");',
      '',
      '    // TODO: 统计 >= 60 的分数个数',
      '    let passed = 0;',
      '    println!("及格人数 = {passed}");',
      '',
      '    // TODO: 求所有分数之和',
      '    let total = 0;',
      '    println!("总分 = {total}");',
      '',
      '    // TODO: 求最高分（max() 返回 Option，记得 unwrap）',
      '    let best = 0;',
      '    println!("最高分 = {best}");',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let scores = vec![58, 91, 76, 43, 88, 100, 67];',
      '',
      '    let adjusted: Vec<i32> = scores',
      '        .iter()',
      '        .copied()',
      '        .filter(|s| *s >= 60)',
      '        .map(|s| (s + 2).min(100))',
      '        .collect();',
      '    println!("调整后：{adjusted:?}");',
      '',
      '    let passed = scores.iter().filter(|s| **s >= 60).count();',
      '    println!("及格人数 = {passed}");',
      '',
      '    let total: i32 = scores.iter().sum();',
      '    println!("总分 = {total}");',
      '',
      '    let best = scores.iter().max().unwrap();',
      '    println!("最高分 = {best}");',
      '}',
    ].join('\n'),
    expectedStdout: '调整后：[93, 78, 90, 100, 69]\n及格人数 = 5\n总分 = 523\n最高分 = 100\n',
    hints: [
      '每一问都是一条链：`scores.iter()` 开头，中间接 `filter` / `map`，最后用 `collect` / `count` / `sum` / `max` 收尾。',
      '在 `.iter()` 后面接 `.copied()`，闭包参数就从 `&i32` 变成 `i32`，`filter(|s| *s >= 60)` 里只需要解一层。',
      '第一条链完整写法：`scores.iter().copied().filter(|s| *s >= 60).map(|s| (s + 2).min(100)).collect()`；`sum` 需要类型标注 `let total: i32 = ...`。',
    ],
  },
  {
    id: 'm4-02',
    moduleId: 'm4',
    title: '实现 word_stats：split_whitespace + fold',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 一次遍历统计两个指标',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn word_stats(text: &str) -> (usize, usize)',
      '```',
      '',
      '返回 `(单词数, 所有单词的字符总数)`。单词按**空白字符**切分（空格、制表符、换行都算），',
      '连续空白不会产生空单词——这正是 `split_whitespace()` 与 `split(\' \')` 的区别。',
      '字符数按 **`chars()`** 计（一个汉字算 1 个字符，不是 3 个字节）。',
      '',
      '| 输入 | 输出 | 说明 |',
      '| --- | --- | --- |',
      '| `"hello world"` | `(2, 10)` | 5 + 5 |',
      '| `""` | `(0, 0)` | 空串没有单词 |',
      '| `"   "` | `(0, 0)` | 全是空白 |',
      '| `"  a  bb   ccc "` | `(3, 6)` | 连续空白不产生空单词 |',
      '| `"你好 世界 rust"` | `(3, 8)` | 2 + 2 + 4 |',
      '',
      '**推荐用 `fold` 一次遍历同时算出两个值**：',
      '',
      '```rust',
      'text.split_whitespace().fold((0, 0), |(count, chars), word| {',
      '    // 累加器是一个元组，每来一个 word 就返回一个新的元组',
      '    todo!()',
      '})',
      '```',
      '',
      '`fold(初值, |累加器, 元素| 新累加器)` 是所有消费器的祖宗——`sum`、`count`、`max` 本质上都是它的特例。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'pub fn word_stats(text: &str) -> (usize, usize) {',
      '    // TODO: 用 split_whitespace() 切词',
      '    // TODO: 用 fold((0, 0), ...) 同时累加"单词数"和"字符总数"',
      '    let _ = text;',
      '    (0, 0)',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn word_stats(text: &str) -> (usize, usize) {',
      '    text.split_whitespace().fold((0, 0), |(count, chars), word| {',
      '        (count + 1, chars + word.chars().count())',
      '    })',
      '}',
    ].join('\n'),
    hints: [
      '`text.split_whitespace()` 直接把连续空白、制表符、换行都处理好了，你不需要自己 `trim` 或过滤空串。',
      '`fold` 的初值写 `(0, 0)`，闭包参数可以直接解构成 `|(count, chars), word|`，返回一个新元组。',
      '闭包体就一行：`(count + 1, chars + word.chars().count())`。注意是 `chars().count()` 不是 `len()`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn counts_words_and_chars() {',
      '        assert_eq!(word_stats("hello world"), (2, 10));',
      '    }',
      '',
      '    #[test]',
      '    fn empty_and_blank_are_zero() {',
      '        assert_eq!(word_stats(""), (0, 0));',
      '        assert_eq!(word_stats("   "), (0, 0));',
      '    }',
      '',
      '    #[test]',
      '    fn collapses_repeated_whitespace() {',
      '        assert_eq!(word_stats("  a  bb   ccc "), (3, 6));',
      '    }',
      '',
      '    #[test]',
      '    fn counts_chars_not_bytes() {',
      '        assert_eq!(word_stats("你好 世界 rust"), (3, 8));',
      '    }',
      '',
      '    #[test]',
      '    fn handles_tabs_and_newlines() {',
      '        assert_eq!(word_stats("a\\tb\\nc"), (3, 3));',
      '        assert_eq!(word_stats("one\\n\\ntwo"), (2, 6));',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm4-03',
    moduleId: 'm4',
    title: '实现 apply_n_times：接收 FnMut 闭包',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 把闭包当参数传进去',
      '',
      '闭包有三个 trait，按"对捕获变量做了什么"从宽到严排列：',
      '',
      '| trait | 含义 | 典型闭包 |',
      '| --- | --- | --- |',
      '| `Fn` | 只读地用捕获变量，可以调用多次 | `\\|x\\| x * factor` |',
      '| `FnMut` | 会**修改**捕获变量，可以调用多次 | `\\|x\\| { count += 1; x }` |',
      '| `FnOnce` | 会**消耗**捕获变量（move 出去），只能调用一次 | `\\|\\| drop(s)` |',
      '',
      '它们是包含关系：`Fn ⊂ FnMut ⊂ FnOnce`。所以**函数参数应该要求最宽松的那个**——',
      '这里我们要重复调用且允许调用方在闭包里改自己的变量，`FnMut` 正合适。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn apply_n_times<F>(init: i32, n: usize, mut f: F) -> i32',
      'where',
      '    F: FnMut(i32) -> i32,',
      '```',
      '',
      '把 `f` 连续作用在 `init` 上 `n` 次并返回结果：`f(f(...f(init)...))`。`n == 0` 时直接返回 `init`。',
      '',
      '| 调用 | 结果 |',
      '| --- | --- |',
      '| `apply_n_times(1, 3, \\|x\\| x * 2)` | `8` |',
      '| `apply_n_times(7, 0, \\|x\\| x + 1)` | `7` |',
      '| `apply_n_times(100, 3, \\|x\\| x - 25)` | `25` |',
      '',
      '注意签名里的 `mut f`：要调用一个 `FnMut` 闭包，你必须持有它的**可变**绑定。',
      '',
      '提示：用 `(0..n).fold(init, |acc, _| f(acc))` 一行搞定，`_` 表示不关心第几次；写 `for` 循环当然也可以。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'pub fn apply_n_times<F>(init: i32, n: usize, mut f: F) -> i32',
      'where',
      '    F: FnMut(i32) -> i32,',
      '{',
      '    // TODO: 把 f 连续作用在 init 上 n 次并返回',
      '    // TODO: n == 0 时直接返回 init',
      '    let _ = &mut f;',
      '    init',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn apply_n_times<F>(init: i32, n: usize, mut f: F) -> i32',
      'where',
      '    F: FnMut(i32) -> i32,',
      '{',
      '    (0..n).fold(init, |acc, _| f(acc))',
      '}',
    ].join('\n'),
    hints: [
      '循环 `n` 次，每次把上一次的结果再喂给 `f`：`let mut acc = init; for _ in 0..n { acc = f(acc); } acc`。',
      '迭代器写法更短：`(0..n)` 就是一个跑 n 次的迭代器，配合 `fold` 把中间结果一路传下去。',
      '完整答案：`(0..n).fold(init, |acc, _| f(acc))`。`f` 已经声明为 `mut f`，所以可以在闭包里调用它。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn applies_repeatedly() {',
      '        assert_eq!(apply_n_times(1, 3, |x| x * 2), 8);',
      '        assert_eq!(apply_n_times(100, 3, |x| x - 25), 25);',
      '    }',
      '',
      '    #[test]',
      '    fn zero_times_returns_init() {',
      '        assert_eq!(apply_n_times(7, 0, |x| x + 1), 7);',
      '    }',
      '',
      '    #[test]',
      '    fn accepts_fn_mut_closure() {',
      '        let mut calls = 0;',
      '        let result = apply_n_times(0, 4, |x| {',
      '            calls += 1;',
      '            x + calls',
      '        });',
      '        assert_eq!(calls, 4);',
      '        assert_eq!(result, 10);',
      '    }',
      '',
      '    #[test]',
      '    fn accepts_captured_environment_and_fn_pointer() {',
      '        let factor = 3;',
      '        assert_eq!(apply_n_times(1, 4, |x| x * factor), 81);',
      '',
      '        fn inc(x: i32) -> i32 {',
      '            x + 1',
      '        }',
      '        assert_eq!(apply_n_times(0, 5, inc), 5);',
      '    }',
      '',
      '    #[test]',
      '    fn runs_many_iterations() {',
      '        assert_eq!(apply_n_times(0, 1000, |x| x + 1), 1000);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm4-04',
    moduleId: 'm4',
    title: 'Box<T> 与递归数据结构：二叉搜索树',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 为什么递归类型必须套一层 Box',
      '',
      '直接写下面这种类型是编译不过的：',
      '',
      '```rust',
      'struct Node { value: i32, left: Option<Node> }   // error[E0072]: recursive type has infinite size',
      '```',
      '',
      '编译器要在编译期算出 `Node` 占多少字节，而 `Node` 里又装着一个 `Node`，算下去是无穷大。',
      '`Box<T>` 是最简单的智能指针：**数据放堆上，`Box` 本身只是一个指针（固定 8 字节）**，这样大小就确定了。',
      '',
      '```rust',
      'struct Node {',
      '    value: i32,',
      '    left: Option<Box<Node>>,     // None = 没有左孩子',
      '    right: Option<Box<Node>>,',
      '}',
      '```',
      '',
      '**要求**：补全三个方法，构建一棵二叉搜索树（BST）并打印统计信息。',
      '',
      '- `insert(&mut self, value: i32)`：`value < self.value` 往左走，否则往右走；空位就挂一个新节点，非空就递归下去；',
      '- `in_order(&self, out: &mut Vec<i32>)`：**中序遍历**（左 → 自己 → 右），把值依次推进 `out`。BST 的中序遍历天然有序；',
      '- `depth(&self) -> usize`：树高，单个节点算 1，空子树算 0。',
      '',
      '插入顺序是 `8, 3, 10, 1, 6, 14, 4, 7, 13`，程序应当**恰好**输出：',
      '',
      '```text',
      '中序遍历：[1, 3, 4, 6, 7, 8, 10, 13, 14]',
      '节点数 = 9',
      '树高 = 4',
      '最小值 = 1',
      '最大值 = 14',
      '```',
      '',
      '提示：处理 `Option<Box<Node>>` 时，`match slot { Some(child) => ..., None => ... }` 里的 `child` 会自动是 `&mut Box<Node>`，',
      '而 `Box` 会自动解引用，`child.insert(value)` 直接就能调到 `Node` 的方法。',
      '读取时用 `self.left.as_ref()` 拿到 `Option<&Box<Node>>`，用 `map_or(0, |n| n.depth())` 处理"空子树算 0"。',
    ].join('\n'),
    starterCode: [
      '#[derive(Debug)]',
      'struct Node {',
      '    value: i32,',
      '    left: Option<Box<Node>>,',
      '    right: Option<Box<Node>>,',
      '}',
      '',
      'impl Node {',
      '    fn new(value: i32) -> Self {',
      '        Node { value, left: None, right: None }',
      '    }',
      '',
      '    fn insert(&mut self, value: i32) {',
      '        // TODO: value < self.value 走左边，否则走右边',
      '        // TODO: 空位挂新节点 Some(Box::new(Node::new(value)))，非空就递归 insert',
      '        let _ = value;',
      '    }',
      '',
      '    fn in_order(&self, out: &mut Vec<i32>) {',
      '        // TODO: 先递归左子树，再 push 自己的 value，最后递归右子树',
      '        let _ = out;',
      '    }',
      '',
      '    fn depth(&self) -> usize {',
      '        // TODO: 1 + 左右子树深度的较大者，空子树算 0',
      '        0',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let mut root = Node::new(8);',
      '    for v in [3, 10, 1, 6, 14, 4, 7, 13] {',
      '        root.insert(v);',
      '    }',
      '',
      '    let mut sorted = Vec::new();',
      '    root.in_order(&mut sorted);',
      '',
      '    println!("中序遍历：{sorted:?}");',
      '    println!("节点数 = {}", sorted.len());',
      '    println!("树高 = {}", root.depth());',
      '    println!("最小值 = {}", sorted.first().unwrap_or(&0));',
      '    println!("最大值 = {}", sorted.last().unwrap_or(&0));',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Debug)]',
      'struct Node {',
      '    value: i32,',
      '    left: Option<Box<Node>>,',
      '    right: Option<Box<Node>>,',
      '}',
      '',
      'impl Node {',
      '    fn new(value: i32) -> Self {',
      '        Node { value, left: None, right: None }',
      '    }',
      '',
      '    fn insert(&mut self, value: i32) {',
      '        let slot = if value < self.value {',
      '            &mut self.left',
      '        } else {',
      '            &mut self.right',
      '        };',
      '',
      '        match slot {',
      '            Some(child) => child.insert(value),',
      '            None => *slot = Some(Box::new(Node::new(value))),',
      '        }',
      '    }',
      '',
      '    fn in_order(&self, out: &mut Vec<i32>) {',
      '        if let Some(left) = &self.left {',
      '            left.in_order(out);',
      '        }',
      '        out.push(self.value);',
      '        if let Some(right) = &self.right {',
      '            right.in_order(out);',
      '        }',
      '    }',
      '',
      '    fn depth(&self) -> usize {',
      '        let left = self.left.as_ref().map_or(0, |node| node.depth());',
      '        let right = self.right.as_ref().map_or(0, |node| node.depth());',
      '        1 + left.max(right)',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let mut root = Node::new(8);',
      '    for v in [3, 10, 1, 6, 14, 4, 7, 13] {',
      '        root.insert(v);',
      '    }',
      '',
      '    let mut sorted = Vec::new();',
      '    root.in_order(&mut sorted);',
      '',
      '    println!("中序遍历：{sorted:?}");',
      '    println!("节点数 = {}", sorted.len());',
      '    println!("树高 = {}", root.depth());',
      '    println!("最小值 = {}", sorted.first().unwrap_or(&0));',
      '    println!("最大值 = {}", sorted.last().unwrap_or(&0));',
      '}',
    ].join('\n'),
    expectedStdout:
      '中序遍历：[1, 3, 4, 6, 7, 8, 10, 13, 14]\n节点数 = 9\n树高 = 4\n最小值 = 1\n最大值 = 14\n',
    hints: [
      '`insert` 先用 `if value < self.value` 选出要操作的那个字段，把它借成 `let slot = &mut self.left;`（或 right）。',
      '拿到 `slot: &mut Option<Box<Node>>` 之后 `match` 它：`Some(child)` 就 `child.insert(value)` 递归下去，`None` 就 `*slot = Some(Box::new(Node::new(value)));`。',
      '`in_order` 的三步顺序是"左、自己、右"：`if let Some(left) = &self.left { left.in_order(out); }` → `out.push(self.value);` → 右子树同理。`depth` 用 `self.left.as_ref().map_or(0, |n| n.depth())` 取子树高度，再 `1 + left.max(right)`。',
    ],
  },
  {
    id: 'm4-05',
    moduleId: 'm4',
    title: '修复：Rc 里的数据改不动',
    difficulty: 3,
    judgeMode: 'compile',
    expectedStdout: "shared = [1, 2, 3, 4]\nsecond = [1, 2, 3, 4]\nstrong_count = 2\n",
    prompt: [
      '### 修编译错误：cannot borrow data in an `Rc` as mutable',
      '',
      '下面这段代码编译不过：',
      '',
      '```text',
      'error[E0596]: cannot borrow data in an `Rc` as mutable',
      'help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<Vec<i32>>`',
      '```',
      '',
      '`Rc<T>`（reference counted）让**多个变量共享同一份数据**，靠引用计数决定什么时候释放。',
      '但它只提供**共享的只读访问**——因为一旦允许任意一个持有者修改，就等于同时存在"多个不可变引用"和"一个可变引用"，直接违反借用规则。',
      '',
      '解法是**内部可变性**：套一层 `RefCell<T>`。',
      '`RefCell` 把借用检查从编译期挪到**运行期**——`borrow()` 拿只读、`borrow_mut()` 拿可写，规则还是那条规则，只是违反时不再是编译错误，而是运行时 panic（`already borrowed`）。',
      '',
      '`Rc<RefCell<T>>` 是单线程里"共享 + 可变"的标准组合（它在多线程版就是 `Arc<Mutex<T>>`）。',
      '',
      '**要求**：把 `Rc<Vec<i32>>` 改成 `Rc<RefCell<Vec<i32>>>`，让程序编译通过并正常运行，输出大致是：',
      '',
      '```text',
      'shared = [1, 2, 3, 4]',
      'second = [1, 2, 3, 4]',
      'strong_count = 2',
      '```',
      '',
      '本题会**逐行比对输出**。注意 `println!` 里也要用 `.borrow()` 才能打印内部数据。',
      '',
      '别忘了 `use std::cell::RefCell;`。',
    ].join('\n'),
    starterCode: [
      'use std::rc::Rc;',
      '',
      'fn main() {',
      '    // TODO: Rc 只给共享的只读访问，想改内容要套一层 RefCell',
      '    let shared = Rc::new(vec![1, 2, 3]);',
      '    let second = Rc::clone(&shared);',
      '',
      '    shared.push(4);',
      '',
      '    println!("shared = {:?}", shared);',
      '    println!("second = {:?}", second);',
      '    println!("strong_count = {}", Rc::strong_count(&shared));',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::cell::RefCell;',
      'use std::rc::Rc;',
      '',
      'fn main() {',
      '    let shared = Rc::new(RefCell::new(vec![1, 2, 3]));',
      '    let second = Rc::clone(&shared);',
      '',
      '    shared.borrow_mut().push(4);',
      '',
      '    println!("shared = {:?}", shared.borrow());',
      '    println!("second = {:?}", second.borrow());',
      '    println!("strong_count = {}", Rc::strong_count(&shared));',
      '}',
    ].join('\n'),
    hints: [
      '报错说 `Rc` 没有实现 `DerefMut`，也就是"透过 Rc 拿不到 `&mut`"。要改数据就得让内部类型自己提供可变性。',
      '把数据包成 `Rc::new(RefCell::new(vec![1, 2, 3]))`，修改时写 `shared.borrow_mut().push(4)`。',
      '打印时也要 `.borrow()`：`println!("shared = {:?}", shared.borrow());`。文件顶部补上 `use std::cell::RefCell;`。',
    ],
  },
  {
    id: 'm4-06',
    moduleId: 'm4',
    title: '实现 share_and_count：Rc 引用计数的增与减',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 亲手观察引用计数',
      '',
      '`Rc::clone(&x)` **不复制数据**，只是把强引用计数 +1，返回一个指向同一块数据的新句柄；',
      '每有一个句柄被 drop，计数 -1；归零时数据才真正释放。`Rc::strong_count(&x)` 可以随时查当前计数。',
      '',
      '> 约定俗成写 `Rc::clone(&x)` 而不是 `x.clone()`：前者一眼看出"这是廉价的计数 +1"，后者容易被误读成深拷贝。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn share_and_count(data: Vec<i32>, clones: usize, extra: i32) -> (usize, usize, Vec<i32>)',
      '```',
      '',
      '步骤：',
      '',
      '1. 把 `data` 装进 `Rc::new(RefCell::new(data))`；',
      '2. 克隆出 `clones` 个句柄，全部保存在一个 `Vec` 里（**必须留着**，否则计数立刻掉回去）；',
      '3. 依次**通过每一个克隆句柄** `push(extra)`——它们改的是同一份数据，所以一共会追加 `clones` 个 `extra`；',
      '4. 记录此时的 `strong_count` 作为 `peak`；',
      '5. `drop` 掉那个装句柄的 `Vec`，再记录一次 `strong_count` 作为 `after`；',
      '6. 返回 `(peak, after, 最终内容)`。',
      '',
      '| 调用 | 返回 |',
      '| --- | --- |',
      '| `share_and_count(vec![1, 2], 3, 9)` | `(4, 1, vec![1, 2, 9, 9, 9])` |',
      '| `share_and_count(vec![1, 2], 0, 9)` | `(1, 1, vec![1, 2])` |',
      '',
      '注意 `peak = clones + 1`（原始那个句柄也算一份），而 `after` 永远是 `1`。',
      '',
      '提示：取最终内容用 `shared.borrow().clone()`——`borrow()` 返回的是 `Ref<Vec<i32>>` 这个守卫类型，不能直接当 `Vec` 返回。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use std::cell::RefCell;',
      'use std::rc::Rc;',
      '',
      'pub fn share_and_count(data: Vec<i32>, clones: usize, extra: i32) -> (usize, usize, Vec<i32>) {',
      '    let shared = Rc::new(RefCell::new(data));',
      '',
      '    // TODO: 克隆 clones 个句柄存进一个 Vec（用 Rc::clone(&shared)）',
      '    // TODO: 遍历这些句柄，每个都 borrow_mut().push(extra)',
      '    // TODO: 记录 peak = Rc::strong_count(&shared)',
      '    // TODO: drop 掉句柄 Vec，再记录 after = Rc::strong_count(&shared)',
      '    // TODO: 用 shared.borrow().clone() 取出最终内容',
      '    let _ = (clones, extra);',
      '',
      '    (0, 0, shared.borrow().clone())',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::cell::RefCell;',
      'use std::rc::Rc;',
      '',
      'pub fn share_and_count(data: Vec<i32>, clones: usize, extra: i32) -> (usize, usize, Vec<i32>) {',
      '    let shared = Rc::new(RefCell::new(data));',
      '',
      '    let handles: Vec<Rc<RefCell<Vec<i32>>>> = (0..clones).map(|_| Rc::clone(&shared)).collect();',
      '',
      '    for handle in &handles {',
      '        handle.borrow_mut().push(extra);',
      '    }',
      '',
      '    let peak = Rc::strong_count(&shared);',
      '    drop(handles);',
      '    let after = Rc::strong_count(&shared);',
      '',
      '    let snapshot = shared.borrow().clone();',
      '    (peak, after, snapshot)',
      '}',
    ].join('\n'),
    hints: [
      '克隆句柄可以写成迭代器：`(0..clones).map(|_| Rc::clone(&shared)).collect::<Vec<_>>()`，也可以老实用 `for` 循环 `push`。',
      '`peak` 必须在 `handles` 还活着的时候取；`drop(handles)` 之后再取一次就是 `after`。顺序错了计数就不对。',
      '每个句柄的写法是 `handle.borrow_mut().push(extra);`；最后 `let snapshot = shared.borrow().clone();` 把内容复制出来再返回。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn counts_clones_and_shares_mutation() {',
      '        assert_eq!(share_and_count(vec![1, 2], 3, 9), (4, 1, vec![1, 2, 9, 9, 9]));',
      '    }',
      '',
      '    #[test]',
      '    fn zero_clones_keeps_count_one() {',
      '        assert_eq!(share_and_count(vec![1, 2], 0, 9), (1, 1, vec![1, 2]));',
      '    }',
      '',
      '    #[test]',
      '    fn works_with_empty_data() {',
      '        assert_eq!(share_and_count(Vec::new(), 2, 7), (3, 1, vec![7, 7]));',
      '        assert_eq!(share_and_count(Vec::new(), 0, 7), (1, 1, Vec::new()));',
      '    }',
      '',
      '    #[test]',
      '    fn count_drops_back_to_one() {',
      '        let (peak, after, values) = share_and_count(vec![0], 10, -1);',
      '        assert_eq!(peak, 11);',
      '        assert_eq!(after, 1);',
      '        assert_eq!(values.len(), 11);',
      '    }',
      '',
      '    #[test]',
      '    fn preserves_original_order() {',
      '        let (_, _, values) = share_and_count(vec![5, 4, 3], 2, 0);',
      '        assert_eq!(values, vec![5, 4, 3, 0, 0]);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm4-07',
    moduleId: 'm4',
    title: 'serde 反序列化：解析并校验订单 JSON',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### serde：JSON ↔ struct 只要一行 derive',
      '',
      '`serde` 是 Rust 生态里出现频率最高的 crate，几乎每份后端 JD 都点名要它：请求体、响应体、配置文件、消息队列负载全靠它。',
      '用法核心就是在 struct 上加一行派生宏：',
      '',
      '```rust',
      'use serde::Deserialize;',
      '',
      '#[derive(Deserialize)]',
      'struct User {',
      '    id: u32,',
      '    #[serde(rename = "userName")]   // JSON 里字段叫 userName，Rust 里叫 name',
      '    name: String,',
      '    #[serde(default)]              // JSON 里没这个字段时用 Default::default()',
      '    tags: Vec<String>,',
      '}',
      '',
      'let user: User = serde_json::from_str(json)?;',
      '```',
      '',
      '**要求**：',
      '',
      '1. 给 `Order` 补上两个字段属性：`customer` 对应 JSON 里的 **`"customerName"`**；`note` 在 JSON 缺失时默认为空串；',
      '2. 实现',
      '',
      '```rust',
      'pub fn parse_order(json: &str) -> Result<Order, String>',
      '```',
      '',
      '- 用 `serde_json::from_str` 解析，解析失败时把错误转成 `String`（内容随意，测试只检查是 `Err`）；',
      '- 解析成功后按顺序校验：`customer` **去掉首尾空白后不能为空**，否则返回 `Err("customer 不能为空".to_string())`；',
      '- 然后 `amount` 必须 **> 0**，否则返回 `Err("amount 必须大于 0".to_string())`；',
      '- 都通过就 `Ok(order)`。',
      '',
      '```text',
      '{"id":1,"customerName":"李雷","amount":99.5,"note":"加急"}  -> Ok',
      '{"id":2,"customerName":"韩梅梅","amount":10.0}              -> Ok，note 为 ""',
      '{"id":3,"customerName":"  ","amount":10.0}                 -> Err("customer 不能为空")',
      '{"id":4,"customerName":"李雷","amount":0.0}                 -> Err("amount 必须大于 0")',
      '{"id":5,"customer":"李雷","amount":10.0}                    -> Err（字段名对不上）',
      '```',
      '',
      '提示：`map_err` 把 `serde_json::Error` 换成 `String`，配合 `?` 用起来很顺手：',
      '`let order: Order = serde_json::from_str(json).map_err(|e| e.to_string())?;`',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，`Order` 与 `parse_order` 都必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use serde::Deserialize;',
      '',
      '#[derive(Debug, PartialEq, Deserialize)]',
      'pub struct Order {',
      '    pub id: u32,',
      '    // TODO: JSON 里这个字段叫 "customerName"，加上 #[serde(rename = "...")]',
      '    pub customer: String,',
      '    pub amount: f64,',
      '    // TODO: JSON 里可能没有 note，加上 #[serde(default)] 让它退化成空串',
      '    pub note: String,',
      '}',
      '',
      'pub fn parse_order(json: &str) -> Result<Order, String> {',
      '    // TODO: 用 serde_json::from_str 解析，失败时 map_err 成 String',
      '    // TODO: 校验 customer 去空白后非空，否则 Err("customer 不能为空")',
      '    // TODO: 校验 amount > 0，否则 Err("amount 必须大于 0")',
      '    let _ = json;',
      '    Err("未实现".to_string())',
      '}',
    ].join('\n'),
    solutionCode: [
      'use serde::Deserialize;',
      '',
      '#[derive(Debug, PartialEq, Deserialize)]',
      'pub struct Order {',
      '    pub id: u32,',
      '    #[serde(rename = "customerName")]',
      '    pub customer: String,',
      '    pub amount: f64,',
      '    #[serde(default)]',
      '    pub note: String,',
      '}',
      '',
      'pub fn parse_order(json: &str) -> Result<Order, String> {',
      '    let order: Order = serde_json::from_str(json).map_err(|e| format!("JSON 解析失败：{e}"))?;',
      '',
      '    if order.customer.trim().is_empty() {',
      '        return Err("customer 不能为空".to_string());',
      '    }',
      '    if order.amount <= 0.0 {',
      '        return Err("amount 必须大于 0".to_string());',
      '    }',
      '',
      '    Ok(order)',
      '}',
    ].join('\n'),
    hints: [
      '两个字段属性分别是 `#[serde(rename = "customerName")]` 和 `#[serde(default)]`，写在对应字段的上一行。',
      '解析一行搞定：`let order: Order = serde_json::from_str(json).map_err(|e| e.to_string())?;`，`?` 会把 `Err(String)` 直接抛出去。',
      '校验顺序不能反：先 `if order.customer.trim().is_empty() { return Err("customer 不能为空".to_string()); }`，再判 `order.amount <= 0.0`，最后 `Ok(order)`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn parses_full_json() {',
      '        let json = r#"{"id":1,"customerName":"李雷","amount":99.5,"note":"加急"}"#;',
      '        assert_eq!(',
      '            parse_order(json).unwrap(),',
      '            Order {',
      '                id: 1,',
      '                customer: "李雷".to_string(),',
      '                amount: 99.5,',
      '                note: "加急".to_string(),',
      '            }',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn note_defaults_to_empty_string() {',
      '        let json = r#"{"id":2,"customerName":"韩梅梅","amount":10.0}"#;',
      '        let order = parse_order(json).unwrap();',
      '        assert_eq!(order.note, "");',
      '        assert_eq!(order.customer, "韩梅梅");',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_blank_customer() {',
      '        let json = r#"{"id":3,"customerName":"  ","amount":10.0}"#;',
      '        assert_eq!(parse_order(json).unwrap_err(), "customer 不能为空");',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_non_positive_amount() {',
      '        let zero = r#"{"id":4,"customerName":"李雷","amount":0.0}"#;',
      '        assert_eq!(parse_order(zero).unwrap_err(), "amount 必须大于 0");',
      '',
      '        let negative = r#"{"id":4,"customerName":"李雷","amount":-3.5}"#;',
      '        assert_eq!(parse_order(negative).unwrap_err(), "amount 必须大于 0");',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_malformed_or_mismatched_json() {',
      '        assert!(parse_order("{ 这不是 JSON").is_err());',
      '        assert!(parse_order(r#"{"id":5,"customer":"李雷","amount":10.0}"#).is_err());',
      '        assert!(parse_order(r#"{"customerName":"李雷","amount":10.0}"#).is_err());',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm4-08',
    moduleId: 'm4',
    title: 'serde 序列化：把发票打印成 JSON',
    difficulty: 4,
    judgeMode: 'stdout',
    prompt: [
      '### 反过来：struct → JSON',
      '',
      '`Serialize` 是 `Deserialize` 的镜像。三个最常用的容器/字段属性：',
      '',
      '```rust',
      '#[derive(Serialize)]',
      '#[serde(rename_all = "camelCase")]        // 整个 struct 的字段统一转成 camelCase',
      'struct Invoice {',
      '    invoice_id: u32,                      // -> "invoiceId"',
      '    #[serde(skip_serializing_if = "Option::is_none")]',
      '    note: Option<String>,                 // None 时这个字段整个消失',
      '}',
      '```',
      '',
      '`serde_json::to_string` 出紧凑单行，`to_string_pretty` 出缩进 2 空格的多行。',
      '',
      '**要求**：补全 `main`。',
      '',
      '1. 用迭代器算出 `total`：每个条目 `qty as f64 * price` 再求和（`sum::<f64>()`）；',
      '2. 先用 `to_string_pretty` 打印 `invoice`（`note` 是 `None`，应当被整个跳过）；',
      '3. 再用 struct update 语法造一份带备注的 `with_note`，用 `to_string` 打印**紧凑**单行。',
      '',
      '程序应当**恰好**输出：',
      '',
      '```text',
      '{',
      '  "invoiceId": 1001,',
      '  "customerName": "李雷",',
      '  "items": [',
      '    {',
      '      "name": "机械键盘",',
      '      "qty": 1,',
      '      "price": 499.0',
      '    },',
      '    {',
      '      "name": "无线鼠标",',
      '      "qty": 2,',
      '      "price": 199.5',
      '    }',
      '  ],',
      '  "total": 898.0',
      '}',
      '{"invoiceId":1001,"customerName":"李雷","items":[{"name":"机械键盘","qty":1,"price":499.0},{"name":"无线鼠标","qty":2,"price":199.5}],"note":"加急发货","total":898.0}',
      '```',
      '',
      '注意 `Item` 没有加 `rename_all`，所以它的字段名保持原样（`name` / `qty` / `price`）；',
      '而 `Invoice` 加了，所以 `invoice_id` → `invoiceId`、`customer_name` → `customerName`。字段顺序就是**声明顺序**。',
      '',
      '提示：struct update 语法是 `Invoice { note: Some("加急发货".to_string()), ..invoice }`——',
      '`invoice` 的其余字段会被 move 进来，所以要放在最后一次使用 `invoice` 之后。',
    ].join('\n'),
    starterCode: [
      'use serde::Serialize;',
      '',
      '#[derive(Serialize)]',
      'struct Item {',
      '    name: String,',
      '    qty: u32,',
      '    price: f64,',
      '}',
      '',
      '#[derive(Serialize)]',
      '#[serde(rename_all = "camelCase")]',
      'struct Invoice {',
      '    invoice_id: u32,',
      '    customer_name: String,',
      '    items: Vec<Item>,',
      '    #[serde(skip_serializing_if = "Option::is_none")]',
      '    note: Option<String>,',
      '    total: f64,',
      '}',
      '',
      'fn main() {',
      '    let items = vec![',
      '        Item { name: "机械键盘".to_string(), qty: 1, price: 499.0 },',
      '        Item { name: "无线鼠标".to_string(), qty: 2, price: 199.5 },',
      '    ];',
      '',
      '    // TODO: 用迭代器求 total：每项 qty as f64 * price，再 sum::<f64>()',
      '    let total = 0.0;',
      '',
      '    let invoice = Invoice {',
      '        invoice_id: 1001,',
      '        customer_name: "李雷".to_string(),',
      '        items,',
      '        note: None,',
      '        total,',
      '    };',
      '',
      '    // TODO: 用 serde_json::to_string_pretty(&invoice) 打印多行 JSON',
      '',
      '    // TODO: 用 struct update 语法造出 note 为 Some("加急发货") 的 with_note',
      '    // TODO: 用 serde_json::to_string(&with_note) 打印紧凑单行 JSON',
      '}',
    ].join('\n'),
    solutionCode: [
      'use serde::Serialize;',
      '',
      '#[derive(Serialize)]',
      'struct Item {',
      '    name: String,',
      '    qty: u32,',
      '    price: f64,',
      '}',
      '',
      '#[derive(Serialize)]',
      '#[serde(rename_all = "camelCase")]',
      'struct Invoice {',
      '    invoice_id: u32,',
      '    customer_name: String,',
      '    items: Vec<Item>,',
      '    #[serde(skip_serializing_if = "Option::is_none")]',
      '    note: Option<String>,',
      '    total: f64,',
      '}',
      '',
      'fn main() {',
      '    let items = vec![',
      '        Item { name: "机械键盘".to_string(), qty: 1, price: 499.0 },',
      '        Item { name: "无线鼠标".to_string(), qty: 2, price: 199.5 },',
      '    ];',
      '',
      '    let total = items.iter().map(|item| item.qty as f64 * item.price).sum::<f64>();',
      '',
      '    let invoice = Invoice {',
      '        invoice_id: 1001,',
      '        customer_name: "李雷".to_string(),',
      '        items,',
      '        note: None,',
      '        total,',
      '    };',
      '',
      '    println!("{}", serde_json::to_string_pretty(&invoice).unwrap());',
      '',
      '    let with_note = Invoice {',
      '        note: Some("加急发货".to_string()),',
      '        ..invoice',
      '    };',
      '    println!("{}", serde_json::to_string(&with_note).unwrap());',
      '}',
    ].join('\n'),
    expectedStdout:
      '{\n  "invoiceId": 1001,\n  "customerName": "李雷",\n  "items": [\n    {\n      "name": "机械键盘",\n      "qty": 1,\n      "price": 499.0\n    },\n    {\n      "name": "无线鼠标",\n      "qty": 2,\n      "price": 199.5\n    }\n  ],\n  "total": 898.0\n}\n{"invoiceId":1001,"customerName":"李雷","items":[{"name":"机械键盘","qty":1,"price":499.0},{"name":"无线鼠标","qty":2,"price":199.5}],"note":"加急发货","total":898.0}\n',
    hints: [
      '`total` 这条链是：`items.iter().map(|item| item.qty as f64 * item.price).sum::<f64>()`。`qty` 是 `u32`，必须 `as f64` 才能和 `price` 相乘。',
      '`to_string_pretty` 和 `to_string` 都返回 `Result<String, _>`，示例里直接 `.unwrap()` 即可。',
      '第二份数据用 `let with_note = Invoice { note: Some("加急发货".to_string()), ..invoice };`，注意它必须写在打印完 `invoice` 之后（因为会 move 走剩余字段）。',
    ],
  },
  {
    id: 'm4-09',
    moduleId: 'm4',
    title: '实现 top_spender：分组求和取最大',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 迭代器综合：fold 分组 + max_by 取最大',
      '',
      '"按某个键分组，再对每组聚合，最后取最大"是后端日常最高频的一类数据处理。Rust 里没有 SQL 的 `GROUP BY`，',
      '标准做法就是 **`HashMap` + `entry` API**：',
      '',
      '```rust',
      'use std::collections::HashMap;',
      '',
      'let totals = orders.iter().fold(HashMap::<&str, u32>::new(), |mut acc, order| {',
      '    *acc.entry(order.customer.as_str()).or_insert(0) += order.amount;',
      '    acc',
      '});',
      '```',
      '',
      '`entry(key).or_insert(0)` 返回的是**已有值或刚插入的 0** 的可变引用，前面加 `*` 就能直接累加——',
      '比"先 `contains_key` 再 `get_mut`"少查一次哈希，也是 clippy 推荐的写法。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn top_spender(orders: &[Order]) -> Option<&str>',
      '```',
      '',
      '返回**累计消费金额最高**的客户名。规则：',
      '',
      '- 同一个客户的多笔订单要**先求和**再比较；',
      '- 空切片返回 `None`；',
      '- **平局时返回名字字典序更小的那个**（必须固定 tie-break，否则 `HashMap` 的遍历顺序随机，结果不确定）。',
      '',
      '| 订单 | 结果 |',
      '| --- | --- |',
      '| `[("amy", 30), ("bob", 60), ("amy", 40)]` | `Some("amy")`（70 > 60） |',
      '| `[("bob", 50), ("amy", 50)]` | `Some("amy")`（平局取字典序小的） |',
      '| `[]` | `None` |',
      '',
      '提示：`max_by` 接收一个返回 `Ordering` 的闭包，`Ordering` 上的 `then_with` 可以串联次级比较：',
      '',
      '```rust',
      'totals',
      '    .into_iter()',
      '    .max_by(|(name_a, total_a), (name_b, total_b)| {',
      '        total_a.cmp(total_b).then_with(|| name_b.cmp(name_a))  // 金额升序取最大；平局时名字反序 => 取字典序小的',
      '    })',
      '    .map(|(name, _)| name)',
      '```',
      '',
      '返回值 `Option<&str>` 借用的是 `orders` 里的字符串，生命周期省略规则会自动把它绑到 `orders` 上，不需要手写标注。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，`Order` 与 `top_spender` 都必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use std::collections::HashMap;',
      '',
      '#[derive(Debug, Clone, PartialEq)]',
      'pub struct Order {',
      '    pub customer: String,',
      '    pub amount: u32,',
      '}',
      '',
      'pub fn top_spender(orders: &[Order]) -> Option<&str> {',
      '    // TODO: 用 fold + HashMap<&str, u32> 把每个客户的金额累加起来',
      '    // TODO: 用 max_by 取金额最大的一项，平局时取名字字典序更小的',
      '    // TODO: 用 map 把 (name, total) 变成 name',
      '    let _: Option<HashMap<&str, u32>> = None;',
      '    let _ = orders;',
      '    None',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::collections::HashMap;',
      '',
      '#[derive(Debug, Clone, PartialEq)]',
      'pub struct Order {',
      '    pub customer: String,',
      '    pub amount: u32,',
      '}',
      '',
      'pub fn top_spender(orders: &[Order]) -> Option<&str> {',
      '    let totals = orders.iter().fold(HashMap::<&str, u32>::new(), |mut acc, order| {',
      '        *acc.entry(order.customer.as_str()).or_insert(0) += order.amount;',
      '        acc',
      '    });',
      '',
      '    totals',
      '        .into_iter()',
      '        .max_by(|(name_a, total_a), (name_b, total_b)| {',
      '            total_a.cmp(total_b).then_with(|| name_b.cmp(name_a))',
      '        })',
      '        .map(|(name, _)| name)',
      '}',
    ].join('\n'),
    hints: [
      '第一步是分组求和：`orders.iter().fold(HashMap::<&str, u32>::new(), |mut acc, order| { ...; acc })`，闭包里用 `*acc.entry(...).or_insert(0) += order.amount;`。',
      '第二步在 `totals.into_iter()` 上用 `max_by`。只比金额的话平局结果不确定，必须再串一个名字比较。',
      '完整比较闭包：`|(name_a, total_a), (name_b, total_b)| total_a.cmp(total_b).then_with(|| name_b.cmp(name_a))`，注意名字是**反着**比的（`b` 在前），这样字典序小的才会被当成"更大"。最后 `.map(|(name, _)| name)`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    fn order(customer: &str, amount: u32) -> Order {',
      '        Order { customer: customer.to_string(), amount }',
      '    }',
      '',
      '    #[test]',
      '    fn empty_slice_is_none() {',
      '        assert_eq!(top_spender(&[]), None);',
      '    }',
      '',
      '    #[test]',
      '    fn single_customer() {',
      '        let orders = vec![order("amy", 10)];',
      '        assert_eq!(top_spender(&orders), Some("amy"));',
      '    }',
      '',
      '    #[test]',
      '    fn sums_orders_per_customer() {',
      '        let orders = vec![order("amy", 30), order("bob", 60), order("amy", 40)];',
      '        assert_eq!(top_spender(&orders), Some("amy"));',
      '    }',
      '',
      '    #[test]',
      '    fn tie_breaks_by_smaller_name() {',
      '        let orders = vec![order("bob", 50), order("amy", 50)];',
      '        assert_eq!(top_spender(&orders), Some("amy"));',
      '',
      '        let reversed = vec![order("amy", 20), order("bob", 20), order("amy", 30), order("bob", 30)];',
      '        assert_eq!(top_spender(&reversed), Some("amy"));',
      '    }',
      '',
      '    #[test]',
      '    fn handles_zero_amounts_deterministically() {',
      '        let orders = vec![order("carol", 0), order("amy", 0), order("bob", 0)];',
      '        assert_eq!(top_spender(&orders), Some("amy"));',
      '',
      '        let mixed = vec![order("carol", 0), order("amy", 0), order("bob", 1)];',
      '        assert_eq!(top_spender(&mixed), Some("bob"));',
      '    }',
      '}',
    ].join('\n'),
  },
];
