import type { Exercise } from '@/lib/rust/types';

export const module2Exercises: Exercise[] = [
  {
    id: 'm2-01',
    moduleId: 'm2',
    title: '定义结构体与字段访问',
    difficulty: 1,
    judgeMode: 'stdout',
    prompt: [
      '### 用 struct 把数据聚成一个整体',
      '',
      '结构体（struct）就是"给一组相关字段起个名字"。定义、构造、取值长这样：',
      '',
      '```rust',
      '#[derive(Debug)]',
      'struct Point {',
      '    x: i32,',
      '    y: i32,',
      '}',
      '',
      'let x = 3;',
      'let p = Point { x, y: 7 };   // 字段简写：变量名和字段名相同时可以只写一次',
      'println!("{}", p.x);         // 用点号访问字段',
      'println!("{p:?}");           // #[derive(Debug)] 之后才能用 {:?} 打印整个结构体',
      '```',
      '',
      '**要求**：用**字段简写**构造一个 `Driver`（`trips` 填 `128`），然后**恰好**输出四行：',
      '',
      '```text',
      '司机：老王',
      '评分：4.8',
      '接单数：128',
      'Driver { name: "老王", rating: 4.8, trips: 128 }',
      '```',
      '',
      '第二行用 `{:.1}` 保留一位小数；最后一行是 `{driver:?}` 的调试输出——注意它会自动给字符串加引号，这正是 `Debug` 与 `Display` 的区别。',
    ].join('\n'),
    starterCode: [
      '#[derive(Debug)]',
      'struct Driver {',
      '    name: String,',
      '    rating: f64,',
      '    trips: u32,',
      '}',
      '',
      'fn main() {',
      '    let name = String::from("老王");',
      '    let rating = 4.8_f64;',
      '',
      '    // TODO: 用字段简写构造 Driver，trips 填 128',
      '    let driver = Driver {',
      '        name,',
      '        rating,',
      '        trips: 0,',
      '    };',
      '',
      '    // TODO: 按题面要求打印四行（前三行访问字段，最后一行用 {driver:?}）',
      '    let _ = &driver;',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Debug)]',
      'struct Driver {',
      '    name: String,',
      '    rating: f64,',
      '    trips: u32,',
      '}',
      '',
      'fn main() {',
      '    let name = String::from("老王");',
      '    let rating = 4.8_f64;',
      '',
      '    let driver = Driver {',
      '        name,',
      '        rating,',
      '        trips: 128,',
      '    };',
      '',
      '    println!("司机：{}", driver.name);',
      '    println!("评分：{:.1}", driver.rating);',
      '    println!("接单数：{}", driver.trips);',
      '    println!("{driver:?}");',
      '}',
    ].join('\n'),
    expectedStdout:
      '司机：老王\n评分：4.8\n接单数：128\nDriver { name: "老王", rating: 4.8, trips: 128 }\n',
    hints: [
      '构造结构体的语法是 `Driver { 字段名: 值, ... }`；`name` 和 `rating` 两个变量名与字段名相同，可以只写变量名（字段简写）。',
      '前三行用 `driver.name` / `driver.rating` / `driver.trips` 取值；评分那行的格式是 `{:.1}`。',
      '最后一行直接 `println!("{driver:?}");` 即可——`#[derive(Debug)]` 已经帮你实现好了。',
    ],
  },
  {
    id: 'm2-02',
    moduleId: 'm2',
    title: 'impl：方法与关联函数',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### 给结构体加行为',
      '',
      '`impl` 块里写两类函数，区别只有一个：**第一个参数是不是 `self`**。',
      '',
      '```rust',
      'impl Rect {',
      '    fn new(w: u32, h: u32) -> Self {   // 关联函数：没有 self，用 Rect::new(...) 调用',
      '        Self { width: w, height: h }   // Self 是"当前类型"的别名',
      '    }',
      '',
      '    fn area(&self) -> u32 {            // 方法：借用自己，用 r.area() 调用',
      '        self.width * self.height',
      '    }',
      '}',
      '```',
      '',
      'Rust 没有构造函数这种语法，`new` 只是社区约定俗成的关联函数名。',
      '`&self` 是 `self: &Self` 的简写——**优先用 `&self`**（只读借用），需要改字段才用 `&mut self`，需要消耗掉自己才用 `self`。',
      '',
      '**要求**：补全四个函数，让程序**恰好**输出：',
      '',
      '```text',
      '大矩形面积 = 1500',
      '正方形面积 = 1600',
      '大矩形能装下小矩形吗？true',
      '大矩形能装下正方形吗？false',
      '```',
      '',
      '- `new(width, height)`：关联函数，构造一个 `Rect`',
      '- `square(side)`：关联函数，构造正方形（内部复用 `Self::new`）',
      '- `area(&self)`：返回面积',
      '- `can_hold(&self, other: &Rect)`：宽和高**都严格大于** `other` 时返回 `true`',
    ].join('\n'),
    starterCode: [
      '#[derive(Debug)]',
      'struct Rect {',
      '    width: u32,',
      '    height: u32,',
      '}',
      '',
      'impl Rect {',
      '    fn new(width: u32, height: u32) -> Self {',
      '        // TODO: 用传入的宽高构造 Self',
      '        Self { width: 0, height: 0 }',
      '    }',
      '',
      '    fn square(side: u32) -> Self {',
      '        // TODO: 复用 Self::new 构造正方形',
      '        Self::new(0, 0)',
      '    }',
      '',
      '    fn area(&self) -> u32 {',
      '        // TODO: 返回宽 * 高',
      '        0',
      '    }',
      '',
      '    fn can_hold(&self, other: &Rect) -> bool {',
      '        // TODO: 宽和高都严格大于 other 时返回 true',
      '        false',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let big = Rect::new(30, 50);',
      '    let small = Rect::new(10, 40);',
      '    let sq = Rect::square(40);',
      '',
      '    println!("大矩形面积 = {}", big.area());',
      '    println!("正方形面积 = {}", sq.area());',
      '    println!("大矩形能装下小矩形吗？{}", big.can_hold(&small));',
      '    println!("大矩形能装下正方形吗？{}", big.can_hold(&sq));',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Debug)]',
      'struct Rect {',
      '    width: u32,',
      '    height: u32,',
      '}',
      '',
      'impl Rect {',
      '    fn new(width: u32, height: u32) -> Self {',
      '        Self { width, height }',
      '    }',
      '',
      '    fn square(side: u32) -> Self {',
      '        Self::new(side, side)',
      '    }',
      '',
      '    fn area(&self) -> u32 {',
      '        self.width * self.height',
      '    }',
      '',
      '    fn can_hold(&self, other: &Rect) -> bool {',
      '        self.width > other.width && self.height > other.height',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let big = Rect::new(30, 50);',
      '    let small = Rect::new(10, 40);',
      '    let sq = Rect::square(40);',
      '',
      '    println!("大矩形面积 = {}", big.area());',
      '    println!("正方形面积 = {}", sq.area());',
      '    println!("大矩形能装下小矩形吗？{}", big.can_hold(&small));',
      '    println!("大矩形能装下正方形吗？{}", big.can_hold(&sq));',
      '}',
    ].join('\n'),
    expectedStdout:
      '大矩形面积 = 1500\n正方形面积 = 1600\n大矩形能装下小矩形吗？true\n大矩形能装下正方形吗？false\n',
    hints: [
      '`new` 里参数名和字段名一样，可以直接写 `Self { width, height }`（字段简写）。',
      '`square(side)` 一行就够：`Self::new(side, side)`——关联函数之间用 `Self::` 互相调用。',
      '`can_hold` 要两个条件同时成立：`self.width > other.width && self.height > other.height`。注意是严格大于，40 装不下 40。',
    ],
  },
  {
    id: 'm2-03',
    moduleId: 'm2',
    title: '枚举携带数据与 match 穷尽',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### enum 不只是常量列表',
      '',
      'Rust 的枚举**每个变体都可以携带自己的数据**，形状还可以各不相同——这是它和 C/Java 枚举的本质区别：',
      '',
      '```rust',
      'enum Message {',
      '    Quit,                        // 无数据',
      '    Write(String),               // 元组变体',
      '    Move { x: i32, y: i32 },     // 结构体变体',
      '}',
      '```',
      '',
      '取出里面的数据只有一条路：**模式匹配**。`match` 必须覆盖所有变体，漏一个直接编译失败：',
      '',
      '```rust',
      'match msg {',
      '    Message::Quit => println!("退出"),',
      '    Message::Write(text) => println!("写入 {text}"),',
      '    Message::Move { x, y } => println!("移动到 {x},{y}"),',
      '}',
      '```',
      '',
      '**要求**：补全 `describe(event: &RideEvent) -> String`，用 `match` 覆盖全部四个变体，让程序**恰好**输出：',
      '',
      '```text',
      '乘客发起了叫车',
      '老王 接单了',
      '车辆移动到 (12, -3)',
      '订单取消：等太久了',
      '```',
      '',
      '注意参数是 `&RideEvent`（借用），所以匹配出来的 `driver` / `reason` 也是引用（`&String`）——用 `format!` 打印它们不需要额外处理。',
    ].join('\n'),
    starterCode: [
      'enum RideEvent {',
      '    Requested,',
      '    Accepted { driver: String },',
      '    Moved(i32, i32),',
      '    Cancelled(String),',
      '}',
      '',
      'fn describe(event: &RideEvent) -> String {',
      '    // TODO: 用 match 覆盖四个变体，分别返回题面要求的字符串',
      '    match event {',
      '        _ => String::new(),',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let events = vec![',
      '        RideEvent::Requested,',
      '        RideEvent::Accepted {',
      '            driver: String::from("老王"),',
      '        },',
      '        RideEvent::Moved(12, -3),',
      '        RideEvent::Cancelled(String::from("等太久了")),',
      '    ];',
      '',
      '    for event in &events {',
      '        println!("{}", describe(event));',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'enum RideEvent {',
      '    Requested,',
      '    Accepted { driver: String },',
      '    Moved(i32, i32),',
      '    Cancelled(String),',
      '}',
      '',
      'fn describe(event: &RideEvent) -> String {',
      '    match event {',
      '        RideEvent::Requested => String::from("乘客发起了叫车"),',
      '        RideEvent::Accepted { driver } => format!("{driver} 接单了"),',
      '        RideEvent::Moved(x, y) => format!("车辆移动到 ({x}, {y})"),',
      '        RideEvent::Cancelled(reason) => format!("订单取消：{reason}"),',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let events = vec![',
      '        RideEvent::Requested,',
      '        RideEvent::Accepted {',
      '            driver: String::from("老王"),',
      '        },',
      '        RideEvent::Moved(12, -3),',
      '        RideEvent::Cancelled(String::from("等太久了")),',
      '    ];',
      '',
      '    for event in &events {',
      '        println!("{}", describe(event));',
      '    }',
      '}',
    ].join('\n'),
    expectedStdout: '乘客发起了叫车\n老王 接单了\n车辆移动到 (12, -3)\n订单取消：等太久了\n',
    hints: [
      '把 `_ => ...` 换成四条具体分支：`RideEvent::Requested => ...`、`RideEvent::Accepted { driver } => ...`、`RideEvent::Moved(x, y) => ...`、`RideEvent::Cancelled(reason) => ...`。',
      '每个分支都要返回 `String`：无数据的用 `String::from("...")`，带数据的用 `format!`。',
      '第三行的格式是 `format!("车辆移动到 ({x}, {y})")`，逗号后面有一个空格。',
    ],
  },
  {
    id: 'm2-04',
    moduleId: 'm2',
    title: 'match 守卫与范围模式',
    difficulty: 2,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 范围模式 + 匹配守卫',
      '',
      '`match` 的模式比 `switch` 强得多，两个高频武器：',
      '',
      '```rust',
      'match n {',
      '    0 => "零",',
      '    1..=9 => "个位数",          // 范围模式，含两端',
      '    x if x % 2 == 0 => "偶数",  // 匹配守卫：模式后面再加一个布尔条件',
      '    _ => "其他",',
      '}',
      '```',
      '',
      '**分支从上到下依次尝试，第一个匹配上的胜出**，所以顺序就是优先级。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn describe(n: i32) -> String',
      '```',
      '',
      '按下表返回（优先级从上到下）：',
      '',
      '| 条件 | 返回 |',
      '| --- | --- |',
      '| `n < 0` | `"负数"` |',
      '| `n == 0` | `"零"` |',
      '| `1 ..= 9` | `"个位数"` |',
      '| `10 ..= 99` | `"两位数"` |',
      '| 其余（`n >= 100`）中的偶数 | `"大偶数"` |',
      '| 其余中的奇数 | `"大奇数"` |',
      '',
      '**本题以隐藏单元测试判分**（`cargo test`），所以写的是库代码：不要写 `main`，函数必须是 `pub`。',
      '',
      '提示：负数那条用守卫 `n if n < 0`，中间两条用范围模式，最后用 `n if n % 2 == 0` 区分奇偶，兜底 `_`。',
    ].join('\n'),
    starterCode: [
      'pub fn describe(n: i32) -> String {',
      '    // TODO: 按题面表格的优先级写 match：守卫 + 范围模式 + 兜底',
      '    match n {',
      '        _ => String::from("大奇数"),',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn describe(n: i32) -> String {',
      '    match n {',
      '        n if n < 0 => String::from("负数"),',
      '        0 => String::from("零"),',
      '        1..=9 => String::from("个位数"),',
      '        10..=99 => String::from("两位数"),',
      '        n if n % 2 == 0 => String::from("大偶数"),',
      '        _ => String::from("大奇数"),',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '第一条分支必须是负数判断，因为范围模式 `1..=9` 只能覆盖正数，而 `_` 会把负数吞掉。',
      '范围模式的写法是 `1..=9 => ...`（`..=` 含右端，`..` 不含）；每条分支都要返回 `String`。',
      '骨架：`match n { n if n < 0 => ..., 0 => ..., 1..=9 => ..., 10..=99 => ..., n if n % 2 == 0 => ..., _ => ... }`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn negatives_and_zero() {',
      '        assert_eq!(describe(-5), "负数");',
      '        assert_eq!(describe(-1), "负数");',
      '        assert_eq!(describe(0), "零");',
      '    }',
      '',
      '    #[test]',
      '    fn single_digits() {',
      '        assert_eq!(describe(1), "个位数");',
      '        assert_eq!(describe(9), "个位数");',
      '    }',
      '',
      '    #[test]',
      '    fn double_digits() {',
      '        assert_eq!(describe(10), "两位数");',
      '        assert_eq!(describe(99), "两位数");',
      '    }',
      '',
      '    #[test]',
      '    fn large_numbers_split_by_parity() {',
      '        assert_eq!(describe(100), "大偶数");',
      '        assert_eq!(describe(101), "大奇数");',
      '        assert_eq!(describe(1000), "大偶数");',
      '    }',
      '',
      '    #[test]',
      '    fn extreme_values() {',
      '        assert_eq!(describe(i32::MIN), "负数");',
      '        assert_eq!(describe(i32::MAX), "大奇数");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm2-05',
    moduleId: 'm2',
    title: '修复：match 分支不穷尽',
    difficulty: 2,
    judgeMode: 'compile',
    prompt: [
      '### 修编译错误：non-exhaustive patterns',
      '',
      '下面这段代码**编译不过**。点"运行"先看看编译器怎么说：',
      '',
      '```text',
      'error[E0004]: non-exhaustive patterns: `&Payment::Emt(_)` not covered',
      '```',
      '',
      '`match` 必须**穷尽**所有可能。这不是编译器挑刺，而是 Rust 最值钱的安全网之一：',
      '当有人给 `Payment` 加一个新变体时，所有没处理它的 `match` 会**当场编译失败**，而不是在生产环境上悄悄走进 `default` 分支。',
      '',
      '**要求**：补上缺失的分支，让程序编译通过并输出（本题只判编译/运行是否成功）：',
      '',
      '```text',
      '现金',
      '信用卡',
      '微信',
      'EMT 转账',
      '```',
      '',
      '> **重要的取舍**：你也可以用 `_ => "未知"` 一把兜住，但那样就**主动放弃了这张安全网**。',
      '> 对自己领域内的枚举，工程上的推荐做法是**老老实实列全**；`_` 留给"确实不关心其余情况"的场合（比如匹配一个整数）。',
      '本题请补出具体变体分支，不要用 `_`。',
    ].join('\n'),
    starterCode: [
      'enum Payment {',
      '    Cash,',
      '    Card { last4: String },',
      '    Wechat,',
      '    Emt(String),',
      '}',
      '',
      'fn label(payment: &Payment) -> &\'static str {',
      '    // TODO: 这个 match 少了一个变体，补上它',
      '    match payment {',
      '        Payment::Cash => "现金",',
      '        Payment::Card { .. } => "信用卡",',
      '        Payment::Wechat => "微信",',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let payments = vec![',
      '        Payment::Cash,',
      '        Payment::Card {',
      '            last4: String::from("4242"),',
      '        },',
      '        Payment::Wechat,',
      '        Payment::Emt(String::from("wang@example.com")),',
      '    ];',
      '',
      '    for payment in &payments {',
      '        println!("{}", label(payment));',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'enum Payment {',
      '    Cash,',
      '    Card { last4: String },',
      '    Wechat,',
      '    Emt(String),',
      '}',
      '',
      'fn label(payment: &Payment) -> &\'static str {',
      '    match payment {',
      '        Payment::Cash => "现金",',
      '        Payment::Card { .. } => "信用卡",',
      '        Payment::Wechat => "微信",',
      '        Payment::Emt(_) => "EMT 转账",',
      '    }',
      '}',
      '',
      'fn main() {',
      '    let payments = vec![',
      '        Payment::Cash,',
      '        Payment::Card {',
      '            last4: String::from("4242"),',
      '        },',
      '        Payment::Wechat,',
      '        Payment::Emt(String::from("wang@example.com")),',
      '    ];',
      '',
      '    for payment in &payments {',
      '        println!("{}", label(payment));',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '报错里 `not covered` 后面跟的就是漏掉的那个变体：`Payment::Emt(_)`。',
      '这个变体带一个 `String`，但你并不需要它的值——用 `_` 占位即可（`Card { .. }` 那行是同样的思路）。',
      '补一行 `Payment::Emt(_) => "EMT 转账",` 就通过了。',
    ],
  },
  {
    id: 'm2-06',
    moduleId: 'm2',
    title: 'Option：Rust 没有 null',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 用类型表达"可能没有"',
      '',
      'Rust 里不存在 `null`。"可能没有值"由标准库枚举表达：',
      '',
      '```rust',
      'enum Option<T> { Some(T), None }',
      '```',
      '',
      '好处是：`Option<i32>` 和 `i32` 是**两个不同类型**，编译器绝不允许你把前者当后者用——空指针异常在 Rust 里从"运行时崩溃"变成了"编译期报错"。',
      '',
      '取值有三种常用姿势：',
      '',
      '```rust',
      'match maybe { Some(n) => ..., None => ... }   // 最完整',
      'if let Some(n) = maybe { ... } else { ... }   // 只关心一种情况时更短',
      'let n = maybe.unwrap_or(0);                    // 给个兜底默认值',
      '```',
      '',
      '**要求**：实现三个函数（后两个请**复用第一个**）：',
      '',
      '```rust',
      'pub fn find_first_even(nums: &[i32]) -> Option<i32>  // 第一个偶数，没有则 None',
      'pub fn describe_first_even(nums: &[i32]) -> String   // 用 if let 描述结果',
      'pub fn first_even_or_zero(nums: &[i32]) -> i32       // 用 unwrap_or 兜底',
      '```',
      '',
      '| 输入 | `find_first_even` | `describe_first_even` | `first_even_or_zero` |',
      '| --- | --- | --- | --- |',
      '| `[1, 3, 4, 6]` | `Some(4)` | `"第一个偶数是 4"` | `4` |',
      '| `[1, 3, 5]` | `None` | `"没有偶数"` | `0` |',
      '| `[]` | `None` | `"没有偶数"` | `0` |',
      '| `[-2, 7]` | `Some(-2)` | `"第一个偶数是 -2"` | `-2` |',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，三个函数都必须是 `pub`。',
      '',
      '提示：`for &n in nums` 可以直接把 `&i32` 解构成 `i32`；找到就 `return Some(n);`，循环结束后 `None`。',
    ].join('\n'),
    starterCode: [
      'pub fn find_first_even(nums: &[i32]) -> Option<i32> {',
      '    // TODO: 遍历 nums，遇到第一个偶数就返回 Some(n)；一个都没有则返回 None',
      '    None',
      '}',
      '',
      'pub fn describe_first_even(nums: &[i32]) -> String {',
      '    // TODO: 用 if let 取出 find_first_even 的结果',
      '    //       有值 -> format!("第一个偶数是 {n}")，没有 -> "没有偶数"',
      '    String::new()',
      '}',
      '',
      'pub fn first_even_or_zero(nums: &[i32]) -> i32 {',
      '    // TODO: 用 unwrap_or 给出兜底值 0',
      '    -1',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn find_first_even(nums: &[i32]) -> Option<i32> {',
      '    for &n in nums {',
      '        if n % 2 == 0 {',
      '            return Some(n);',
      '        }',
      '    }',
      '    None',
      '}',
      '',
      'pub fn describe_first_even(nums: &[i32]) -> String {',
      '    if let Some(n) = find_first_even(nums) {',
      '        format!("第一个偶数是 {n}")',
      '    } else {',
      '        String::from("没有偶数")',
      '    }',
      '}',
      '',
      'pub fn first_even_or_zero(nums: &[i32]) -> i32 {',
      '    find_first_even(nums).unwrap_or(0)',
      '}',
    ].join('\n'),
    hints: [
      '`find_first_even` 用 `for &n in nums`，命中就 `return Some(n);`；函数最后一行写 `None` 作为兜底返回值。',
      '`describe_first_even` 的骨架是 `if let Some(n) = find_first_even(nums) { format!("第一个偶数是 {n}") } else { String::from("没有偶数") }`——注意 `if let` 也是表达式。',
      '`first_even_or_zero` 一行就够：`find_first_even(nums).unwrap_or(0)`。别用 `unwrap()`，空切片会直接 panic。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn finds_the_first_even_number() {',
      '        assert_eq!(find_first_even(&[1, 3, 4, 6]), Some(4));',
      '    }',
      '',
      '    #[test]',
      '    fn returns_none_when_all_odd_or_empty() {',
      '        assert_eq!(find_first_even(&[1, 3, 5]), None);',
      '        assert_eq!(find_first_even(&[]), None);',
      '    }',
      '',
      '    #[test]',
      '    fn negative_even_counts() {',
      '        assert_eq!(find_first_even(&[-2, 7]), Some(-2));',
      '        assert_eq!(find_first_even(&[0, 1]), Some(0));',
      '    }',
      '',
      '    #[test]',
      '    fn describes_both_cases() {',
      '        assert_eq!(describe_first_even(&[1, 3, 4, 6]), "第一个偶数是 4");',
      '        assert_eq!(describe_first_even(&[-2, 7]), "第一个偶数是 -2");',
      '        assert_eq!(describe_first_even(&[1, 3, 5]), "没有偶数");',
      '        assert_eq!(describe_first_even(&[]), "没有偶数");',
      '    }',
      '',
      '    #[test]',
      '    fn falls_back_to_zero() {',
      '        assert_eq!(first_even_or_zero(&[1, 3, 4, 6]), 4);',
      '        assert_eq!(first_even_or_zero(&[1, 3, 5]), 0);',
      '        assert_eq!(first_even_or_zero(&[]), 0);',
      '        assert_eq!(first_even_or_zero(&[-2, 7]), -2);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm2-07',
    moduleId: 'm2',
    title: 'Result 入门：解析字符串',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 用类型表达"可能失败"',
      '',
      '`Option` 说的是"有没有"，`Result` 说的是"成没成、为什么没成"：',
      '',
      '```rust',
      'enum Result<T, E> { Ok(T), Err(E) }',
      '```',
      '',
      'Rust 没有异常，任何可能失败的操作都把失败**当成返回值**交给你。比如字符串转数字：',
      '',
      '```rust',
      'let r: Result<i32, _> = "42".parse::<i32>();   // Ok(42)',
      'match "abc".parse::<i32>() {',
      '    Ok(n) => println!("成功 {n}"),',
      '    Err(e) => println!("失败 {e}"),           // e 实现了 Display，可以直接打印',
      '}',
      '```',
      '',
      '**要求**：依次处理 `["42", "-7", "abc", "", "2147483648"]` 这五个输入，每个输入打印一行：',
      '',
      '- 解析成功：`输入 "42" -> 双倍 84`',
      '- 解析失败：`输入 "abc" -> 失败：invalid digit found in string`',
      '',
      '程序应当**恰好**输出：',
      '',
      '```text',
      '输入 "42" -> 双倍 84',
      '输入 "-7" -> 双倍 -14',
      '输入 "abc" -> 失败：invalid digit found in string',
      '输入 "" -> 失败：cannot parse integer from empty string',
      '输入 "2147483648" -> 失败：number too large to fit in target type',
      '```',
      '',
      '注意输入两侧的引号是 `{raw:?}` 打印出来的（`Debug` 会给字符串加引号），不是你手写的。',
      '最后一个输入是 `i32::MAX + 1`——**溢出也是一种解析失败**，这正是把错误编码进类型的价值。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let inputs = ["42", "-7", "abc", "", "2147483648"];',
      '',
      '    for raw in inputs {',
      '        // TODO: 用 raw.parse::<i32>() 得到 Result，再用 match 分别处理 Ok / Err',
      '        //       成功打印：输入 {raw:?} -> 双倍 {n * 2}',
      '        //       失败打印：输入 {raw:?} -> 失败：{e}',
      '        let _ = raw;',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let inputs = ["42", "-7", "abc", "", "2147483648"];',
      '',
      '    for raw in inputs {',
      '        match raw.parse::<i32>() {',
      '            Ok(n) => println!("输入 {raw:?} -> 双倍 {}", n * 2),',
      '            Err(e) => println!("输入 {raw:?} -> 失败：{e}"),',
      '        }',
      '    }',
      '}',
    ].join('\n'),
    expectedStdout:
      '输入 "42" -> 双倍 84\n输入 "-7" -> 双倍 -14\n输入 "abc" -> 失败：invalid digit found in string\n输入 "" -> 失败：cannot parse integer from empty string\n输入 "2147483648" -> 失败：number too large to fit in target type\n',
    hints: [
      '`raw.parse::<i32>()` 返回 `Result<i32, ParseIntError>`，用 `match` 分成 `Ok(n)` 和 `Err(e)` 两条分支。',
      '成功那行要算 `n * 2`：`println!("输入 {raw:?} -> 双倍 {}", n * 2);`。',
      '失败那行直接打印错误值：`println!("输入 {raw:?} -> 失败：{e}");`——错误信息由标准库给出，不用自己写。注意 `->` 两侧各一个半角空格，「失败：」后面用的是中文冒号。',
    ],
  },
  {
    id: 'm2-08',
    moduleId: 'm2',
    title: 'Result 与 map_err：校验年龄',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 把失败翻译成自己的错误类型',
      '',
      '真实业务里，底层错误（比如 `ParseIntError`）往往不是你想暴露给调用方的东西。',
      '`map_err` 负责**只改错误分支、保留成功分支**，`?` 负责**成功就取值、失败就提前返回**：',
      '',
      '```rust',
      'let n: i32 = s.parse::<i32>().map_err(|e| format!("无法解析：{e}"))?;',
      '//                            ^^^^^^^ Err(ParseIntError) -> Err(String)',
      '//                                                                    ^ 失败就 return Err(...)',
      '```',
      '',
      '这一行等价于一大段 `match`，但读起来是"主干逻辑 + 出错就走人"。（`?` 的完整规则在模块三细讲。）',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn parse_age(s: &str) -> Result<u8, String>',
      '```',
      '',
      '规则：',
      '',
      '1. 先 `s.trim()` 去掉首尾空白，再解析成 `i32`（**别直接解析成 `u8`**，否则负数和超大值的报错就分不出来了）；',
      '2. 解析失败 → `Err(format!("无法解析：{e}"))`，`e` 是标准库给的错误；',
      '3. 解析成功但不在 `0..=130` 范围内 → `Err(format!("年龄超出范围：{n}"))`；',
      '4. 否则 → `Ok(n as u8)`。',
      '',
      '| 输入 | 结果 |',
      '| --- | --- |',
      '| `"18"` | `Ok(18)` |',
      '| `" 42 "` | `Ok(42)` |',
      '| `"0"` / `"130"` | `Ok(0)` / `Ok(130)` |',
      '| `"abc"` | `Err("无法解析：invalid digit found in string")` |',
      '| `"-1"` | `Err("年龄超出范围：-1")` |',
      '| `"200"` | `Err("年龄超出范围：200")` |',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
      '',
      '提示：范围判断可以写 `if !(0..=130).contains(&n) { return Err(...); }`。',
    ].join('\n'),
    starterCode: [
      'pub fn parse_age(s: &str) -> Result<u8, String> {',
      '    // TODO: 1) s.trim().parse::<i32>()，用 map_err 把错误换成 format!("无法解析：{e}")，再用 ? 传播',
      '    // TODO: 2) 不在 0..=130 范围内 -> Err(format!("年龄超出范围：{n}"))',
      '    // TODO: 3) 否则 Ok(n as u8)',
      '    let _ = s;',
      '    Ok(0)',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn parse_age(s: &str) -> Result<u8, String> {',
      '    let n: i32 = s',
      '        .trim()',
      '        .parse::<i32>()',
      '        .map_err(|e| format!("无法解析：{e}"))?;',
      '',
      '    if !(0..=130).contains(&n) {',
      '        return Err(format!("年龄超出范围：{n}"));',
      '    }',
      '',
      '    Ok(n as u8)',
      '}',
    ].join('\n'),
    hints: [
      '第一步：`let n: i32 = s.trim().parse::<i32>().map_err(|e| format!("无法解析：{e}"))?;`——`map_err` 只动错误分支。',
      '第二步是普通的 `if` 判断，不满足就 `return Err(format!("年龄超出范围：{n}"));`（这里必须写 `return`，因为不是函数最后一个表达式）。',
      '最后一行 `Ok(n as u8)`。注意判断范围要在转成 `u8` **之前**做——先转的话 `-1` 会解析失败或截断，错误信息就对不上了。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn parses_plain_number() {',
      '        assert_eq!(parse_age("18"), Ok(18));',
      '    }',
      '',
      '    #[test]',
      '    fn trims_whitespace() {',
      '        assert_eq!(parse_age(" 42 "), Ok(42));',
      '        assert_eq!(parse_age("\\n7\\t"), Ok(7));',
      '    }',
      '',
      '    #[test]',
      '    fn accepts_boundaries() {',
      '        assert_eq!(parse_age("0"), Ok(0));',
      '        assert_eq!(parse_age("130"), Ok(130));',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_out_of_range() {',
      '        assert_eq!(parse_age("-1"), Err(String::from("年龄超出范围：-1")));',
      '        assert_eq!(parse_age("200"), Err(String::from("年龄超出范围：200")));',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_non_numeric() {',
      '        let err = parse_age("abc").unwrap_err();',
      '        assert!(err.starts_with("无法解析："), "实际错误：{err}");',
      '        assert!(parse_age("").is_err());',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm2-09',
    moduleId: 'm2',
    title: '综合：用枚举建模订单状态机',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 让非法状态无法表示',
      '',
      '这是本模块的收尾题，也是 Rust 类型建模最典型的用法：**把状态机写成枚举**，',
      '再用 `match` 把"哪些流转是合法的"钉死在编译器能检查的地方——而不是靠一堆 `if status == "accepted"` 字符串比较。',
      '',
      '给定打车订单的五个状态：',
      '',
      '```text',
      'Created  --下单--> Accepted --上车--> PickedUp --到达--> Completed',
      '   \\                   \\',
      '    \\----取消----> Cancelled <----取消----/',
      '```',
      '',
      '**要求**：实现两个函数',
      '',
      '```rust',
      'pub fn next_status(current: OrderStatus) -> Option<OrderStatus>',
      'pub fn can_cancel(status: OrderStatus) -> bool',
      '```',
      '',
      '`next_status`：返回**正常流转**的下一个状态，已经是终态则返回 `None`。',
      '',
      '| 当前 | 下一个 |',
      '| --- | --- |',
      '| `Created` | `Some(Accepted)` |',
      '| `Accepted` | `Some(PickedUp)` |',
      '| `PickedUp` | `Some(Completed)` |',
      '| `Completed` | `None` |',
      '| `Cancelled` | `None` |',
      '',
      '`can_cancel`：只有 `Created` 和 `Accepted` 可以取消（上车之后、完成之后、已取消都不行）。',
      '',
      '`OrderStatus` 已经给你定义好了，注意它 `#[derive(Debug, Clone, Copy, PartialEq, Eq)]`——',
      '因为是 `Copy`，函数按值接收它不会 move 掉调用方的变量。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，两个函数都必须是 `pub`。',
      '',
      '提示：两个函数都写成一个 `match` 表达式；`can_cancel` 可以用 `|` 把两个变体合并成一条分支：`Created | Accepted => true`。',
    ].join('\n'),
    starterCode: [
      '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
      'pub enum OrderStatus {',
      '    Created,',
      '    Accepted,',
      '    PickedUp,',
      '    Completed,',
      '    Cancelled,',
      '}',
      '',
      'pub fn next_status(current: OrderStatus) -> Option<OrderStatus> {',
      '    // TODO: 用 match 覆盖五个状态，返回正常流转的下一个状态；终态返回 None',
      '    let _ = current;',
      '    None',
      '}',
      '',
      'pub fn can_cancel(status: OrderStatus) -> bool {',
      '    // TODO: 只有 Created 和 Accepted 可以取消',
      '    let _ = status;',
      '    false',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
      'pub enum OrderStatus {',
      '    Created,',
      '    Accepted,',
      '    PickedUp,',
      '    Completed,',
      '    Cancelled,',
      '}',
      '',
      'pub fn next_status(current: OrderStatus) -> Option<OrderStatus> {',
      '    match current {',
      '        OrderStatus::Created => Some(OrderStatus::Accepted),',
      '        OrderStatus::Accepted => Some(OrderStatus::PickedUp),',
      '        OrderStatus::PickedUp => Some(OrderStatus::Completed),',
      '        OrderStatus::Completed | OrderStatus::Cancelled => None,',
      '    }',
      '}',
      '',
      'pub fn can_cancel(status: OrderStatus) -> bool {',
      '    match status {',
      '        OrderStatus::Created | OrderStatus::Accepted => true,',
      '        OrderStatus::PickedUp | OrderStatus::Completed | OrderStatus::Cancelled => false,',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '`next_status` 的每条分支返回的都是 `Option<OrderStatus>`：前三条是 `Some(OrderStatus::…)`，后两条是 `None`。',
      '多个变体走同一条分支时用 `|` 合并：`OrderStatus::Completed | OrderStatus::Cancelled => None,`。',
      '`can_cancel` 同理：`OrderStatus::Created | OrderStatus::Accepted => true,` 其余 `=> false`。这里刻意不写 `_`，将来加新状态时编译器会提醒你重新想一遍取消规则。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '    use OrderStatus::*;',
      '',
      '    #[test]',
      '    fn happy_path_flows_forward() {',
      '        assert_eq!(next_status(Created), Some(Accepted));',
      '        assert_eq!(next_status(Accepted), Some(PickedUp));',
      '        assert_eq!(next_status(PickedUp), Some(Completed));',
      '    }',
      '',
      '    #[test]',
      '    fn terminal_states_have_no_next() {',
      '        assert_eq!(next_status(Completed), None);',
      '        assert_eq!(next_status(Cancelled), None);',
      '    }',
      '',
      '    #[test]',
      '    fn full_chain_reaches_completed() {',
      '        let mut status = Created;',
      '        let mut steps = 0;',
      '        while let Some(next) = next_status(status) {',
      '            status = next;',
      '            steps += 1;',
      '        }',
      '        assert_eq!(status, Completed);',
      '        assert_eq!(steps, 3);',
      '    }',
      '',
      '    #[test]',
      '    fn only_early_states_are_cancellable() {',
      '        assert!(can_cancel(Created));',
      '        assert!(can_cancel(Accepted));',
      '        assert!(!can_cancel(PickedUp));',
      '        assert!(!can_cancel(Completed));',
      '        assert!(!can_cancel(Cancelled));',
      '    }',
      '',
      '    #[test]',
      '    fn status_is_copy_and_comparable() {',
      '        let status = Accepted;',
      '        let copied = status;',
      '        assert_eq!(status, copied);',
      '        assert_ne!(status, Created);',
      '    }',
      '}',
    ].join('\n'),
  },
];
