import type { Exercise } from '@/lib/rust/types';

export const module5Exercises: Exercise[] = [
  {
    id: 'm5-01',
    moduleId: 'm5',
    title: 'spawn + join：等子线程算完',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 启动线程，并把结果带回主线程',
      '',
      '`thread::spawn` 立即启动一个子线程，并返回 `JoinHandle<T>`。闭包最后一个表达式的值就是子线程的结果；调用 `join()` 会阻塞当前线程，直到子线程结束，并得到 `Result<T, _>`。',
      '',
      '**要求**：',
      '',
      '1. 在子线程中计算 `1..=5` 的和，并返回字符串 `子线程计算结果：15`；',
      '2. 主线程启动子线程后先打印 `主线程：已启动子线程`；',
      '3. 调用 `join()` 取回字符串，再依次打印子线程结果和 `主线程：子线程已结束`。',
      '',
      '程序必须恰好输出：',
      '',
      '```text',
      '主线程：已启动子线程',
      '子线程计算结果：15',
      '主线程：子线程已结束',
      '```',
      '',
      '子线程不要直接打印：调度顺序不可预测。让它**返回数据**，主线程在 `join` 之后打印，输出顺序才是确定的。',
    ].join('\n'),
    starterCode: [
      'use std::thread;',
      '',
      'fn main() {',
      '    let handle = thread::spawn(|| {',
      '        // TODO: 计算 1..=5 的和，并返回 "子线程计算结果：<sum>"',
      '        String::new()',
      '    });',
      '',
      '    println!("主线程：已启动子线程");',
      '',
      '    // TODO: join 子线程，取出它返回的字符串',
      '    let message = String::new();',
      '    println!("{message}");',
      '    println!("主线程：子线程已结束");',
      '',
      '    let _ = handle;',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::thread;',
      '',
      'fn main() {',
      '    let handle = thread::spawn(|| {',
      '        let sum: i32 = (1..=5).sum();',
      '        format!("子线程计算结果：{sum}")',
      '    });',
      '',
      '    println!("主线程：已启动子线程");',
      '',
      '    let message = handle.join().expect("子线程不应 panic");',
      '    println!("{message}");',
      '    println!("主线程：子线程已结束");',
      '}',
    ].join('\n'),
    expectedStdout: '主线程：已启动子线程\n子线程计算结果：15\n主线程：子线程已结束\n',
    hints: [
      '把子线程闭包的最后一个表达式写成 `format!(...)`，这个 `String` 会成为 `JoinHandle` 携带的结果。',
      '区间求和可写成 `let sum: i32 = (1..=5).sum();`；主线程通过 `handle.join()` 等待。',
      '取结果的完整写法是 `let message = handle.join().expect("子线程不应 panic");`，随后再打印 `message`。',
    ],
  },
  {
    id: 'm5-02',
    moduleId: 'm5',
    title: '分片多线程求和',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 把 Vec 分给多个工作线程',
      '',
      '实现：',
      '',
      '```rust',
      'pub fn parallel_sum(nums: Vec<i32>, n_threads: usize) -> i32',
      '```',
      '',
      '把输入尽量均匀地切成若干非空 chunk，每个 chunk 交给一个 `thread::spawn` 求局部和，最后按 `JoinHandle` 的保存顺序逐个 `join` 并求总和。',
      '',
      '**边界约定**：',
      '',
      '- 空 `Vec` 返回 `0`；',
      '- `n_threads == 0` 时按 `1` 个线程处理；',
      '- 线程数多于元素数时，不创建空任务。',
      '',
      '可以先令 `workers = n_threads.max(1).min(nums.len())`，再用 `nums.len().div_ceil(workers)` 得到向上取整的 chunk 大小。普通 `thread::spawn` 要求闭包拥有其中的数据，所以可对每个切片调用 `to_vec()`，再用 `move` 把这个小 `Vec` 交给线程。',
      '',
      '本题以隐藏单元测试判分：不要写 `main`，函数必须是 `pub`。最终只断言总和，不观察线程完成顺序。',
    ].join('\n'),
    starterCode: [
      'use std::thread;',
      '',
      'pub fn parallel_sum(nums: Vec<i32>, n_threads: usize) -> i32 {',
      '    // TODO: 处理空输入，并计算实际工作线程数与 chunk 大小',
      '    // TODO: 为每个 chunk spawn 一个 move 闭包，保存 JoinHandle',
      '    // TODO: join 所有线程，把局部和累加后返回',
      '    let _ = (nums, n_threads);',
      '    0',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::thread;',
      '',
      'pub fn parallel_sum(nums: Vec<i32>, n_threads: usize) -> i32 {',
      '    if nums.is_empty() {',
      '        return 0;',
      '    }',
      '',
      '    let workers = n_threads.max(1).min(nums.len());',
      '    let chunk_size = nums.len().div_ceil(workers);',
      '    let mut handles = Vec::new();',
      '',
      '    for chunk in nums.chunks(chunk_size) {',
      '        let owned_chunk = chunk.to_vec();',
      '        handles.push(thread::spawn(move || owned_chunk.into_iter().sum::<i32>()));',
      '    }',
      '',
      '    handles',
      '        .into_iter()',
      '        .map(|handle| handle.join().expect("工作线程不应 panic"))',
      '        .sum()',
      '}',
    ].join('\n'),
    hints: [
      '先单独处理空输入；否则 `workers = n_threads.max(1).min(nums.len())` 能同时覆盖零线程和线程过多。',
      '用 `let owned_chunk = chunk.to_vec();` 取得独立所有权，再 `thread::spawn(move || ...)`；把每个 handle 推入 `Vec`。',
      '最后对 handles 调用 `into_iter()`，把每个 `join().expect(...)` 得到的局部和交给 `.sum()`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn sums_even_chunks() {',
      '        assert_eq!(parallel_sum(vec![1, 2, 3, 4, 5, 6], 3), 21);',
      '    }',
      '',
      '    #[test]',
      '    fn handles_uneven_chunks() {',
      '        assert_eq!(parallel_sum(vec![10, 20, 30, 40, 50], 2), 150);',
      '    }',
      '',
      '    #[test]',
      '    fn caps_workers_at_the_number_of_elements() {',
      '        assert_eq!(parallel_sum(vec![7, 8, 9], 20), 24);',
      '    }',
      '',
      '    #[test]',
      '    fn zero_threads_falls_back_to_one() {',
      '        assert_eq!(parallel_sum(vec![3, -8, 13], 0), 8);',
      '    }',
      '',
      '    #[test]',
      '    fn handles_empty_and_negative_inputs() {',
      '        assert_eq!(parallel_sum(Vec::new(), 4), 0);',
      '        assert_eq!(parallel_sum(vec![-5, -10, 4, 1], 3), -10);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm5-03',
    moduleId: 'm5',
    title: '修复 E0373：线程闭包需要 move',
    difficulty: 3,
    judgeMode: 'compile',
    expectedStdout: "所有权已进入子线程\n",
    prompt: [
      '### 子线程不能借用可能先被释放的局部变量',
      '',
      '下面的代码会触发类似诊断：',
      '',
      '```text',
      'error[E0373]: closure may outlive the current function, but it borrows `message`',
      '```',
      '',
      '`thread::spawn` 启动的线程理论上可能比当前函数活得更久，因此它的闭包必须满足 `\'static`。原闭包默认借用局部 `String`；如果主线程作用域先结束，这个引用就会悬垂。',
      '',
      '**要求**：只调整闭包的捕获方式，让闭包取得 `message` 的所有权。保留 `spawn`、`join` 和打印逻辑，使程序可以编译运行。',
      '',
      '`move` 的意思是“按值捕获”，不是“强制创建深拷贝”：这里 `String` 会真正转移进闭包，之后主线程不能再使用原变量。',
    ].join('\n'),
    starterCode: [
      'use std::thread;',
      '',
      'fn main() {',
      '    let message = String::from("所有权已进入子线程");',
      '',
      '    // TODO: 这个闭包借用了局部变量，无法满足 spawn 的生命周期要求',
      '    let handle = thread::spawn(|| {',
      '        println!("{message}");',
      '    });',
      '',
      '    handle.join().expect("子线程不应 panic");',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::thread;',
      '',
      'fn main() {',
      '    let message = String::from("所有权已进入子线程");',
      '',
      '    let handle = thread::spawn(move || {',
      '        println!("{message}");',
      '    });',
      '',
      '    handle.join().expect("子线程不应 panic");',
      '}',
    ].join('\n'),
    hints: [
      '错误来自闭包默认按借用捕获 `message`，而新线程的生命周期不能依赖当前栈帧。',
      '在闭包参数 `||` 前加捕获关键字，让闭包拥有它用到的局部值。',
      '把 `thread::spawn(|| {` 改成 `thread::spawn(move || {` 即可。',
    ],
  },
  {
    id: 'm5-04',
    moduleId: 'm5',
    title: 'mpsc：多生产者汇入一个接收端',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 用 channel 传所有权，不共享可变容器',
      '',
      '实现：',
      '',
      '```rust',
      'pub fn collect_messages(producers: Vec<Vec<String>>) -> Vec<String>',
      '```',
      '',
      '外层 `Vec` 的每一项代表一个生产者要发送的一批消息。为每批消息启动一个线程；每个线程持有一份 `Sender` 克隆，并逐条 `send`。主线程从唯一的 `Receiver` 收集全部消息，排序后返回。',
      '',
      '关键步骤：',
      '',
      '1. `let (tx, rx) = mpsc::channel();`；',
      '2. 对每批消息克隆 `tx`，用 `move` 交给生产者线程；',
      '3. 所有线程启动后 `drop(tx)`，否则接收端会一直等原始发送端关闭；',
      '4. 用 `rx.into_iter().collect()` 收到 channel 关闭，再排序；',
      '5. `join` 所有生产者，确保没有线程 panic。',
      '',
      '生产者发送顺序受调度影响，测试只比较**排序后的集合**。本题以隐藏单元测试判分，不要写 `main`。',
    ].join('\n'),
    starterCode: [
      'use std::sync::mpsc;',
      'use std::thread;',
      '',
      'pub fn collect_messages(producers: Vec<Vec<String>>) -> Vec<String> {',
      '    let (tx, rx) = mpsc::channel();',
      '',
      '    // TODO: 每批消息启动一个生产者线程；克隆 tx 并逐条 send',
      '    // TODO: drop 原始 tx，收集 rx，排序并 join 全部线程',
      '    let _ = (producers, tx, rx);',
      '    Vec::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::sync::mpsc;',
      'use std::thread;',
      '',
      'pub fn collect_messages(producers: Vec<Vec<String>>) -> Vec<String> {',
      '    let (tx, rx) = mpsc::channel();',
      '    let mut handles = Vec::new();',
      '',
      '    for messages in producers {',
      '        let worker_tx = tx.clone();',
      '        handles.push(thread::spawn(move || {',
      '            for message in messages {',
      '                worker_tx.send(message).expect("接收端仍然存在");',
      '            }',
      '        }));',
      '    }',
      '',
      '    drop(tx);',
      '    let mut received: Vec<String> = rx.into_iter().collect();',
      '',
      '    for handle in handles {',
      '        handle.join().expect("生产者不应 panic");',
      '    }',
      '',
      '    received.sort();',
      '    received',
      '}',
    ].join('\n'),
    hints: [
      '`mpsc` 的 `Sender` 可以 `clone`；每轮循环创建 `worker_tx`，再和当前 `messages` 一起 `move` 进闭包。',
      '启动全部线程后必须 `drop(tx)`，这样最后一个克隆发送端被释放时，`rx.into_iter()` 才会结束。',
      '声明 `let mut received: Vec<String> = rx.into_iter().collect();`，join handles 后调用 `received.sort()` 并返回。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    fn strings(items: &[&str]) -> Vec<String> {',
      '        items.iter().map(|item| (*item).to_owned()).collect()',
      '    }',
      '',
      '    #[test]',
      '    fn collects_from_multiple_producers_in_sorted_order() {',
      '        let batches = vec![strings(&["pear", "apple"]), strings(&["orange", "banana"])];',
      '        assert_eq!(collect_messages(batches), strings(&["apple", "banana", "orange", "pear"]));',
      '    }',
      '',
      '    #[test]',
      '    fn preserves_duplicate_messages() {',
      '        let batches = vec![strings(&["same", "x"]), strings(&["same"])];',
      '        assert_eq!(collect_messages(batches), strings(&["same", "same", "x"]));',
      '    }',
      '',
      '    #[test]',
      '    fn handles_one_producer() {',
      '        assert_eq!(collect_messages(vec![strings(&["b", "a"])]), strings(&["a", "b"]));',
      '    }',
      '',
      '    #[test]',
      '    fn handles_empty_batches() {',
      '        let batches = vec![Vec::new(), strings(&["only"]), Vec::new()];',
      '        assert_eq!(collect_messages(batches), strings(&["only"]));',
      '    }',
      '',
      '    #[test]',
      '    fn no_producers_yields_an_empty_collection() {',
      '        assert!(collect_messages(Vec::new()).is_empty());',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm5-05',
    moduleId: 'm5',
    title: 'Arc<Mutex<HashMap>> 并发词频',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 跨线程共享一个可变计数器',
      '',
      '实现：',
      '',
      '```rust',
      'pub fn count_words_parallel(lines: Vec<String>) -> HashMap<String, usize>',
      '```',
      '',
      '为每一行文本启动一个线程，按 `split_whitespace()` 分词，把所有线程的词频合并进同一个 `HashMap`。分词结果**区分大小写**，不移除标点。',
      '',
      '`Rc` 不能跨线程；这里要用 `Arc<Mutex<HashMap<...>>>`：`Arc` 提供线程安全的共享所有权，`Mutex` 保证同一时刻只有一个线程能修改 map。每个线程先在自己的局部 `HashMap` 中计数，再只加锁一次完成合并，可以显著缩短锁的持有时间。',
      '',
      '全部 `join` 后，用 `Arc::try_unwrap` 取回唯一的 `Mutex`，再用 `into_inner()` 得到最终 map。不要依赖 `HashMap` 的遍历顺序；隐藏测试按键查询或直接比较映射。',
      '',
      '本题以隐藏单元测试判分，不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use std::collections::HashMap;',
      'use std::sync::{Arc, Mutex};',
      'use std::thread;',
      '',
      'pub fn count_words_parallel(lines: Vec<String>) -> HashMap<String, usize> {',
      '    // TODO: 创建 Arc<Mutex<HashMap<...>>>，每行启动一个线程',
      '    // TODO: 在线程中先做局部计数，再加锁合并',
      '    // TODO: join 后解开 Arc 和 Mutex，返回最终 HashMap',
      '    let _ = (lines, Arc::new(Mutex::new(())), thread::current());',
      '    HashMap::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::collections::HashMap;',
      'use std::sync::{Arc, Mutex};',
      'use std::thread;',
      '',
      'pub fn count_words_parallel(lines: Vec<String>) -> HashMap<String, usize> {',
      '    let counts = Arc::new(Mutex::new(HashMap::new()));',
      '    let mut handles = Vec::new();',
      '',
      '    for line in lines {',
      '        let shared_counts = Arc::clone(&counts);',
      '        handles.push(thread::spawn(move || {',
      '            let mut local = HashMap::new();',
      '            for word in line.split_whitespace() {',
      '                *local.entry(word.to_owned()).or_insert(0) += 1;',
      '            }',
      '',
      '            let mut global = shared_counts.lock().expect("词频锁不应中毒");',
      '            for (word, count) in local {',
      '                *global.entry(word).or_insert(0) += count;',
      '            }',
      '        }));',
      '    }',
      '',
      '    for handle in handles {',
      '        handle.join().expect("计数线程不应 panic");',
      '    }',
      '',
      '    Arc::try_unwrap(counts)',
      '        .expect("所有线程中的 Arc 克隆都应释放")',
      '        .into_inner()',
      '        .expect("词频锁不应中毒")',
      '}',
    ].join('\n'),
    hints: [
      '创建 `Arc::new(Mutex::new(HashMap::new()))`；每轮用 `Arc::clone(&counts)` 给新线程一份共享所有权。',
      '线程内部先创建局部 map 并用 `entry(...).or_insert(0)` 计数，然后 `lock()` 一次，把局部键值合并到全局 map。',
      'join 全部 handle 后，链式调用 `Arc::try_unwrap(counts).expect(...).into_inner().expect(...)` 取出结果。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    fn lines(items: &[&str]) -> Vec<String> {',
      '        items.iter().map(|item| (*item).to_owned()).collect()',
      '    }',
      '',
      '    #[test]',
      '    fn counts_words_across_lines() {',
      '        let counts = count_words_parallel(lines(&["rust is fast", "rust is safe"]));',
      '        assert_eq!(counts.get("rust"), Some(&2));',
      '        assert_eq!(counts.get("is"), Some(&2));',
      '        assert_eq!(counts.get("fast"), Some(&1));',
      '        assert_eq!(counts.get("safe"), Some(&1));',
      '    }',
      '',
      '    #[test]',
      '    fn counts_repetitions_within_one_line() {',
      '        let counts = count_words_parallel(lines(&["go go rust go"]));',
      '        assert_eq!(counts.get("go"), Some(&3));',
      '        assert_eq!(counts.get("rust"), Some(&1));',
      '    }',
      '',
      '    #[test]',
      '    fn empty_input_and_blank_lines_are_empty() {',
      '        assert!(count_words_parallel(Vec::new()).is_empty());',
      '        assert!(count_words_parallel(lines(&["", "   \\t"])).is_empty());',
      '    }',
      '',
      '    #[test]',
      '    fn supports_unicode_words() {',
      '        let counts = count_words_parallel(lines(&["无畏 并发", "无畏 Rust"]));',
      '        assert_eq!(counts.get("无畏"), Some(&2));',
      '        assert_eq!(counts.get("并发"), Some(&1));',
      '        assert_eq!(counts.get("Rust"), Some(&1));',
      '    }',
      '',
      '    #[test]',
      '    fn counting_is_case_sensitive() {',
      '        let counts = count_words_parallel(lines(&["Rust rust RUST"]));',
      '        assert_eq!(counts.get("Rust"), Some(&1));',
      '        assert_eq!(counts.get("rust"), Some(&1));',
      '        assert_eq!(counts.get("RUST"), Some(&1));',
      '        assert_eq!(counts.len(), 3);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm5-06',
    moduleId: 'm5',
    title: '修复 E0277：Rc 不能跨线程',
    difficulty: 4,
    judgeMode: 'compile',
    expectedStdout: "子线程求和 = 20，主线程仍持有 4 个元素\n",
    prompt: [
      '### 单线程引用计数不能在线程间转移',
      '',
      '下面的代码会触发类似诊断：',
      '',
      '```text',
      'error[E0277]: `Rc<Vec<i32>>` cannot be sent between threads safely',
      '```',
      '',
      '`Send` 表示“值的所有权可以安全地转移到另一个线程”。`Rc<T>` 的引用计数增减不是原子操作；若允许多个线程同时修改计数，就会发生数据竞争，所以 `Rc<T>` 没有实现 `Send`。',
      '',
      '**要求**：把共享所有权类型从 `Rc` 改成线程安全的原子引用计数 `Arc`，并调整构造与克隆代码。保留子线程求和与最终断言。',
      '',
      '`Arc` 只让**引用计数**线程安全，并不会自动让内部的 `T` 可变；需要共享修改时还要组合 `Mutex`、`RwLock` 或原子类型。',
    ].join('\n'),
    starterCode: [
      'use std::rc::Rc;',
      'use std::thread;',
      '',
      'fn main() {',
      '    let numbers = Rc::new(vec![2, 4, 6, 8]);',
      '    let worker_numbers = Rc::clone(&numbers);',
      '',
      '    // TODO: Rc 不是 Send，不能被 move 到新线程；改用线程安全的共享所有权',
      '    let handle = thread::spawn(move || worker_numbers.iter().sum::<i32>());',
      '',
      '    let total = handle.join().expect("子线程不应 panic");',
      '    assert_eq!(total, 20);',
      '    assert_eq!(numbers.len(), 4);',
      '    println!("子线程求和 = {total}，主线程仍持有 {} 个元素", numbers.len());',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::sync::Arc;',
      'use std::thread;',
      '',
      'fn main() {',
      '    let numbers = Arc::new(vec![2, 4, 6, 8]);',
      '    let worker_numbers = Arc::clone(&numbers);',
      '',
      '    let handle = thread::spawn(move || worker_numbers.iter().sum::<i32>());',
      '',
      '    let total = handle.join().expect("子线程不应 panic");',
      '    assert_eq!(total, 20);',
      '    assert_eq!(numbers.len(), 4);',
      '    println!("子线程求和 = {total}，主线程仍持有 {} 个元素", numbers.len());',
      '}',
    ].join('\n'),
    hints: [
      '`Rc` 的计数器不是原子的；跨线程共享所有权应使用 `std::sync` 中的对应类型。',
      '把导入改成 `use std::sync::Arc;`，并把构造和克隆处的类型名一并替换。',
      '三处分别改为 `Arc`、`Arc::new(...)`、`Arc::clone(&numbers)`。',
    ],
  },
  {
    id: 'm5-07',
    moduleId: 'm5',
    title: 'AtomicUsize：无锁计数',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 用原子操作替代简单计数锁',
      '',
      '实现：',
      '',
      '```rust',
      'pub fn atomic_count(n_threads: usize, increments_per_thread: usize) -> usize',
      '```',
      '',
      '创建一个 `Arc<AtomicUsize>`；启动 `n_threads` 个线程，每个线程循环 `increments_per_thread` 次，并调用：',
      '',
      '```rust',
      'counter.fetch_add(1, Ordering::Relaxed);',
      '```',
      '',
      '全部线程 `join` 后，用 `load(Ordering::Relaxed)` 读取最终值并返回。只断言总数 `n_threads * increments_per_thread`，不观察各线程的先后顺序。',
      '',
      '`fetch_add` 是不可分割的读-改-写，因此不会丢失增量。`Relaxed` 只保证这次原子操作本身安全，不为其他内存读写建立顺序；本题的数据只有独立计数器，而且 `join` 已确保所有工作结束，所以足够。需要最容易推理的全局顺序时可先用 `SeqCst`。',
      '',
      '本题以隐藏单元测试判分，不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use std::sync::atomic::{AtomicUsize, Ordering};',
      'use std::sync::Arc;',
      'use std::thread;',
      '',
      'pub fn atomic_count(n_threads: usize, increments_per_thread: usize) -> usize {',
      '    // TODO: 用 Arc<AtomicUsize> 创建共享计数器',
      '    // TODO: 每个线程循环 fetch_add(1, Ordering::Relaxed)，再 join',
      '    // TODO: load 最终值并返回',
      '    let _ = (n_threads, increments_per_thread, AtomicUsize::new(0), Ordering::Relaxed);',
      '    Arc::strong_count(&Arc::new(())) - 1',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::sync::atomic::{AtomicUsize, Ordering};',
      'use std::sync::Arc;',
      'use std::thread;',
      '',
      'pub fn atomic_count(n_threads: usize, increments_per_thread: usize) -> usize {',
      '    let counter = Arc::new(AtomicUsize::new(0));',
      '    let mut handles = Vec::new();',
      '',
      '    for _ in 0..n_threads {',
      '        let worker_counter = Arc::clone(&counter);',
      '        handles.push(thread::spawn(move || {',
      '            for _ in 0..increments_per_thread {',
      '                worker_counter.fetch_add(1, Ordering::Relaxed);',
      '            }',
      '        }));',
      '    }',
      '',
      '    for handle in handles {',
      '        handle.join().expect("计数线程不应 panic");',
      '    }',
      '',
      '    counter.load(Ordering::Relaxed)',
      '}',
    ].join('\n'),
    hints: [
      '共享值写成 `Arc::new(AtomicUsize::new(0))`；每次 spawn 前用 `Arc::clone(&counter)`。',
      '线程闭包中循环 `0..increments_per_thread`，每轮调用 `worker_counter.fetch_add(1, Ordering::Relaxed);`。',
      '保存并 join 全部 handles 后，返回 `counter.load(Ordering::Relaxed)`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn counts_all_increments() {',
      '        assert_eq!(atomic_count(4, 1_000), 4_000);',
      '    }',
      '',
      '    #[test]',
      '    fn works_with_one_thread() {',
      '        assert_eq!(atomic_count(1, 137), 137);',
      '    }',
      '',
      '    #[test]',
      '    fn zero_threads_produces_zero() {',
      '        assert_eq!(atomic_count(0, 500), 0);',
      '    }',
      '',
      '    #[test]',
      '    fn zero_increments_produces_zero() {',
      '        assert_eq!(atomic_count(8, 0), 0);',
      '    }',
      '',
      '    #[test]',
      '    fn total_depends_only_on_the_product() {',
      '        assert_eq!(atomic_count(3, 777), 2_331);',
      '        assert_eq!(atomic_count(7, 333), 2_331);',
      '    }',
      '}',
    ].join('\n'),
  },
];
