import type { Exercise } from '@/lib/rust/types';

export const module7Exercises: Exercise[] = [
  {
    id: 'm7-01',
    moduleId: 'm7',
    title: 'REST 路由匹配：资源与动作',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 先把路由表写成纯函数',
      '',
      'REST 路由应该围绕**资源**命名，再用 HTTP method 表达动作，而不是把动词塞进路径：',
      '',
      '| method | path | handler 名 |',
      '| --- | --- | --- |',
      '| `GET` | `/orders` | `list_orders` |',
      '| `POST` | `/orders` | `create_order` |',
      '| `GET` | `/orders/{id}` | `get_order` |',
      '| `PATCH` | `/orders/{id}` | `update_order` |',
      '| `DELETE` | `/orders/{id}` | `delete_order` |',
      '',
      '**要求**：实现',
      '',
      '```rust',
      "pub fn route(method: &str, path: &str) -> &'static str",
      '```',
      '',
      '按上表返回 handler 名；没有匹配时统一返回 `"not_found"`。',
      '`{id}` 可以是任意**非空的单个路径段**，例如 `42` 或 `ord-2026`，但 `/orders/` 与 `/orders/42/items` 都不匹配。',
      'method 大小写敏感，只接受表中列出的全大写形式。',
      '',
      '真实 axum 会用 `Router::route` 完成匹配；这里先把路由决策做成纯函数，隐藏测试能直接覆盖资源表和边界，不需要绑定端口。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      "pub fn route(method: &str, path: &str) -> &'static str {",
      '    // TODO: 先处理 /orders 集合路由，再识别 /orders/{id} 单段路径',
      '    // TODO: 按 method 返回对应 handler 名，其他情况返回 not_found',
      '    let _ = (method, path);',
      '    "not_found"',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn is_order_item(path: &str) -> bool {',
      '    path',
      '        .strip_prefix("/orders/")',
      "        .is_some_and(|id| !id.is_empty() && !id.contains('/'))",
      '}',
      '',
      "pub fn route(method: &str, path: &str) -> &'static str {",
      '    match (method, path) {',
      '        ("GET", "/orders") => "list_orders",',
      '        ("POST", "/orders") => "create_order",',
      '        ("GET", path) if is_order_item(path) => "get_order",',
      '        ("PATCH", path) if is_order_item(path) => "update_order",',
      '        ("DELETE", path) if is_order_item(path) => "delete_order",',
      '        _ => "not_found",',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '先用 `match (method, path)` 处理两个完全固定的集合路由。',
      '对详情路由可先 `strip_prefix("/orders/")`，再确认剩余 id 非空且不包含 `/`。',
      '三个详情分支分别匹配 `GET` / `PATCH` / `DELETE` 并加守卫 `if is_order_item(path)`，最后用 `_ => "not_found"` 收口。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn matches_collection_routes() {',
      '        assert_eq!(route("GET", "/orders"), "list_orders");',
      '        assert_eq!(route("POST", "/orders"), "create_order");',
      '    }',
      '',
      '    #[test]',
      '    fn matches_item_routes() {',
      '        assert_eq!(route("GET", "/orders/42"), "get_order");',
      '        assert_eq!(route("PATCH", "/orders/42"), "update_order");',
      '        assert_eq!(route("DELETE", "/orders/42"), "delete_order");',
      '    }',
      '',
      '    #[test]',
      '    fn accepts_any_non_empty_single_id_segment() {',
      '        assert_eq!(route("GET", "/orders/ord-2026"), "get_order");',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_unknown_method_or_resource() {',
      '        assert_eq!(route("PUT", "/orders"), "not_found");',
      '        assert_eq!(route("GET", "/users"), "not_found");',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_empty_or_nested_item_paths() {',
      '        assert_eq!(route("GET", "/orders/"), "not_found");',
      '        assert_eq!(route("GET", "/orders/42/items"), "not_found");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm7-02',
    moduleId: 'm7',
    title: 'JSON 请求校验：一次返回全部问题',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 反序列化不等于业务校验',
      '',
      '`serde_json::from_str` 能确认 JSON 的语法和字段类型，却不知道“空客户名”或“数量过大”是不是业务错误。',
      '一个好用的创建接口会先反序列化，再按稳定顺序**累积所有字段错误**，让调用方一次改完。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn validate_create_order(json: &str) -> Result<CreateOrder, Vec<String>>',
      '```',
      '',
      '规则如下：',
      '',
      '1. JSON 语法错误、字段类型错误或出现未知字段，返回 `["请求体格式错误"]`；',
      '2. `customer` 去掉两端空白后不能为空，否则加入 `"customer 不能为空"`；',
      '3. `item` 去掉两端空白后不能为空，否则加入 `"item 不能为空"`；',
      '4. `quantity` 必须在 `1..=100`，否则加入 `"quantity 必须在 1..=100"`；',
      '5. 字段错误按 `customer` → `item` → `quantity` 的顺序累积；成功时返回已经 `trim` 的字符串。',
      '',
      '结构体上的 `#[serde(default)]` 让缺失字段先变成默认值，随后也能参加累积校验；`#[serde(deny_unknown_fields)]` 则防止调用方悄悄传入拼错的字段。',
      '',
      '**本题使用真实 `serde` / `serde_json`，以隐藏单元测试判分**：不要写 `main`，公开函数与字段名不能修改。',
    ].join('\n'),
    starterCode: [
      'use serde::Deserialize;',
      '',
      '#[derive(Debug, Default, Deserialize, PartialEq, Eq)]',
      '#[serde(default, deny_unknown_fields)]',
      'pub struct CreateOrder {',
      '    pub customer: String,',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub fn validate_create_order(json: &str) -> Result<CreateOrder, Vec<String>> {',
      '    // TODO: 用 serde_json::from_str 反序列化；失败时返回“请求体格式错误”',
      '    // TODO: trim 两个字符串，按固定顺序累积字段错误',
      '    let _ = json;',
      '    Err(vec!["尚未实现".to_string()])',
      '}',
    ].join('\n'),
    solutionCode: [
      'use serde::Deserialize;',
      '',
      '#[derive(Debug, Default, Deserialize, PartialEq, Eq)]',
      '#[serde(default, deny_unknown_fields)]',
      'pub struct CreateOrder {',
      '    pub customer: String,',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub fn validate_create_order(json: &str) -> Result<CreateOrder, Vec<String>> {',
      '    let parsed: CreateOrder = match serde_json::from_str(json) {',
      '        Ok(order) => order,',
      '        Err(_) => return Err(vec!["请求体格式错误".to_string()]),',
      '    };',
      '',
      '    let customer = parsed.customer.trim().to_string();',
      '    let item = parsed.item.trim().to_string();',
      '    let mut errors = Vec::new();',
      '',
      '    if customer.is_empty() {',
      '        errors.push("customer 不能为空".to_string());',
      '    }',
      '    if item.is_empty() {',
      '        errors.push("item 不能为空".to_string());',
      '    }',
      '    if !(1..=100).contains(&parsed.quantity) {',
      '        errors.push("quantity 必须在 1..=100".to_string());',
      '    }',
      '',
      '    if errors.is_empty() {',
      '        Ok(CreateOrder {',
      '            customer,',
      '            item,',
      '            quantity: parsed.quantity,',
      '        })',
      '    } else {',
      '        Err(errors)',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '先写 `let parsed: CreateOrder = match serde_json::from_str(json) { ... };`，解析失败直接提前返回格式错误。',
      '把两个 `trim()` 结果保存为拥有所有权的 `String`，再依次检查 customer、item、quantity，错误都 push 到同一个 `Vec`。',
      '最后判断 `errors.is_empty()`：为空就组装规范化后的 `CreateOrder`，否则返回 `Err(errors)`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn accepts_and_normalizes_a_valid_order() {',
      '        let order = validate_create_order(',
      '            r#"{"customer":"  Alice  ","item":" Rust Book ","quantity":2}"#,',
      '        )',
      '        .unwrap();',
      '        assert_eq!(',
      '            order,',
      '            CreateOrder {',
      '                customer: "Alice".into(),',
      '                item: "Rust Book".into(),',
      '                quantity: 2,',
      '            }',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn accumulates_field_errors_in_stable_order() {',
      '        assert_eq!(',
      '            validate_create_order(r#"{"customer":" ","item":"","quantity":0}"#),',
      '            Err(vec![',
      '                "customer 不能为空".to_string(),',
      '                "item 不能为空".to_string(),',
      '                "quantity 必须在 1..=100".to_string(),',
      '            ])',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn missing_fields_are_validated_together() {',
      '        assert_eq!(',
      '            validate_create_order("{}"),',
      '            Err(vec![',
      '                "customer 不能为空".to_string(),',
      '                "item 不能为空".to_string(),',
      '                "quantity 必须在 1..=100".to_string(),',
      '            ])',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn rejects_malformed_or_unknown_json_shape() {',
      '        assert_eq!(',
      '            validate_create_order("{"),',
      '            Err(vec!["请求体格式错误".to_string()])',
      '        );',
      '        assert_eq!(',
      '            validate_create_order(',
      '                r#"{"customer":"A","item":"B","quantity":1,"admin":true}"#,',
      '            ),',
      '            Err(vec!["请求体格式错误".to_string()])',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn enforces_the_quantity_upper_bound() {',
      '        assert_eq!(',
      '            validate_create_order(r#"{"customer":"A","item":"B","quantity":101}"#),',
      '            Err(vec!["quantity 必须在 1..=100".to_string()])',
      '        );',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm7-03',
    moduleId: 'm7',
    title: '修复 handler：extractor 顺序与返回类型',
    difficulty: 4,
    judgeMode: 'compile',
    assertSource: [
      "// 断言：create_order 必须保持 (Path<u64>, Json<CreateOrder>) 的 extractor 顺序，",
      "// 且返回 Future<Output = Result<Json<Order>, StatusCode>>，否则不满足 Handler 约束。",
      "fn _assert_handler_shape() {",
      "    register(create_order);",
      "}",
    ].join('\n'),
    prompt: [
      '### 为什么一个普通 async fn 会“不满足 Handler”？',
      '',
      '真实 axum handler 由类型驱动：`Path<T>` 只读取请求头部信息，属于 `FromRequestParts`；`Json<T>` 会消费 body，属于 `FromRequest`。',
      '消费 body 的 extractor 必须放在**最后一个参数**，而所有分支还必须返回同一种可转为响应的类型。',
      '',
      '当前 Rust Playground **没有提供 axum crate**，所以本题用手写的 `Path<T>`、`Json<T>` 和 `Handler` trait 精确模拟这条签名契约。',
      '手写的 `Handler<F>` 只接受下面这种 async 函数形状：',
      '',
      '```rust',
      'async fn create_order(',
      '    Path(id): Path<u64>,',
      '    Json(input): Json<CreateOrder>,',
      ') -> Result<Json<Order>, StatusCode>',
      '```',
      '',
      'starter 把 `Json` 放在了 `Path` 前面，而且直接返回 `Json<Order>`，因此注册时会得到类似 axum 的错误：',
      '',
      '```text',
      'the trait bound `fn(...) -> ...: Handler` is not satisfied',
      '```',
      '',
      '**要求**：调整 `create_order` 的 extractor 顺序和 Future 输出类型，使它符合 `Handler<F>`；数量为 `0` 时返回 `Err(StatusCode::BadRequest)`，否则返回 `Ok(Json(Order { ... }))`。',
      '',
      '本题只判断能否编译通过；`main` 中的 `register` 就是模拟的路由注册点。',
    ].join('\n'),
    starterCode: [
      'use std::future::Future;',
      '',
      'pub struct Path<T>(pub T);',
      'pub struct Json<T>(pub T);',
      '',
      'pub struct CreateOrder {',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub struct Order {',
      '    pub id: u64,',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub enum StatusCode {',
      '    BadRequest,',
      '}',
      '',
      'pub trait Handler<F> {}',
      '',
      'impl<H, F> Handler<F> for H',
      'where',
      '    H: Fn(Path<u64>, Json<CreateOrder>) -> F,',
      '    F: Future<Output = Result<Json<Order>, StatusCode>>,',
      '{}',
      '',
      'pub fn register<H, F>(_handler: H)',
      'where',
      '    H: Handler<F>,',
      '{}',
      '',
      'async fn create_order(',
      '    // TODO: Path 必须在前，消费 body 的 Json 必须在最后',
      '    Json(input): Json<CreateOrder>,',
      '    Path(id): Path<u64>,',
      ') -> Json<Order> {',
      '    // TODO: 返回 Result<Json<Order>, StatusCode>，并拒绝 quantity == 0',
      '    Json(Order {',
      '        id,',
      '        item: input.item,',
      '        quantity: input.quantity,',
      '    })',
      '}',
      '',
      'fn main() {',
      '    register(create_order);',
      '}',
    ].join('\n'),
    solutionCode: [
      'use std::future::Future;',
      '',
      'pub struct Path<T>(pub T);',
      'pub struct Json<T>(pub T);',
      '',
      'pub struct CreateOrder {',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub struct Order {',
      '    pub id: u64,',
      '    pub item: String,',
      '    pub quantity: u32,',
      '}',
      '',
      'pub enum StatusCode {',
      '    BadRequest,',
      '}',
      '',
      'pub trait Handler<F> {}',
      '',
      'impl<H, F> Handler<F> for H',
      'where',
      '    H: Fn(Path<u64>, Json<CreateOrder>) -> F,',
      '    F: Future<Output = Result<Json<Order>, StatusCode>>,',
      '{}',
      '',
      'pub fn register<H, F>(_handler: H)',
      'where',
      '    H: Handler<F>,',
      '{}',
      '',
      'async fn create_order(',
      '    Path(id): Path<u64>,',
      '    Json(input): Json<CreateOrder>,',
      ') -> Result<Json<Order>, StatusCode> {',
      '    if input.quantity == 0 {',
      '        return Err(StatusCode::BadRequest);',
      '    }',
      '',
      '    Ok(Json(Order {',
      '        id,',
      '        item: input.item,',
      '        quantity: input.quantity,',
      '    }))',
      '}',
      '',
      'fn main() {',
      '    register(create_order);',
      '}',
    ].join('\n'),
    hints: [
      '先对照 `Handler<F>` 的约束：参数顺序与 Future 的 `Output` 类型都必须一模一样。',
      '签名应以 `Path(id): Path<u64>` 开头、`Json(input): Json<CreateOrder>` 结尾，并返回 `Result<Json<Order>, StatusCode>`。',
      '数量为零时提前 `return Err(StatusCode::BadRequest);`，成功分支写 `Ok(Json(Order { ... }))`，最后保留 `register(create_order)`。',
    ],
  },
  {
    id: 'm7-04',
    moduleId: 'm7',
    title: '分页边界：切片、总数与越界页',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 分页不是只写 skip / take',
      '',
      'REST 列表接口通常先按查询条件过滤，再把结果交给分页函数。为了让边界可以脱离数据库测试，本题只实现分页核心：',
      '',
      '```rust',
      'pub fn paginate(orders: &[Order], page: usize, per_page: usize) -> Page',
      '```',
      '',
      '`page` 从 **1** 开始。返回的 `Page` 必须保留 `page`、`per_page`，并填写：',
      '',
      '- `items`：当前页订单的克隆；',
      '- `total`：输入订单总数；',
      '- `total_pages`：向上取整后的总页数。',
      '',
      '边界规则：空集的 `total_pages == 0`；`page == 0` 或越界页返回空 `items`，但总数元数据仍正确；`per_page == 0` 返回空项且 `total_pages == 0`。',
      '计算起始下标时要避免整数溢出，隐藏测试会传入 `usize::MAX`。',
      '',
      '真实 sqlx 查询会把过滤条件放在 `WHERE`，分页放在 `LIMIT / OFFSET`；纯函数版本让你先把页码语义和边界钉死。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，公开类型和字段不能修改。',
    ].join('\n'),
    starterCode: [
      '#[derive(Clone, Debug, PartialEq, Eq)]',
      'pub struct Order {',
      '    pub id: u64,',
      '    pub item: String,',
      '}',
      '',
      '#[derive(Debug, PartialEq, Eq)]',
      'pub struct Page {',
      '    pub items: Vec<Order>,',
      '    pub page: usize,',
      '    pub per_page: usize,',
      '    pub total: usize,',
      '    pub total_pages: usize,',
      '}',
      '',
      'pub fn paginate(orders: &[Order], page: usize, per_page: usize) -> Page {',
      '    // TODO: 计算 total / total_pages，处理 0 与越界边界',
      '    // TODO: 用安全的起止下标克隆当前页',
      '    let _ = orders;',
      '    Page {',
      '        items: Vec::new(),',
      '        page,',
      '        per_page,',
      '        total: 0,',
      '        total_pages: 0,',
      '    }',
      '}',
    ].join('\n'),
    solutionCode: [
      '#[derive(Clone, Debug, PartialEq, Eq)]',
      'pub struct Order {',
      '    pub id: u64,',
      '    pub item: String,',
      '}',
      '',
      '#[derive(Debug, PartialEq, Eq)]',
      'pub struct Page {',
      '    pub items: Vec<Order>,',
      '    pub page: usize,',
      '    pub per_page: usize,',
      '    pub total: usize,',
      '    pub total_pages: usize,',
      '}',
      '',
      'pub fn paginate(orders: &[Order], page: usize, per_page: usize) -> Page {',
      '    let total = orders.len();',
      '    let total_pages = if per_page == 0 {',
      '        0',
      '    } else {',
      '        total.div_ceil(per_page)',
      '    };',
      '',
      '    if page == 0 || per_page == 0 {',
      '        return Page {',
      '            items: Vec::new(),',
      '            page,',
      '            per_page,',
      '            total,',
      '            total_pages,',
      '        };',
      '    }',
      '',
      '    let start = (page - 1).saturating_mul(per_page);',
      '    let items = if start >= total {',
      '        Vec::new()',
      '    } else {',
      '        let end = start.saturating_add(per_page).min(total);',
      '        orders[start..end].to_vec()',
      '    };',
      '',
      '    Page {',
      '        items,',
      '        page,',
      '        per_page,',
      '        total,',
      '        total_pages,',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '`total` 就是 `orders.len()`；`per_page > 0` 时可用 `total.div_ceil(per_page)` 算总页数。',
      '先提前处理 `page == 0 || per_page == 0`，返回空 items，但别丢掉已经算好的 total 元数据。',
      '起点用 `(page - 1).saturating_mul(per_page)`；若起点未越界，终点用 `start.saturating_add(per_page).min(total)`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    fn orders(n: u64) -> Vec<Order> {',
      '        (1..=n)',
      '            .map(|id| Order {',
      '                id,',
      '                item: format!("item-{id}"),',
      '            })',
      '            .collect()',
      '    }',
      '',
      '    #[test]',
      '    fn returns_the_requested_page() {',
      '        let page = paginate(&orders(5), 2, 2);',
      '        assert_eq!(page.items.iter().map(|o| o.id).collect::<Vec<_>>(), [3, 4]);',
      '        assert_eq!((page.total, page.total_pages), (5, 3));',
      '    }',
      '',
      '    #[test]',
      '    fn last_page_may_be_partial() {',
      '        let page = paginate(&orders(5), 3, 2);',
      '        assert_eq!(page.items.iter().map(|o| o.id).collect::<Vec<_>>(), [5]);',
      '        assert_eq!((page.page, page.per_page), (3, 2));',
      '    }',
      '',
      '    #[test]',
      '    fn out_of_range_page_is_empty_but_keeps_metadata() {',
      '        let page = paginate(&orders(3), usize::MAX, 2);',
      '        assert!(page.items.is_empty());',
      '        assert_eq!((page.total, page.total_pages), (3, 2));',
      '    }',
      '',
      '    #[test]',
      '    fn empty_input_has_zero_pages() {',
      '        let page = paginate(&[], 1, 10);',
      '        assert!(page.items.is_empty());',
      '        assert_eq!((page.total, page.total_pages), (0, 0));',
      '    }',
      '',
      '    #[test]',
      '    fn zero_page_or_page_size_never_panics() {',
      '        let zero_page = paginate(&orders(3), 0, 2);',
      '        assert!(zero_page.items.is_empty());',
      '        assert_eq!(zero_page.total_pages, 2);',
      '',
      '        let zero_size = paginate(&orders(3), 1, 0);',
      '        assert!(zero_size.items.is_empty());',
      '        assert_eq!(zero_size.total_pages, 0);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm7-05',
    moduleId: 'm7',
    title: 'WebSocket 协议：房间状态机',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 把长连接拆成可测试的消息状态机',
      '',
      'WebSocket 连接负责收发字节；业务层应该只接收“当前状态 + 一条消息”，返回“新状态 + 要发出的事件”。',
      '本题用 serde 的内部 tagged enum 描述三种客户端消息：',
      '',
      '```json',
      '{"type":"join","user":"alice"}',
      '{"type":"leave","user":"alice"}',
      '{"type":"broadcast","from":"alice","text":"hello"}',
      '```',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn handle_ws_msg(state: &mut RoomState, msg: &str) -> Vec<OutMsg>',
      '```',
      '',
      '状态机规则：',
      '',
      '- `join`：用户名 trim 后不能为空；新成员按加入顺序放进 `members`，返回一个 `Joined`；重复加入返回错误且不改状态；',
      '- `leave`：只移除已存在成员并返回 `Left`，否则返回错误；',
      '- `broadcast`：发送者必须已经加入，文本 trim 后不能为空；为当前每位成员（包括发送者）按加入顺序生成一个 `Message { to, from, text }`；',
      '- JSON 无法解析时返回 `Error { reason: "消息格式错误" }`。',
      '',
      '`OutMsg` 同样是 tagged enum，序列化后会带 `"type":"joined"` / `"type":"message"` 等字段。',
      '纯状态机没有 socket、锁和调度时序，因此隐藏测试可以确定性检查 join / leave / broadcast 的每个分支。',
      '',
      '**本题使用真实 `serde_json`，以隐藏单元测试判分**：不要写 `main`。',
    ].join('\n'),
    starterCode: [
      'use serde::{Deserialize, Serialize};',
      '',
      '#[derive(Debug, Deserialize)]',
      '#[serde(tag = "type", rename_all = "snake_case", deny_unknown_fields)]',
      'enum ClientMsg {',
      '    Join { user: String },',
      '    Leave { user: String },',
      '    Broadcast { from: String, text: String },',
      '}',
      '',
      '#[derive(Debug, Default, PartialEq, Eq)]',
      'pub struct RoomState {',
      '    pub members: Vec<String>,',
      '}',
      '',
      '#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]',
      '#[serde(tag = "type", rename_all = "snake_case")]',
      'pub enum OutMsg {',
      '    Joined { user: String },',
      '    Left { user: String },',
      '    Message { to: String, from: String, text: String },',
      '    Error { reason: String },',
      '}',
      '',
      'pub fn handle_ws_msg(state: &mut RoomState, msg: &str) -> Vec<OutMsg> {',
      '    // TODO: 用 serde_json::from_str::<ClientMsg> 解析消息',
      '    // TODO: 实现 join / leave / broadcast 状态转移和错误分支',
      '    let _ = (state, msg);',
      '    Vec::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      'use serde::{Deserialize, Serialize};',
      '',
      '#[derive(Debug, Deserialize)]',
      '#[serde(tag = "type", rename_all = "snake_case", deny_unknown_fields)]',
      'enum ClientMsg {',
      '    Join { user: String },',
      '    Leave { user: String },',
      '    Broadcast { from: String, text: String },',
      '}',
      '',
      '#[derive(Debug, Default, PartialEq, Eq)]',
      'pub struct RoomState {',
      '    pub members: Vec<String>,',
      '}',
      '',
      '#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]',
      '#[serde(tag = "type", rename_all = "snake_case")]',
      'pub enum OutMsg {',
      '    Joined { user: String },',
      '    Left { user: String },',
      '    Message { to: String, from: String, text: String },',
      '    Error { reason: String },',
      '}',
      '',
      'fn error(reason: &str) -> Vec<OutMsg> {',
      '    vec![OutMsg::Error {',
      '        reason: reason.to_string(),',
      '    }]',
      '}',
      '',
      'pub fn handle_ws_msg(state: &mut RoomState, msg: &str) -> Vec<OutMsg> {',
      '    let message: ClientMsg = match serde_json::from_str(msg) {',
      '        Ok(message) => message,',
      '        Err(_) => return error("消息格式错误"),',
      '    };',
      '',
      '    match message {',
      '        ClientMsg::Join { user } => {',
      '            let user = user.trim().to_string();',
      '            if user.is_empty() {',
      '                return error("用户名不能为空");',
      '            }',
      '            if state.members.contains(&user) {',
      '                return error("用户已在房间中");',
      '            }',
      '',
      '            state.members.push(user.clone());',
      '            vec![OutMsg::Joined { user }]',
      '        }',
      '        ClientMsg::Leave { user } => {',
      '            let user = user.trim().to_string();',
      '            let Some(index) = state.members.iter().position(|member| member == &user) else {',
      '                return error("用户不在房间中");',
      '            };',
      '',
      '            state.members.remove(index);',
      '            vec![OutMsg::Left { user }]',
      '        }',
      '        ClientMsg::Broadcast { from, text } => {',
      '            let from = from.trim().to_string();',
      '            let text = text.trim().to_string();',
      '            if !state.members.contains(&from) {',
      '                return error("发送者尚未加入房间");',
      '            }',
      '            if text.is_empty() {',
      '                return error("消息内容不能为空");',
      '            }',
      '',
      '            state',
      '                .members',
      '                .iter()',
      '                .map(|to| OutMsg::Message {',
      '                    to: to.clone(),',
      '                    from: from.clone(),',
      '                    text: text.clone(),',
      '                })',
      '                .collect()',
      '        }',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '先把 `serde_json::from_str(msg)` 的错误统一转换为一个 `OutMsg::Error`，成功后再 `match` 三种 `ClientMsg`。',
      'join / leave 都先 trim 用户名；用 `contains` 检查重复，用 `position` 找到 leave 时要删除的下标。',
      'broadcast 先验证 `from` 和 `text`，再对 `state.members.iter()` 做 `map`，为每个 `to` 克隆 from/text 并 `collect()`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn join_adds_a_trimmed_member_and_emits_tagged_output() {',
      '        let mut state = RoomState::default();',
      '        let out = handle_ws_msg(',
      '            &mut state,',
      '            r#"{"type":"join","user":" alice "}"#,',
      '        );',
      '        assert_eq!(state.members, ["alice"]);',
      '        assert_eq!(out, [OutMsg::Joined { user: "alice".into() }]);',
      '        assert_eq!(',
      '            serde_json::to_string(&out[0]).unwrap(),',
      '            r#"{"type":"joined","user":"alice"}"#',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn duplicate_join_is_rejected_without_mutation() {',
      '        let mut state = RoomState {',
      '            members: vec!["alice".into()],',
      '        };',
      '        let out = handle_ws_msg(',
      '            &mut state,',
      '            r#"{"type":"join","user":"alice"}"#,',
      '        );',
      '        assert_eq!(state.members, ["alice"]);',
      '        assert_eq!(',
      '            out,',
      '            [OutMsg::Error {',
      '                reason: "用户已在房间中".into(),',
      '            }]',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn leave_removes_only_an_existing_member() {',
      '        let mut state = RoomState {',
      '            members: vec!["alice".into(), "bob".into()],',
      '        };',
      '        assert_eq!(',
      '            handle_ws_msg(',
      '                &mut state,',
      '                r#"{"type":"leave","user":"alice"}"#,',
      '            ),',
      '            [OutMsg::Left { user: "alice".into() }]',
      '        );',
      '        assert_eq!(state.members, ["bob"]);',
      '',
      '        assert_eq!(',
      '            handle_ws_msg(',
      '                &mut state,',
      '                r#"{"type":"leave","user":"nobody"}"#,',
      '            ),',
      '            [OutMsg::Error {',
      '                reason: "用户不在房间中".into(),',
      '            }]',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn broadcast_delivers_to_every_member_in_join_order() {',
      '        let mut state = RoomState {',
      '            members: vec!["alice".into(), "bob".into()],',
      '        };',
      '        assert_eq!(',
      '            handle_ws_msg(',
      '                &mut state,',
      '                r#"{"type":"broadcast","from":"alice","text":" hi "}"#,',
      '            ),',
      '            [',
      '                OutMsg::Message {',
      '                    to: "alice".into(),',
      '                    from: "alice".into(),',
      '                    text: "hi".into(),',
      '                },',
      '                OutMsg::Message {',
      '                    to: "bob".into(),',
      '                    from: "alice".into(),',
      '                    text: "hi".into(),',
      '                },',
      '            ]',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn malformed_or_unauthorized_messages_become_errors() {',
      '        let mut state = RoomState::default();',
      '        assert_eq!(',
      '            handle_ws_msg(&mut state, "{"),',
      '            [OutMsg::Error {',
      '                reason: "消息格式错误".into(),',
      '            }]',
      '        );',
      '        assert_eq!(',
      '            handle_ws_msg(',
      '                &mut state,',
      '                r#"{"type":"broadcast","from":"alice","text":"hi"}"#,',
      '            ),',
      '            [OutMsg::Error {',
      '                reason: "发送者尚未加入房间".into(),',
      '            }]',
      '        );',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm7-06',
    moduleId: 'm7',
    title: '分层错误：从数据库到 API',
    difficulty: 5,
    judgeMode: 'compile',
    assertSource: [
      "// 断言：两个跨层映射函数必须保持签名，From 转换链必须存在。",
      "const _DB_TO_API: fn(DbErr) -> ApiError = db_error_to_api;",
      "const _SVC_TO_API: fn(ServiceError) -> ApiError = service_error_to_api;",
      "const _FROM_DB: fn(DbErr) -> ApiError = ApiError::from;",
      "const _FROM_SVC: fn(ServiceError) -> ApiError = ApiError::from;",
    ].join('\n'),
    prompt: [
      '### 不要让数据库错误穿透到 HTTP 边界',
      '',
      '后端常见三层错误流是 `db → service → handler`：数据库层知道“唯一键冲突/连接失败”，service 层还会产生业务输入错误，handler 最终只应该看到稳定的 `ApiError`。',
      '',
      '本题用 `DbErr` 模拟 sqlx 错误，并用真实 `thiserror` 生成 `Display` / `Error` 实现：',
      '',
      '- `DbErr::NotFound(_)` → `ApiError::NotFound`；',
      '- `DbErr::UniqueViolation(field)` → `ApiError::Conflict(field)`；',
      '- `DbErr::Connection(_)` → `ApiError::Unavailable`，不要把内部连接串泄露给客户端；',
      '- `ServiceError::InvalidInput(message)` → `ApiError::BadRequest(message)`；',
      '- `ServiceError::Database(db_error)` → 复用上面的数据库映射。',
      '',
      '**要求**：分别实现 `From<DbErr> for ApiError` 与 `From<ServiceError> for ApiError`。',
      'starter 中两个 `.into()` 因缺少 trait 实现而编译失败；补全后应让这两个转换函数都能编译。',
      '',
      '真实项目里 handler 可直接写 `service_call().await?`，`From` 会逐层完成错误转换；同时 `ApiError` 再实现 axum 的 `IntoResponse`，统一决定状态码和响应体。',
      '',
      '本题只判断能否编译通过。',
    ].join('\n'),
    starterCode: [
      'use thiserror::Error;',
      '',
      '#[derive(Debug, Error)]',
      'pub enum DbErr {',
      '    #[error("order {0} not found")]',
      '    NotFound(u64),',
      '    #[error("duplicate key: {0}")]',
      '    UniqueViolation(String),',
      '    #[error("database unavailable: {0}")]',
      '    Connection(String),',
      '}',
      '',
      '#[derive(Debug, Error)]',
      'pub enum ServiceError {',
      '    #[error("invalid input: {0}")]',
      '    InvalidInput(String),',
      '    #[error(transparent)]',
      '    Database(#[from] DbErr),',
      '}',
      '',
      '#[derive(Debug, Error, PartialEq, Eq)]',
      'pub enum ApiError {',
      '    #[error("bad request: {0}")]',
      '    BadRequest(String),',
      '    #[error("order not found")]',
      '    NotFound,',
      '    #[error("conflict: {0}")]',
      '    Conflict(String),',
      '    #[error("service unavailable")]',
      '    Unavailable,',
      '}',
      '',
      '// TODO: 实现 From<DbErr> for ApiError，穷尽映射三个数据库错误',
      '// TODO: 实现 From<ServiceError> for ApiError，并复用 DbErr 的转换',
      '',
      'pub fn db_error_to_api(error: DbErr) -> ApiError {',
      '    error.into()',
      '}',
      '',
      'pub fn service_error_to_api(error: ServiceError) -> ApiError {',
      '    error.into()',
      '}',
      '',
      'fn main() {}',
    ].join('\n'),
    solutionCode: [
      'use thiserror::Error;',
      '',
      '#[derive(Debug, Error)]',
      'pub enum DbErr {',
      '    #[error("order {0} not found")]',
      '    NotFound(u64),',
      '    #[error("duplicate key: {0}")]',
      '    UniqueViolation(String),',
      '    #[error("database unavailable: {0}")]',
      '    Connection(String),',
      '}',
      '',
      '#[derive(Debug, Error)]',
      'pub enum ServiceError {',
      '    #[error("invalid input: {0}")]',
      '    InvalidInput(String),',
      '    #[error(transparent)]',
      '    Database(#[from] DbErr),',
      '}',
      '',
      '#[derive(Debug, Error, PartialEq, Eq)]',
      'pub enum ApiError {',
      '    #[error("bad request: {0}")]',
      '    BadRequest(String),',
      '    #[error("order not found")]',
      '    NotFound,',
      '    #[error("conflict: {0}")]',
      '    Conflict(String),',
      '    #[error("service unavailable")]',
      '    Unavailable,',
      '}',
      '',
      'impl From<DbErr> for ApiError {',
      '    fn from(error: DbErr) -> Self {',
      '        match error {',
      '            DbErr::NotFound(_) => ApiError::NotFound,',
      '            DbErr::UniqueViolation(field) => ApiError::Conflict(field),',
      '            DbErr::Connection(_) => ApiError::Unavailable,',
      '        }',
      '    }',
      '}',
      '',
      'impl From<ServiceError> for ApiError {',
      '    fn from(error: ServiceError) -> Self {',
      '        match error {',
      '            ServiceError::InvalidInput(message) => ApiError::BadRequest(message),',
      '            ServiceError::Database(error) => error.into(),',
      '        }',
      '    }',
      '}',
      '',
      'pub fn db_error_to_api(error: DbErr) -> ApiError {',
      '    error.into()',
      '}',
      '',
      'pub fn service_error_to_api(error: ServiceError) -> ApiError {',
      '    error.into()',
      '}',
      '',
      'fn main() {}',
    ].join('\n'),
    hints: [
      '两个 `From` 实现都写 `fn from(error: ...) -> Self`，内部用 `match` 穷尽枚举变体。',
      '数据库连接错误的内部字符串不能进入 `ApiError`；匹配成 `DbErr::Connection(_) => ApiError::Unavailable`。',
      '`ServiceError::Database(error)` 分支直接写 `error.into()`，它会调用你刚实现的 `From<DbErr> for ApiError`。',
    ],
  },
];
