import type { Exercise } from '@/lib/rust/types';

export const module1Exercises: Exercise[] = [
  {
    id: 'm1-01',
    moduleId: 'm1',
    title: 'println! 与格式化占位符',
    difficulty: 1,
    judgeMode: 'stdout',
    prompt: [
      '### 打印你的第一行 Rust',
      '',
      '`println!` 是宏（注意末尾的 `!`），花括号 `{}` 是占位符。Rust 2021 之后可以把变量名直接写进花括号里：',
      '',
      '```rust',
      'let who = "世界";',
      'println!("你好，{who}！");      // 内联变量名',
      'println!("你好，{}！", who);    // 位置参数，等价',
      'println!("{:.2}", 3.14159);    // 保留两位小数 -> 3.14',
      '```',
      '',
      '**要求**：补全 `main`，让程序**恰好**输出下面三行：',
      '',
      '```text',
      '你好，Rust 道场！',
      '在学人数：42',
      '通过率：87.5%',
      '```',
      '',
      '提示：`pass_rate * 100.0` 得到 `87.5`，用 `{:.1}` 控制成一位小数。百分号本身直接写在字符串里即可。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let name = "Rust 道场";',
      '    let learners = 42;',
      '    let pass_rate = 0.875_f64;',
      '',
      '    // TODO: 用 println! 打印题面要求的三行',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let name = "Rust 道场";',
      '    let learners = 42;',
      '    let pass_rate = 0.875_f64;',
      '',
      '    println!("你好，{name}！");',
      '    println!("在学人数：{}", learners);',
      '    println!("通过率：{:.1}%", pass_rate * 100.0);',
      '}',
    ].join('\n'),
    expectedStdout: '你好，Rust 道场！\n在学人数：42\n通过率：87.5%\n',
    hints: [
      '三行输出就写三条 `println!`，顺序不能错。',
      '第三行需要先算 `pass_rate * 100.0`，再用 `{:.1}` 格式化成一位小数。',
      '第三行可以写成 `println!("通过率：{:.1}%", pass_rate * 100.0);`。',
    ],
  },
  {
    id: 'm1-02',
    moduleId: 'm1',
    title: '变量、mut 与遮蔽',
    difficulty: 1,
    judgeMode: 'stdout',
    prompt: [
      '### 可变性与遮蔽',
      '',
      'Rust 变量默认不可变；要原地修改就加 `mut`。而**遮蔽（shadowing）**是用 `let` 重新声明同名变量，可以换类型：',
      '',
      '```rust',
      'let mut n = 1;',
      'n += 1;            // 原地修改，需要 mut',
      'let n = "一";       // 遮蔽：这是一个新变量，类型也变了',
      '```',
      '',
      '**要求**：按注释顺序操作变量 `count`，让程序**恰好**输出：',
      '',
      '```text',
      'count = 3',
      'count = 5',
      'count = 50',
      'count = 五十',
      '```',
      '',
      '即：初值 3 打印一次 → 加 2 后打印 → 用遮蔽把它变成"原值乘 10"后打印 → 再用遮蔽把它变成字符串 `"五十"` 后打印。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let mut count = 3;',
      '    println!("count = {count}");',
      '',
      '    // TODO: 让 count 增加 2，然后打印',
      '',
      '    // TODO: 用遮蔽把 count 变成它的 10 倍，然后打印',
      '',
      '    // TODO: 用遮蔽把 count 变成字符串 "五十"，然后打印',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let mut count = 3;',
      '    println!("count = {count}");',
      '',
      '    count += 2;',
      '    println!("count = {count}");',
      '',
      '    let count = count * 10;',
      '    println!("count = {count}");',
      '',
      '    let count = "五十";',
      '    println!("count = {count}");',
      '}',
    ].join('\n'),
    expectedStdout: 'count = 3\ncount = 5\ncount = 50\ncount = 五十\n',
    hints: [
      '第一处改动用 `count += 2;`，因为 `count` 声明时带了 `mut`。',
      '遮蔽是再写一次 `let count = ...;`，右边可以引用旧的 `count`。',
      '最后一次遮蔽把类型从整数换成了 `&str`：`let count = "五十";`。',
    ],
  },
  {
    id: 'm1-03',
    moduleId: 'm1',
    title: '函数与表达式返回值',
    difficulty: 1,
    judgeMode: 'stdout',
    prompt: [
      '### 函数、表达式与那个要命的分号',
      '',
      'Rust 函数体的**最后一个表达式**（不带分号）就是返回值；加上分号就变成语句，返回值会变成 `()`。',
      '`if` 和 `{}` 块本身也都是表达式：',
      '',
      '```rust',
      'fn double(n: i32) -> i32 {',
      '    n * 2        // 没有分号 = 返回值',
      '}',
      '',
      'let v = { let x = 3; x + 1 };   // 块表达式，v == 4',
      '```',
      '',
      '**要求**：实现 `square`（求平方）和 `max_of`（返回较大者，用 `if` 表达式，不要写 `return`），',
      '并在 `main` 里用块表达式算出 `block_value`，让程序**恰好**输出：',
      '',
      '```text',
      '7 的平方 = 49',
      '12 和 30 的较大者 = 30',
      '块表达式的值 = 5',
      '```',
      '',
      '其中 `block_value` 由一个块表达式产生：块里先 `let x = 4;`，块的值为 `x + 1`。',
    ].join('\n'),
    starterCode: [
      'fn square(n: i32) -> i32 {',
      '    // TODO: 返回 n 的平方（用表达式，不写分号）',
      '    0',
      '}',
      '',
      'fn max_of(a: i32, b: i32) -> i32 {',
      '    // TODO: 用 if 表达式返回较大的那个',
      '    0',
      '}',
      '',
      'fn main() {',
      '    println!("7 的平方 = {}", square(7));',
      '    println!("12 和 30 的较大者 = {}", max_of(12, 30));',
      '',
      '    // TODO: 用块表达式算出 block_value（块里 let x = 4; 块的值是 x + 1）',
      '    let block_value = 0;',
      '    println!("块表达式的值 = {block_value}");',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn square(n: i32) -> i32 {',
      '    n * n',
      '}',
      '',
      'fn max_of(a: i32, b: i32) -> i32 {',
      '    if a > b { a } else { b }',
      '}',
      '',
      'fn main() {',
      '    println!("7 的平方 = {}", square(7));',
      '    println!("12 和 30 的较大者 = {}", max_of(12, 30));',
      '',
      '    let block_value = {',
      '        let x = 4;',
      '        x + 1',
      '    };',
      '    println!("块表达式的值 = {block_value}");',
      '}',
    ].join('\n'),
    expectedStdout: '7 的平方 = 49\n12 和 30 的较大者 = 30\n块表达式的值 = 5\n',
    hints: [
      '`square` 的函数体只需要一行 `n * n`，**不要加分号**。',
      '`max_of` 里 `if a > b { a } else { b }` 整体就是一个表达式，可以直接作为返回值。',
      '块表达式写法：`let block_value = { let x = 4; x + 1 };`（最后一行没有分号）。',
    ],
  },
  {
    id: 'm1-04',
    moduleId: 'm1',
    title: '控制流：FizzBuzz 变体与求和',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### for + if：FizzBuzz 变体',
      '',
      '`for n in 1..=15` 会遍历 1 到 15（含 15）；`1..15` 则不含 15。',
      '',
      '**要求**：遍历 1 到 15，每行输出一个结果：',
      '',
      '- 同时是 3 和 5 的倍数 → 打印 `FizzBuzz`',
      '- 只是 3 的倍数 → 打印 `Fizz`',
      '- 只是 5 的倍数 → 打印 `Buzz`',
      '- 其他情况 → 打印这个数字本身，**并把它累加进 `sum`**',
      '',
      '循环结束后再打印一行：`未被替换的数字之和 = <sum>`。',
      '',
      '开头几行长这样：',
      '',
      '```text',
      '1',
      '2',
      'Fizz',
      '4',
      'Buzz',
      '...',
      '```',
      '',
      '注意判断顺序：必须先判断"同时是 3 和 5 的倍数"（即 15 的倍数），否则永远轮不到 `FizzBuzz`。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let mut sum = 0;',
      '',
      '    for n in 1..=15 {',
      '        // TODO: 按题面规则打印 FizzBuzz / Fizz / Buzz / 数字本身',
      '        // TODO: 只有打印数字本身时，才把 n 累加进 sum',
      '        let _ = n;',
      '    }',
      '',
      '    // TODO: 打印 "未被替换的数字之和 = <sum>"',
      '    let _ = sum;',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let mut sum = 0;',
      '',
      '    for n in 1..=15 {',
      '        if n % 15 == 0 {',
      '            println!("FizzBuzz");',
      '        } else if n % 3 == 0 {',
      '            println!("Fizz");',
      '        } else if n % 5 == 0 {',
      '            println!("Buzz");',
      '        } else {',
      '            println!("{n}");',
      '            sum += n;',
      '        }',
      '    }',
      '',
      '    println!("未被替换的数字之和 = {sum}");',
      '}',
    ].join('\n'),
    expectedStdout: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n未被替换的数字之和 = 60\n',
    hints: [
      '用 `if / else if / else` 链，第一个分支判断 `n % 15 == 0`。',
      '`sum += n;` 只能写在最后那个 `else` 分支里。',
      '最后一行是 `println!("未被替换的数字之和 = {sum}");`，注意等号两边各有一个空格。',
    ],
  },
  {
    id: 'm1-05',
    moduleId: 'm1',
    title: '修复：move 之后还在用',
    difficulty: 2,
    judgeMode: 'compile',
    expectedStdout: "s1 = Rust 道场\ns2 = Rust 道场\n",
    prompt: [
      '### 修编译错误：borrow of moved value',
      '',
      '下面这段代码**编译不过**。点"运行"先看看编译器怎么说：',
      '',
      '```text',
      'error[E0382]: borrow of moved value: `s1`',
      '```',
      '',
      '原因：`String` 没有实现 `Copy`。`let s2 = s1;` 不是拷贝，而是把堆内存的**所有权从 `s1` 转移（move）给了 `s2`**，',
      '此后 `s1` 就失效了——因为如果两个变量都认为自己拥有同一块内存，作用域结束时会释放两次。',
      '',
      '**要求**：修好这段代码，让它能编译运行，且**两行输出都要保留**：',
      '',
      '```text',
      's1 = Rust 道场',
      's2 = Rust 道场',
      '```',
      '',
      '本题会**逐行比对输出**，所以两行打印都要保留，不能靠删代码蒙混过关。',
      '',
      '想一想有几种改法：`clone()` 是最直接的一种；如果只是想"看一眼"，用借用（`&s1`）会更省。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let s1 = String::from("Rust 道场");',
      '',
      '    // TODO: 这一行把所有权 move 走了，想办法让 s1 之后仍然可用',
      '    let s2 = s1;',
      '',
      '    println!("s1 = {s1}");',
      '    println!("s2 = {s2}");',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let s1 = String::from("Rust 道场");',
      '',
      '    let s2 = s1.clone();',
      '',
      '    println!("s1 = {s1}");',
      '    println!("s2 = {s2}");',
      '}',
    ].join('\n'),
    hints: [
      '错误信息里的 `value moved here` 指向的就是要改的那一行。',
      '想要两份独立的数据，可以显式深拷贝一份。',
      '把 `let s2 = s1;` 改成 `let s2 = s1.clone();` 即可；另一种思路是 `let s2 = &s1;`（借用而非拥有）。',
    ],
  },
  {
    id: 'm1-06',
    moduleId: 'm1',
    title: '不可变借用与字符串切片',
    difficulty: 2,
    judgeMode: 'stdout',
    prompt: [
      '### 借用：只看不夺走',
      '',
      '把 `String` 传给函数会把所有权 move 进去；传 `&String` / `&str` 则只是**借用**，调用方仍然拥有它：',
      '',
      '```rust',
      'fn char_count(s: &str) -> usize {',
      '    s.chars().count()      // 按字符数，不是字节数',
      '}',
      '```',
      '',
      '**要求**：',
      '',
      '1. 实现 `char_count(s: &str) -> usize`，返回**字符**个数（用 `s.chars().count()`）。',
      '2. 实现 `describe(text: &str) -> String`，返回形如 `所有权与借用（6 字符）` 的字符串（用 `format!`）。',
      '3. 在 `main` 里取出 `title` 的**前 3 个字节**作为切片 `&title[0..3]`——一个中文字在 UTF-8 里正好占 3 字节。',
      '',
      '程序应当**恰好**输出：',
      '',
      '```text',
      '所有权与借用（6 字符）',
      '原字符串仍可用：所有权与借用',
      '第一个字：所',
      '```',
      '',
      '注意括号用的是中文全角括号 `（）`。字符串切片按字节索引，切在多字节字符中间会 panic。',
    ].join('\n'),
    starterCode: [
      'fn char_count(s: &str) -> usize {',
      '    // TODO: 返回字符个数',
      '    0',
      '}',
      '',
      'fn describe(text: &str) -> String {',
      '    // TODO: 用 format! 拼出 "<text>（<n> 字符）"',
      '    String::new()',
      '}',
      '',
      'fn main() {',
      '    let title = String::from("所有权与借用");',
      '',
      '    println!("{}", describe(&title));',
      '    println!("原字符串仍可用：{title}");',
      '',
      '    // TODO: 取 title 的前 3 个字节作为切片并打印',
      '    let first_char = "";',
      '    println!("第一个字：{first_char}");',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn char_count(s: &str) -> usize {',
      '    s.chars().count()',
      '}',
      '',
      'fn describe(text: &str) -> String {',
      '    format!("{}（{} 字符）", text, char_count(text))',
      '}',
      '',
      'fn main() {',
      '    let title = String::from("所有权与借用");',
      '',
      '    println!("{}", describe(&title));',
      '    println!("原字符串仍可用：{title}");',
      '',
      '    let first_char = &title[0..3];',
      '    println!("第一个字：{first_char}");',
      '}',
    ].join('\n'),
    expectedStdout: '所有权与借用（6 字符）\n原字符串仍可用：所有权与借用\n第一个字：所\n',
    hints: [
      '`char_count` 一行就够：`s.chars().count()`。注意 `s.len()` 返回的是字节数，不是字符数。',
      '`describe` 用 `format!` 宏拼字符串，它和 `println!` 的格式语法完全一样，只是返回 `String`。',
      '切片写法是 `&title[0..3]`；`&String` 可以自动当作 `&str` 传给函数（deref 强制转换）。',
    ],
  },
  {
    id: 'm1-07',
    moduleId: 'm1',
    title: '修复：可变借用与不可变借用打架',
    difficulty: 3,
    judgeMode: 'compile',
    expectedStdout: "第一个分数是 90\n现在共有 4 个分数\n",
    prompt: [
      '### 修编译错误：cannot borrow as mutable',
      '',
      '下面这段代码编译不过：',
      '',
      '```text',
      'error[E0502]: cannot borrow `scores` as mutable because it is also borrowed as immutable',
      '```',
      '',
      '借用检查器的铁律：**同一时刻，要么有任意多个不可变引用 `&T`，要么有恰好一个可变引用 `&mut T`**。',
      '这里 `first` 是指向 `scores` 内部元素的不可变引用，而 `push` 需要 `&mut scores`；',
      '更要命的是 `push` 可能触发扩容、把整个底层数组搬到新地址，那 `first` 就会变成悬垂指针——Rust 直接在编译期拦下。',
      '',
      '**要求**：修好它，让程序编译通过并输出（本题只判编译/运行是否成功）：',
      '',
      '```text',
      '第一个分数是 90',
      '现在共有 4 个分数',
      '```',
      '',
      '思路：`i32` 是 `Copy` 类型，你其实不需要一个"引用"，把值**复制**一份出来就没有借用冲突了。',
      '另一个思路是调整顺序 / 缩短引用的存活范围——想想 NLL（引用在最后一次使用处就结束）。',
    ].join('\n'),
    starterCode: [
      'fn main() {',
      '    let mut scores = vec![90, 78, 66];',
      '',
      '    // TODO: 这里借了一个不可变引用，导致下面的 push 无法通过借用检查',
      '    let first = &scores[0];',
      '',
      '    scores.push(100);',
      '',
      '    println!("第一个分数是 {first}");',
      '    println!("现在共有 {} 个分数", scores.len());',
      '}',
    ].join('\n'),
    solutionCode: [
      'fn main() {',
      '    let mut scores = vec![90, 78, 66];',
      '',
      '    let first = scores[0];',
      '',
      '    scores.push(100);',
      '',
      '    println!("第一个分数是 {first}");',
      '    println!("现在共有 {} 个分数", scores.len());',
      '}',
    ].join('\n'),
    hints: [
      '问题出在 `let first = &scores[0];` 这一行留下了一个活到最后的不可变引用。',
      '`i32` 实现了 `Copy`，你可以直接拿到值的副本，而不是引用。',
      '把 `&scores[0]` 改成 `scores[0]` 即可（去掉 `&`）；这样 `first` 是一份独立的 i32，之后随便 push。',
    ],
  },
  {
    id: 'm1-08',
    moduleId: 'm1',
    title: '实现 first_word：返回首个空格前的切片',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 用切片写一个 first_word',
      '',
      '这是《Rust 程序设计语言》里的经典练习，也是理解"切片为什么存在"的最佳例子。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn first_word(s: &str) -> &str',
      '```',
      '',
      '返回 `s` 中**第一个空格之前**的那一段（作为切片返回，不要新建 `String`）；',
      '如果整个字符串里没有空格，就返回整个 `s`。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `"hello world"` | `"hello"` |',
      '| `"rust"` | `"rust"` |',
      '| `""` | `""` |',
      '| `"a b c"` | `"a"` |',
      '| `" leading"` | `""` |',
      '',
      '**本题以隐藏单元测试判分**（`cargo test`），所以写的是库代码：不要写 `main`，函数必须是 `pub`。',
      '',
      '提示：`s.find(\' \')` 返回 `Option<usize>`——找到就是 `Some(下标)`，没找到是 `None`。用 `match` 处理这两种情况。',
    ].join('\n'),
    starterCode: [
      'pub fn first_word(s: &str) -> &str {',
      "    // TODO: 用 s.find(' ') 找到第一个空格的下标，返回它之前的切片",
      '    // TODO: 没有空格时返回整个 s',
      '    s',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn first_word(s: &str) -> &str {',
      "    match s.find(' ') {",
      '        Some(index) => &s[..index],',
      '        None => s,',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      "`str` 有个方法 `find(' ')`，返回 `Option<usize>`：`Some(i)` 表示第一个空格在下标 i。",
      '用 `match` 分别处理 `Some(i)` 和 `None`；`Some(i)` 时返回 `&s[..i]`。',
      "完整骨架：`match s.find(' ') { Some(i) => &s[..i], None => s }`。",
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn takes_word_before_first_space() {',
      '        assert_eq!(first_word("hello world"), "hello");',
      '    }',
      '',
      '    #[test]',
      '    fn returns_whole_string_without_space() {',
      '        assert_eq!(first_word("rust"), "rust");',
      '    }',
      '',
      '    #[test]',
      '    fn handles_empty_string() {',
      '        assert_eq!(first_word(""), "");',
      '    }',
      '',
      '    #[test]',
      '    fn stops_at_the_first_space_only() {',
      '        assert_eq!(first_word("a b c"), "a");',
      '    }',
      '',
      '    #[test]',
      '    fn leading_space_yields_empty_slice() {',
      '        assert_eq!(first_word(" leading"), "");',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm1-09',
    moduleId: 'm1',
    title: '实现 sum_even：切片求偶数和',
    difficulty: 3,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 借用一段切片并求和',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub fn sum_even(nums: &[i32]) -> i32',
      '```',
      '',
      '返回切片中**所有偶数之和**；没有偶数（含空切片）时返回 `0`。负偶数也算偶数。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `[1, 2, 3, 4]` | `6` |',
      '| `[]` | `0` |',
      '| `[1, 3, 5]` | `0` |',
      '| `[-4, -3, 2]` | `-2` |',
      '',
      '为什么参数写 `&[i32]` 而不是 `&Vec<i32>`？因为 `&[i32]` 更通用——数组、`Vec`、子切片都能直接传进来，',
      '这是 code review 里的高频建议。',
      '',
      '**本题以隐藏单元测试判分**：不要写 `main`，函数必须是 `pub`。',
      '',
      '提示：用 `for` 循环累加即可；想更地道可以写迭代器链 `nums.iter().filter(...).sum()`（模块四会详讲）。',
      '注意 Rust 里 `-4 % 2 == 0`，所以判偶数用 `n % 2 == 0` 对负数同样成立。',
    ].join('\n'),
    starterCode: [
      'pub fn sum_even(nums: &[i32]) -> i32 {',
      '    // TODO: 遍历 nums，把偶数累加起来并返回',
      '    0',
      '}',
    ].join('\n'),
    solutionCode: [
      'pub fn sum_even(nums: &[i32]) -> i32 {',
      '    let mut total = 0;',
      '    for n in nums {',
      '        if n % 2 == 0 {',
      '            total += n;',
      '        }',
      '    }',
      '    total',
      '}',
    ].join('\n'),
    hints: [
      '先 `let mut total = 0;`，再 `for n in nums { ... }`，最后把 `total` 作为表达式返回（不写分号）。',
      '`for n in nums` 里的 `n` 是 `&i32`，直接写 `n % 2 == 0` 和 `total += n` 都能通过（自动解引用）。',
      '迭代器写法：`nums.iter().filter(|n| *n % 2 == 0).sum()`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn sums_even_numbers() {',
      '        assert_eq!(sum_even(&[1, 2, 3, 4]), 6);',
      '    }',
      '',
      '    #[test]',
      '    fn empty_slice_is_zero() {',
      '        assert_eq!(sum_even(&[]), 0);',
      '    }',
      '',
      '    #[test]',
      '    fn all_odd_is_zero() {',
      '        assert_eq!(sum_even(&[1, 3, 5]), 0);',
      '    }',
      '',
      '    #[test]',
      '    fn handles_negative_numbers() {',
      '        assert_eq!(sum_even(&[-4, -3, 2]), -2);',
      '    }',
      '',
      '    #[test]',
      '    fn works_with_vec_and_subslice() {',
      '        let v = vec![10, 11, 12, 13];',
      '        assert_eq!(sum_even(&v), 22);',
      '        assert_eq!(sum_even(&v[1..]), 12);',
      '    }',
      '}',
    ].join('\n'),
  },
];
