import type { Exercise } from '@/lib/rust/types';

export const module6Exercises: Exercise[] = [
  {
    id: 'm6-01',
    moduleId: 'm6',
    title: 'async fn 与 .await：第一个 tokio 程序',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 把 main 变成 async',
      '',
      '`async fn` 不会立刻执行函数体，它返回一个 **Future**（一个还没跑的状态机）。只有 `.await` 才会驱动它往前走：',
      '',
      '```rust',
      'async fn ping() -> u32 {',
      '    tokio::time::sleep(std::time::Duration::from_millis(10)).await;',
      '    1',
      '}',
      '',
      '#[tokio::main]                 // 宏把 async main 包进一个 Tokio 运行时',
      'async fn main() {',
      '    let n = ping().await;      // 到这里 ping 的函数体才真正执行',
      '    println!("{n}");',
      '}',
      '```',
      '',
      '`#[tokio::main]` 做的事很朴素：把你的 `async fn main` 改写成一个普通 `fn main`，里面建好运行时再 `block_on` 你的 Future。',
      '',
      '**要求**：',
      '',
      '1. 补全 `fetch_user`：先 `sleep` 20 毫秒模拟一次网络往返，再返回 `format!("user-{id}")`。',
      '2. 补全 `greet`：返回 `format!("你好，{name}！")`（全角感叹号）。',
      '3. 在 `main` 里**依次** `.await` 这两个函数，让程序**恰好**输出：',
      '',
      '```text',
      '开始查询',
      '拿到：user-7',
      '你好，user-7！',
      '查询结束',
      '```',
      '',
      '注意 `fetch_user(7)` 只写这一句什么都不会发生——编译器还会给你一个 `unused_must_use` 警告提醒你「这个 Future 没被 await」。',
    ].join('\n'),
    starterCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'async fn fetch_user(id: u32) -> String {',
      '    // TODO: 先 sleep 20 毫秒，再返回 format!("user-{id}")',
      '    let _ = id;',
      '    String::new()',
      '}',
      '',
      'async fn greet(name: &str) -> String {',
      '    // TODO: 返回 format!("你好，{name}！")',
      '    let _ = name;',
      '    String::new()',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    println!("开始查询");',
      '',
      '    // TODO: await fetch_user(7)，把结果绑到 user 上，打印 "拿到：user-7"',
      '    // TODO: 再 await greet(&user)，打印它返回的那句话',
      '    // TODO: 最后打印 "查询结束"',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'async fn fetch_user(id: u32) -> String {',
      '    sleep(Duration::from_millis(20)).await;',
      '    format!("user-{id}")',
      '}',
      '',
      'async fn greet(name: &str) -> String {',
      '    format!("你好，{name}！")',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    println!("开始查询");',
      '',
      '    let user = fetch_user(7).await;',
      '    println!("拿到：{user}");',
      '',
      '    let message = greet(&user).await;',
      '    println!("{message}");',
      '',
      '    println!("查询结束");',
      '}',
    ].join('\n'),
    expectedStdout: '开始查询\n拿到：user-7\n你好，user-7！\n查询结束\n',
    hints: [
      '`sleep(Duration::from_millis(20))` 本身也是一个 Future，别忘了在它后面接 `.await`。',
      '`main` 里的调用形如 `let user = fetch_user(7).await;`——先 await 拿到 `String`，再打印。',
      '`greet` 接收 `&str`，直接传 `&user` 即可（`&String` 会自动解引用成 `&str`）。',
    ],
  },
  {
    id: 'm6-02',
    moduleId: 'm6',
    title: 'join!：两件事一起等',
    difficulty: 3,
    judgeMode: 'stdout',
    prompt: [
      '### 顺序 await 是串行，join! 才是并发',
      '',
      '连着写两个 `.await` 意味着「等第一件事做完，再开始第二件」——总耗时是两者之和：',
      '',
      '```rust',
      'let a = load_a().await;   // 60ms',
      'let b = load_b().await;   // 40ms  → 总共约 100ms',
      '```',
      '',
      '如果两件事互不依赖，应该用 `tokio::join!` 把它们**同时**推进，总耗时约等于**较慢的那个**：',
      '',
      '```rust',
      'let (a, b) = tokio::join!(load_a(), load_b());   // 约 60ms',
      '```',
      '',
      '`join!` 返回一个元组，**顺序与你写的参数顺序严格一致**（不是「谁先完成谁在前」），所以输出是确定的。',
      '它也不需要 `spawn`：两个 Future 在**同一个任务**里被交替 poll，没有额外的线程开销。',
      '',
      '**要求**：用 `tokio::join!` 并发执行 `load("用户资料", 60)` 与 `load("订单列表", 40)`，然后按顺序打印两者的返回值，最后打印一行耗时判断。程序应当**恰好**输出：',
      '',
      '```text',
      '用户资料就绪（耗时 60ms）',
      '订单列表就绪（耗时 40ms）',
      '总耗时小于 95ms：true',
      '```',
      '',
      '最后一行用 `start.elapsed() < Duration::from_millis(95)` 判断：并发时约 60ms → `true`；如果你老老实实串行 await，就是约 100ms → `false`。',
    ].join('\n'),
    starterCode: [
      'use tokio::time::{Duration, Instant, sleep};',
      '',
      'async fn load(name: &str, ms: u64) -> String {',
      '    sleep(Duration::from_millis(ms)).await;',
      '    format!("{name}就绪（耗时 {ms}ms）")',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    let start = Instant::now();',
      '',
      '    // TODO: 用 tokio::join! 并发执行 load("用户资料", 60) 与 load("订单列表", 40)',
      '    let (user, orders) = (String::new(), String::new());',
      '',
      '    println!("{user}");',
      '    println!("{orders}");',
      '    println!(',
      '        "总耗时小于 95ms：{}",',
      '        start.elapsed() < Duration::from_millis(95)',
      '    );',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::time::{Duration, Instant, sleep};',
      '',
      'async fn load(name: &str, ms: u64) -> String {',
      '    sleep(Duration::from_millis(ms)).await;',
      '    format!("{name}就绪（耗时 {ms}ms）")',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    let start = Instant::now();',
      '',
      '    let (user, orders) = tokio::join!(load("用户资料", 60), load("订单列表", 40));',
      '',
      '    println!("{user}");',
      '    println!("{orders}");',
      '    println!(',
      '        "总耗时小于 95ms：{}",',
      '        start.elapsed() < Duration::from_millis(95)',
      '    );',
      '}',
    ].join('\n'),
    expectedStdout:
      '用户资料就绪（耗时 60ms）\n订单列表就绪（耗时 40ms）\n总耗时小于 95ms：true\n',
    hints: [
      '`join!` 的参数是**还没 await 的 Future**：直接写 `load("用户资料", 60)`，不要加 `.await`。',
      '`tokio::join!` 这个宏内部已经帮你 await 了，**不要**在它后面再写 `.await`；但它只能在 async 函数里用。',
      '完整写法：`let (user, orders) = tokio::join!(load("用户资料", 60), load("订单列表", 40));`。',
    ],
  },
  {
    id: 'm6-03',
    moduleId: 'm6',
    title: '修复：忘了 .await 的 Future',
    difficulty: 3,
    judgeMode: 'compile',
    expectedStdout: "库存金额 = 100\n",
    prompt: [
      '### 修编译错误：expected `u32`, found future',
      '',
      '下面这段代码编译不过。先点「运行」看看编译器怎么说：',
      '',
      '```text',
      'error[E0308]: mismatched types',
      '  = note: expected type `u32`',
      '          found opaque type `impl Future<Output = u32>`',
      'help: consider `await`ing on the `Future`',
      '```',
      '',
      '这是所有人写 async Rust 的第一课：**`async fn` 的返回值不是 `u32`，而是一个「将来会产出 u32」的 Future**。',
      '调用它只是把状态机造出来放在那里，函数体一行都没执行——Future 是**惰性**的，没人 `.await`（或者交给 `spawn`）它就永远不会前进。',
      '',
      '这也解释了另一个新手困惑：只写 `do_something();` 却发现什么都没发生，编译器只给一个 `unused_must_use` 警告。',
      '在 Rust 里，Future 不像 JavaScript 的 Promise 那样一创建就开始跑。',
      '',
      '**要求**：修好这段代码，让它编译通过并**恰好**输出：',
      '',
      '```text',
      '库存金额 = 100',
      '```',
      '',
      '注意：`.await` 只能写在 `async` 上下文里——本题的 `main` 已经被 `#[tokio::main]` 标成 async 了，所以可以直接用。',
    ].join('\n'),
    starterCode: [
      'async fn unit_price(sku: &str) -> u32 {',
      '    match sku {',
      '        "book" => 25,',
      '        _ => 10,',
      '    }',
      '}',
      '',
      'async fn stock(sku: &str) -> u32 {',
      '    match sku {',
      '        "book" => 4,',
      '        _ => 0,',
      '    }',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    // TODO: 这两行编译不过——想清楚 async fn 到底返回了什么',
      '    let price: u32 = unit_price("book");',
      '    let count: u32 = stock("book");',
      '',
      '    println!("库存金额 = {}", price * count);',
      '}',
    ].join('\n'),
    solutionCode: [
      'async fn unit_price(sku: &str) -> u32 {',
      '    match sku {',
      '        "book" => 25,',
      '        _ => 10,',
      '    }',
      '}',
      '',
      'async fn stock(sku: &str) -> u32 {',
      '    match sku {',
      '        "book" => 4,',
      '        _ => 0,',
      '    }',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    let price: u32 = unit_price("book").await;',
      '    let count: u32 = stock("book").await;',
      '',
      '    println!("库存金额 = {}", price * count);',
      '}',
    ].join('\n'),
    hints: [
      '报错信息最后一行的 `help:` 已经直接把答案写出来了。',
      '`async fn f() -> u32` 的真实返回类型是 `impl Future<Output = u32>`，要拿到 `u32` 得先驱动它。',
      '两行分别改成 `unit_price("book").await` 和 `stock("book").await`。',
    ],
  },
  {
    id: 'm6-04',
    moduleId: 'm6',
    title: 'tokio::spawn 与 JoinHandle',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 把任务甩给运行时',
      '',
      '`join!` 是在**当前任务**里交替推进几个 Future；而 `tokio::spawn` 是把一个 Future 交给运行时，变成一个**独立任务**，',
      '多线程调度器可以把它偷到别的工作线程上去跑（work stealing）。它立刻返回一个 `JoinHandle<T>`：',
      '',
      '```rust',
      'let handle = tokio::spawn(async move { 1 + 1 });',
      'let value: i32 = handle.await.unwrap();   // await JoinHandle 得到 Result<T, JoinError>',
      '```',
      '',
      '`spawn` 的 Future 必须满足 `Send + \'static`：它可能被搬到另一个线程执行，而且运行时不知道它会活多久，',
      '所以不能借用栈上的局部变量——这就是 `async move` 几乎总是必需的原因（和模块五里 `thread::spawn` 要 `move` 闭包是同一个道理）。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub async fn spawn_and_collect(inputs: Vec<u64>) -> Vec<u64>',
      '```',
      '',
      '- 为**每个**输入 `n` spawn 一个任务，任务里先 `sleep(Duration::from_millis(n % 5))`，再返回 `n * n`；',
      '- 先把所有任务都 spawn 出去，**再**逐个 await 它们的 `JoinHandle`（这样才是并发）；',
      '- 把收集到的结果**升序排序**后返回（任务完成顺序不可控，排序保证结果确定）。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `[3, 1, 2]` | `[1, 4, 9]` |',
      '| `[]` | `[]` |',
      '| `[2, 2, 3]` | `[4, 4, 9]` |',
      '',
      '**本题以隐藏测试判分**（其中一条会计时，串行写法会超时失败）：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'pub async fn spawn_and_collect(inputs: Vec<u64>) -> Vec<u64> {',
      '    // TODO: 第一轮循环：为每个 n 用 tokio::spawn 起一个任务，把 JoinHandle 收进 Vec',
      '    // TODO: 第二轮循环：逐个 await JoinHandle，取出 n * n',
      '    // TODO: 排序后返回',
      '    let _ = inputs;',
      '    Vec::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'pub async fn spawn_and_collect(inputs: Vec<u64>) -> Vec<u64> {',
      '    let mut handles = Vec::new();',
      '',
      '    for n in inputs {',
      '        handles.push(tokio::spawn(async move {',
      '            sleep(Duration::from_millis(n % 5)).await;',
      '            n * n',
      '        }));',
      '    }',
      '',
      '    let mut results = Vec::new();',
      '    for handle in handles {',
      '        results.push(handle.await.expect("任务不应 panic"));',
      '    }',
      '',
      '    results.sort();',
      '    results',
      '}',
    ].join('\n'),
    hints: [
      '两轮循环缺一不可：如果在第一轮里就 `.await` 每个 handle，任务就变成串行了，计时那条测试会挂。',
      '闭包要写成 `async move { ... }`，否则 `n` 是借来的，过不了 `\'static` 检查。',
      '`handle.await` 的类型是 `Result<u64, JoinError>`，用 `.expect(...)` 或 `.unwrap()` 取值；最后别忘了 `results.sort();`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[tokio::test]',
      '    async fn squares_are_sorted() {',
      '        assert_eq!(spawn_and_collect(vec![3, 1, 2]).await, vec![1, 4, 9]);',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn empty_input_gives_empty_output() {',
      '        assert_eq!(spawn_and_collect(vec![]).await, Vec::<u64>::new());',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn keeps_duplicates() {',
      '        assert_eq!(spawn_and_collect(vec![2, 2, 3]).await, vec![4, 4, 9]);',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn tasks_really_run_concurrently() {',
      '        let start = std::time::Instant::now();',
      '        let out = spawn_and_collect(vec![9; 10]).await;',
      '        assert_eq!(out, vec![81; 10]);',
      '        assert!(',
      '            start.elapsed() < std::time::Duration::from_millis(30),',
      '            "10 个任务各睡 4ms，并发应该远快于 30ms，看起来是串行执行的"',
      '        );',
      '    }',
      '',
      '    #[test]',
      '    fn works_on_a_manually_built_runtime() {',
      '        let rt = tokio::runtime::Runtime::new().unwrap();',
      '        assert_eq!(rt.block_on(spawn_and_collect(vec![5, 4])), vec![16, 25]);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm6-05',
    moduleId: 'm6',
    title: 'tokio::sync::mpsc：异步生产者消费者',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 用 async 通道把结果汇总起来',
      '',
      '`tokio::sync::mpsc` 是 `std::sync::mpsc` 的异步版：`send` / `recv` 都是 `.await`，队列满或空时**让出**执行权而不是阻塞线程。',
      '',
      '```rust',
      'let (tx, mut rx) = tokio::sync::mpsc::channel::<u64>(8);   // 8 = 缓冲区容量（背压）',
      'tokio::spawn(async move { tx.send(1).await.unwrap(); });',
      'while let Some(v) = rx.recv().await { println!("{v}"); }',
      '```',
      '',
      '**最重要的一条规则**：`rx.recv()` 只有在**所有** `Sender` 都被丢弃后才返回 `None`。',
      '你在函数里保留了一个没用的 `tx`，接收循环就会永远等下去——这是异步代码里最常见的「莫名其妙卡住」。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub async fn pipeline_sum(chunks: Vec<Vec<u64>>) -> u64',
      '```',
      '',
      '- 建一个容量为 8 的 `mpsc::channel::<u64>`；',
      '- 每个 `chunk` 交给一个 `tokio::spawn` 的生产者任务，把 chunk 里的每个数逐个 `send().await` 进通道；',
      '- 主流程用 `while let Some(v) = rx.recv().await` 把收到的数全部累加，返回总和；',
      '- 记得在开始接收前 `drop` 掉自己手里那个原始的 `tx`。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `[]` | `0` |',
      '| `[[1, 2, 3]]` | `6` |',
      '| `[[1, 2], [3, 4], []]` | `10` |',
      '',
      '注意元素总数可能远大于通道容量 8——这正是背压生效的地方：生产者会在 `send().await` 处挂起等待消费者取走。',
      '',
      '**本题以隐藏测试判分**：不要写 `main`，函数必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use tokio::sync::mpsc;',
      '',
      'pub async fn pipeline_sum(chunks: Vec<Vec<u64>>) -> u64 {',
      '    // TODO: let (tx, mut rx) = mpsc::channel::<u64>(8);',
      '    // TODO: 为每个 chunk 克隆一个 tx，spawn 一个生产者任务把数字 send 进去',
      '    // TODO: drop 掉原始的 tx，否则接收循环永远不会结束',
      '    // TODO: while let Some(value) = rx.recv().await { ... } 累加并返回',
      '    let _ = chunks;',
      '    0',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::sync::mpsc;',
      '',
      'pub async fn pipeline_sum(chunks: Vec<Vec<u64>>) -> u64 {',
      '    let (tx, mut rx) = mpsc::channel::<u64>(8);',
      '',
      '    for chunk in chunks {',
      '        let tx = tx.clone();',
      '        tokio::spawn(async move {',
      '            for value in chunk {',
      '                if tx.send(value).await.is_err() {',
      '                    return;',
      '                }',
      '            }',
      '        });',
      '    }',
      '    drop(tx);',
      '',
      '    let mut total = 0;',
      '    while let Some(value) = rx.recv().await {',
      '        total += value;',
      '    }',
      '    total',
      '}',
    ].join('\n'),
    hints: [
      '每个生产者任务都需要自己的一份发送端：循环里先 `let tx = tx.clone();`，再 `tokio::spawn(async move { ... })`。',
      '起完所有生产者后写一句 `drop(tx);`——原始发送端不丢掉，`rx.recv()` 就永远不返回 `None`，测试会直接卡死。',
      '接收侧骨架：`let mut total = 0; while let Some(v) = rx.recv().await { total += v; } total`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[tokio::test]',
      '    async fn empty_input_is_zero() {',
      '        assert_eq!(pipeline_sum(vec![]).await, 0);',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn single_chunk() {',
      '        assert_eq!(pipeline_sum(vec![vec![1, 2, 3]]).await, 6);',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn several_chunks_with_an_empty_one() {',
      '        assert_eq!(pipeline_sum(vec![vec![1, 2], vec![3, 4], vec![]]).await, 10);',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn survives_backpressure() {',
      '        let chunks: Vec<Vec<u64>> = (0..4).map(|_| (1..=50).collect()).collect();',
      '        assert_eq!(pipeline_sum(chunks).await, 4 * 1275);',
      '    }',
      '',
      '    #[test]',
      '    fn works_on_a_manually_built_runtime() {',
      '        let rt = tokio::runtime::Runtime::new().unwrap();',
      '        assert_eq!(rt.block_on(pipeline_sum(vec![vec![10], vec![20, 30]])), 60);',
      '    }',
      '}',
    ].join('\n'),
  },
  {
    id: 'm6-06',
    moduleId: 'm6',
    title: 'timeout：给每个等待加上限',
    difficulty: 4,
    judgeMode: 'stdout',
    prompt: [
      '### 没有超时的 await 就是定时炸弹',
      '',
      '线上服务里任何一次外部调用都可能一直没有响应。`tokio::time::timeout` 给一个 Future 套上时限，返回 `Result`：',
      '',
      '```rust',
      'use tokio::time::{Duration, timeout};',
      '',
      'match timeout(Duration::from_millis(100), work()).await {',
      '    Ok(value) => println!("成功：{value}"),',
      '    Err(_elapsed) => println!("超时"),   // Err 里是 Elapsed，没有更多信息',
      '}',
      '```',
      '',
      '超时发生时，里面那个 Future 会被**直接丢弃**（drop）——也就是被取消，它停在哪个 `.await` 就死在哪里。',
      '所以「超时」在 Rust 里不是抛异常，而是取消：已经写了一半的数据不会自动回滚，这一点在设计接口时必须想清楚。',
      '',
      '**要求**：用 `timeout` 分别跑一次会成功的调用和一次会超时的调用，程序应当**恰好**输出：',
      '',
      '```text',
      '快接口：库存 42',
      '慢接口：超时（已取消）',
      '全部处理完毕',
      '```',
      '',
      '- 第一次：时限 100ms，任务 `query(20)`（睡 20ms 后返回 `库存 42`）→ 走 `Ok` 分支，打印 `快接口：` 加返回值；',
      '- 第二次：时限 30ms，任务 `query(500)` → 走 `Err` 分支，打印 `慢接口：超时（已取消）`；',
      '- 最后打印 `全部处理完毕`。',
      '',
      '注意第二次不会真的等满 500ms——超时一到整个 Future 就被丢掉了，所以程序总共只跑约 50ms。',
    ].join('\n'),
    starterCode: [
      'use tokio::time::{Duration, sleep, timeout};',
      '',
      'async fn query(ms: u64) -> String {',
      '    sleep(Duration::from_millis(ms)).await;',
      '    String::from("库存 42")',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    // TODO: timeout(100ms, query(20))，match 出 Ok/Err，打印 "快接口：<值>"',
      '',
      '    // TODO: timeout(30ms, query(500))，走 Err 分支，打印 "慢接口：超时（已取消）"',
      '',
      '    // TODO: 打印 "全部处理完毕"',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::time::{Duration, sleep, timeout};',
      '',
      'async fn query(ms: u64) -> String {',
      '    sleep(Duration::from_millis(ms)).await;',
      '    String::from("库存 42")',
      '}',
      '',
      '#[tokio::main]',
      'async fn main() {',
      '    match timeout(Duration::from_millis(100), query(20)).await {',
      '        Ok(value) => println!("快接口：{value}"),',
      '        Err(_) => println!("快接口：超时（已取消）"),',
      '    }',
      '',
      '    match timeout(Duration::from_millis(30), query(500)).await {',
      '        Ok(value) => println!("慢接口：{value}"),',
      '        Err(_) => println!("慢接口：超时（已取消）"),',
      '    }',
      '',
      '    println!("全部处理完毕");',
      '}',
    ].join('\n'),
    expectedStdout: '快接口：库存 42\n慢接口：超时（已取消）\n全部处理完毕\n',
    hints: [
      '`timeout(时限, 未 await 的 Future)` 本身还是个 Future，整体要 `.await` 一次才拿到 `Result`。',
      '两次调用结构完全一样，都是 `match ... { Ok(value) => ..., Err(_) => ... }`，只是时限和参数不同。',
      '第一句写成 `match timeout(Duration::from_millis(100), query(20)).await { Ok(value) => println!("快接口：{value}"), Err(_) => println!("快接口：超时（已取消）"), }`。',
    ],
  },
  {
    id: 'm6-07',
    moduleId: 'm6',
    title: 'select!：谁先回来用谁',
    difficulty: 4,
    judgeMode: 'tests',
    crateType: 'lib',
    prompt: [
      '### 竞速：对冲请求（hedged request）',
      '',
      '`tokio::select!` 同时推进多个分支，**第一个完成的分支胜出**，它的结果成为整个 `select!` 的值，其余分支的 Future 当场被丢弃：',
      '',
      '```rust',
      'let winner = tokio::select! {',
      '    v = fast() => v,',
      '    v = slow() => v,',
      '};',
      '```',
      '',
      '这正是生产环境里「对冲请求」的写法：同时问主副本和备份副本，谁先答就用谁的，把长尾延迟压下去。',
      '',
      '> **cancel safety（取消安全）**：落败分支的 Future 会在任意一个 `.await` 点被直接丢弃，中间状态不会保留。',
      '> 所以放进 `select!` 的操作必须是「被取消也不会丢数据」的——`sleep`、`recv()` 是取消安全的；',
      '> 而「读了一半的字节流」「已经扣款但还没记账」这类操作放进 `select!` 就会出事。文档里会明确标注哪些方法 cancel safe。',
      '',
      '**要求**：实现',
      '',
      '```rust',
      'pub async fn fastest_reply(primary_ms: u64, backup_ms: u64) -> String',
      '```',
      '',
      '用 `tokio::select!` 让 `respond("primary", primary_ms)` 和 `respond("backup", backup_ms)` 竞速，返回**先完成**的那个的结果。',
      '`respond` 已经写好了：睡指定毫秒后返回 `format!("{name}:{delay_ms}")`。',
      '',
      '| 输入 | 输出 |',
      '| --- | --- |',
      '| `(10, 300)` | `"primary:10"` |',
      '| `(300, 10)` | `"backup:10"` |',
      '',
      '**本题以隐藏测试判分**（其中一条会验证它确实没等慢的那个）：不要写 `main`，`fastest_reply` 必须是 `pub`。',
    ].join('\n'),
    starterCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'async fn respond(name: &str, delay_ms: u64) -> String {',
      '    sleep(Duration::from_millis(delay_ms)).await;',
      '    format!("{name}:{delay_ms}")',
      '}',
      '',
      'pub async fn fastest_reply(primary_ms: u64, backup_ms: u64) -> String {',
      '    // TODO: 用 tokio::select! 让两个 respond 竞速，返回先完成的那个',
      '    let _ = (primary_ms, backup_ms);',
      '    String::new()',
      '}',
    ].join('\n'),
    solutionCode: [
      'use tokio::time::{Duration, sleep};',
      '',
      'async fn respond(name: &str, delay_ms: u64) -> String {',
      '    sleep(Duration::from_millis(delay_ms)).await;',
      '    format!("{name}:{delay_ms}")',
      '}',
      '',
      'pub async fn fastest_reply(primary_ms: u64, backup_ms: u64) -> String {',
      '    tokio::select! {',
      '        reply = respond("primary", primary_ms) => reply,',
      '        reply = respond("backup", backup_ms) => reply,',
      '    }',
      '}',
    ].join('\n'),
    hints: [
      '`select!` 的分支写法是 `模式 = 异步表达式 => 结果表达式,`，分支之间用逗号分隔。',
      '两个分支产出的类型必须一致（这里都是 `String`），`select!` 整体就是函数的返回值表达式。',
      '完整骨架：`tokio::select! { reply = respond("primary", primary_ms) => reply, reply = respond("backup", backup_ms) => reply, }`。',
    ],
    hiddenTests: [
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[tokio::test]',
      '    async fn primary_wins_when_it_is_faster() {',
      '        assert_eq!(fastest_reply(10, 300).await, "primary:10");',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn backup_wins_when_primary_is_slow() {',
      '        assert_eq!(fastest_reply(300, 10).await, "backup:10");',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn does_not_wait_for_the_loser() {',
      '        let start = std::time::Instant::now();',
      '        assert_eq!(fastest_reply(20, 400).await, "primary:20");',
      '        assert!(',
      '            start.elapsed() < std::time::Duration::from_millis(150),',
      '            "落败分支应当被丢弃，不该等满 400ms"',
      '        );',
      '    }',
      '',
      '    #[tokio::test]',
      '    async fn zero_delay_returns_immediately() {',
      '        assert_eq!(fastest_reply(0, 500).await, "primary:0");',
      '    }',
      '',
      '    #[test]',
      '    fn works_on_a_manually_built_runtime() {',
      '        let rt = tokio::runtime::Runtime::new().unwrap();',
      '        assert_eq!(rt.block_on(fastest_reply(500, 5)), "backup:5");',
      '    }',
      '}',
    ].join('\n'),
  },
];
