import type { ChecklistItem, ProjectDef } from '@/lib/rust/types';

// 本地实战项目：网站不跑 cargo，只负责给出题面（brief）与验收清单（items）。
// 清单项 id（'p1-01'）与练习 id（'m1-01'）共用同一个进度命名空间，前缀 'p' 保证互不冲突。

const p1: ProjectDef = {
  id: 'p1',
  afterModuleId: 'm2',
  title: 'mini-grep 命令行工具',
  summary: '用 std::env::args + fs 读文件做行过滤，把 Result 与 ? 真正用在一条完整的错误链上。',
  brief: [
    '## 目标',
    '',
    '写一个能用的命令行搜索工具：`mini-grep 关键词 文件路径`，逐行扫描文件，把命中的行连同行号打印到标准输出；参数不对、文件读不到时，打印中文错误到**标准错误**并返回非零退出码。全程不用任何第三方 crate，只靠标准库。',
    '',
    '## 为什么是这个项目',
    '',
    '这是第一次把模块 1、2 学到的东西合成一个能交付的二进制：所有权与借用（返回 `Vec<&str>` 借用原文本而不是到处 clone）、`Option` / `Result` 的模式匹配、`?` 传播、`Box<dyn Error>` 装箱。招聘方看 Rust 简历时最先确认的就是「这个人是否会写符合 Rust 习惯的错误处理」——不是 `unwrap()` 一路到底，而是错误能一层层往上传、在 `main` 里统一呈现。同时你会第一次体验 `cargo clippy` 的严苛程度，这在任何一个正规 Rust 团队里都是 CI 的第一道门。',
    '',
    '## 建议目录结构',
    '',
    '```text',
    'mini_grep/',
    '├── Cargo.toml',
    '├── README.md',
    '├── test.txt          # 手工造的测试样本',
    '└── src/',
    '    ├── main.rs       # 只做：读参数 → 调 run → 打印错误 → 设退出码',
    '    └── lib.rs        # Config::build / run / search / search_case_insensitive',
    '```',
    '',
    '把逻辑放进 `lib.rs`、`main.rs` 只留薄薄一层，是为了让单元测试直接测到核心函数——这也是 Rust 社区标准的二进制项目布局。',
    '',
    '## 起步命令',
    '',
    '```bash',
    'cargo new mini_grep && cd mini_grep',
    'printf "hello rust\\nRust is fast\\nsafe by default\\n" > test.txt',
    'cargo run -- rust test.txt',
    '```',
    '',
    '## 分步引导',
    '',
    '1. **先跑通最笨的版本**：`env::args().collect::<Vec<String>>()`，硬取 `args[1]`、`args[2]`，`fs::read_to_string` 之后 `for line in content.lines()` 打印含关键词的行。先让它能跑，再谈优雅。',
    '2. **抽出 Config**：写 `Config::build(args: &[String]) -> Result<Config, String>`，参数不足时返回 `Err("用法: mini-grep <关键词> <文件>".into())`。`main` 里用 `unwrap_or_else` 捕获，`eprintln!` 之后 `process::exit(2)`。',
    '3. **抽出 run**：`fn run(config: Config) -> Result<(), Box<dyn Error>>`，里面用 `fs::read_to_string(&config.path)?`。`?` 会自动把 `io::Error` 装箱成 `Box<dyn Error>`，这就是 trait 对象的第一次实战。',
    '4. **纯函数化搜索**：`fn search<\'a>(needle: &str, haystack: &\'a str) -> Vec<(usize, &\'a str)>`。生命周期标注在这里是必须的——返回的切片借用的是 `haystack`，编译器需要你说清楚谁借谁。这一步会逼你真正理解模块 2 的借用规则。',
    '5. **加大小写不敏感**：`-i` / `--ignore-case` 参数或环境变量 `IGNORE_CASE`，复用同一份主流程，不要复制粘贴出第二条分支。',
    '6. **补测试与 lint**：在 `lib.rs` 底部写 `#[cfg(test)] mod tests`，覆盖命中、未命中、大小写两种模式；最后 `cargo clippy -- -D warnings` 必须零输出。',
    '',
    '## 常见坑',
    '',
    '- `search` 想返回 `Vec<String>` 是在偷懒（多一次分配），返回 `&str` 切片才是 Rust 写法，但你必须写对生命周期标注。',
    '- 错误信息打到 `println!` 会污染标准输出，管道给 `grep` / `wc` 时就出问题——错误一律走 `eprintln!`。',
    '- `main` 直接 `return Err(...)` 时 Rust 打印的是 `Debug` 格式且退出码固定为 1；要自定义退出码就得显式 `process::exit`。',
    '- clippy 大概率会点名 `needless_range_loop` 和 `&String` 参数（应改成 `&str`）——这两条是新手最常见的。',
  ].join('\n'),
  items: [
    {
      id: 'p1-01',
      text: '用 cargo new 初始化 mini_grep，核心逻辑在 src/lib.rs、src/main.rs 只留薄薄一层，cargo run 能跑通',
      testCommand: 'cargo new mini_grep && cd mini_grep && cargo run',
      hint: '二进制 crate 可以同时有 lib.rs：main.rs 里 `use mini_grep::run;` 就能引用同名 lib。',
    },
    {
      id: 'p1-02',
      text: 'std::env::args 解析两个位置参数（关键词、文件路径），参数不足时打印中文用法说明并以退出码 2 结束',
      testCommand: 'cargo run --',
      hint: 'args() 的第 0 项是程序名；用 args.len() < 3 判断，取值时记得 skip(1)。',
    },
    {
      id: 'p1-03',
      text: 'Config 结构体 + Config::build(&[String]) -> Result<Config, String>，参数解析与主流程彻底分离',
      hint: '让 build 返回 Result 而不是 panic，是把「用户输入错误」和「程序 bug」区分开的第一步。',
    },
    {
      id: 'p1-04',
      text: 'fs::read_to_string 读入文件，逐行过滤并按「行号: 行内容」格式打印所有命中行',
      testCommand: 'cargo run -- rust test.txt',
      hint: 'content.lines().enumerate() 拿到从 0 开始的下标，展示时记得 +1。',
    },
    {
      id: 'p1-05',
      text: "search<'a>(needle: &str, haystack: &'a str) 返回借用原文本的切片，不做多余的 String 分配",
      hint: '返回值借用的是 haystack，所以生命周期参数只标在 haystack 和返回值上，needle 不需要。',
    },
    {
      id: 'p1-06',
      text: 'run() 返回 Result<(), Box<dyn Error>>，IO 错误用 ? 传播，main 只负责呈现错误与设置退出码',
      hint: '? 会通过 From 自动把 io::Error 转成 Box<dyn Error>，不需要手写 map_err。',
    },
    {
      id: 'p1-07',
      text: '文件不存在时，中文错误信息写入 stderr（不是 stdout），进程退出码为 1',
      testCommand: 'cargo run -- rust 不存在.txt; echo "exit=$?"',
      hint: '加上 2>/dev/null 再跑一次，如果还能看到错误文本，说明你写错到 stdout 了。',
    },
    {
      id: 'p1-08',
      text: '支持 -i / --ignore-case（或环境变量 IGNORE_CASE）做大小写不敏感搜索，与默认模式共用主流程',
      testCommand: 'cargo run -- -i RUST test.txt',
      hint: 'to_lowercase() 会分配新 String，注意别把它的临时值借用到函数外面。',
    },
    {
      id: 'p1-09',
      text: '至少 3 个单元测试覆盖命中、未命中、大小写不敏感三种场景，cargo test 全绿',
      testCommand: 'cargo test',
      hint: '#[cfg(test)] mod tests 放在 lib.rs 底部，use super::*; 引入被测函数。',
    },
    {
      id: 'p1-10',
      text: 'cargo fmt --check 与 cargo clippy -- -D warnings 均零输出，README 写清用法示例',
      testCommand: 'cargo fmt --check && cargo clippy -- -D warnings',
      hint: '把这两条命令写进 README，后面每个项目照抄——这就是你未来 CI 的雏形。',
    },
  ],
};

const p2: ProjectDef = {
  id: 'p2',
  afterModuleId: 'm4',
  title: 'todo-json 待办 CLI',
  summary: 'serde_json 持久化 + 结构体建模 + 迭代器统计，第一个「有状态」的命令行程序。',
  brief: [
    '## 目标',
    '',
    '做一个把待办事项存成 JSON 文件的命令行工具，支持 `add` / `list` / `done` / `rm` / `stats` 五个子命令。数据落盘到 `todos.json`，重启后状态还在；`stats` 用迭代器算出完成率并按标签分组统计。',
    '',
    '## 为什么是这个项目',
    '',
    'serde 是 Rust 后端 JD 里出现频率最高的第三方 crate，几乎所有 axum 项目的请求与响应都由它序列化。这个项目让你在没有网络、没有数据库的干净环境里，先把 `#[derive(Serialize, Deserialize)]`、字段重命名、`Option` 字段、默认值这些常见姿势练熟。`stats` 那一段则是迭代器链的集中训练：`filter` / `map` / `fold` / `HashMap::entry`——面试里「不写 for 循环怎么做分组统计」几乎是必考题。最后，「读文件—改内存—写回文件」这个循环会第一次让你直面**原子写**，而这正是生产代码与玩具代码的分界线。',
    '',
    '## 建议目录结构',
    '',
    '```text',
    'todo_json/',
    '├── Cargo.toml',
    '├── README.md',
    '└── src/',
    '    ├── main.rs      # 子命令分发',
    '    ├── model.rs     # Task 结构体 + Status 枚举 + serde 派生',
    '    ├── store.rs     # load() / save()（临时文件 + rename 原子写）',
    '    └── stats.rs     # 完成率、按标签分组',
    '```',
    '',
    '## 起步命令',
    '',
    '```bash',
    'cargo new todo_json && cd todo_json',
    'cargo add serde --features derive',
    'cargo add serde_json',
    'cargo run -- add "看完模块 4" --tag rust',
    '```',
    '',
    '## 分步引导',
    '',
    '1. **先建模**：`struct Task { id: u32, title: String, done: bool, tags: Vec<String>, created_at: u64 }`，派生 `Serialize, Deserialize, Debug, Clone`。时间用 `SystemTime::now().duration_since(UNIX_EPOCH)` 取秒即可，不必引入 chrono。',
    '2. **读写落盘**：`load(path) -> Result<Vec<Task>>` 在文件不存在时返回空 `Vec` 而不是报错（用 `ErrorKind::NotFound` 判断）；`save` 先写 `todos.json.tmp` 再 `fs::rename`，保证进程被 kill 时不会留下半个 JSON。',
    '3. **子命令分发**：手写 `match args[1].as_str()`，暂时不引 clap——先感受一次手写解析的痛，之后你才知道 clap 到底替你做了什么。',
    '4. **迭代器统计**：完成率 = `tasks.iter().filter(|t| t.done).count()` 除以 `tasks.len()`（注意空列表除零）；按标签分组用 `flat_map` 把 `(tag, done)` 摊平，再 `fold` 进 `HashMap<&str, (usize, usize)>`。',
    '5. **错误统一**：定义 `enum AppError { Io(io::Error), Json(serde_json::Error), NotFound(u32) }` 并实现 `From` 与 `Display`，让 `?` 在各层自动转换。这是手写错误类型的最小完整练习，比直接上 anyhow 学到的更多。',
    '6. **测试**：把存储路径做成函数参数而不是硬编码常量，测试里指向临时目录；覆盖序列化 round-trip、空文件、完成率、标签分组、id 不存在五种情况。',
    '',
    '## 常见坑',
    '',
    '- `serde_json::from_str` 遇到空文件会报 `EOF while parsing a value`——空文件要单独当作空列表处理。',
    '- 结构体加字段后旧 JSON 反序列化会失败，用 `#[serde(default)]` 让新字段可缺省，这在真实迭代里天天遇到。',
    '- 直接 `File::create` 覆盖写，中途 panic 就会毁掉整个待办文件；临时文件 + rename 才是安全做法。',
    '- 完成率别用 `{}` 打印，`{:.1}%` 才好看；列表为空时先返回 0.0，别让它输出 `NaN`。',
    '- clippy 会点名「先 collect 成 Vec 再 iter()」这类多余分配，顺手改掉。',
  ].join('\n'),
  items: [
    {
      id: 'p2-01',
      text: 'cargo new todo_json 并加入 serde（derive 特性）与 serde_json 依赖，cargo build 通过',
      testCommand: 'cargo add serde --features derive && cargo add serde_json && cargo build',
      hint: 'cargo add 会自动写好 Cargo.toml 里的版本与特性，比手改可靠。',
    },
    {
      id: 'p2-02',
      text: 'Task 结构体建模（id / title / done / tags / created_at）并派生 Serialize、Deserialize、Debug、Clone',
      hint: '后加的字段配上 #[serde(default)]，旧数据文件才不会反序列化失败。',
    },
    {
      id: 'p2-03',
      text: 'add / list / done / rm / stats 五个子命令都能从命令行分发到对应函数，未知子命令给出中文提示',
      testCommand: 'cargo run -- list',
      hint: 'match args.get(1).map(String::as_str)：None 分支就打印用法说明。',
    },
    {
      id: 'p2-04',
      text: '持久化到 todos.json：load() 在文件不存在时返回空列表，save() 用「临时文件 + rename」原子写',
      testCommand: 'cargo run -- add "写原子写" --tag rust && cat todos.json',
      hint: 'io::ErrorKind::NotFound 单独分支处理，其余 IO 错误照常向上传播。',
    },
    {
      id: 'p2-05',
      text: 'list 支持按标签过滤（--tag rust）与只看未完成（--open），过滤逻辑全部用迭代器链实现',
      testCommand: 'cargo run -- list --tag rust',
      hint: 'filter 闭包里用 t.tags.iter().any(|x| x == tag)，避免多余 clone。',
    },
    {
      id: 'p2-06',
      text: 'stats 用迭代器算出完成率（保留一位小数、空列表不输出 NaN）并按标签分组给出「完成 / 总数」',
      testCommand: 'cargo run -- stats',
      hint: 'HashMap 的 entry(key).or_insert((0, 0)) 是分组计数的惯用写法。',
    },
    {
      id: 'p2-07',
      text: '自定义错误枚举（含 From 与 Display 实现）串起 IO 与 JSON 两类错误，各层统一用 ? 传播',
      hint: '实现 From<io::Error> 与 From<serde_json::Error> 之后，? 就能自动转换了。',
    },
    {
      id: 'p2-08',
      text: 'done <id> / rm <id> 遇到不存在的 id 返回明确的中文错误并以非零退出码结束，不 panic',
      testCommand: 'cargo run -- done 9999; echo "exit=$?"',
      hint: '库层返回 AppError::NotFound(id)，由 main 决定退出码——别在库里调 process::exit。',
    },
    {
      id: 'p2-09',
      text: '至少 5 个单元测试：序列化 round-trip、空文件、完成率、标签分组、id 不存在，cargo test 全绿',
      testCommand: 'cargo test',
      hint: '把路径做成参数，测试里用 std::env::temp_dir() 下的唯一文件名，测完删掉。',
    },
    {
      id: 'p2-10',
      text: 'cargo clippy --all-targets -- -D warnings 零警告、cargo fmt --check 干净，README 列出全部子命令',
      testCommand: 'cargo fmt --check && cargo clippy --all-targets -- -D warnings',
      hint: '--all-targets 会连测试代码一起 lint，比默认更严格，正好模拟 CI。',
    },
  ],
};

const p3: ProjectDef = {
  id: 'p3',
  afterModuleId: 'm6',
  title: 'tokio 并发抓取器',
  summary: 'tokio::spawn + Semaphore 限并发、reqwest 超时与错误分类、mpsc 汇总——异步能力的第一次实战。',
  brief: [
    '## 目标',
    '',
    '写一个并发 HTTP 抓取器：从文件读入一批 URL，用 tokio 并发请求，`--concurrency N` 控制同时在飞的请求数，每个请求带超时；结果通过 mpsc 汇总成一份报告（成功数、各类失败数、平均耗时），且输出顺序确定。',
    '',
    '## 为什么是这个项目',
    '',
    'Rust 后端 JD 里 async / Tokio 的出现频率仅次于所有权本身，而面试官分辨「用过 async」和「懂 async」的方式几乎固定是三个问题：怎么限并发、怎么设超时、任务 panic 了会怎样。这个项目正好把这三点全部覆盖。你会亲手体会 `Arc<Semaphore>` 的 permit 生命周期（提前 drop 就限不住并发）、`JoinHandle` 的双层 Result（外层是 JoinError，内层才是业务错误）、以及 mpsc 的发送端必须全部 drop 接收端才会结束——这三个坑几乎人人踩一遍。它同时是 p4 那个 axum 服务的热身：那里的每个连接同样是一个 spawn 出去的任务。',
    '',
    '## 建议目录结构',
    '',
    '```text',
    'fetcher/',
    '├── Cargo.toml',
    '├── urls.txt',
    '└── src/',
    '    ├── main.rs      # CLI 解析 + 运行时启动',
    '    ├── fetch.rs     # 单个 URL 的抓取与错误分类',
    '    └── report.rs    # 结果聚合与打印',
    '```',
    '',
    '## 起步命令',
    '',
    '```bash',
    'cargo new fetcher && cd fetcher',
    'cargo add tokio --features full',
    'cargo add reqwest --features rustls-tls --no-default-features',
    'printf "https://example.com\\nhttps://httpbin.org/delay/2\\n" > urls.txt',
    'cargo run -- urls.txt --concurrency 4',
    '```',
    '',
    '## 分步引导',
    '',
    '1. **串行版本先跑通**：`#[tokio::main]` 加一个 `for` 循环里 `client.get(url).send().await`。确认能拿到状态码再谈并发——你会立刻感受到它有多慢，这就是并发的动机。',
    '2. **spawn 出去**：把每个 URL 包成 `tokio::spawn(async move { ... })`，收集 `Vec<JoinHandle<_>>` 后逐个 `.await`。闭包里用到的 `Client` 要 `clone()`（reqwest 的 Client 内部就是 `Arc`，clone 很便宜，千万别每个任务新建一个）。',
    '3. **限并发**：`let sem = Arc::new(Semaphore::new(n));`，任务开头 `let _permit = sem.clone().acquire_owned().await?;`。permit 必须绑到一个活到任务结束的变量上——写成 `let _ = ...` 会立刻 drop，限流当场失效。',
    '4. **超时与错误分类**：`Client::builder().timeout(Duration::from_secs(5))`，再定义 `enum FetchError { Timeout, Connect, Status(u16), Other(String) }`，用 `err.is_timeout()` / `err.is_connect()` 归类。分类的意义在于报告能告诉你「是对方慢还是网断了」。',
    '5. **mpsc 汇总**：`let (tx, mut rx) = mpsc::channel(64);`，每个任务发一条结果，主任务 `while let Some(r) = rx.recv().await` 聚合。**关键**：主任务手上那个 `tx` 要显式 `drop(tx)`，否则 `recv()` 永远等不到 `None`，程序挂死。',
    '6. **确定性输出**：聚合完成后按 URL 排序再打印，或用输入下标回填到 `Vec<Option<_>>`。异步任务完成顺序天然不确定，不排序的话每次输出都不一样，测试也没法写。',
    '7. **测试**：`#[tokio::test]` 覆盖限并发（用 `AtomicUsize` 记录峰值在飞数）、错误分类映射、报告聚合三块，把纯计算部分从网络请求里拆出来单独测。',
    '',
    '## 常见坑',
    '',
    '- `handle.await` 返回的是 `Result<T, JoinError>`：任务里 panic 不会让主程序崩，而是变成 `Err(JoinError)`——别 `unwrap()` 把它吞掉。',
    '- 忘记 `drop(tx)` 导致程序卡在 `recv()` 不退出，是 mpsc 最经典的死锁。',
    '- 在 async 里调用阻塞 IO（`std::fs` 读大文件、`std::thread::sleep`）会卡住整个 worker 线程，要用 `tokio::fs` 或 `spawn_blocking`。',
    '- `Semaphore::acquire()` 返回的 permit 借用了 semaphore，move 进 spawn 会报生命周期错误——用 `acquire_owned()` 配 `Arc`。',
    '- reqwest 默认走 native-tls，交叉编译和 Docker 里常翻车，换 rustls 省事。',
  ].join('\n'),
  items: [
    {
      id: 'p3-01',
      text: 'cargo new fetcher，装好 tokio（full）与 reqwest 依赖，#[tokio::main] 下能串行跑通单个 URL 请求',
      testCommand: 'cargo add tokio --features full && cargo add reqwest --features rustls-tls && cargo run',
      hint: '先串行跑通一个 URL 再谈并发，能省掉一半调试时间。',
    },
    {
      id: 'p3-02',
      text: 'CLI 读入 URL 列表文件（每行一个，忽略空行与 # 注释）并支持 --concurrency N 参数',
      testCommand: 'cargo run -- urls.txt --concurrency 4',
      hint: "lines().map(str::trim).filter(|l| !l.is_empty() && !l.starts_with('#'))。",
    },
    {
      id: 'p3-03',
      text: '每个 URL 用 tokio::spawn 起独立任务，JoinHandle 的双层 Result 都被正确处理（任务 panic 不被吞掉）',
      hint: 'handle.await 是 Result<T, JoinError>，外层 JoinError 要单独报告出来。',
    },
    {
      id: 'p3-04',
      text: 'Arc<Semaphore> + acquire_owned 限制同时在飞的请求数，permit 绑定到活到任务结束的变量',
      hint: '写 let _permit = ...（不是 let _ = ...），否则 permit 立刻释放，限流形同虚设。',
    },
    {
      id: 'p3-05',
      text: '全程复用同一个 reqwest::Client（clone 而非每个任务新建），并在 builder 上设置 5 秒超时',
      hint: 'Client 内部是 Arc，clone 成本极低；每次 new 会重建连接池，反而更慢。',
    },
    {
      id: 'p3-06',
      text: '错误分类为枚举：超时 / 连接失败 / 非 2xx 状态 / 其他，报告里分别计数',
      hint: 'reqwest::Error 提供 is_timeout()、is_connect()、is_status() 供判别。',
    },
    {
      id: 'p3-07',
      text: '结果经 tokio::sync::mpsc 汇总到聚合任务，主任务显式 drop 发送端，程序能自然退出不挂死',
      testCommand: 'cargo run -- urls.txt --concurrency 2',
      hint: '所有 sender 被 drop 后 recv() 才返回 None；主任务手里那个最容易忘。',
    },
    {
      id: 'p3-08',
      text: '输出确定性：结果按 URL（或输入顺序）排序后打印，多次运行输出完全一致',
      testCommand: 'cargo run -- urls.txt > a.txt && cargo run -- urls.txt > b.txt && diff a.txt b.txt',
      hint: '异步完成顺序不确定，不排序就没法写断言，也没法做回归对比。',
    },
    {
      id: 'p3-09',
      text: '报告输出成功数、各类失败数、平均耗时与总耗时，耗时用 Instant::elapsed 测量',
      hint: 'Instant 在 async 里照常可用；别用 SystemTime 算时长，它会受系统时钟调整影响。',
    },
    {
      id: 'p3-10',
      text: '至少 3 个 #[tokio::test]：限并发峰值不超过 N、错误分类映射正确、报告聚合正确，cargo test 全绿',
      testCommand: 'cargo test',
      hint: '用 AtomicUsize 在任务进出时 fetch_add / fetch_sub 记录峰值，断言不超过 N。',
    },
    {
      id: 'p3-11',
      text: 'cargo clippy --all-targets -- -D warnings 零警告，且代码里没有在 async 中调用阻塞 IO',
      testCommand: 'cargo clippy --all-targets -- -D warnings',
      hint: '文件读写换成 tokio::fs，CPU 密集或阻塞调用交给 spawn_blocking。',
    },
  ],
};

const p4: ProjectDef = {
  id: 'p4',
  afterModuleId: 'm7',
  title: 'axum + sqlx + WebSocket 订单后端',
  summary: '毕业项目：REST CRUD、sqlx 迁移、WebSocket 广播、tracing、Docker 与 CI，一套完整可上线的服务。',
  brief: [
    '## 目标',
    '',
    '用 axum + sqlx(SQLite) 写一个订单服务：完整 REST CRUD、按状态过滤与分页、统一错误响应；`/ws` 端点把订单状态变更实时广播给所有连接的客户端；配上 tracing 结构化日志、多阶段 Dockerfile、GitHub Actions CI，以及一份别人照着就能跑起来的 README。',
    '',
    '## 为什么是这个项目',
    '',
    '这是整条路径的终点，也是你简历上那个可以被点开的链接。前面 JD 调研里的高频硬要求——async / Tokio、axum、serde、sqlx、错误处理、Docker 与 CI——在这一个仓库里同时出现，而且以「订单域」这种真实业务形态呈现，不是又一个 todo demo。面试时对方会问的几件事这里都有答案：extractor 怎么组织、错误怎么映射成 HTTP 状态码、连接池放在哪、WebSocket 的广播通道满了怎么办、镜像多大、CI 跑什么。做完它，你就具备了维护一个生产 Rust 服务的最小完整能力。',
    '',
    '## 建议目录结构',
    '',
    '```text',
    'orders_api/',
    '├── Cargo.toml',
    '├── Dockerfile',
    '├── README.md',
    '├── .github/workflows/ci.yml',
    '├── migrations/0001_init.sql',
    '├── src/',
    '│   ├── main.rs      # 启动、日志初始化、路由装配',
    '│   ├── state.rs     # AppState { pool, tx: broadcast::Sender<Event> }',
    '│   ├── error.rs     # AppError + IntoResponse',
    '│   ├── model.rs     # Order / OrderStatus / 请求响应 DTO',
    '│   ├── routes/      # orders.rs, ws.rs',
    '│   └── db.rs        # 查询封装',
    '└── tests/api.rs     # 集成测试',
    '```',
    '',
    '## 起步命令',
    '',
    '```bash',
    'cargo new orders_api && cd orders_api',
    'cargo add axum && cargo add tokio --features full',
    'cargo add sqlx --features runtime-tokio-rustls,sqlite,migrate',
    'cargo add serde --features derive',
    'cargo add serde_json tower-http tracing tracing-subscriber',
    'DATABASE_URL=sqlite:orders.db cargo run',
    '```',
    '',
    '## 分步引导',
    '',
    '1. **先起一个 hello 路由**：`Router::new().route("/health", get(|| async { "ok" }))` 配 `axum::serve(listener, app)`，确认端口能通。',
    '2. **接数据库**：`SqlitePoolOptions` 建池，启动时跑 `sqlx::migrate!("./migrations").run(&pool).await?`。迁移文件里建 `orders(id TEXT PRIMARY KEY, customer TEXT, amount_cents INTEGER, status TEXT, created_at INTEGER)`。金额一律存整数分——用浮点存钱是事故之源。',
    '3. **AppState 与 extractor**：把连接池和广播发送端放进 `AppState`，用 `State<AppState>` 注入 handler；请求体用 `Json<CreateOrder>`，查询串用 `Query<ListParams>`，路径参数用 `Path<String>`。',
    '4. **统一错误**：`enum AppError { NotFound, Validation(String), Db(sqlx::Error) }` 并 `impl IntoResponse`，分别映射到 404 / 400 / 500，响应体统一是 `{"error": "..."}`。handler 全部返回 `Result<Json<T>, AppError>`，`?` 一路顺畅。',
    '5. **CRUD 落地**：`POST /orders`、`GET /orders?status=paid&limit=20&offset=0`、`GET /orders/:id`、`PATCH /orders/:id/status`、`DELETE /orders/:id`，用 `query_as::<_, Order>` 把行映射到带 `#[derive(sqlx::FromRow)]` 的结构体。',
    '6. **WebSocket 广播**：`broadcast::channel(128)`，状态变更后 `tx.send(event)`；`/ws` 里 `ws.on_upgrade(...)`，每个连接一个 `rx.recv()` 循环把事件 JSON 推给客户端。慢客户端会收到 `RecvError::Lagged`，跳过继续收，别把整条连接断掉。',
    '7. **可观测性**：`tracing_subscriber::fmt().with_env_filter(EnvFilter::from_default_env())`，挂上 `tower_http::trace::TraceLayer`，关键 handler 加 `#[tracing::instrument]`，让日志自动带上订单 id。',
    '8. **测试**：`tests/api.rs` 里用 `sqlite::memory:` 建一次性库，通过 `tower::ServiceExt::oneshot` 把请求直接打进 Router，不绑端口。覆盖创建、查询、404、非法状态流转、分页五种。',
    '9. **打包与 CI**：多阶段 Dockerfile（builder 编 release，运行阶段用 debian:bookworm-slim 只复制二进制）；CI 三步 `cargo fmt --check`、`cargo clippy -- -D warnings`、`cargo test`。',
    '',
    '## 常见坑',
    '',
    '- `sqlx::query!` 宏需要编译期连数据库或备好 `.sqlx` 离线缓存，CI 里没库会直接编译失败；不想折腾就先用运行时的 `query_as`。',
    '- SQLite 只有单写者，高并发写会报 `database is locked`；开 WAL 模式并把池调小。',
    '- axum 的 extractor 有顺序要求：消费请求体的（`Json`）必须放在参数列表的最后一个。',
    '- 广播通道满了会给慢接收者返回 `Lagged(n)`，要跳过继续收，而不是当致命错误处理。',
    '- Docker 里编 Rust 不做依赖层缓存的话每次都要重编全部依赖；先 copy Cargo.toml 单独 build 一次占坑是标准技巧。',
    '- 容器里监听 `127.0.0.1` 外面永远连不上，必须绑 `0.0.0.0`。',
  ].join('\n'),
  items: [
    {
      id: 'p4-01',
      text: 'cargo new orders_api，装好 axum / tokio / sqlx / serde / tracing 依赖，GET /health 返回 ok',
      testCommand: 'curl -s localhost:8080/health',
      hint: '先让服务起得来再谈数据库——分步验证比一次写完好调试得多。',
    },
    {
      id: 'p4-02',
      text: 'migrations/0001_init.sql 建 orders 表，启动时 sqlx::migrate! 自动执行，金额以整数分存储',
      testCommand: 'DATABASE_URL=sqlite:orders.db cargo run',
      hint: 'sqlx::migrate!("./migrations") 在编译期嵌入迁移文件，部署时不用额外带目录。',
    },
    {
      id: 'p4-03',
      text: 'AppState 持有连接池与 broadcast::Sender，经 State extractor 注入所有 handler',
      hint: 'AppState 需要 Clone；里面放的 Pool 和 Sender 本身就是廉价 clone 的。',
    },
    {
      id: 'p4-04',
      text: 'REST CRUD 五个端点齐活：创建、列表（状态过滤 + limit/offset 分页）、详情、改状态、删除',
      testCommand: 'curl -s -XPOST localhost:8080/orders -H "content-type: application/json" -d \'{"customer":"张三","amount_cents":1999}\'',
      hint: 'Query<ListParams> 里的字段用 Option<T> 配 serde default，参数才是可选的。',
    },
    {
      id: 'p4-05',
      text: 'AppError 枚举实现 IntoResponse：校验失败 400、找不到 404、内部错误 500 各有统一 JSON 错误体，非法请求不落库',
      testCommand: 'curl -s -o /dev/null -w "%{http_code}\\n" localhost:8080/orders/does-not-exist',
      hint: '状态用枚举 + serde 反序列化，非法值在解析阶段就被拒掉；sqlx::Error 别原样透给客户端。',
    },
    {
      id: 'p4-06',
      text: 'sqlx query_as 映射到 #[derive(FromRow)] 的 Order 结构体，时间与可空字段处理正确',
      hint: 'SQLite 没有原生布尔与时间类型，存 INTEGER 再在 Rust 侧转换最省心。',
    },
    {
      id: 'p4-07',
      text: 'WebSocket /ws：订单创建与状态变更实时广播给所有连接，遇到 Lagged 跳过而不是断开连接',
      testCommand: 'websocat ws://localhost:8080/ws',
      hint: '没装 websocat 就在浏览器 console 里写十行 new WebSocket(...) 看推送。',
    },
    {
      id: 'p4-08',
      text: 'tracing + tower_http::TraceLayer 输出结构化日志（方法、路径、状态码、耗时），RUST_LOG 可调级别',
      testCommand: 'RUST_LOG=info,tower_http=debug cargo run',
      hint: '关键 handler 上加 #[tracing::instrument(skip(state))]，日志会自动带上参数字段。',
    },
    {
      id: 'p4-09',
      text: '集成测试用内存 SQLite + oneshot 直接打进 Router，至少 5 个用例覆盖 CRUD、404 与分页，全绿',
      testCommand: 'cargo test',
      hint: 'sqlite::memory: 每个测试一份独立库，天然隔离，不用清表。',
    },
    {
      id: 'p4-10',
      text: '多阶段 Dockerfile 构建成功，服务在容器内绑定 0.0.0.0，容器跑起来后 /health 可访问',
      testCommand: 'docker build -t orders-api . && docker run --rm -p 8080:8080 orders-api',
      hint: '先单独 copy Cargo.toml 构建一次做依赖层缓存，后续构建能快一个数量级。',
    },
    {
      id: 'p4-11',
      text: 'GitHub Actions CI 三步全绿：cargo fmt --check、cargo clippy -- -D warnings、cargo test',
      testCommand: 'cargo fmt --check && cargo clippy --all-targets -- -D warnings && cargo test',
      hint: '给 CI 加上 rust 缓存 action，否则每次都从零编译依赖。',
    },
    {
      id: 'p4-12',
      text: 'README 写清架构说明、API 一览表、本地运行步骤、环境变量与部署方式，别人照着能跑起来',
      hint: '这是招聘方真正会读的部分——把它当项目门面来写，别只留一句 cargo run。',
    },
  ],
};

export const allProjects: ProjectDef[] = [p1, p2, p3, p4];

export function getProjectById(id: string): ProjectDef | undefined {
  return allProjects.find((project) => project.id === id);
}

export function projectsByModule(moduleId: string): ProjectDef[] {
  return allProjects.filter((project) => project.afterModuleId === moduleId);
}

// 供进度接口校验用：判断某个 id 是否是已知的验收清单项。
export function getChecklistItemById(id: string): ChecklistItem | undefined {
  for (const project of allProjects) {
    const item = project.items.find((i) => i.id === id);
    if (item) return item;
  }
  return undefined;
}
