import type { ModuleDef } from '@/lib/rust/types';

export type ResourceKind = 'capability' | 'interview' | 'cheatsheet';

export interface ResourceItem {
  id: string;
  kind: ResourceKind;
  title: string;
  summary: string;
  category: string;
  level: ModuleDef['tierLabel'];
  tags: string[];
  moduleId?: string;
  exerciseId?: string;
  projectId?: string;
  readingTime?: string;
  body?: string;
  code?: string;
}

export interface ResourceGroup {
  id: 'jd' | 'interview' | 'cheatsheet';
  title: string;
  eyebrow: string;
  summary: string;
  items: ResourceItem[];
}

export interface ScenarioCard {
  title: string;
  question: string;
  moduleId: string;
  exerciseId?: string;
  tags: string[];
}

/**
 * 内容依据：2026-07 Indeed CA / US 岗位抓取 + 公开 JD 调研。
 * 薪资只写有公开出处的锚点，不做区间推断。
 */

const md = (...lines: string[]) => lines.join('\n');

const jdItems: ResourceItem[] = [
  {
    id: 'jd-ownership',
    kind: 'capability',
    title: '所有权与借用',
    summary: '几乎每份 Rust JD 的第一条硬要求：能讲清 move、借用规则与切片，并据此设计 API。',
    category: '语言核心',
    level: '硬要求',
    tags: ['ownership', 'borrowing', 'slice'],
    moduleId: 'm1',
    projectId: 'p1',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Strong understanding of ownership, borrowing and lifetimes”',
      '- “Able to reason about memory without a garbage collector”',
      '',
      '## 面试官在验的信号',
      '',
      '- 函数签名默认写 `&str` / `&[T]` 而不是 `String` / `Vec<T>`，只有真正需要所有权时才要求所有权。',
      '- 遇到借用冲突时先想“调整作用域 / 拆分结构”，而不是一路 `clone()` 或 `Rc<RefCell<_>>`。',
      '- 能解释 move 之后原变量为什么不可用，以及 `Copy` 类型为什么例外。',
      '',
      '## 对应训练',
      '',
      '- 模块 m1：变量、控制流、move、借用、切片。',
      '- 实战项目 p1 `mini-grep`：把命令行参数与文件内容按借用切分，全程不做多余拷贝。',
    ),
  },
  {
    id: 'jd-types',
    kind: 'capability',
    title: '结构体、枚举与模式匹配',
    summary: '用类型把非法状态表达为不可构造，是 Rust 岗位区别于“会写 Rust 语法”的分水岭。',
    category: '语言核心',
    level: '硬要求',
    tags: ['enum', 'match', 'Option', 'Result'],
    moduleId: 'm2',
    projectId: 'p1',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Model domain logic with enums and exhaustive pattern matching”',
      '- “Idiomatic use of Option / Result instead of sentinel values”',
      '',
      '## 面试官在验的信号',
      '',
      '- 用枚举表达状态机，而不是 `status: String` 加一堆 `if`。',
      '- `match` 穷尽分支，不习惯性写 `_ => {}` 吞掉新增变体。',
      '- 知道 `Option::map` / `and_then` / `ok_or` 与 `?` 的配合方式。',
      '',
      '## 对应训练',
      '',
      '- 模块 m2：结构体、枚举、模式匹配、Option/Result 入门。',
      '- 实战项目 p1：把“找不到文件 / 参数缺失 / 匹配为空”三种情况分别建模。',
    ),
  },
  {
    id: 'jd-traits',
    kind: 'capability',
    title: 'trait、泛型与生命周期',
    summary: '抽象层能力：写库、写中间件、写可测试的服务层都卡在这一关。',
    category: '语言核心',
    level: '硬要求',
    tags: ['trait', 'generics', 'lifetime'],
    moduleId: 'm3',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Traits, generics, trait bounds, lifetimes”',
      '- “Design reusable abstractions without runtime cost”',
      '',
      '## 面试官在验的信号',
      '',
      '- 能在泛型（静态分发）与 `dyn Trait`（动态分发）之间给出取舍理由，而不是只会一种。',
      '- 会用 trait 做依赖注入，把外部依赖抽象成可以在测试里替换的接口。',
      '- 生命周期标注写不出来时，知道先看“返回值的引用来自哪个入参”。',
      '',
      '## 对应训练',
      '',
      '- 模块 m3：trait、泛型、生命周期，含大量“修标注”式编译题。',
    ),
  },
  {
    id: 'jd-errors',
    kind: 'capability',
    title: '错误处理：Result + thiserror / anyhow',
    summary: '后端 JD 的高频细节题——库层用具名错误，应用层用聚合错误，边界处转换成 HTTP 状态。',
    category: '工程实践',
    level: '硬要求',
    tags: ['Result', 'thiserror', 'anyhow', '?'],
    moduleId: 'm2',
    projectId: 'p2',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Robust error handling with Result, thiserror / anyhow”',
      '- “No unwrap in production code paths”',
      '',
      '## 面试官在验的信号',
      '',
      '- 知道 `unwrap` / `expect` 只出现在测试、启动期不变量和确实不可能失败的地方。',
      '- 能说清 `?` 背后的 `From` 转换链路。',
      '- 服务层能把内部错误映射成对外安全的响应，不把数据库错误直接透传给用户。',
      '',
      '## 对应训练',
      '',
      '- 模块 m2 打底，速查表《错误处理决策树》给出选型顺序。',
      '- 实战项目 p2 `todo-json`：持久化失败、格式损坏、并发写入三类错误分层处理。',
    ),
  },
  {
    id: 'jd-iterators',
    kind: 'capability',
    title: '迭代器、智能指针与单元测试',
    summary: '日常写代码的“手感层”：迭代器链、Box/Rc/RefCell 的选择，以及内建测试框架。',
    category: '工程实践',
    level: '硬要求',
    tags: ['iterator', 'Box', 'Rc', 'RefCell', 'test'],
    moduleId: 'm4',
    projectId: 'p2',
    readingTime: '2 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Idiomatic Rust: iterators, closures, smart pointers”',
      '- “Write unit and integration tests; keep clippy clean”',
      '',
      '## 面试官在验的信号',
      '',
      '- 迭代器链是惰性的，`collect` 之前不产生中间 `Vec`。',
      '- 能说明什么时候需要 `Box<dyn Trait>`（大小未知 / 异构集合），什么时候 `Rc<RefCell<_>>` 是设计走偏的信号。',
      '- `#[cfg(test)] mod tests` 写在被测模块旁边，测试同样要求可读。',
      '',
      '## 对应训练',
      '',
      '- 模块 m4：迭代器、智能指针、测试与 serde。',
      '- 实战项目 p2：要求 `cargo clippy` 零警告。',
    ),
  },
  {
    id: 'jd-serde',
    kind: 'capability',
    title: 'serde 序列化',
    summary: 'serde 出现在几乎所有 Rust 后端 JD 里，是 HTTP、配置、消息队列的公共地基。',
    category: '生态',
    level: '硬要求',
    tags: ['serde', 'serde_json', 'JSON'],
    moduleId: 'm4',
    projectId: 'p2',
    readingTime: '2 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “serde / serde_json for API payloads and configuration”',
      '',
      '## 面试官在验的信号',
      '',
      '- 会用 `#[serde(rename_all = "camelCase")]`、`default`、`skip_serializing_if` 处理真实接口契约。',
      '- 知道反序列化失败属于输入校验问题，应返回 4xx 而不是 500。',
      '- 请求 DTO 与领域结构分开，不把数据库结构直接暴露成 API。',
      '',
      '## 对应训练',
      '',
      '- 模块 m4 的 serde 练习；实战项目 p2 用 JSON 文件做持久化。',
    ),
  },
  {
    id: 'jd-concurrency',
    kind: 'capability',
    title: '线程、Arc/Mutex 与 Send + Sync',
    summary: '“无畏并发”是 Rust 被选中的核心理由，也是中高级岗位的必考点。',
    category: '并发',
    level: '硬要求',
    tags: ['thread', 'Arc', 'Mutex', 'channel', 'Send', 'Sync'],
    moduleId: 'm5',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Concurrent and parallel programming; Send + Sync reasoning”',
      '- “Shared state with Arc/Mutex, message passing with channels”',
      '',
      '## 面试官在验的信号',
      '',
      '- 优先用 channel 传消息，共享可变状态是退而求其次的选择。',
      '- 能解释 `Send` 与 `Sync` 分别约束什么，以及为什么 `Rc<T>` 不是 `Send`。',
      '- 知道锁的粒度与持锁时间会直接决定吞吐。',
      '',
      '## 对应训练',
      '',
      '- 模块 m5：channel、Mutex、Arc、Send + Sync（输出保证确定性）。',
    ),
  },
  {
    id: 'jd-async',
    kind: 'capability',
    title: 'async / await 与 Tokio',
    summary: '云后端方向是 Rust 岗位最大头，Tokio 几乎是这一方向的默认运行时。',
    category: '并发',
    level: '硬要求',
    tags: ['async', 'tokio', 'Future', 'runtime'],
    moduleId: 'm6',
    projectId: 'p3',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Async Rust with Tokio; high-throughput network services”',
      '- “Experience with async ecosystems (tokio, hyper, tower)”',
      '',
      '## 面试官在验的信号',
      '',
      '- 知道 Future 是惰性的：不 `.await` 就什么都不会发生。',
      '- 不在异步任务里做阻塞调用，需要时用 `spawn_blocking` 隔离。',
      "- 能说出 `tokio::spawn` 的任务需要 `Send + 'static` 以及原因。",
      '',
      '## 对应训练',
      '',
      '- 模块 m6：async 与 tokio。',
      '- 实战项目 p3：并发抓取器，控制并发度并聚合结果。',
    ),
  },
  {
    id: 'jd-web',
    kind: 'capability',
    title: 'Axum / Actix 与 REST、gRPC',
    summary: '写服务的门面能力：路由、提取器、中间件、状态共享，以及 gRPC（Tonic）接口。',
    category: '后端框架',
    level: '硬要求',
    tags: ['axum', 'actix-web', 'tower', 'REST', 'tonic', 'gRPC'],
    moduleId: 'm7',
    projectId: 'p4',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Build REST / gRPC services with Axum or Actix Web”',
      '- “WebSocket or streaming endpoints”',
      '',
      '## 面试官在验的信号',
      '',
      '- handler 尽量写成纯函数，业务逻辑不与框架类型纠缠，方便单测。',
      '- 共享状态经 `State` 注入，而不是全局静态变量。',
      '- 知道 tower 中间件层（超时、限流、追踪）应该加在哪一层。',
      '',
      '## 对应训练',
      '',
      '- 模块 m7：axum + sqlx + WebSocket（handler 纯函数化练习）。',
      '- 实战项目 p4：完整后端服务。',
    ),
  },
  {
    id: 'jd-data',
    kind: 'capability',
    title: 'sqlx 与 PostgreSQL',
    summary: '数据访问层：编译期校验的 SQL、连接池、事务、迁移，是后端 JD 的固定项。',
    category: '数据',
    level: '硬要求',
    tags: ['sqlx', 'PostgreSQL', 'migration', 'transaction'],
    moduleId: 'm7',
    projectId: 'p4',
    readingTime: '2 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “PostgreSQL with sqlx / diesel; schema migrations”',
      '',
      '## 面试官在验的信号',
      '',
      '- 用参数化查询，不拼字符串。',
      '- 知道连接池大小与数据库最大连接数的关系。',
      '- 事务边界放在业务用例层，而不是散落在多个 handler 里。',
      '',
      '## 对应训练',
      '',
      '- 模块 m7 的数据访问练习；实战项目 p4 用 sqlx 落库并带迁移。',
    ),
  },
  {
    id: 'jd-ops',
    kind: 'capability',
    title: '生产化：Linux、Docker/K8s、CI 与可观测性',
    summary: '把服务交付出去的能力：容器化、流水线，以及 tracing / Prometheus / OpenTelemetry。',
    category: '生产化',
    level: '硬要求',
    tags: ['Linux', 'Docker', 'Kubernetes', 'CI/CD', 'tracing', 'Prometheus', 'OpenTelemetry'],
    moduleId: 'm8',
    projectId: 'p4',
    readingTime: '3 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Linux, Docker, Kubernetes, CI/CD pipelines”',
      '- “Observability: tracing, metrics, OpenTelemetry”',
      '',
      '## 面试官在验的信号',
      '',
      '- 会写多阶段 Dockerfile，产物是小体积运行镜像而不是带工具链的构建镜像。',
      '- 日志是结构化的，带请求级 span，能在故障时串起一次调用。',
      '- CI 至少包含 `cargo fmt --check`、`cargo clippy -D warnings`、`cargo test`。',
      '',
      '## 对应训练',
      '',
      '- 模块 m8：生产化与求职。',
      '- 实战项目 p4：含 tracing、Dockerfile 与 CI 的验收清单。',
    ),
  },
  {
    id: 'jd-unsafe',
    kind: 'capability',
    title: 'FFI 与 unsafe（加分项）',
    summary: '多数后端岗位不要求你天天写 unsafe，但要求你说得清它的边界与封装方式。',
    category: '进阶',
    level: '加分项',
    tags: ['unsafe', 'FFI', 'C ABI'],
    moduleId: 'm5',
    readingTime: '2 分钟',
    body: md(
      '## JD 里长什么样',
      '',
      '- “Familiarity with unsafe Rust and FFI is a plus”',
      '- 常见于把 Rust 嵌入既有 C/C++ 系统的岗位。',
      '',
      '## 面试官在验的信号',
      '',
      '- 知道 `unsafe` 关闭的只是编译器的四项检查，不是关闭所有规则。',
      '- 会把 `unsafe` 收敛在极小的模块里，对外暴露安全接口并写明不变量。',
      '- 明白跨 FFI 边界不能 panic，字符串与所有权要显式约定。',
      '',
      '## 对应训练',
      '',
      '- 模块 m5 讲 Send/Sync 时会一并处理 unsafe 的心智模型；面试题库有专门一题。',
    ),
  },
];

const interviewItems: ResourceItem[] = [
  {
    id: 'q-move-clone',
    kind: 'interview',
    title: '什么时候该 clone，什么时候说明设计有问题？',
    summary: '考点：所有权模型的实际运用，以及“借用不过就 clone”的坏习惯。',
    category: '所有权',
    level: '高频',
    tags: ['ownership', 'clone', 'move'],
    moduleId: 'm1',
    readingTime: '2 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- 先分清需求：需要**读**就借用（`&T`），需要**改**就可变借用（`&mut T`），需要**保存或跨线程搬走**才要所有权。',
      '- 合理的 clone：数据小且是 `Copy` 级别的成本；需要把值放进另一个生命周期更长的容器；跨线程移动一份独立数据。',
      '- 不合理的 clone：为了绕开借用检查器；在热路径上每次请求都克隆大结构；克隆之后原值立刻废弃（说明本该 move）。',
      '- 替代方案：缩小借用作用域、把结构体拆成互不冲突的字段、用索引/ID 代替引用、用 `Arc` 共享只读数据。',
      '',
      '## 面试官在听什么',
      '',
      '你是否把 clone 当作**成本明确的选择**，而不是编译器报错时的止痛药。',
    ),
  },
  {
    id: 'q-lifetime',
    kind: 'interview',
    title: "为什么这个函数需要写 <'a>？'static 又意味着什么？",
    summary: "考点：生命周期标注的来源，以及对 `'static` 的常见误解。",
    category: '生命周期',
    level: '高频',
    tags: ['lifetime', "'static", 'borrow checker'],
    moduleId: 'm3',
    readingTime: '3 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- 生命周期标注不改变任何值的存活时间，它只是**告诉编译器返回引用与哪个入参同源**。',
      '- 只有一个引用入参时，省略规则会自动把它绑给返回值；出现两个及以上引用入参且要返回引用时，就必须显式标注。',
      '- 结构体持有引用时也要标注：意思是“这个结构体不能活得比它借用的数据更久”。',
      "- `'static` 有两种含义：引用指向程序全生命周期存在的数据（如字符串字面量）；作为 trait bound（`T: 'static`）时表示该类型内部**不含任何短于 'static 的借用**，`String` 就满足 `T: 'static`。",
      "- `tokio::spawn` 要求 `'static`，正是因为任务可能比调用方活得久。",
      '',
      '## 面试官在听什么',
      '',
      "能不能区分“'static 引用”和“T: 'static 约束”——这是最常见的混淆点。",
    ),
  },
  {
    id: 'q-dispatch',
    kind: 'interview',
    title: 'trait object 和泛型怎么选？静态分发与动态分发的取舍是什么？',
    summary: '考点：抽象方式的成本模型，以及 object safety。',
    category: 'trait 与泛型',
    level: '高频',
    tags: ['dyn', 'generics', 'dispatch'],
    moduleId: 'm3',
    readingTime: '3 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- 泛型 = 静态分发：单态化后每个具体类型生成一份代码，可内联、零运行时开销，代价是编译时间与二进制体积。',
      '- `dyn Trait` = 动态分发：一次虚表跳转，无法内联，但只有一份代码，且支持**异构集合**（`Vec<Box<dyn Handler>>`）。',
      '- 选择依据：类型在编译期已知且在热路径上 → 泛型；需要运行时决定实现、插件式注册、减少泛型传染 → `dyn`。',
      '- 注意 object safety：带泛型方法、返回 `Self`、`Sized` 约束的 trait 不能直接做 trait object。',
      '- 工程经验：库的内层用泛型保性能，跨层边界用 `dyn` 控制编译期爆炸，是常见折中。',
      '',
      '## 面试官在听什么',
      '',
      '有没有成本意识，而不是背诵“Rust 是零成本抽象”。',
    ),
  },
  {
    id: 'q-send-sync',
    kind: 'interview',
    title: 'Send 和 Sync 分别约束了什么？为什么 Rc 不是 Send？',
    summary: '考点：并发安全在类型系统里的表达方式。',
    category: '并发',
    level: '高频',
    tags: ['Send', 'Sync', 'Rc', 'Arc'],
    moduleId: 'm5',
    readingTime: '3 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- `Send`：类型的所有权可以安全地**移动**到另一个线程。',
      '- `Sync`：`&T` 可以安全地在多个线程间**共享**；等价定义是 `T: Sync` 当且仅当 `&T: Send`。',
      '- 两者都是自动 trait：只要成员全满足就自动实现，需要手动实现时必须写 `unsafe`。',
      '- `Rc<T>` 的引用计数是非原子的，跨线程并发增减会产生数据竞争并导致 double free，所以 `Rc` 既不是 `Send` 也不是 `Sync`；`Arc<T>` 用原子计数因此是 `Send + Sync`（前提 `T: Send + Sync`）。',
      '- `Cell` / `RefCell` 提供内部可变性但不加锁，因此不是 `Sync`；跨线程共享可变状态要用 `Mutex` / `RwLock`。',
      '',
      '## 面试官在听什么',
      '',
      '能否用一句话把“移动”和“共享”这两种安全性分开讲清楚。',
    ),
  },
  {
    id: 'q-shared-mutation',
    kind: 'interview',
    title: 'Rc<RefCell<T>> 和 Arc<Mutex<T>> 各自的适用场景？',
    summary: '考点：内部可变性、运行时借用检查，以及单线程 / 多线程的区别。',
    category: '并发',
    level: '高频',
    tags: ['Rc', 'RefCell', 'Arc', 'Mutex'],
    moduleId: 'm5',
    readingTime: '2 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- `Rc<RefCell<T>>`：单线程内多所有者 + 内部可变；借用检查推迟到运行时，违规会 panic（`already borrowed`）。',
      '- `Arc<Mutex<T>>`：跨线程多所有者 + 互斥可变；违规表现为死锁或竞争而不是 panic。',
      '- 读多写少时用 `RwLock`；只读共享其实不需要锁，`Arc<T>` 足够。',
      '- 异步代码里持锁不要跨 `.await`，否则会把整段临界区拉长甚至死锁；需要跨 await 时用 `tokio::sync::Mutex`。',
      '- 更好的做法往往是消息传递：把可变状态交给一个 owner 任务，其他任务通过 channel 发消息。',
      '',
      '## 面试官在听什么',
      '',
      '会不会把共享可变状态当作默认方案，而不是最后手段。',
    ),
  },
  {
    id: 'q-future-lazy',
    kind: 'interview',
    title: 'async fn 返回什么？“不 await 就什么都没发生”是什么意思？',
    summary: '考点：Future 的惰性与状态机模型。',
    category: 'async',
    level: '高频',
    tags: ['async', 'Future', 'poll'],
    moduleId: 'm6',
    readingTime: '2 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- `async fn` 返回一个实现了 `Future` 的匿名状态机，调用它本身**不执行任何函数体代码**。',
      '- 只有被 `.await`（由外层执行器 poll）或交给 `tokio::spawn` 之后，状态机才会推进。',
      '- 每个 `.await` 是一个可能的暂停点，状态机在这里保存局部变量并让出线程。',
      '- 因此忘记 `.await` 的代码通常只会收到一个 `unused_must_use` 警告，行为上完全没跑。',
      '- 想并发执行多个 future 要显式组合：`tokio::join!`、`try_join!`、`FuturesUnordered` 或 `tokio::spawn`；顺序 `.await` 就是串行。',
      '',
      '## 面试官在听什么',
      '',
      '是否理解 Rust 的 async 是**拉模型**，与其他语言的 Promise 立即执行不同。',
    ),
  },
  {
    id: 'q-blocking',
    kind: 'interview',
    title: '在 async 任务里做阻塞调用会发生什么？怎么修？',
    summary: '考点：async 最常见的生产事故——工作线程被占满。',
    category: 'async',
    level: '高频',
    tags: ['tokio', 'spawn_blocking', 'runtime'],
    moduleId: 'm6',
    projectId: 'p3',
    readingTime: '2 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- Tokio 的工作线程数默认与 CPU 核心数相当；一个阻塞调用会**占死**一个工作线程，无法让出给其他任务。',
      '- 阻塞源包括：同步文件 IO、同步数据库/HTTP 客户端、`std::thread::sleep`、大 CPU 计算、以及跨 `.await` 持有的 `std::sync::Mutex`。',
      '- 症状是尾延迟飙升、吞吐塌陷，但 CPU 使用率并不高。',
      '- 修法：IO 换异步客户端；不可避免的阻塞或 CPU 密集任务用 `tokio::task::spawn_blocking`（或专用 rayon 线程池）隔离；`sleep` 用 `tokio::time::sleep`。',
      '- 长循环里可以插入 `tokio::task::yield_now().await` 主动让出。',
      '',
      '## 面试官在听什么',
      '',
      '有没有真在异步服务上排查过性能问题。',
    ),
  },
  {
    id: 'q-cancel-safety',
    kind: 'interview',
    title: 'cancel safety 是什么？select! 里丢掉一个分支会怎样？',
    summary: '考点：异步取消语义，中高级岗位的区分题。',
    category: 'async',
    level: '进阶',
    tags: ['cancel safety', 'select', 'drop'],
    moduleId: 'm6',
    readingTime: '3 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- Rust 的异步取消是**直接 drop 掉 future**：状态机停在最近一个 `.await` 处，之后的代码永远不会执行。',
      '- `tokio::select!` 每轮只保留胜出的分支，其余分支的 future 会被丢弃——如果那个 future 已经消费了部分数据，数据就丢了。',
      '- cancel safe 的操作：中途被丢弃不会丢状态、也不会破坏不变量（例如 `mpsc::Receiver::recv`、`tokio::time::sleep`）。',
      '- 不 cancel safe 的典型：读到一半的带缓冲读取、跨多个 `.await` 的“先扣款再记账”流程。',
      '- 应对：把这类操作 `tokio::spawn` 成独立任务再等它的 handle；或在循环外持有 future（`tokio::pin!`）避免每轮重建；或用超时 + 幂等重试兜住。',
      '',
      '## 面试官在听什么',
      '',
      '能否意识到“超时/取消”在 Rust 里不是抛异常，而是悄悄停在半路。',
    ),
  },
  {
    id: 'q-error-layers',
    kind: 'interview',
    title: 'thiserror 和 anyhow 分别用在哪一层？',
    summary: '考点：错误类型设计，后端 JD 的高频细节题。',
    category: '错误处理',
    level: '高频',
    tags: ['thiserror', 'anyhow', 'Result'],
    moduleId: 'm2',
    projectId: 'p4',
    readingTime: '2 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- 库 / 领域层：用 `thiserror` 定义具名枚举错误，调用方可以按变体做分支处理。',
      '- 应用 / 二进制层：用 `anyhow::Error` 聚合各种错误并附加上下文（`.context("加载配置失败")`），因为最终只是记录并退出。',
      '- HTTP 边界：把内部错误映射成状态码与对外文案，内部细节只进日志，不进响应体。',
      '- `?` 依赖 `From` 转换；`thiserror` 的 `#[from]` 生成这些实现，链式 `source()` 保留原因。',
      '- 判断标准：**调用方需要按错误类型做不同处理吗？** 需要就具名，不需要就聚合。',
      '',
      '## 面试官在听什么',
      '',
      '有没有“错误也是 API 的一部分”的意识。',
    ),
  },
  {
    id: 'q-unsafe',
    kind: 'interview',
    title: 'unsafe 什么时候是必要的？如何把它封装成安全抽象？',
    summary: '考点：对语言边界的理解，也是 FFI 岗位的必问题。',
    category: '进阶',
    level: '进阶',
    tags: ['unsafe', 'FFI', 'invariant'],
    moduleId: 'm5',
    readingTime: '3 分钟',
    body: md(
      '## 要点式参考答案',
      '',
      '- `unsafe` 只解锁五件事：解引用裸指针、调用 unsafe 函数、实现 unsafe trait、访问可变静态变量、访问 union 字段。它**不关闭借用检查**。',
      '- 必要场景：FFI 调用 C 库、实现编译器无法证明安全的数据结构（侵入式链表、自引用）、性能关键处跳过重复的边界检查、手动实现 `Send` / `Sync`。',
      '- 封装原则：把 unsafe 收敛到最小模块内，对外只暴露安全 API；在注释里写明调用方必须维持的**不变量**，并用 `// SAFETY:` 标注每一处理由。',
      '- 用 `miri` 跑测试检查未定义行为，用类型系统（newtype、PhantomData）把不变量固化下来。',
      '- 跨 FFI 边界：不能让 panic 越过边界（用 `catch_unwind`），字符串和内存所有权要明确由哪一侧释放。',
      '',
      '## 面试官在听什么',
      '',
      '你把 unsafe 当成需要写文档和证明的契约，而不是“绕过编译器的开关”。',
    ),
  },
];

const cheatsheetItems: ResourceItem[] = [
  {
    id: 'cheat-error-tree',
    kind: 'cheatsheet',
    title: '错误处理决策树（文字版）',
    summary: '从“这个失败会不会被调用方区分处理”出发，四步决定错误类型与传播方式。',
    category: '速查',
    level: '必备',
    tags: ['Result', 'thiserror', 'anyhow', 'panic'],
    moduleId: 'm2',
    readingTime: '3 分钟',
    body: md(
      '## 第 1 步：这是错误，还是 bug？',
      '',
      '- 外部世界导致的失败（IO、网络、用户输入、解析）→ 用 `Result`。',
      '- 代码不变量被破坏（数组越界、状态机进入不可能分支）→ `panic!` / `unreachable!` 是合理的。',
      '- 启动期缺少必需配置 → 直接 `expect("DATABASE_URL 未设置")` 让进程起不来，比运行时半死不活好。',
      '',
      '## 第 2 步：调用方需要区分不同失败吗？',
      '',
      '- 需要（要重试、要降级、要映射状态码）→ `thiserror` 定义具名枚举，每个变体一种可处理的失败。',
      '- 不需要（只是记录并退出）→ `anyhow::Result` + `.context(...)` 补充上下文。',
      '',
      '## 第 3 步：错误要跨层传播吗？',
      '',
      '- 跨层 → 用 `?`，并为下层错误实现 `From`（`thiserror` 的 `#[from]`）。',
      '- 到达 HTTP / CLI 边界 → 转成对外表示：状态码 + 安全文案；内部细节写日志，不回传。',
      '',
      '## 第 4 步：Option 还是 Result？',
      '',
      '- “没有值”是正常情况 → `Option`。',
      '- “本该有值却失败了” → `Result`，用 `ok_or_else` 从 `Option` 转过来。',
      '',
      '## 反模式清单',
      '',
      '- 生产路径上的 `unwrap()` / `expect()`（启动期不变量除外）。',
      '- 用 `String` 当错误类型：调用方只能靠字符串匹配。',
      '- 吞掉错误：`let _ = do_something();`。',
      '- 把数据库错误原文返回给用户。',
    ),
  },
  {
    id: 'cheat-crates',
    kind: 'cheatsheet',
    title: '后端常用 crate 清单',
    summary: '按 JD 出现频率整理的后端工具箱：每个 crate 解决什么问题、什么时候才需要它。',
    category: '速查',
    level: '必备',
    tags: ['crate', 'tokio', 'axum', 'sqlx', 'serde', 'tracing'],
    moduleId: 'm7',
    projectId: 'p4',
    readingTime: '3 分钟',
    body: md(
      '## 运行时与网络',
      '',
      '| crate | 用途 | 什么时候引入 |',
      '| --- | --- | --- |',
      '| `tokio` | 异步运行时、任务、定时器、异步同步原语 | 任何异步服务的地基 |',
      '| `axum` | 基于 tower/hyper 的 Web 框架，提取器 + 中间件 | 写 HTTP / WebSocket 服务 |',
      '| `actix-web` | 另一主流 Web 框架，actor 模型出身 | 团队已有 Actix 技术栈 |',
      '| `tower` / `tower-http` | 中间件抽象：超时、限流、追踪、CORS | 需要横切关注点时 |',
      '| `tonic` | gRPC（基于 prost 的 protobuf 实现） | 内部服务间通信 |',
      '| `reqwest` | 异步 HTTP 客户端 | 调用外部 API |',
      '',
      '## 数据与序列化',
      '',
      '| crate | 用途 | 什么时候引入 |',
      '| --- | --- | --- |',
      '| `serde` / `serde_json` | 序列化框架与 JSON 实现 | 几乎必备 |',
      '| `sqlx` | 异步 SQL 客户端，支持编译期校验查询与迁移 | Postgres / MySQL / SQLite |',
      '| `redis` | 缓存与轻量队列 | 需要缓存或分布式锁 |',
      '| `uuid` / `chrono` / `time` | 标识符与时间处理 | 领域模型里出现 ID 与时间戳 |',
      '',
      '## 错误、日志与配置',
      '',
      '| crate | 用途 | 什么时候引入 |',
      '| --- | --- | --- |',
      '| `thiserror` | 派生具名错误枚举（库/领域层） | 调用方需要区分失败类型 |',
      '| `anyhow` | 聚合错误 + 上下文（应用层） | 只需记录并退出 |',
      '| `tracing` / `tracing-subscriber` | 结构化日志与 span | 生产服务标配 |',
      '| `opentelemetry` | 把 span 导出到 Jaeger / Tempo 等后端 | 需要分布式追踪 |',
      '| `metrics` / `prometheus` | 指标采集与暴露 | 需要 SLO 监控 |',
      '| `config` / `dotenvy` | 分层配置与本地环境变量 | 多环境部署 |',
      '',
      '## 开发期工具',
      '',
      '| 工具 | 用途 |',
      '| --- | --- |',
      '| `clippy` | lint，CI 里配 `-D warnings` |',
      '| `rustfmt` | 统一格式，CI 里配 `--check` |',
      '| `cargo-nextest` | 更快的测试执行器 |',
      '| `criterion` | 基准测试 |',
      '| `cargo-audit` / `cargo-deny` | 依赖漏洞与许可证审查 |',
      '',
      '## 选型原则',
      '',
      '每加一个依赖都要能回答“它替我解决了什么我不想自己写的问题”。标准库能解决的（`std::collections`、`std::thread`、`std::fs`）就不要引入第三方。',
    ),
  },
  {
    id: 'cheat-market',
    kind: 'cheatsheet',
    title: 'Rust 岗位地图与薪资锚点',
    summary: '四大岗位类别的技能侧重，以及 2026-07 抓到的公开薪资锚点（只列有出处的数字）。',
    category: '速查',
    level: '必备',
    tags: ['求职', '岗位', '薪资'],
    moduleId: 'm8',
    readingTime: '3 分钟',
    body: md(
      '## 四大岗位类别',
      '',
      '| 类别 | 典型需求 | 技术侧重 |',
      '| --- | --- | --- |',
      '| 云后端服务（最大头） | API、微服务、高并发网关 | tokio、axum/actix、sqlx、gRPC、K8s |',
      '| 交易 / 量化系统 | 低延迟撮合、行情处理、风控 | 无锁与内存布局、延迟测量、确定性 |',
      '| 区块链 | 节点、智能合约工具链、钱包 | 密码学、共识、`no_std` 与 WASM |',
      '| 基础设施 / 编译器 | 数据库、运行时、开发者工具 | 语言内部、性能剖析、unsafe |',
      '',
      '想尽快就业、且已有后端背景，第一类的投产比最高——这也是本站路线的默认方向。',
      '',
      '## 公开薪资锚点（2026-07 调研）',
      '',
      '| 公司 / 地区 | 岗位 | 公开区间 |',
      '| --- | --- | --- |',
      '| Sangoma（加拿大远程） | Senior Backend Developer (Rust) | 120,000–135,000 CAD |',
      '| EngFlow（美国） | Rust 工程师 | 160,000–220,000 USD |',
      '| Radar（美国） | Rust 工程师 | 200,000–300,000 USD |',
      '',
      '这三条是抓取到的具体挂牌区间，不是市场中位数；美国整体挂牌大致落在 160k–300k USD 这个跨度内，具体取决于城市与级别。',
      '',
      '## 为什么需求在涨',
      '',
      '内存安全问题长期占据 C/C++ 代码库严重漏洞的大头，监管与大厂都在推动新组件用内存安全语言重写。这类迁移项目通常要求“懂系统 + 懂 Rust”，而不是只会写业务代码，因此对**能讲清所有权与并发模型**的候选人溢价明显。',
      '',
      '## 简历自检',
      '',
      '- 有没有一个可运行、可读、带测试与 CI 的 Rust 服务仓库？',
      '- README 能不能让人 3 分钟内跑起来？',
      '- 能不能用 5 分钟讲清项目里一个真实的所有权 / 并发决策？',
    ),
  },
];

export const resourceGroups: ResourceGroup[] = [
  {
    id: 'jd',
    title: 'JD 能力对照清单',
    eyebrow: 'Capability Ledger',
    summary:
      '把 2026-07 Indeed CA / US 抓到的高频硬要求逐条拆开，每一项都指向本站对应的模块与实战项目。',
    items: jdItems,
  },
  {
    id: 'interview',
    title: '面试高频题',
    eyebrow: 'Interview Drills',
    summary:
      '按真实面试复盘整理的十道题：所有权深挖、生命周期、分发方式、Send + Sync、async 陷阱与 unsafe 边界。',
    items: interviewItems,
  },
  {
    id: 'cheatsheet',
    title: '速查表',
    eyebrow: 'Field Notes',
    summary: '写代码和临阵复习时直接翻的三张表：错误处理决策树、后端 crate 清单、岗位与薪资地图。',
    items: cheatsheetItems,
  },
];

export const allResourceItems: ResourceItem[] = resourceGroups.flatMap((group) => group.items);

export const featuredResources: ResourceItem[] = [
  jdItems[0],
  jdItems[7],
  interviewItems[6],
  cheatsheetItems[0],
];

export function getResourceById(id: string): ResourceItem | undefined {
  return allResourceItems.find((item) => item.id === id);
}

export const scenarioCards: ScenarioCard[] = [
  {
    title: '写一个扛得住并发的 HTTP 服务',
    question: '路由、共享状态、超时与限流分别放在哪一层？handler 怎么写才好测？',
    moduleId: 'm7',
    tags: ['axum', 'tower', 'state'],
  },
  {
    title: '同时抓 100 个接口而不打爆下游',
    question: '并发度怎么控制？失败怎么重试？异步任务里出现阻塞调用会发生什么？',
    moduleId: 'm6',
    tags: ['tokio', 'concurrency', 'backpressure'],
  },
  {
    title: '让服务在故障时能被查清楚',
    question: '结构化日志、请求级 span、指标与追踪，怎么在一个 Rust 服务里搭起来？',
    moduleId: 'm8',
    tags: ['tracing', 'metrics', 'OpenTelemetry'],
  },
];
